// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// list filters: TMF630 attribute style + JSONPath filter= on ./hub.filter.ts (common/filter)
import { IsOptional, IsString } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { QueryBaseDto } from '../../common/dto/query-base.dto';

export class QueryHubDto extends QueryBaseDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;
}
