// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// filters applied by the service: q, sort
import { IsOptional, IsString } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { QueryBaseDto } from '../../common/dto/query-base.dto';

export class QueryEventDto extends QueryBaseDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;
}
