// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EventEmitterModule } from '@nestjs/event-emitter';
import { entities } from './entities';
import { TmfEventModule } from './tmf-event/tmf-event.module';
import { TopicModule } from './topic/topic.module';
import { HubModule } from './hub/hub.module';
import { EventModule } from './event/event.module';
import { SubscriptionModule } from './subscription/subscription.module';
import { ListenerModule } from './listener/listener.module';

@Module({
  imports: [
    ConfigModule.forRoot(),
    EventEmitterModule.forRoot(),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => {
        const dbType = configService.get<string>('DATABASE_TYPE') || 'sqlite';
        if (dbType === 'postgres') {
          return {
            type: 'postgres',
            host: configService.get<string>('DATABASE_HOST') || 'localhost',
            port: configService.get<number>('DATABASE_PORT') || 5432,
            username:
              configService.get<string>('DATABASE_USERNAME') || 'postgres',
            password:
              configService.get<string>('DATABASE_PASSWORD') || 'postgres',
            database:
              configService.get<string>('DATABASE_NAME') || 'event',
            entities,
            synchronize:
              configService.get<string>('DATABASE_SYNCHRONIZE') === 'true',
            logging: configService.get<string>('DATABASE_LOGGING') === 'true',
          };
        }
        return {
          type: 'sqlite',
          database: configService.get<string>('DATABASE_PATH') || './dev.db',
          entities,
          synchronize:
            configService.get<string>('DATABASE_SYNCHRONIZE') !== 'false',
          logging: configService.get<string>('DATABASE_LOGGING') === 'true',
        };
      },
    }),
    TmfEventModule,
    TopicModule,
    HubModule,
    EventModule,
    SubscriptionModule,
    ListenerModule,
  ],
})
export class AppModule {}
