// E2E of the Module Federation remote: a separate host app (e2e/mfe-host, its own shell) loads
// the remote's remoteEntry.js and mounts every exposed page; react / react-dom / neudela are
// shared singletons; the pages work there (list rows, create dialog, record page).
// Needs the remote running (`npm run dev:mock`, LAB_URL, default :4010); starts the host itself.
//
//   node e2e/mfe-host.mjs [--port 4012]
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const require = createRequire(path.join(here, '..', '..', '..', 'generator', 'package.json'));
const { chromium } = require('@playwright/test');
const REMOTE = (process.env.LAB_URL ?? 'http://localhost:4010').replace(/\/$/, '');
const PORT = args.includes('--port') ? Number(args[args.indexOf('--port') + 1]) : 4012;
const HOST_DIR = path.join(here, 'mfe-host');

const results = [];
const check = (name, ok, detail = '') => {
  results.push(ok);
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? `  — ${detail}` : ''}`);
};

// what the remote exposes, from its own manifest
const manifest = await (await fetch(`${REMOTE}/mf-manifest.json`)).json();
const remoteName = manifest.name;
const exposes = manifest.exposes.map((e) => e.path);
check('remote manifest lists the exposed pages', exposes.length > 0, `${remoteName}: ${exposes.join(', ')}`);
fs.mkdirSync(path.join(HOST_DIR, '.generated'), { recursive: true });
fs.writeFileSync(path.join(HOST_DIR, '.generated', 'remotes.ts'), `// generated by e2e/mfe-host.mjs from ${REMOTE}/mf-manifest.json
import { lazy } from 'react';
import type { ComponentType } from 'react';

export const REMOTE = { name: ${JSON.stringify(remoteName)}, url: ${JSON.stringify(REMOTE)} };
export const PAGES: { key: string; label: string; Page: ComponentType }[] = [
${exposes.map((p) => `  { key: ${JSON.stringify(p)}, label: ${JSON.stringify(p.replace('./', ''))}, Page: lazy(() => import(${JSON.stringify(`${remoteName}/${p.replace('./', '')}`)})) },`).join('\n')}
];
`);

const { createServer } = await import('vite');
const { default: react } = await import('@vitejs/plugin-react');
const { federation } = await import('@module-federation/vite');
const proxy = Object.fromEntries(['/tmf-api', '/mock-policy-api', '/mock-lookup-api'].map((p) => [p, { target: REMOTE, changeOrigin: true }]));
const server = await createServer({
  configFile: false,
  root: HOST_DIR,
  logLevel: 'error',
  plugins: [
    react(),
    federation({
      name: 'mfe_host',
      remotes: { [remoteName]: { type: 'module', name: remoteName, entry: `${REMOTE}/remoteEntry.js` } },
      shared: {
        react: { singleton: true },
        'react-dom': { singleton: true },
        neudela: { singleton: true },
      },
      dts: false,
    }),
  ],
  server: { port: PORT, strictPort: true, proxy },
});
await server.listen();

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
const remoteRequests = [];
page.on('request', (r) => { if (r.url().startsWith(REMOTE)) remoteRequests.push(new URL(r.url()).pathname); });

try {
  await page.goto(`http://localhost:${PORT}/`);
  await page.getByText('Federation host').waitFor({ timeout: 15000 });
  check('host shell is the host\'s own (no remote sidebar)', await page.locator('.lab-sidebar').count() === 0);
  await page.locator('.lt-table tbody tr').first().waitFor({ timeout: 15000 }).catch(() => {});
  check('remoteEntry.js loaded from the remote', remoteRequests.includes('/remoteEntry.js'), remoteRequests.slice(0, 5).join(' '));
  check(`${exposes[0]} renders inside the host, with data`, await page.locator('.lt-table tbody tr').count() > 0);
  const shared = await page.evaluate(() => {
    const share = window.__FEDERATION__?.__SHARE__ ?? {};
    const out = {};
    for (const scope of Object.values(share)) {
      for (const [pkg, versions] of Object.entries(scope.default ?? scope)) {
        out[pkg] = Object.values(versions).map((v) => `${v.from}${v.loaded ? ':loaded' : ''}`).join(',');
      }
    }
    return out;
  });
  check('react, react-dom and neudela are shared (one runtime)', ['react', 'react-dom', 'neudela'].every((p) => shared[p]), JSON.stringify(shared));

  // the page works there: create dialog, record page
  const primary = page.locator('.lt-toolbar').getByRole('button').filter({ hasText: /^New / }).first();
  if (await primary.count()) {
    await primary.click();
    check('create dialog opens inside the host', await page.getByRole('dialog').isVisible());
    await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click();
    await page.getByRole('dialog').waitFor({ state: 'hidden' }).catch(() => {});
    await page.waitForTimeout(500); // the modal's exit transition still covers the table
  }
  await page.locator('.lt-table tbody tr').first().locator('td').nth(2).click();
  await page.locator('.dt-header__title').waitFor({ timeout: 8000 }).catch(() => {});
  check('record page opens inside the host', await page.locator('.dt-header__title').isVisible());
  await page.screenshot({ path: path.join(here, 'screenshots', 'mfe-host.png') });

  // every other exposed page mounts too
  for (const p of exposes.slice(1)) {
    await page.getByRole('button', { name: p.replace('./', ''), exact: true }).click();
    await page.locator(`[data-remote-page="${p}"] .lt`).waitFor({ timeout: 10000 }).catch(() => {});
    check(`${p} mounts inside the host`, await page.locator(`[data-remote-page="${p}"] .lt`).isVisible());
  }
  check('no runtime errors (no duplicate React, no failed share)', errors.length === 0, errors.join(' | ').slice(0, 300));
} finally {
  await browser.close();
  await server.close();
}
console.log(`${results.filter(Boolean).length}/${results.length} passed`);
process.exit(results.every(Boolean) ? 0 : 1);
