// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
export { CreateTopicDto } from './create-topic.dto';
export { UpdateTopicDto } from './update-topic.dto';
export { QueryTopicDto } from './query-topic.dto';
