// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * GeographicSite
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { NotFoundException } from '@nestjs/common';
import { PATH_METADATA, ROUTE_ARGS_METADATA } from '@nestjs/common/constants';
import { RouteParamtypes } from '@nestjs/common/enums/route-paramtypes.enum';
import { Test } from '@nestjs/testing';
import { GeographicSiteService } from '../../src/geographic-site/geographic-site.service';
import { GeographicSiteController } from '../../src/geographic-site/geographic-site.controller';
import { GeographicSiteEventType } from '../../src/event/event-types';
import {
  CreateGeographicSiteDto,
  UpdateGeographicSiteDto,
} from '../../src/geographic-site/dto';
import { CalendarPeriod } from '../../src/geographic-site/entities/calendar-period.entity';
import { GeographicSite } from '../../src/geographic-site/entities/geographic-site.entity';
import { GeographicSiteRelationship } from '../../src/geographic-site/entities/geographic-site-relationship.entity';
import { HourPeriod } from '../../src/geographic-site/entities/hour-period.entity';
import { PlaceRefOrValue } from '../../src/geographic-site/entities/place-ref-or-value.entity';
import { RelatedParty } from '../../src/geographic-site/entities/related-party.entity';
import { TimePeriod } from '../../src/geographic-site/entities/time-period.entity';
import * as hooks from '../../src/geographic-site/geographic-site.hooks';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

/**
 * The double REMEMBERS its window and applies it, which a double returning
 * every row whatever was asked for cannot: findAll reads the total BEFORE it
 * narrows the query, so `total` is the unpaged count while `data` is one page.
 * With an unwindowed double the two are always equal and neither half of that
 * sentence is under test - counting after the window, or reporting
 * `data.length` as the total, both stay green.
 */
function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  let offset = 0;
  let limit: number | undefined;
  const windowed = () =>
    limit === undefined ? rows : rows.slice(offset, offset + limit);
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn((n: number) => {
      offset = n;
      return qb;
    }),
    take: jest.fn((n: number) => {
      limit = n;
      return qb;
    }),
    getCount: jest.fn(async () => windowed().length),
    getMany: jest.fn(async () => windowed()),
  };
  return qb;
}

const HREF = '/tmf-api/geographicSiteManagement/v4/geographicSite/res-1';

/** The route Nest registers from @Controller(`${BASE_PATH}/...`). */
const ROUTE_PATH = 'tmf-api/geographicSiteManagement/v4/geographicSite';

/** The id every delegation asserts on, and the scalar the write paths move. */
const ID = 'res-1';
const FIELD = 'code';
const LIST_QUERY = { limit: 5 };
const CREATE_BODY = { code: 'res-code' };
const UPDATE_BODY = { code: 'res-updated' };

/** The owner-bound collections this resource maps. */
const COLLECTIONS = [
  'calendar',
  'place',
  'relatedParty',
  'siteRelationship',
] as const;

/** The path segment each collection's row mapper writes into its href. */
const HREF_SEGMENT: Record<string, string> = {
  calendar: 'calendar',
  place: 'place',
  relatedParty: 'relatedParty',
  siteRelationship: 'siteRelationship',
};

/**
 * What an owned row's href is built on. NOT `HREF`: renderService hands a
 * child mapper the FLAT `resource.pathSegment`, while the root mapper gets
 * `nested.hrefSegment` under --nested-routes - so the two bases diverge for
 * a nested resource, and only here is that visible.
 */
const ROW_HREF_BASE =
  '/tmf-api/geographicSiteManagement/v4/geographicSite/res-1';

/** The `@type` each collection's rows carry: their own entity class name. */
const ROW_AT_TYPE: Record<string, string> = {
  calendar: 'CalendarPeriod',
  place: 'PlaceRefOrValue',
  relatedParty: 'RelatedParty',
  siteRelationship: 'GeographicSiteRelationship',
};

function row(collection: string, index: number): AnyRec {
  return {
    id: `${collection}-row-${index}`,
    refId: `${collection}-ref-${index}`,
    atType: ROW_AT_TYPE[collection],
    sortOrder: index,
  };
}

/** The `@type` a create stamps on a payload that carries none. */
const AT_TYPE = 'GeographicSite';
/** One the payload supplies instead, which must survive that default. */
const SUPPLIED_AT_TYPE = 'CustomGeographicSite';

/** Each settable root scalar: the payload key it is read from -> its column. */
const SCALARS: Record<string, string> = {
  code: 'code',
  description: 'description',
  name: 'name',
  status: 'status',
  '@schemaLocation': 'atSchemaLocation',
  '@baseType': 'atBaseType',
};

function scalarPayload(): AnyRec {
  const out: AnyRec = {};
  for (const w of Object.keys(SCALARS)) out[w] = `res-${SCALARS[w]}`;
  return out;
}

/** A collection whose rows carry a normalised ref row of their own. */
const NESTED_COLLECTION = 'siteRelationship';
const NESTED_REF = 'validFor';

/** What each collection's rows report as their id on the way out. */
const ROW_ID: Record<string, string> = {
  calendar: 'calendar-ref-0',
  place: 'place-ref-0',
  relatedParty: 'relatedParty-ref-0',
  siteRelationship: 'siteRelationship-ref-0',
};

/** Owned collections, whose rows fall back to their own key with no refId. */
const REF_ID_FALLBACK = [
  'calendar',
  'place',
  'relatedParty',
  'siteRelationship',
] as const;

/**
 * A sort key and a selected attribute. They are named differently on
 * purpose: applyBaseFilters turns `sort` straight into `e.<key>` SQL, so
 * that one is the COLUMN name, while projectFields matches `fields`
 * against the keys of the MAPPED row, which are the response keys.
 */
const SORT_KEY = 'code';
const SELECTED = 'code';
/** One the client did not ask for, which selection must then drop. */
const NOT_SELECTED = 'description';

/**
 * Root scalars an UPDATE may reassign: payload key -> column. Deliberately
 * narrower than SCALARS, which is the create path: `@type`, the two TMF
 * trailers and every nested-route parent key are immutable, so a create
 * sets them and an update leaves them alone.
 */
const UPDATABLE: Record<string, string> = {
  code: 'code',
  description: 'description',
  name: 'name',
  status: 'status',
};

function updatePayload(): AnyRec {
  const out: AnyRec = {};
  for (const w of Object.keys(UPDATABLE)) out[w] = `patched-${UPDATABLE[w]}`;
  return out;
}

/** The entity class each collection's owned rows are deleted as. */
const COLLECTION_ROW_ENTITY: Record<string, unknown> = {
  calendar: CalendarPeriod,
  place: PlaceRefOrValue,
  relatedParty: RelatedParty,
  siteRelationship: GeographicSiteRelationship,
};

/**
 * The property that child's back-reference to this resource is exposed
 * under, which is what the wholesale delete is keyed on. Usually `owner`,
 * renamed when the child's own spec declares a field by that name.
 */
const COLLECTION_OWNER: Record<string, string> = {
  calendar: 'owner',
  place: 'owner',
  relatedParty: 'owner',
  siteRelationship: 'owner',
};

/** The class a ref nested inside a collection row normalises into. */
const NESTED_REF_ENTITY = TimePeriod;

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    code: 'res-code',
    description: 'res-description',
    name: 'res-name',
    status: 'res-status',
    atType: 'GeographicSite',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    calendar: [row('calendar', 0)],
    place: [row('place', 0)],
    relatedParty: [row('relatedParty', 0)],
    siteRelationship: [row('siteRelationship', 0)],
    ...over,
  };
}

describe('GeographicSite entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [
      CalendarPeriod,
      GeographicSite,
      GeographicSiteRelationship,
      HourPeriod,
      PlaceRefOrValue,
      RelatedParty,
      TimePeriod,
    ]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});

describe('GeographicSiteService', () => {
  let repo: AnyRec;
  let refSave: jest.Mock;
  let manager: AnyRec;
  let dataSource: AnyRec;
  let eventEmitter: AnyRec;
  let service: GeographicSiteService;

  beforeEach(() => {
    repo = makeRepo();
    refSave = jest.fn(async (e: AnyRec) => e);
    manager = {
      findOne: jest.fn(),
      delete: jest.fn(async () => ({ affected: 1 })),
      save: jest.fn(async (a: AnyRec, b?: AnyRec) => b ?? a),
    };
    dataSource = {
      getRepository: jest.fn(() => ({
        create: jest.fn((v: AnyRec) => v),
        findOne: jest.fn(async () => null),
        save: refSave,
      })),
      transaction: jest.fn(async (cb: (m: AnyRec) => unknown) => cb(manager)),
    };
    eventEmitter = { emitEvent: jest.fn() };
    service = new GeographicSiteService(
      repo as never,
      makeRepo() as never,
      makeRepo() as never,
      makeRepo() as never,
      makeRepo() as never,
      makeRepo() as never,
      makeRepo() as never,
      dataSource as never,
      eventEmitter as never,
    );
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('create', () => {
    beforeEach(() => {
      // beforeCreate is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(undefined);
    });

    it('persists every scalar and answers with the stored resource plus its href', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.create(scalarPayload() as never);

      const persisted = repo.save.mock.calls[0][0];
      for (const w of Object.keys(SCALARS)) {
        expect(persisted[SCALARS[w]]).toBe(`res-${SCALARS[w]}`);
      }
      expect(res.id).toBe(ID);
      expect(res.href).toBe(HREF);
    });

    it('emits a create event carrying the mapped response', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.create({} as never);
      expect(eventEmitter.emitEvent).toHaveBeenCalledWith(
        GeographicSiteEventType.GEOGRAPHIC_SITE_CREATE,
        ID,
        'GeographicSite',
        res,
      );
    });

    it('keeps a client-supplied id and defaults @type to GeographicSite', async () => {
      repo.findOne.mockResolvedValue(entity({ id: 'chosen' }));
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('chosen');
      expect(persisted.atType).toBe(AT_TYPE);
    });

    it('generates a uuid when no id is supplied and keeps a supplied @type', async () => {
      repo.findOne.mockResolvedValue(entity());
      await service.create({ '@type': SUPPLIED_AT_TYPE } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toMatch(/^[0-9a-f-]{36}$/);
      expect(persisted.atType).toBe(SUPPLIED_AT_TYPE);
    });

    it('clears the soft-delete stamps so a reused id is resurrected', async () => {
      // A client may reuse the id of a row that was soft-deleted. Left stamped,
      // save() updates a row findEntity cannot see, and the POST answers 404
      // on the very id it just wrote.
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.deletedAt).toBeNull();
      expect(persisted.deletedBy).toBeUndefined();
      expect(persisted.deletedReason).toBeUndefined();
    });

    it('writes a nested ref row before the aggregate that points at it', async () => {
      repo.findOne.mockResolvedValue(entity());
      const payload: AnyRec = {};
      const nestedRow: AnyRec = { id: `${NESTED_COLLECTION}-a` };
      nestedRow[NESTED_REF] = { id: `${NESTED_REF}-9` };
      payload[NESTED_COLLECTION] = [nestedRow];
      await service.create(payload as never);

      const persisted = repo.save.mock.calls[0][0];
      const nested = persisted[NESTED_COLLECTION][0][NESTED_REF];
      expect(nested).toBeDefined();
      // cascade does not reach a ref owned by a row that is itself cascaded
      expect(refSave).toHaveBeenCalledWith(nested);
      for (const order of refSave.mock.invocationCallOrder) {
        expect(order).toBeLessThan(repo.save.mock.invocationCallOrder[0]);
      }
    });

    it('numbers each collection row by its position in the payload', async () => {
      // a row carrying no sortOrder sorts at 0 on the way out, so the
      // first row written has to carry 0 for both paths to agree
      repo.findOne.mockResolvedValue(entity());
      const payload: AnyRec = {};
      for (const c of COLLECTIONS) {
        payload[c] = [{ id: `${c}-a` }, { id: `${c}-b` }];
      }
      await service.create(payload as never);

      const persisted = repo.save.mock.calls[0][0];
      for (const c of COLLECTIONS) {
        const rows = persisted[c] as AnyRec[];
        expect(rows.map((r) => r.sortOrder)).toEqual([0, 1]);
        expect(rows.map((r) => r.refId)).toEqual([`${c}-a`, `${c}-b`]);
      }
    });

    it('leaves every collection empty when the payload omits them', async () => {
      repo.findOne.mockResolvedValue(entity());
      await service.create({} as never);
      const persisted = repo.save.mock.calls[0][0];
      for (const c of COLLECTIONS) expect(persisted[c]).toEqual([]);
      expect(refSave).not.toHaveBeenCalled();
    });

    it('builds from the payload the beforeCreate hook returns, not the dto', async () => {
      // beforeCreate lives in a file tmfgen does not manage. What it returns is
      // its owner's business, so it is SPIED here rather than asserted on: what
      // is under test is that create builds from the value it got back.
      const HOOK_PAYLOAD: AnyRec = { id: 'from-hook', code: 'res-from-hook' };
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(HOOK_PAYLOAD);
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'ignored' } as never);

      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('from-hook');
      expect(persisted.code).toBe('res-from-hook');
    });
  });

  describe('findAll', () => {
    it('maps the page it asked for and reports the unpaged total', async () => {
      const rows = [entity(), entity({ id: 'res-2' }), entity({ id: 'res-3' })];
      repo.createQueryBuilder.mockReturnValue(makeQueryBuilder(rows));
      const { data, total } = await service.findAll({ limit: 2 } as never);
      // the count is taken BEFORE the window narrows the query
      expect(total).toBe(3);
      expect(data.map((d) => d.id)).toEqual([ID, 'res-2']);
      for (const w of Object.keys(SCALARS)) {
        expect(data[0][w]).toBe(`res-${SCALARS[w]}`);
      }
    });

    it('excludes soft-deleted rows and narrows by id', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({ id: ID } as never);
      expect(qb.where).toHaveBeenCalledWith('e.deletedAt IS NULL');
      expect(qb.andWhere).toHaveBeenCalledWith('e.id = :id', { id: ID });
    });

    it('pages with the supplied window', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      // deliberately not the defaults asserted below
      await service.findAll({ offset: 40, limit: 25 } as never);
      expect(qb.skip).toHaveBeenCalledWith(40);
      expect(qb.take).toHaveBeenCalledWith(25);
    });

    it('defaults to 20 rows from offset 0', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({} as never);
      expect(qb.skip).toHaveBeenCalledWith(0);
      expect(qb.take).toHaveBeenCalledWith(20);
    });

    it('orders by the requested sort key', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({ sort: `-${SORT_KEY}` } as never);
      expect(qb.addOrderBy).toHaveBeenCalledWith(`e.${SORT_KEY}`, 'DESC');
    });

    it('projects only the requested fields, keeping id and href', async () => {
      repo.createQueryBuilder.mockReturnValue(makeQueryBuilder([entity()]));
      const { data } = await service.findAll({ fields: SELECTED } as never);
      expect(data[0][SELECTED]).toBe(`res-${SCALARS[SELECTED]}`);
      expect(data[0].id).toBe(ID);
      expect(data[0].href).toBe(HREF);
      expect(Object.keys(data[0])).not.toContain('@type');
      expect(Object.keys(data[0])).not.toContain(NOT_SELECTED);
    });
  });

  describe('findEntity / findOne', () => {
    beforeEach(() => {
      // afterFindOne is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'afterFindOne').mockResolvedValue(undefined);
    });

    it('throws NotFoundException when the row is missing or soft-deleted', async () => {
      repo.findOne.mockResolvedValue(null);
      await expect(service.findEntity('nope')).rejects.toBeInstanceOf(
        NotFoundException,
      );
      await expect(service.findOne('nope')).rejects.toBeInstanceOf(
        NotFoundException,
      );
    });

    it('maps every scalar and the resource href', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID);
      for (const w of Object.keys(SCALARS)) {
        expect(res[w]).toBe(`res-${SCALARS[w]}`);
      }
      expect(res.href).toBe(HREF);
    });

    it('maps every collection row, with the href its own mapper writes', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) {
        expect(res[c]).toHaveLength(1);
        expect(res[c][0].id).toBe(ROW_ID[c]);
        if (HREF_SEGMENT[c]) {
          expect(res[c][0].href).toBe(
            `${ROW_HREF_BASE}/${HREF_SEGMENT[c]}/${ROW_ID[c]}`,
          );
        }
      }
    });

    it('falls back to the row key when an owned row carries no refId', async () => {
      const over: AnyRec = {};
      for (const c of REF_ID_FALLBACK) over[c] = [{ id: `${c}-only` }];
      repo.findOne.mockResolvedValue(entity(over));
      const res = await service.findOne(ID);
      for (const c of REF_ID_FALLBACK) expect(res[c][0].id).toBe(`${c}-only`);
    });

    it('returns empty collections when the row carries none', async () => {
      repo.findOne.mockResolvedValue({ id: ID, atType: AT_TYPE });
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) expect(res[c]).toEqual([]);
    });

    it('orders each collection by sortOrder rather than by insertion', async () => {
      const over: AnyRec = {};
      for (const c of Object.keys(ROW_ID)) {
        over[c] = [
          { id: `${c}-b`, refId: `${c}-b`, sortOrder: 2 },
          { id: `${c}-a`, refId: `${c}-a`, sortOrder: 1 },
        ];
      }
      repo.findOne.mockResolvedValue(entity(over));
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) {
        expect(res[c].map((r: AnyRec) => r.id)).toEqual([`${c}-a`, `${c}-b`]);
      }
    });

    it('treats a row with no sortOrder as 0, so it sorts first', async () => {
      const over: AnyRec = {};
      for (const c of Object.keys(ROW_ID)) {
        over[c] = [
          { id: `${c}-b`, refId: `${c}-b`, sortOrder: 1 },
          { id: `${c}-a`, refId: `${c}-a` },
        ];
      }
      repo.findOne.mockResolvedValue(entity(over));
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) {
        expect(res[c].map((r: AnyRec) => r.id)).toEqual([`${c}-a`, `${c}-b`]);
      }
    });

    it('defaults @schemaLocation and @baseType to ""', async () => {
      repo.findOne.mockResolvedValue({ id: ID, atType: AT_TYPE });
      const res = await service.findOne(ID);
      expect(res['@schemaLocation']).toBe('');
      expect(res['@baseType']).toBe('');
    });

    it('projects the requested fields on a single read', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID, SELECTED);
      expect(res[SELECTED]).toBe(`res-${SCALARS[SELECTED]}`);
      expect(Object.keys(res)).not.toContain(NOT_SELECTED);
    });

    it('answers with whatever the afterFindOne hook gives back', async () => {
      // afterFindOne lives in a file tmfgen does not manage. What it returns is
      // its owner's business, so it is SPIED here rather than asserted on: what
      // is under test is that findOne hands it the mapped response and answers
      // with the value it got back.
      const DECORATED: AnyRec = { id: 'from-hook' };
      jest.spyOn(hooks, 'afterFindOne').mockResolvedValue(DECORATED);
      const stored = entity();
      repo.findOne.mockResolvedValue(stored);
      const res = await service.findOne(ID);
      expect(hooks.afterFindOne).toHaveBeenCalledWith(
        expect.objectContaining({ href: HREF }),
        stored,
      );
      expect(res).toBe(DECORATED);
    });
  });

  describe('update', () => {
    beforeEach(() => {
      // beforeUpdate is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'beforeUpdate').mockResolvedValue(undefined);
      // the transaction commits, then update() re-READS through findEntity
      repo.findOne.mockImplementation(async () => entity());
    });

    it('throws NotFoundException when the row is missing or soft-deleted', async () => {
      manager.findOne.mockResolvedValue(null);
      await expect(service.update('nope', {} as never)).rejects.toBeInstanceOf(
        NotFoundException,
      );
    });

    it('applies every scalar the payload carries', async () => {
      const existing = entity();
      manager.findOne.mockResolvedValue(existing);
      await service.update(ID, updatePayload() as never);
      for (const w of Object.keys(UPDATABLE)) {
        expect(existing[UPDATABLE[w]]).toBe(`patched-${UPDATABLE[w]}`);
      }
    });

    it('leaves the columns the payload omits untouched', async () => {
      // PATCH semantics: an absent key is not the same as a null one
      const existing = entity();
      manager.findOne.mockResolvedValue(existing);
      const [sent, omitted] = Object.keys(UPDATABLE);
      const dto: AnyRec = {};
      dto[sent] = `patched-${UPDATABLE[sent]}`;
      await service.update(ID, dto as never);
      expect(existing[UPDATABLE[sent]]).toBe(`patched-${UPDATABLE[sent]}`);
      expect(existing[UPDATABLE[omitted]]).toBe(`res-${UPDATABLE[omitted]}`);
    });

    it('replaces each collection wholesale, deleting the owned rows first', async () => {
      const existing = entity();
      manager.findOne.mockResolvedValue(existing);
      const dto: AnyRec = {};
      for (const c of COLLECTIONS) dto[c] = [{ id: `${c}-new` }];
      await service.update(ID, dto as never);

      for (const c of COLLECTIONS) {
        expect(manager.delete).toHaveBeenCalledWith(COLLECTION_ROW_ENTITY[c], {
          [COLLECTION_OWNER[c]]: { id: ID },
        });
        expect(existing[c]).toHaveLength(1);
        expect(existing[c][0].refId).toBe(`${c}-new`);
      }
      // the delete has to land BEFORE the aggregate save, or the rows it
      // removes are the replacements rather than the old ones
      const saves = manager.save.mock.invocationCallOrder;
      const aggregate = saves[saves.length - 1];
      for (const order of manager.delete.mock.invocationCallOrder) {
        expect(order).toBeLessThan(aggregate);
      }
    });

    it('empties a collection sent as null just as one sent as []', async () => {
      for (const c of COLLECTIONS) {
        const viaNull = entity();
        manager.findOne.mockResolvedValue(viaNull);
        await service.update(ID, { [c]: null } as never);
        expect(viaNull[c]).toEqual([]);

        const viaEmpty = entity();
        manager.findOne.mockResolvedValue(viaEmpty);
        await service.update(ID, { [c]: [] } as never);
        expect(viaEmpty[c]).toEqual([]);
      }
    });

    it('deletes the ref rows orphaned by replacing a collection row', async () => {
      // the wholesale delete removes the OWNED rows; the normalised rows they
      // pointed at are @ManyToOne, which has no orphanedRowAction to follow
      const orphan: AnyRec = { id: `${NESTED_COLLECTION}-old` };
      orphan[NESTED_REF] = { id: `${NESTED_REF}-old` };
      const over: AnyRec = {};
      over[NESTED_COLLECTION] = [orphan];
      manager.findOne.mockResolvedValue(entity(over));
      const dto: AnyRec = {};
      dto[NESTED_COLLECTION] = [{ id: `${NESTED_COLLECTION}-new` }];
      await service.update(ID, dto as never);
      expect(manager.delete).toHaveBeenCalledWith(NESTED_REF_ENTITY, [
        `${NESTED_REF}-old`,
      ]);
    });

    it('leaves that ref table alone when no collection row nested one', async () => {
      const over: AnyRec = {};
      over[NESTED_COLLECTION] = [{ id: `${NESTED_COLLECTION}-old` }];
      manager.findOne.mockResolvedValue(entity(over));
      const dto: AnyRec = {};
      dto[NESTED_COLLECTION] = [];
      await service.update(ID, dto as never);
      expect(manager.delete).not.toHaveBeenCalledWith(
        NESTED_REF_ENTITY,
        expect.anything(),
      );
    });

    it('answers with the re-read resource and emits a change event', async () => {
      manager.findOne.mockResolvedValue(entity());
      const res = await service.update(ID, {} as never);
      // mapped from a FRESH findEntity, so the response carries the relations
      // the transaction just rewrote rather than the half-built aggregate
      expect(repo.findOne).toHaveBeenCalled();
      expect(res.id).toBe(ID);
      expect(res.href).toBe(HREF);
      expect(eventEmitter.emitEvent).toHaveBeenCalledWith(
        GeographicSiteEventType.GEOGRAPHIC_SITE_ATTRIBUTE_VALUE_CHANGE,
        ID,
        'GeographicSite',
        res,
      );
    });

    it('applies the payload the beforeUpdate hook returns, not the dto', async () => {
      // beforeUpdate lives in a file tmfgen does not manage. What it returns
      // is its owner's business, so it is SPIED here rather than asserted on:
      // what is under test is that update applies the value it got back.
      const [w] = Object.keys(UPDATABLE);
      const HOOK_PAYLOAD: AnyRec = {};
      HOOK_PAYLOAD[w] = `from-hook-${UPDATABLE[w]}`;
      jest.spyOn(hooks, 'beforeUpdate').mockResolvedValue(HOOK_PAYLOAD);

      const existing = entity();
      manager.findOne.mockResolvedValue(existing);
      const dto: AnyRec = {};
      dto[w] = `ignored-${UPDATABLE[w]}`;
      await service.update(ID, dto as never);
      expect(hooks.beforeUpdate).toHaveBeenCalledWith(ID, dto);
      expect(existing[UPDATABLE[w]]).toBe(`from-hook-${UPDATABLE[w]}`);
    });
  });

  describe('remove', () => {
    it('soft-deletes the row, recording who and why', async () => {
      // the row STAYS: a hard delete would take the TMF audit trail with it
      const e = entity();
      repo.findOne.mockResolvedValue(e);
      await service.remove(ID, 'by-deletedBy', 'by-deletedReason');
      expect(e.deletedAt).toBeInstanceOf(Date);
      expect(e.deletedBy).toBe('by-deletedBy');
      expect(e.deletedReason).toBe('by-deletedReason');
      expect(repo.save).toHaveBeenCalledWith(e);
    });

    it('defaults deletedBy and deletedReason when the caller names neither', async () => {
      const e = entity();
      repo.findOne.mockResolvedValue(e);
      await service.remove(ID);
      expect(e.deletedBy).toBe('system');
      expect(e.deletedReason).toBe('Deleted via API');
    });

    it('emits a delete event carrying only the id and the href', async () => {
      repo.findOne.mockResolvedValue(entity());
      await service.remove(ID);
      // the row is gone from the API: a full payload would describe a
      // resource the subscriber can no longer GET
      expect(eventEmitter.emitEvent).toHaveBeenCalledWith(
        GeographicSiteEventType.GEOGRAPHIC_SITE_DELETE,
        ID,
        'GeographicSite',
        { id: ID, href: HREF },
      );
    });

    it('throws NotFoundException for a row that is already gone', async () => {
      repo.findOne.mockResolvedValue(null);
      await expect(service.remove('nope')).rejects.toBeInstanceOf(
        NotFoundException,
      );
      expect(repo.save).not.toHaveBeenCalled();
      expect(eventEmitter.emitEvent).not.toHaveBeenCalled();
    });
  });
});

/** The design:paramtype Nest hands ValidationPipe for a route's @Body(). */
function bodyParamType(route: string): unknown {
  const args = Reflect.getMetadata(
    ROUTE_ARGS_METADATA,
    GeographicSiteController,
    route,
  ) as AnyRec;
  const prefix = `${RouteParamtypes.BODY}:`;
  const bodyKey = Object.keys(args).find((k) => k.startsWith(prefix));
  expect(bodyKey).toBeDefined();
  const index = Number((bodyKey as string).split(':')[1]);
  const types = Reflect.getMetadata(
    'design:paramtypes',
    GeographicSiteController.prototype,
    route,
  );
  return types[index];
}

describe('GeographicSiteController', () => {
  let svc: AnyRec;
  let ctrl: GeographicSiteController;

  beforeEach(() => {
    svc = {
      create: jest.fn(async () => ({ id: ID, href: HREF })),
      findAll: jest.fn(async () => ({ data: [], total: 0 })),
      findOne: jest.fn(async () => ({ id: ID })),
      update: jest.fn(async () => ({ id: ID, code: 'res-updated' })),
      remove: jest.fn(async () => undefined),
    };
    ctrl = new GeographicSiteController(svc as never);
  });

  it('sets the Location header from the created resource href', async () => {
    const res = { location: jest.fn() };
    const out = await ctrl.create(CREATE_BODY as never, res as never);
    expect(svc.create).toHaveBeenCalledWith(CREATE_BODY);
    expect(res.location).toHaveBeenCalledWith(HREF);
    expect(out.id).toBe(ID);
  });

  it('omits the Location header when the created resource has no href', async () => {
    svc.create.mockResolvedValue({ id: ID });
    const res = { location: jest.fn() };
    await ctrl.create({} as never, res as never);
    expect(res.location).not.toHaveBeenCalled();
  });

  it('passes the query through to findAll', async () => {
    await ctrl.findAll(LIST_QUERY as never);
    expect(svc.findAll).toHaveBeenCalledWith(LIST_QUERY);
  });

  it('forwards the id and the field selection to findOne', async () => {
    await ctrl.findOne(ID, FIELD);
    expect(svc.findOne).toHaveBeenCalledWith(ID, FIELD);
  });

  it('forwards the id and the payload to update', async () => {
    const out = await ctrl.update(ID, UPDATE_BODY as never);
    expect(svc.update).toHaveBeenCalledWith(ID, UPDATE_BODY);
    expect(out[FIELD]).toBe('res-updated');
  });

  it('delegates the delete route', async () => {
    await ctrl.remove(ID);
    expect(svc.remove).toHaveBeenCalledWith(ID);
  });

  it('is constructible by Nest with its route metadata intact', async () => {
    // A concrete controller carrying no decorator of its own emits no
    // constructor `design:paramtypes`, so Nest builds it with zero arguments
    // and every route 500s; losing only @Controller() keeps injection working
    // but silently unmounts the routes. Both are checked separately.
    const moduleRef = await Test.createTestingModule({
      controllers: [GeographicSiteController],
      providers: [{ provide: GeographicSiteService, useValue: svc }],
    }).compile();

    const resolved = moduleRef.get(
      GeographicSiteController,
    ) as unknown as AnyRec;
    expect(resolved.service).toBe(svc);
    const paramtypes = Reflect.getMetadata(
      'design:paramtypes',
      GeographicSiteController,
    );
    expect(paramtypes).toEqual([GeographicSiteService]);
    const routePath = Reflect.getMetadata(
      PATH_METADATA,
      GeographicSiteController,
    );
    expect(routePath).toBe(ROUTE_PATH);
  });

  it('types every write body as its DTO class, so ValidationPipe has a schema', () => {
    // ValidationPipe validates against the parameter's design:paramtype. A body
    // left as `any`/`unknown` erases to Object, which accepts every payload
    // unchecked and makes Swagger emit no request body schema.
    expect(bodyParamType('create')).toBe(CreateGeographicSiteDto);
    expect(bodyParamType('update')).toBe(UpdateGeographicSiteDto);
  });
});
