// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * GeographicSite
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { PATH_METADATA, ROUTE_ARGS_METADATA } from '@nestjs/common/constants';
import { RouteParamtypes } from '@nestjs/common/enums/route-paramtypes.enum';
import { Test } from '@nestjs/testing';
import { GeographicSiteService } from '../../src/geographic-site/geographic-site.service';
import { GeographicSiteController } from '../../src/geographic-site/geographic-site.controller';
import { GeographicSiteEventType } from '../../src/event/event-types';
import {
  CreateGeographicSiteDto,
  UpdateGeographicSiteDto,
} from '../../src/geographic-site/dto';
import { CalendarPeriod } from '../../src/geographic-site/entities/calendar-period.entity';
import { GeographicSite } from '../../src/geographic-site/entities/geographic-site.entity';
import { GeographicSiteRelationship } from '../../src/geographic-site/entities/geographic-site-relationship.entity';
import { HourPeriod } from '../../src/geographic-site/entities/hour-period.entity';
import { PlaceRefOrValue } from '../../src/geographic-site/entities/place-ref-or-value.entity';
import { RelatedParty } from '../../src/geographic-site/entities/related-party.entity';
import { TimePeriod } from '../../src/geographic-site/entities/time-period.entity';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn(() => qb),
    take: jest.fn(() => qb),
    getCount: jest.fn(async () => rows.length),
    getMany: jest.fn(async () => rows),
  };
  return qb;
}

const HREF = '/tmf-api/geographicSiteManagement/v4/geographicSite/res-1';

/** The route Nest registers from @Controller(`${BASE_PATH}/...`). */
const ROUTE_PATH = 'tmf-api/geographicSiteManagement/v4/geographicSite';

/** The id every delegation asserts on, and the scalar the write paths move. */
const ID = 'res-1';
const FIELD = 'code';
const LIST_QUERY = { limit: 5 };
const CREATE_BODY = { code: 'res-code' };
const UPDATE_BODY = { code: 'res-updated' };

/** The owner-bound collections this resource maps. */
const COLLECTIONS = [
  'calendar',
  'place',
  'relatedParty',
  'siteRelationship',
] as const;

/** The path segment each collection's row mapper writes into its href. */
const HREF_SEGMENT: Record<string, string> = {
  calendar: 'calendar',
  place: 'place',
  relatedParty: 'relatedParty',
  siteRelationship: 'siteRelationship',
};

/** The `@type` each collection's rows carry: their own entity class name. */
const ROW_AT_TYPE: Record<string, string> = {
  calendar: 'CalendarPeriod',
  place: 'PlaceRefOrValue',
  relatedParty: 'RelatedParty',
  siteRelationship: 'GeographicSiteRelationship',
};

function row(collection: string, index: number): AnyRec {
  return {
    id: `${collection}-row-${index}`,
    refId: `${collection}-ref-${index}`,
    atType: ROW_AT_TYPE[collection],
    sortOrder: index,
  };
}

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    code: 'res-code',
    description: 'res-description',
    name: 'res-name',
    status: 'res-status',
    atType: 'GeographicSite',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    calendar: [row('calendar', 0)],
    place: [row('place', 0)],
    relatedParty: [row('relatedParty', 0)],
    siteRelationship: [row('siteRelationship', 0)],
    ...over,
  };
}

describe('GeographicSite entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [
      CalendarPeriod,
      GeographicSite,
      GeographicSiteRelationship,
      HourPeriod,
      PlaceRefOrValue,
      RelatedParty,
      TimePeriod,
    ]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});

/** The design:paramtype Nest hands ValidationPipe for a route's @Body(). */
function bodyParamType(route: string): unknown {
  const args = Reflect.getMetadata(
    ROUTE_ARGS_METADATA,
    GeographicSiteController,
    route,
  ) as AnyRec;
  const prefix = `${RouteParamtypes.BODY}:`;
  const bodyKey = Object.keys(args).find((k) => k.startsWith(prefix));
  expect(bodyKey).toBeDefined();
  const index = Number((bodyKey as string).split(':')[1]);
  const types = Reflect.getMetadata(
    'design:paramtypes',
    GeographicSiteController.prototype,
    route,
  );
  return types[index];
}

describe('GeographicSiteController', () => {
  let svc: AnyRec;
  let ctrl: GeographicSiteController;

  beforeEach(() => {
    svc = {
      create: jest.fn(async () => ({ id: ID, href: HREF })),
      findAll: jest.fn(async () => ({ data: [], total: 0 })),
      findOne: jest.fn(async () => ({ id: ID })),
      update: jest.fn(async () => ({ id: ID, code: 'res-updated' })),
      remove: jest.fn(async () => undefined),
    };
    ctrl = new GeographicSiteController(svc as never);
  });

  it('sets the Location header from the created resource href', async () => {
    const res = { location: jest.fn() };
    const out = await ctrl.create(CREATE_BODY as never, res as never);
    expect(svc.create).toHaveBeenCalledWith(CREATE_BODY);
    expect(res.location).toHaveBeenCalledWith(HREF);
    expect(out.id).toBe(ID);
  });

  it('omits the Location header when the created resource has no href', async () => {
    svc.create.mockResolvedValue({ id: ID });
    const res = { location: jest.fn() };
    await ctrl.create({} as never, res as never);
    expect(res.location).not.toHaveBeenCalled();
  });

  it('passes the query through to findAll', async () => {
    await ctrl.findAll(LIST_QUERY as never);
    expect(svc.findAll).toHaveBeenCalledWith(LIST_QUERY);
  });

  it('forwards the id and the field selection to findOne', async () => {
    await ctrl.findOne(ID, FIELD);
    expect(svc.findOne).toHaveBeenCalledWith(ID, FIELD);
  });

  it('forwards the id and the payload to update', async () => {
    const out = await ctrl.update(ID, UPDATE_BODY as never);
    expect(svc.update).toHaveBeenCalledWith(ID, UPDATE_BODY);
    expect(out[FIELD]).toBe('res-updated');
  });

  it('delegates the delete route', async () => {
    await ctrl.remove(ID);
    expect(svc.remove).toHaveBeenCalledWith(ID);
  });

  it('is constructible by Nest with its route metadata intact', async () => {
    // A concrete controller carrying no decorator of its own emits no
    // constructor `design:paramtypes`, so Nest builds it with zero arguments
    // and every route 500s; losing only @Controller() keeps injection working
    // but silently unmounts the routes. Both are checked separately.
    const moduleRef = await Test.createTestingModule({
      controllers: [GeographicSiteController],
      providers: [{ provide: GeographicSiteService, useValue: svc }],
    }).compile();

    const resolved = moduleRef.get(
      GeographicSiteController,
    ) as unknown as AnyRec;
    expect(resolved.service).toBe(svc);
    const paramtypes = Reflect.getMetadata(
      'design:paramtypes',
      GeographicSiteController,
    );
    expect(paramtypes).toEqual([GeographicSiteService]);
    const routePath = Reflect.getMetadata(
      PATH_METADATA,
      GeographicSiteController,
    );
    expect(routePath).toBe(ROUTE_PATH);
  });

  it('types every write body as its DTO class, so ValidationPipe has a schema', () => {
    // ValidationPipe validates against the parameter's design:paramtype. A body
    // left as `any`/`unknown` erases to Object, which accepts every payload
    // unchecked and makes Swagger emit no request body schema.
    expect(bodyParamType('create')).toBe(CreateGeographicSiteDto);
    expect(bodyParamType('update')).toBe(UpdateGeographicSiteDto);
  });
});
