// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { GeographicLocation } from './geographic-location.entity';

/**
 * A GeoPoint defines a geographic point through coordinates
 */
@Entity('geographic_point')
export class GeographicPoint {
  @PrimaryColumn({ type: 'varchar', length: 100 })
  id: string;

  /** The id the client gave this item. Unique within its parent only, so it is not the primary key; served back as `id`. */
  @Column({ type: 'varchar', length: 100, nullable: true })
  refId?: string;

  @Column({ type: 'int', nullable: true })
  sortOrder?: number;

  /** x coordinate (usually latitude) */
  @Column({ type: 'varchar', length: 255 })
  x: string;

  /** y coordinate (usually longitude) */
  @Column({ type: 'varchar', length: 255 })
  y: string;

  /** z coordinate (usually elevation) */
  @Column({ type: 'varchar', length: 255, nullable: true })
  z?: string;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  @ManyToOne(() => GeographicLocation, (parent) => parent.geometry, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'geographic_location_id' })
  owner: GeographicLocation;
}
