// GENERATED by fe-gen emit mcs-common - DO NOT EDIT. Re-run `fe-gen emit` instead.
// TMF wire shape for "partyRevSharingAlgorithm" - derived from the add/edit form's api.payload spec.

export interface PartyRevSharingAlgorithm {
  "@type": string;
  name: string;
  description?: string;
  policy: {
    "@type"?: string;
    id: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
    version?: string;
  }[];
  conditionVariable?: {
    "@type"?: string;
    value: string;
    policyCondition?: {
    "@type"?: string;
    id?: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
  };
    policyConditionVariable?: {
    "@type"?: string;
    id?: string;
    name?: string;
    "@referredType"?: string;
  };
  }[];
  actionVariable?: {
    "@type"?: string;
    value: string;
    policyAction?: {
    "@type"?: string;
    id?: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
  };
    policyActionVariable?: {
    "@type"?: string;
    id?: string;
    name?: string;
    "@referredType"?: string;
  };
  }[];
  id: string;
  href?: string;
}

export interface PartyRevSharingAlgorithm_FVO {
  "@type": string;
  name: string;
  description?: string;
  policy: {
    "@type"?: string;
    id: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
    version?: string;
  }[];
  conditionVariable?: {
    "@type"?: string;
    value: string;
    policyCondition?: {
    "@type"?: string;
    id?: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
  };
    policyConditionVariable?: {
    "@type"?: string;
    id?: string;
    name?: string;
    "@referredType"?: string;
  };
  }[];
  actionVariable?: {
    "@type"?: string;
    value: string;
    policyAction?: {
    "@type"?: string;
    id?: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
  };
    policyActionVariable?: {
    "@type"?: string;
    id?: string;
    name?: string;
    "@referredType"?: string;
  };
  }[];
}

export interface PartyRevSharingAlgorithm_MVO {
  name: string;
  description?: string;
  policy: {
    "@type"?: string;
    id: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
    version?: string;
  }[];
  conditionVariable?: {
    "@type"?: string;
    value: string;
    policyCondition?: {
    "@type"?: string;
    id?: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
  };
    policyConditionVariable?: {
    "@type"?: string;
    id?: string;
    name?: string;
    "@referredType"?: string;
  };
  }[];
  actionVariable?: {
    "@type"?: string;
    value: string;
    policyAction?: {
    "@type"?: string;
    id?: string;
    href?: string;
    name?: string;
    "@referredType"?: string;
  };
    policyActionVariable?: {
    "@type"?: string;
    id?: string;
    name?: string;
    "@referredType"?: string;
  };
  }[];
}
