// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Controller, Get, Post, Body, Param, Query, HttpCode, HttpStatus, Res, UseGuards, UseInterceptors } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiParam, ApiResponse } from '@nestjs/swagger';
import { Response } from 'express';
import { TMF688_BASE_PATH } from '../common/constants/tmf.constants';
import { ApiKeyGuard } from '../common/guards/api-key.guard';
import { PaginationInterceptor } from '../common/interceptors/pagination.interceptor';
import { EventService } from './event.service';
import { CreateEventDto, QueryEventDto } from './dto';

@ApiTags('event')
@UseGuards(ApiKeyGuard)
@UseInterceptors(PaginationInterceptor)
@Controller(`${TMF688_BASE_PATH}/event`)
export class EventController {
  constructor(private readonly service: EventService) {}

  @Post()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Creates a Event', description: 'This operation creates a Event entity.', operationId: 'createEvent' })
  @ApiResponse({ status: 201, description: 'Created' })
  @ApiResponse({ status: 400, description: 'Bad Request' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  @ApiResponse({ status: 405, description: 'Method Not Allowed' })
  @ApiResponse({ status: 409, description: 'Conflict' })
  async create(
    @Body() dto: CreateEventDto,
    @Res({ passthrough: true }) res: Response,
  ): Promise<Record<string, any>> {
    const result = await this.service.create(dto);
    if (result?.href) {
      res.location(result.href);
    }
    return result;
  }

  @Get()
  @ApiOperation({ summary: 'List or find Event objects', description: 'This operation list or find Event entities', operationId: 'listEvent' })
  @ApiResponse({ status: 200, description: 'Success' })
  @ApiResponse({ status: 400, description: 'Bad Request' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  @ApiResponse({ status: 404, description: 'Not Found' })
  @ApiResponse({ status: 405, description: 'Method Not Allowed' })
  @ApiResponse({ status: 409, description: 'Conflict' })
  findAll(@Query() query: QueryEventDto) {
    return this.service.findAll(query);
  }

  @Get(':id')
  @ApiOperation({ summary: 'Retrieves a Event by ID', description: 'This operation retrieves a Event entity. Attribute selection is enabled for all first level attributes.', operationId: 'retrieveEvent' })
  @ApiResponse({ status: 200, description: 'Success' })
  @ApiResponse({ status: 400, description: 'Bad Request' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  @ApiResponse({ status: 404, description: 'Not Found' })
  @ApiResponse({ status: 405, description: 'Method Not Allowed' })
  @ApiResponse({ status: 409, description: 'Conflict' })
  @ApiParam({ name: 'id', description: 'Identifier of the Event' })
  findOne(
    @Param('id') id: string,
    @Query('fields') fields?: string,
  ): Promise<Record<string, any>> {
    return this.service.findOne(id, fields);
  }
}
