// GENERATED by fe-gen — CRA5 + Craco full-repo app (M3 scaffold runtime).
// Re-run `fe-gen scaffold` instead of editing when the app is regenerated.
//
// Module Federation: DISABLED for full-repo apps. The MFE-mode configuration
// below is emitted by `fe-gen emit --mode mfe` (M5) — it is kept here as
// reference only (convention: name `<app>_remote`, filename `<camel>RemoteEntry.js`,
// shared react trio singleton:true requiredVersion:false).
//
// The .mjs webpack rule at the bottom MUST stay: it is the Webpack 4 + strict
// ESM compatibility fix (reference: capacity-management craco.config.js:41-47).
//
// WHY optimization.sideEffects=false (empirical M3 — lihat .omo/evidence/):
//   react-scripts 5 (webpack 5) mengaktifkan sideEffects optimization; MUI
//   (@mui/utils/@mui/material) mendeklarasikan "sideEffects": false dan ESM
//   subpath-nya adalah barrel re-export (`export { default } from './leaf'`).
//   Dengan sideEffects optimization aktif, webpack menandai barrel utk di-prune
//   → production build gagal: "Attempted import error: '@mui/utils/chainPropTypes'
//   does not contain a default export (module has no exports)". sideEffects=false
//   pada optimization mengembalikan ekspor default (verified: 0 import-errors).
const { ModuleFederationPlugin } = require("webpack").container;

module.exports = {
  webpack: {
    configure: (webpackConfig) => {
      webpackConfig.output.publicPath = "auto";
      webpackConfig.output.crossOriginLoading = "anonymous";

      // ── MFE mode (M5) — emitted by fe-gen emit mfe, not written by hand ──
      // webpackConfig.plugins.push(
      //   new ModuleFederationPlugin({
      //     name: "<appName>_remote",
      //     filename: "<camelAppName>RemoteEntry.js",
      //     exposes: {},
      //     shared: {
      //       react: { singleton: true, requiredVersion: false },
      //       "react-dom": { singleton: true, requiredVersion: false },
      //       "react-router-dom": { singleton: true, requiredVersion: false },
      //     },
      //   })
      // );

      // Fix: Webpack 4 + .mjs strict ESM compatibility (ALWAYS present).
      webpackConfig.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto",
        resolve: { fullySpecified: false },
      });

      // Fix: MUI barrel ESM + sideEffects optimization (lihat komentar header).
      if (webpackConfig.optimization) webpackConfig.optimization.sideEffects = false;
      else webpackConfig.optimization = { sideEffects: false };

      return webpackConfig;
    },
  },
};