import { synthesizePayload, resetPayloadSeed } from './payload.mjs';
import { buildCollection } from './collection.mjs';

/**
 * Emits a self-contained Conformance Test Kit for a component that TM Forum does not
 * ship one for.
 *
 * Seven components in this workspace have no `ctk/` directory at all, so there is no
 * way to check them the way the other twelve were checked. This produces the
 * newman-based layout TM Forum used for the older kits (config.json + collection +
 * index.js runner), because that one runs directly on the host - the newer kits pull a
 * Docker image per component, which cannot be generated here.
 *
 * The kit is explicitly labelled as generated. It carries no certification weight;
 * it is a regression harness for the generated service.
 */

const RUNNER = `// GENERATED by tmfgen. Runner for a generated Conformance Test Kit.
//
// Mirrors the shipped TM Forum kits: read config.json, inject the target URL and the
// per-resource POST payloads into the collection, then run newman with an html and a
// json reporter so results can be diffed between runs.
const fs = require('fs');
const path = require('path');
const newman = require('newman');

const configPath = path.join(__dirname, '..', 'config.json');
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
const collectionFile = fs.readdirSync(__dirname).find((f) => /postman_collection\\.json$/.test(f));
const collection = JSON.parse(fs.readFileSync(path.join(__dirname, collectionFile), 'utf8'));

const baseUrl = String(config.url || '').trim().replace(/\\/+$/, '');
if (!baseUrl) {
  console.error('config.json: "url" is empty - point it at the running service first');
  process.exit(2);
}

// header block from config, applied to every request
const headers = Object.entries(config.headers || {}).map(([key, value]) => ({ key, value }));

function walk(items) {
  for (const item of items || []) {
    if (item.item) walk(item.item);
    if (!item.request) continue;
    if (headers.length) item.request.header = headers;
    // payload override: config.json is the one place a human edits
    const resource = /^Post (.+)$/.exec(item.name || '');
    if (resource && config.payloads && config.payloads[resource[1]]) {
      const p = config.payloads[resource[1]].POST && config.payloads[resource[1]].POST.payload;
      if (p) item.request.body = { mode: 'raw', raw: JSON.stringify(p, null, 2) };
    }
  }
}
walk(collection.item);

collection.variable = [{ key: 'BASE_URL', value: baseUrl }];

newman.run(
  {
    collection,
    insecure: true,
    reporters: ['cli', 'html', 'json'],
    reporter: {
      html: { export: path.join(__dirname, '..', 'htmlResults.html') },
      json: { export: path.join(__dirname, '..', 'jsonResults.json') },
    },
  },
  function (err, summary) {
    if (err) {
      console.error('collection run failed: ' + err);
      process.exit(2);
    }
    const stats = summary.run.stats.assertions;
    console.log('');
    console.log('assertions: ' + (stats.total - stats.failed) + '/' + stats.total + ' passed, ' + stats.failed + ' failed');
    console.log('reports   : htmlResults.html, jsonResults.json');
    // non-zero on failure so CI can gate on it - the shipped kits exit 0 regardless,
    // which is why their "success" message is misleading
    process.exit(stats.failed > 0 ? 1 : 0);
  },
);
`;

const PKG = version => ({
  name: 'ctk-generated',
  version,
  private: true,
  description: 'Generated Conformance Test Kit (tmfgen)',
  main: 'index.js',
  scripts: { start: 'node index.js' },
  dependencies: {
    newman: '^6.2.1',
    'newman-reporter-html': '^1.0.5',
  },
});

function readme(ir, port) {
  const t = `TMF${ir.meta.tmfNumber} ${ir.meta.specTitle} v${ir.meta.specVersion}`;
  return `# Conformance Test Kit - ${t}

> **GENERATED by tmfgen.** TM Forum ships no kit for this component, so this one was
> derived from the component spec. It mirrors the coverage of TM Forum's own
> newman-based kits but is **not** a TM Forum artefact and carries no certification
> weight. For certification, contact TM Forum.

## Coverage

Per resource, for the operations the spec actually declares:

| Request | Asserts |
|---|---|
| \`POST /<resource>\` | 201, mandatory attributes, \`id\`, \`href\`, body echoes both |
| \`GET /<resource>\` | 200, collection shape, mandatory attributes |
| \`GET /<resource>/{id}\` | 200, \`id\` and \`href\` match the created instance |
| \`GET /<resource>?fields=id\` | 200, only \`id\`/\`href\`/requested attribute |
| \`GET /<resource>?id={id}\` | 200, filter returns the instance |
| \`GET /<resource>/404ID\` | 404 |

A read-only resource gets no create test, and without a create there is no id to
retrieve or filter by - so those requests are omitted rather than left to fail.

## Running

Start the service first (default port ${port}), then:

\`\`\`bash
cd ctk
npm install
npm start
\`\`\`

Point \`config.json\` at your deployment. Use an IPv4 literal, not \`localhost\`:
since Node 17 \`localhost\` resolves to IPv6 first, which older newman transports
cannot handle.

\`\`\`json
{ "url": "http://127.0.0.1:${port}/${ir.meta.basePath}/" }
\`\`\`

Results land in \`htmlResults.html\` and \`jsonResults.json\`. Unlike the shipped kits,
this runner **exits non-zero when assertions fail**, so it can gate CI.

## Editing payloads

\`config.json\` holds one POST payload per resource, synthesised from the spec's
required attributes. Where the spec carried a POST example, that example was used
instead. Adjust them to match your data - the payload is the usual reason a create
test fails.
`;
}

/**
 * @param ir   component IR
 * @param opts { url, port }
 * @returns [{ path, text }] relative to the service's backend/ctk/
 */
export function buildCtk(ir, opts = {}) {
  resetPayloadSeed();

  const payloads = {};
  const configPayloads = {};
  for (const resource of ir.resources) {
    if (!resource.operations?.create) continue;
    const body = synthesizePayload(resource, ir);
    payloads[resource.name] = body;
    configPayloads[resource.name] = { POST: { payload: body } };
  }

  const collection = buildCollection(ir, payloads);
  const port = opts.port ?? `3${ir.meta.tmfNumber}`;
  const url = opts.url ?? `http://127.0.0.1:${port}/${ir.meta.basePath}/`;

  const config = {
    url,
    headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
    payloads: configPayloads,
  };

  const slug = `CTK-${ir.meta.specTitle.replace(/\s+/g, '')}-${ir.meta.specVersion}`;

  return {
    files: [
      { path: 'config.json', text: `${JSON.stringify(config, null, 4)}\n` },
      { path: 'README.md', text: readme(ir, port) },
      { path: `ctk/${slug}.postman_collection.json`, text: `${JSON.stringify(collection, null, 2)}\n` },
      { path: 'ctk/index.js', text: RUNNER },
      { path: 'ctk/package.json', text: `${JSON.stringify(PKG(ir.meta.specVersion), null, 2)}\n` },
    ],
    resourceCount: collection.item.length,
    requestCount: collection.item.reduce((a, g) => a + g.item.length, 0),
    payloadCount: Object.keys(configPayloads).length,
  };
}
