// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// What GeographicAddressValidation lists can be filtered and sorted on (TMF630 attribute style + JSONPath
// `filter=`): the resource's own attributes, its single references and its embedded lists.
import type { FilterSchema } from '../common/filter/filter.types';
import { GeographicAddressValidation } from './entities/geographic-address-validation.entity';
import { GeographicAddressValidationAlternateGeographicAddress } from './entities/geographic-address-validation-alternate-geographic-address.entity';

export const GEOGRAPHIC_ADDRESS_VALIDATION_FILTER: FilterSchema = {
  entity: GeographicAddressValidation,
  attrs: {
    id: { property: 'id', type: 'string' },
    provideAlternative: { property: 'provideAlternative', type: 'boolean' },
    validationDate: { property: 'validationDate', type: 'date' },
    validationResult: { property: 'validationResult', type: 'string' },
    state: { property: 'state', type: 'string' },
    '@type': { property: 'atType', type: 'string' },
    '@schemaLocation': { property: 'atSchemaLocation', type: 'string' },
    '@baseType': { property: 'atBaseType', type: 'string' },
  },
  refs: {},
  arrays: {
    alternateGeographicAddress: {
      entity: GeographicAddressValidationAlternateGeographicAddress,
      attrs: {
        id: { property: 'refId', type: 'string' },
        city: { property: 'city', type: 'string' },
        country: { property: 'country', type: 'string' },
        locality: { property: 'locality', type: 'string' },
        name: { property: 'name', type: 'string' },
        postcode: { property: 'postcode', type: 'string' },
        stateOrProvince: { property: 'stateOrProvince', type: 'string' },
        streetName: { property: 'streetName', type: 'string' },
        streetNr: { property: 'streetNr', type: 'string' },
        streetNrLast: { property: 'streetNrLast', type: 'string' },
        streetNrLastSuffix: { property: 'streetNrLastSuffix', type: 'string' },
        streetNrSuffix: { property: 'streetNrSuffix', type: 'string' },
        streetSuffix: { property: 'streetSuffix', type: 'string' },
        streetType: { property: 'streetType', type: 'string' },
        '@type': { property: 'atType', type: 'string' },
        '@schemaLocation': { property: 'atSchemaLocation', type: 'string' },
        '@baseType': { property: 'atBaseType', type: 'string' },
      },
      refs: {
        geographicLocation: {
          relation: 'geographicLocation',
          attrs: {
            id: { property: 'refId', type: 'string' },
            href: { property: 'href', type: 'string' },
            name: { property: 'name', type: 'string' },
            '@referredType': { property: 'referredType', type: 'string' },
            '@type': { property: 'atType', type: 'string' },
            '@schemaLocation': { property: 'atSchemaLocation', type: 'string' },
            '@baseType': { property: 'atBaseType', type: 'string' },
          },
        },
      },
    },
  },
  timestamps: {
    createdDate: { property: 'createdDate', type: 'date' },
    lastUpdate: { property: 'lastUpdate', type: 'date' },
  },
  reserved: [],
};
