import fs from 'node:fs';
import path from 'node:path';
import { kebab } from '../ir/naming.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';

/**
 * Controller emitter.
 *
 * Routes are emitted ONLY for operations the spec declares, so a read-only resource
 * (TMF673's GeographicAddress declares just list + retrieve) never gets invented
 * create/update/delete endpoints.
 *
 * Swagger goes beyond the reference, which carries only @ApiTags: operationId,
 * summary, description and the documented status codes are already in the spec, so
 * emitting them costs nothing and makes the generated API self-describing.
 *
 * Pagination headers come from PaginationInterceptor (it unwraps { data, total });
 * @Res is used only in create, to set the TMF Location header.
 */

const STATUS_TEXT = {
  200: 'Success', 201: 'Created', 202: 'Accepted', 204: 'Deleted',
  400: 'Bad Request', 401: 'Unauthorized', 403: 'Forbidden', 404: 'Not Found',
  405: 'Method Not Allowed', 409: 'Conflict', 500: 'Internal Server Error',
  501: 'Not Implemented', 503: 'Service Unavailable',
};

function swaggerFor(op, extra = []) {
  if (!op) return [];
  const lines = [];
  const parts = [];
  if (op.summary) parts.push(`summary: '${op.summary.replace(/'/g, "\\'")}'`);
  if (op.description && op.description !== op.summary) {
    parts.push(`description: '${op.description.replace(/\s+/g, ' ').trim().replace(/'/g, "\\'")}'`);
  }
  if (op.operationId) parts.push(`operationId: '${op.operationId}'`);
  if (parts.length) lines.push(`  @ApiOperation({ ${parts.join(', ')} })`);
  for (const code of op.statuses ?? []) {
    const n = Number(code);
    if (n >= 500) continue; // the filter handles these uniformly; keep the surface readable
    lines.push(`  @ApiResponse({ status: ${n}, description: '${STATUS_TEXT[n] ?? 'Response'}' })`);
  }
  lines.push(...extra);
  return lines;
}

export function renderController(resource, ctx) {
  const { basePathConstant } = ctx;
  // nested: { routeSegment, params } from nestedRouteInfo(); null when flat, in which
  // case every line below is byte-identical to what it emitted before
  const nested = ctx.nested ?? null;
  const parentParams = nested?.params ?? [];
  const parentArgs = parentParams.map(p => `    @Param('${p}') ${p}: string,`);
  const parentSpread = parentParams.map(p => `${p}`).join(', ');
  const parentObj = parentParams.length ? `, { ${parentSpread} }` : '';
  // A hand-written host may not have ApiKeyGuard at all (the geographic service has
  // no guards directory), so the decorator and its import are conditional.
  const useGuard = ctx.host ? ctx.host.hasApiKeyGuard !== false : true;
  const className = `${resource.name}Controller`;
  const serviceClass = `${resource.name}Service`;
  const ops = resource.operations;

  const nestImports = new Set(['Controller', 'UseInterceptors']);
  if (parentParams.length) nestImports.add('Param');
  if (useGuard) nestImports.add('UseGuards');
  const swaggerImports = new Set(['ApiTags']);
  if (ops.list || ops.retrieve || ops.create || ops.update || ops.delete) swaggerImports.add('ApiOperation').add('ApiResponse');

  const methods = [];

  if (ops.create) {
    nestImports.add('Post').add('Body').add('HttpCode').add('HttpStatus').add('Res');
    methods.push([
      '  @Post()',
      '  @HttpCode(HttpStatus.CREATED)',
      ...swaggerFor(ops.create),
      `  async create(`,
      ...parentArgs,
      `    @Body() dto: Create${resource.name}Dto,`,
      '    @Res({ passthrough: true }) res: Response,',
      '  ): Promise<Record<string, any>> {',
      parentParams.length
        ? `    const result = await this.service.create({ ...dto, ${parentSpread} } as Create${resource.name}Dto);`
        : '    const result = await this.service.create(dto);',
      '    if (result?.href) {',
      '      res.location(result.href);',
      '    }',
      '    return result;',
      '  }',
    ].join('\n'));
  }

  if (ops.list) {
    nestImports.add('Get').add('Query');
    methods.push([
      '  @Get()',
      ...swaggerFor(ops.list),
      parentParams.length
        ? `  findAll(${parentParams.map(x => `@Param('${x}') ${x}: string`).join(', ')}, @Query() query: Query${resource.name}Dto) {`
        : `  findAll(@Query() query: Query${resource.name}Dto) {`,
      parentParams.length
        ? `    return this.service.findAll({ ...query, ${parentSpread} });`
        : '    return this.service.findAll(query);',
      '  }',
    ].join('\n'));
  }

  if (ops.retrieve) {
    nestImports.add('Get').add('Param').add('Query');
    swaggerImports.add('ApiParam');
    methods.push([
      "  @Get(':id')",
      ...swaggerFor(ops.retrieve, [`  @ApiParam({ name: 'id', description: 'Identifier of the ${resource.name}' })`]),
      '  findOne(',
      ...parentArgs,
      "    @Param('id') id: string,",
      "    @Query('fields') fields?: string,",
      '  ): Promise<Record<string, any>> {',
      `    return this.service.findOne(id, fields${parentObj});`,
      '  }',
    ].join('\n'));
  }

  if (ops.update) {
    nestImports.add('Patch').add('Param').add('Body');
    swaggerImports.add('ApiParam');
    methods.push([
      "  @Patch(':id')",
      ...swaggerFor(ops.update, [`  @ApiParam({ name: 'id', description: 'Identifier of the ${resource.name}' })`]),
      '  update(',
      ...parentArgs,
      "    @Param('id') id: string,",
      `    @Body() dto: Update${resource.name}Dto,`,
      '  ): Promise<Record<string, any>> {',
      `    return this.service.update(id, dto${parentObj});`,
      '  }',
    ].join('\n'));
  }

  if (ops.delete) {
    nestImports.add('Delete').add('Param').add('HttpCode').add('HttpStatus');
    swaggerImports.add('ApiParam');
    methods.push([
      "  @Delete(':id')",
      '  @HttpCode(HttpStatus.NO_CONTENT)',
      ...swaggerFor(ops.delete, [`  @ApiParam({ name: 'id', description: 'Identifier of the ${resource.name}' })`]),
      parentParams.length
        ? `  remove(${parentParams.map(x => `@Param('${x}') ${x}: string`).join(', ')}, @Param('id') id: string): Promise<void> {`
        : "  remove(@Param('id') id: string): Promise<void> {",
      parentParams.length
        ? `    return this.service.remove(id, undefined, undefined, { ${parentSpread} });`
        : '    return this.service.remove(id);',
      '  }',
    ].join('\n'));
  }

  const dtoNames = [
    ops.create ? `Create${resource.name}Dto` : null,
    ops.update ? `Update${resource.name}Dto` : null,
    ops.list ? `Query${resource.name}Dto` : null,
  ].filter(Boolean);

  const order = ['Controller', 'Get', 'Post', 'Patch', 'Delete', 'Body', 'Param', 'Query',
    'HttpCode', 'HttpStatus', 'Res', 'UseGuards', 'UseInterceptors'];

  const imports = [
    `import { ${order.filter(n => nestImports.has(n)).join(', ')} } from '@nestjs/common';`,
    `import { ${['ApiTags', 'ApiOperation', 'ApiParam', 'ApiResponse'].filter(n => swaggerImports.has(n)).join(', ')} } from '@nestjs/swagger';`,
    ...(ops.create ? ["import { Response } from 'express';"] : []),
    `import { ${basePathConstant} } from '../common/constants/tmf.constants';`,
    ...(useGuard ? ["import { ApiKeyGuard } from '../common/guards/api-key.guard';"] : []),
    "import { PaginationInterceptor } from '../common/interceptors/pagination.interceptor';",
    `import { ${serviceClass} } from './${kebab(resource.name)}.service';`,
    ...(dtoNames.length ? [`import { ${dtoNames.join(', ')} } from './dto';`] : []),
  ];

  return {
    fileName: `${kebab(resource.name)}.controller.ts`,
    className,
    text: [
      BANNER,
      imports.join('\n'),
      '',
      `@ApiTags('${resource.camelName}')`,
      ...(useGuard ? ['@UseGuards(ApiKeyGuard)'] : []),
      '@UseInterceptors(PaginationInterceptor)',
      `@Controller(\`\${${basePathConstant}}/${nested ? nested.routeSegment : resource.pathSegment}\`)`,
      `export class ${className} {`,
      `  constructor(private readonly service: ${serviceClass}) {}`,
      '',
      methods.join('\n\n'),
      '}',
      '',
    ].join('\n'),
  };
}

/**
 * A resource may carry a HAND-WRITTEN controller beside the generated one, at
 * `src/<dir>/<dir>.controller.extra.ts`. The README has advertised this as a
 * supported extension point all along, but nothing implemented it: the module is
 * generated, so whoever registered the extra controller had their one line silently
 * removed by the next `emit`. TMF654's hand-written `POST /bucket` route went from
 * 486/0 back to 476/9 exactly that way, during a routine re-emit.
 *
 * Detected by the file simply being there - no flag, no config - and registered
 * alongside the generated controller. Nest is happy with two controllers on one base
 * path as long as no method+path pair collides, which is the whole point: the extra
 * file exists to add operations the spec does not declare.
 */
export function extraControllerFor(backendDir, dir) {
  if (!backendDir) return null;
  const file = `${dir}.controller.extra.ts`;
  if (!fs.existsSync(path.join(backendDir, 'src', dir, file))) return null;
  const text = fs.readFileSync(path.join(backendDir, 'src', dir, file), 'utf8');
  const className = (text.match(/export\s+class\s+(\w+)/) ?? [])[1];
  return className ? { className, importPath: `./${dir}.controller.extra` } : null;
}

export function renderModule(resource, entityClasses, naming = null, extra = null) {
  // naming comes from moduleNaming(): a resource whose kebab name collides with a
  // scaffold-owned directory (event/subscription/listener/common) is emitted under a
  // prefixed identity so it cannot overwrite the infra module of the same name.
  const className = naming?.moduleClass ?? `${resource.name}Module`;
  const fileBase = naming?.moduleFileBase ?? kebab(resource.name);
  return {
    fileName: `${fileBase}.module.ts`,
    className,
    text: [
      BANNER,
      "import { Module } from '@nestjs/common';",
      "import { TypeOrmModule } from '@nestjs/typeorm';",
      "import { EventModule } from '../event/event.module';",
      `import { ${resource.name}Controller } from './${kebab(resource.name)}.controller';`,
      `import { ${resource.name}Service } from './${kebab(resource.name)}.service';`,
      ...(extra ? [`import { ${extra.className} } from '${extra.importPath}';`] : []),
      ...entityClasses.map(c => `import { ${c.className} } from '${c.importFrom}';`),
      '',
      '@Module({',
      '  imports: [',
      '    TypeOrmModule.forFeature([',
      ...entityClasses.map(c => `      ${c.className},`),
      '    ]),',
      '    EventModule,',
      '  ],',
      `  controllers: [${resource.name}Controller${extra ? `, ${extra.className}` : ''}],`,
      `  providers: [${resource.name}Service],`,
      `  exports: [${resource.name}Service],`,
      '})',
      `export class ${className} {}`,
      '',
    ].join('\n'),
  };
}

/**
 * Hand-written extension point. Written ONCE if absent and never overwritten, so
 * the always-overwrite policy for generated files stays safe: nothing a human edits
 * lives in a managed file.
 */
export function renderHooks(resource) {
  return {
    fileName: `${kebab(resource.name)}.hooks.ts`,
    text: [
      `// NOT managed by tmfgen. Created once if missing; never overwritten.`,
      '//',
      '// Put domain logic here - cross-resource reference resolution, business-rule',
      '// validation, response decoration. The generated service calls these at fixed',
      '// points. Returning undefined leaves the input untouched.',
      '',
      `import { Create${resource.name}Dto, Update${resource.name}Dto } from './dto';`,
      '',
      '/** Runs before the entity is built. Return a modified payload, or undefined. */',
      `export async function beforeCreate(`,
      `  dto: Record<string, any> | Create${resource.name}Dto,`,
      '): Promise<Record<string, any> | undefined> {',
      '  return undefined;',
      '}',
      '',
      '/** Runs before the update transaction. Return a modified payload, or undefined. */',
      'export async function beforeUpdate(',
      '  id: string,',
      `  dto: Record<string, any> | Update${resource.name}Dto,`,
      '): Promise<Record<string, any> | undefined> {',
      '  return undefined;',
      '}',
      '',
      '/** Runs after a single resource is mapped. Return a modified response, or undefined. */',
      'export async function afterFindOne(',
      '  response: Record<string, any>,',
      '  entity: unknown,',
      '): Promise<Record<string, any> | undefined> {',
      '  return undefined;',
      '}',
      '',
    ].join('\n'),
  };
}
