import { createHash } from 'node:crypto';
import { kebab, snake } from '../ir/naming.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';

/**
 * Column types that are not portable across the databases the scaffold offers.
 *
 * The IR stores dates as `datetime` - a deliberate invariant in ir/typeMap.mjs, taken
 * for SQLite portability. But the scaffold ALSO emits an app.module.ts that branches
 * on DATABASE_TYPE at runtime and an .env.example carrying a ready-made postgres
 * block, so postgres was advertised as a supported option while the column type was
 * frozen at generate time. Every service with a date field died at
 * DataSource.initialize() with:
 *
 *   DataTypeNotSupportedError: Data type "datetime" ... is not supported by "postgres"
 *
 * Translating here keeps the IR db-agnostic and leaves `sqlite` byte-identical to
 * what it emitted before.
 */
const DB_COLUMN_TYPES = {
  datetime: { sqlite: 'datetime', postgres: 'timestamp' },
};

export function columnTypeFor(type, dbType = 'sqlite') {
  const row = DB_COLUMN_TYPES[type];
  if (!row) return type;
  return row[dbType] ?? type;
}

/** Serialise column options in the reference's key order. */
function columnOptions(col, dbType) {
  const parts = [];
  if (col.type) parts.push(`type: '${columnTypeFor(col.type, dbType)}'`);
  if (col.length) parts.push(`length: ${col.length}`);
  if (col.nullable) parts.push('nullable: true');
  if (col.default !== undefined && col.default !== null) parts.push(`default: '${col.default}'`);
  return `{ ${parts.join(', ')} }`;
}

function renderColumn(c, dbType) {
  const lines = [];
  const q = c.optional ? '?' : '';

  if (c.description) lines.push(`  /** ${c.description.replace(/\s+/g, ' ').trim()} */`);
  if (c.enumValues?.length) lines.push(`  /** Allowed: ${c.enumValues.join(' | ')} */`);

  if (c.primary) {
    lines.push(`  @PrimaryColumn(${columnOptions(c.column, dbType)})`);
    lines.push(`  ${c.name}: ${c.tsType};`);
    return lines.join('\n');
  }
  if (c.createDateColumn) {
    lines.push('  @CreateDateColumn()');
    lines.push(`  ${c.name}: Date;`);
    return lines.join('\n');
  }
  if (c.updateDateColumn) {
    lines.push('  @UpdateDateColumn()');
    lines.push(`  ${c.name}: Date;`);
    return lines.join('\n');
  }
  if (c.deleteDateColumn) {
    lines.push('  @DeleteDateColumn({ nullable: true })');
    lines.push(`  ${c.name}?: Date;`);
    return lines.join('\n');
  }

  if (c.expose) lines.push(`  @Expose({ name: '${c.expose}' })`);
  lines.push(`  @Column(${columnOptions(c.column, dbType)})`);
  lines.push(`  ${c.name}${q}: ${c.tsType};`);
  return lines.join('\n');
}

/**
 * Join-column names for one entity, de-duplicated.
 *
 * The owner back-reference takes its name from the TARGET class
 * (`<target>_id`) while a normalised ref takes it from the PROPERTY
 * (`<property>_id`). Those two rules can land on the same string: TMF909's
 * service_relationship has a `many-to-one-owner` to `Service` and a
 * `many-to-one-ref` on property `service` (target `ServiceRef`), and both wanted
 * `service_id`.
 *
 * Nothing checked for that, so TypeORM derived one FK constraint name (a hash of
 * table + columns) for both and synchronize died on the FIRST run with
 *
 *   constraint "FK_8fef8b83..." for relation "service_relationship" already exists
 *
 * The service could never boot - not a query-time failure, a startup failure.
 *
 * Owner relations are resolved first so the structural parent FK keeps the
 * unsuffixed name and only the colliding ref is renamed.
 */
/**
 * Keep a join-column name inside PostgreSQL's 63-byte identifier limit.
 *
 * Postgres does NOT reject a long column name - it truncates it, and then never
 * agrees with the name TypeORM has in its metadata. `synchronize` sees one column
 * it does not know and one it expects but cannot find, reads that as a rename, and
 * the ALTER fails:
 *
 *   column "measurement_collection_job_performance_indicator_group_specific" of
 *   relation "performance_indicator_specification_ref_or_value" already exists
 *
 * TMF628 hit exactly this: a 71-character owner FK. It survived a first boot (one
 * CREATE TABLE, no rename step) and then failed on every boot against an existing
 * schema - `yarn seed` followed by `yarn start` was enough to make it unbootable.
 *
 * Same rule as the query aliases in service.mjs: truncate and append a hash of the
 * FULL name, so two names sharing a truncated prefix stay distinct and the result is
 * stable across runs.
 */
const PG_IDENTIFIER_LIMIT = 63;
const IDENTIFIER_HASH_LEN = 6;
function pgIdentifier(name) {
  if (name.length <= PG_IDENTIFIER_LIMIT) return name;
  const suffix = createHash('sha1').update(name).digest('hex').slice(0, IDENTIFIER_HASH_LEN);
  return `${name.slice(0, PG_IDENTIFIER_LIMIT - IDENTIFIER_HASH_LEN - 1)}_${suffix}`;
}

function joinColumnNames(entity, resolve) {
  const taken = new Set();
  const names = new Map();
  const ordered = [
    ...entity.relations.filter(r => r.kind === 'many-to-one-owner'),
    ...entity.relations.filter(r => r.kind !== 'many-to-one-owner'),
  ];

  for (const r of ordered) {
    if (r.kind === 'one-to-many') continue;
    const target = resolve(r.targetKey);
    const base = r.kind === 'many-to-one-owner'
      ? `${snake(target?.className ?? r.property)}_id`
      : r.joinColumn;

    let name = base;
    if (taken.has(name)) {
      // prefer the target class, which is what actually distinguishes the two
      const byTarget = target ? `${snake(target.className)}_id` : null;
      name = byTarget && !taken.has(byTarget)
        ? byTarget
        : `${snake(r.property)}_${snake(target?.className ?? 'ref')}_id`;
    }
    name = pgIdentifier(name);
    taken.add(name);
    names.set(r, name);
  }
  return names;
}

function renderRelation(r, resolve, joinColumn) {
  const target = resolve(r.targetKey);
  if (!target) throw new Error(`relation ${r.property} targets unresolved key ${r.targetKey}`);

  switch (r.kind) {
    case 'one-to-many':
      return [
        `  @OneToMany(() => ${target.className}, (child) => child.${r.inverse}, {`,
        // cascade ONLY for a REQUIRED reference. There the FK cannot be null, so the
        // referenced row has to be written with the aggregate - including its own
        // required references (TMF708 nests two levels deep). For a NULLABLE reference
        // we must not fabricate a row: TMF654 posts bucket {id:"11"} for a bucket that
        // does not exist, and inventing it put a blank row into the Bucket resource's
        // own table, which its conformance kit then listed and failed on.
        ...(r.nullable ? [] : ['    cascade: true,']),
        '    eager: true,',
        "    orphanedRowAction: 'delete',",
        '  })',
        `  ${r.property}: ${target.className}[];`,
      ].join('\n');

    case 'many-to-one-owner':
      return [
        `  @ManyToOne(() => ${target.className}, (parent) => parent.${r.inverse}, {`,
        "    onDelete: 'CASCADE',",
        '    nullable: false,',
        '  })',
        `  @JoinColumn({ name: '${joinColumn}' })`,
        `  ${r.property}: ${target.className};`,
      ].join('\n');

    case 'many-to-one-ref':
      return [
        '  // normalised single ref: own table, FK held here',
        `  @ManyToOne(() => ${target.className}, {`,
        '    cascade: true,',
        '    eager: true,',
        '    nullable: true,',
        '  })',
        `  @JoinColumn({ name: '${joinColumn}' })`,
        `  ${r.property}?: ${target.className};`,
      ].join('\n');

    case 'many-to-one-resource':
      return [
        '  // reference to a sibling resource of this service',
        `  @ManyToOne(() => ${target.className}, {`,
        '    eager: true,',
        // cascade so a referenced row that does not exist yet is written with the
        // aggregate, INCLUDING its own required references. The builder upserts the
        // first level explicitly (see service.mjs), but a reference two levels deep -
        // TMF708 posts TestSuiteExecution -> provisioningExecution -> allocationExecution -
        // was left with a null FK and the insert failed on the constraint.
        '    cascade: true,',
        `    nullable: ${r.nullable},`,
        '  })',
        `  @JoinColumn({ name: '${joinColumn}' })`,
        `  ${r.property}${r.nullable ? '?' : ''}: ${target.className};`,
      ].join('\n');

    default:
      throw new Error(`unknown relation kind: ${r.kind}`);
  }
}

function typeormImports(entity) {
  const used = new Set(['Entity', 'Column']);
  for (const c of entity.columns) {
    if (c.primary) used.add('PrimaryColumn');
    if (c.createDateColumn) used.add('CreateDateColumn');
    if (c.updateDateColumn) used.add('UpdateDateColumn');
    if (c.deleteDateColumn) used.add('DeleteDateColumn');
  }
  for (const r of entity.relations) {
    if (r.kind === 'one-to-many') used.add('OneToMany');
    else { used.add('ManyToOne'); used.add('JoinColumn'); }
  }
  const order = ['Entity', 'PrimaryColumn', 'Column', 'ManyToOne', 'OneToMany', 'JoinColumn',
    'CreateDateColumn', 'UpdateDateColumn', 'DeleteDateColumn'];
  return order.filter(n => used.has(n));
}

export const entityFileName = className => `${kebab(className)}.entity.ts`;

/**
 * @param entity plan entity
 * @param self   resolved { className, tableName } for this entity
 * @param resolve key -> resolved { className, tableName }
 * @param importDirOf key -> module directory of the target (for cross-module imports)
 */
export function renderEntity(entity, self, resolve, importDirOf, selfDir, dbType = 'sqlite') {
  const tmImports = typeormImports(entity);
  const needsExpose = entity.columns.some(c => c.expose);

  const targets = new Map();
  for (const r of entity.relations) {
    const t = resolve(r.targetKey);
    if (!t || t.className === self.className) continue;
    const dir = importDirOf(r.targetKey);
    const rel = dir === selfDir
      ? `./${kebab(t.className)}.entity`
      : `../../${dir}/entities/${kebab(t.className)}.entity`;
    targets.set(t.className, rel);
  }

  const imports = [
    `import { ${tmImports.join(', ')} } from 'typeorm';`,
    ...(needsExpose ? ["import { Expose } from 'class-transformer';"] : []),
    ...[...targets.entries()].sort((a, b) => a[0].localeCompare(b[0]))
      .map(([name, rel]) => `import { ${name} } from '${rel}';`),
  ];

  const doc = entity.description
    ? ['/**', ` * ${entity.description.replace(/\s+/g, ' ').trim()}`, ' */'].join('\n')
    : null;

  const joinColumns = joinColumnNames(entity, resolve);
  const body = [
    ...entity.columns.map(c => renderColumn(c, dbType)),
    ...entity.relations.map(r => renderRelation(r, resolve, joinColumns.get(r))),
  ].join('\n\n');

  return [
    BANNER,
    imports.join('\n'),
    '',
    ...(doc ? [doc] : []),
    `@Entity('${self.tableName}')`,
    `export class ${self.className} {`,
    body,
    '}',
    '',
  ].join('\n');
}
