import { kebab, snake } from '../ir/naming.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';

/** Serialise column options in the reference's key order. */
function columnOptions(col) {
  const parts = [];
  if (col.type) parts.push(`type: '${col.type}'`);
  if (col.length) parts.push(`length: ${col.length}`);
  if (col.nullable) parts.push('nullable: true');
  if (col.default !== undefined && col.default !== null) parts.push(`default: '${col.default}'`);
  return `{ ${parts.join(', ')} }`;
}

function renderColumn(c) {
  const lines = [];
  const q = c.optional ? '?' : '';

  if (c.description) lines.push(`  /** ${c.description.replace(/\s+/g, ' ').trim()} */`);
  if (c.enumValues?.length) lines.push(`  /** Allowed: ${c.enumValues.join(' | ')} */`);

  if (c.primary) {
    lines.push(`  @PrimaryColumn(${columnOptions(c.column)})`);
    lines.push(`  ${c.name}: ${c.tsType};`);
    return lines.join('\n');
  }
  if (c.createDateColumn) {
    lines.push('  @CreateDateColumn()');
    lines.push(`  ${c.name}: Date;`);
    return lines.join('\n');
  }
  if (c.updateDateColumn) {
    lines.push('  @UpdateDateColumn()');
    lines.push(`  ${c.name}: Date;`);
    return lines.join('\n');
  }
  if (c.deleteDateColumn) {
    lines.push('  @DeleteDateColumn({ nullable: true })');
    lines.push(`  ${c.name}?: Date;`);
    return lines.join('\n');
  }

  if (c.expose) lines.push(`  @Expose({ name: '${c.expose}' })`);
  lines.push(`  @Column(${columnOptions(c.column)})`);
  lines.push(`  ${c.name}${q}: ${c.tsType};`);
  return lines.join('\n');
}

function renderRelation(r, resolve) {
  const target = resolve(r.targetKey);
  if (!target) throw new Error(`relation ${r.property} targets unresolved key ${r.targetKey}`);

  switch (r.kind) {
    case 'one-to-many':
      return [
        `  @OneToMany(() => ${target.className}, (child) => child.${r.inverse}, {`,
        '    cascade: true,',
        '    eager: true,',
        "    orphanedRowAction: 'delete',",
        '  })',
        `  ${r.property}: ${target.className}[];`,
      ].join('\n');

    case 'many-to-one-owner':
      return [
        `  @ManyToOne(() => ${target.className}, (parent) => parent.${r.inverse}, {`,
        "    onDelete: 'CASCADE',",
        '    nullable: false,',
        '  })',
        `  @JoinColumn({ name: '${snake(target.className)}_id' })`,
        `  ${r.property}: ${target.className};`,
      ].join('\n');

    case 'many-to-one-ref':
      return [
        '  // normalised single ref: own table, FK held here',
        `  @ManyToOne(() => ${target.className}, {`,
        '    cascade: true,',
        '    eager: true,',
        '    nullable: true,',
        '  })',
        `  @JoinColumn({ name: '${r.joinColumn}' })`,
        `  ${r.property}?: ${target.className};`,
      ].join('\n');

    case 'many-to-one-resource':
      return [
        '  // reference to a sibling resource of this service',
        `  @ManyToOne(() => ${target.className}, {`,
        '    eager: true,',
        `    nullable: ${r.nullable},`,
        '  })',
        `  @JoinColumn({ name: '${r.joinColumn}' })`,
        `  ${r.property}${r.nullable ? '?' : ''}: ${target.className};`,
      ].join('\n');

    default:
      throw new Error(`unknown relation kind: ${r.kind}`);
  }
}

function typeormImports(entity) {
  const used = new Set(['Entity', 'Column']);
  for (const c of entity.columns) {
    if (c.primary) used.add('PrimaryColumn');
    if (c.createDateColumn) used.add('CreateDateColumn');
    if (c.updateDateColumn) used.add('UpdateDateColumn');
    if (c.deleteDateColumn) used.add('DeleteDateColumn');
  }
  for (const r of entity.relations) {
    if (r.kind === 'one-to-many') used.add('OneToMany');
    else { used.add('ManyToOne'); used.add('JoinColumn'); }
  }
  const order = ['Entity', 'PrimaryColumn', 'Column', 'ManyToOne', 'OneToMany', 'JoinColumn',
    'CreateDateColumn', 'UpdateDateColumn', 'DeleteDateColumn'];
  return order.filter(n => used.has(n));
}

export const entityFileName = className => `${kebab(className)}.entity.ts`;

/**
 * @param entity plan entity
 * @param self   resolved { className, tableName } for this entity
 * @param resolve key -> resolved { className, tableName }
 * @param importDirOf key -> module directory of the target (for cross-module imports)
 */
export function renderEntity(entity, self, resolve, importDirOf, selfDir) {
  const tmImports = typeormImports(entity);
  const needsExpose = entity.columns.some(c => c.expose);

  const targets = new Map();
  for (const r of entity.relations) {
    const t = resolve(r.targetKey);
    if (!t || t.className === self.className) continue;
    const dir = importDirOf(r.targetKey);
    const rel = dir === selfDir
      ? `./${kebab(t.className)}.entity`
      : `../../${dir}/entities/${kebab(t.className)}.entity`;
    targets.set(t.className, rel);
  }

  const imports = [
    `import { ${tmImports.join(', ')} } from 'typeorm';`,
    ...(needsExpose ? ["import { Expose } from 'class-transformer';"] : []),
    ...[...targets.entries()].sort((a, b) => a[0].localeCompare(b[0]))
      .map(([name, rel]) => `import { ${name} } from '${rel}';`),
  ];

  const doc = entity.description
    ? ['/**', ` * ${entity.description.replace(/\s+/g, ' ').trim()}`, ' */'].join('\n')
    : null;

  const body = [
    ...entity.columns.map(renderColumn),
    ...entity.relations.map(r => renderRelation(r, resolve)),
  ].join('\n\n');

  return [
    BANNER,
    imports.join('\n'),
    '',
    ...(doc ? [doc] : []),
    `@Entity('${self.tableName}')`,
    `export class ${self.className} {`,
    body,
    '}',
    '',
  ].join('\n');
}
