import fs from 'node:fs';
import path from 'node:path';
import { kebab } from '../ir/naming.mjs';
import { buildEntityPlan, resolveEntityNames } from './entityPlan.mjs';
import { renderEntity, entityFileName } from './entity.mjs';
import { renderPayloadDto, renderQueryDto, renderDtoBarrel } from './dto.mjs';
import { renderService } from './service.mjs';
import { renderController, renderModule, renderHooks, extraControllerFor } from './controller.mjs';
import { renderSeedData, renderLocalSeedStub, orderSeedsByReference } from './seed.mjs';
import { moduleNaming, SCAFFOLD_OWNED_ROUTES } from './moduleNaming.mjs';
import { nestedRouteInfo, parentKeyColumn } from './nestedRoutes.mjs';
import { buildEagerGraph, countEagerJoinPaths, SQLITE_MAX_JOIN_TABLES, JOIN_WARN_THRESHOLD } from './eagerJoins.mjs';
import { scaffoldContext } from '../scaffold/newService.mjs';
import { readManifest, writeManifest, componentEntry, writeWiring, orderedComponents } from './wiring.mjs';
import { emitSpecs } from './spec/index.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';

/**
 * Emit entities + DTOs for every resource, then regenerate the global entities.ts
 * barrel so TypeORM registers everything.
 *
 * Names are resolved across ALL resources at once, so two resources referencing the
 * same schema share one normalised table instead of duplicating it, and any table
 * name past PostgreSQL's 63-byte identifier limit fails the run.
 *
 * Module directory is kebab(resource.name). Nested resources are emitted flat for
 * now; the reference nests them, which matters for controller routes in M4, not for
 * entity registration.
 */
export function emitResources(ir, options) {
  // dbType decides column types that are not portable (see entity.mjs). Default
  // 'sqlite' keeps output byte-identical to what earlier runs produced.
  const { backendDir, host = null, mode = 'own', dryRun = false, dbType = 'sqlite',
    nestedRoutes = false } = options;
  const written = [];
  const warnings = [];

  // ── pass 1: plan every resource, collect all entities ──
  const plans = [];
  for (const resource of ir.resources) {
    const plan = buildEntityPlan(resource, options);
    warnings.push(...plan.warnings);
    // Module identity is guarded against the namespaces scaffold owns; see
    // moduleNaming.mjs. Route paths are NOT touched - those belong to the spec.
    const naming = moduleNaming(resource.name);
    if (naming.remappedFrom) {
      warnings.push(
        `${resource.name}: resource name collides with the scaffold-owned src/${naming.remappedFrom}/ module; ` +
        `emitted as ${naming.moduleClass} in src/${naming.dir}/ instead. Route path is unchanged.`,
      );
    }
    const ownedBy = SCAFFOLD_OWNED_ROUTES.get(resource.pathSegment);
    if (ownedBy && !resource.nested) {
      warnings.push(
        `${resource.name}: route /${resource.pathSegment} is also claimed by ${ownedBy}; ` +
        `Nest resolves the overlap by module registration order, not by rejecting it. Verify which one you want serving that path.`,
      );
    }
    // Nested routes are opt-in: enabling them changes the API contract of any
    // already-generated service that has a nested resource. See nestedRoutes.mjs.
    const nested = nestedRouteInfo(resource, nestedRoutes);
    if (nested) {
      const root = plan.entities.find(e => e.kind === 'root');
      const parentLabel = (resource.parentSegments ?? []).join('/') || 'parent';
      for (const pp of nested.params) {
        if (!root.columns.some(c => c.name === pp)) {
          root.columns.push(parentKeyColumn(pp, resource.name, parentLabel));
        }
      }
    } else if (resource.nested && !nestedRoutes) {
      warnings.push(
        `${resource.name}: the spec nests this under ${resource.paths?.collection ?? '(unknown)'} but it is emitted flat ` +
        `at /${resource.pathSegment}; the parent key is dropped, so rows are indistinguishable across parents. ` +
        `Pass --nested-routes to emit it as the spec declares (changes the API contract).`,
      );
    }
    plans.push({ resource, plan, dir: naming.dir, naming, nested });
  }

  const allEntities = plans.flatMap(p => p.plan.entities);
  const { names, merged, errors, collisions } = resolveEntityNames(allEntities);
  warnings.push(...collisions);
  if (errors.length) {
    const err = new Error(`entity naming failed:\n  - ${errors.join('\n  - ')}`);
    err.errors = errors;
    throw err;
  }

  const resolve = key => names.get(key) ?? null;

  // Eager relations expand transitively across SHARED entity classes, so the real
  // join width is far above any single resource's relation list. See eagerJoins.mjs.
  const eagerGraph = buildEagerGraph(plans, resolve);
  for (const { resource, plan } of plans) {
    const rootEntity = plan.entities.find(e => e.kind === 'root');
    const rootClass = rootEntity ? resolve(rootEntity.key)?.className : null;
    if (!rootClass) continue;
    const tables = countEagerJoinPaths(eagerGraph, rootClass) + 1;
    if (tables < JOIN_WARN_THRESHOLD) continue;
    warnings.push(
      `${resource.name}: one read eagerly joins about ${tables} tables (a lower bound), ` +
      `against SQLite's hard limit of ${SQLITE_MAX_JOIN_TABLES} ("SQLITE_ERROR: at most 64 tables in a join"). ` +
      `This fails at RUNTIME, not here - run this component on postgres (emit --db postgres).`,
    );
  }

  // A shared entity is written ONCE, under the module of the first resource that
  // needs it. Import paths must point at where the file actually lands, so the
  // directory is keyed by final class name (first writer wins) - not by the plan
  // currently being rendered, which is what produced broken relative imports.
  const dirByClass = new Map();
  for (const p of plans) {
    for (const e of p.plan.entities) {
      const self = resolve(e.key);
      if (self && !dirByClass.has(self.className)) dirByClass.set(self.className, p.dir);
    }
  }
  const importDirOf = key => {
    const self = resolve(key);
    return self ? dirByClass.get(self.className) ?? '' : '';
  };

  const writeFile = (rel, content) => {
    written.push(rel);
    if (dryRun) return;
    const abs = path.join(backendDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf8');
  };

  // ── pass 2: render ──
  const resourceModules = [];
  const seeds = [];
  const preserved = [];
  const barrelEntries = [];
  const emittedClasses = new Set();
  const perResource = [];

  for (const { resource, plan, dir, naming, nested } of plans) {
    const rows = [];
    for (const entity of plan.entities) {
      const self = resolve(entity.key);
      // a merged duplicate resolves to a class another resource already emitted
      if (emittedClasses.has(self.className)) {
        rows.push({ ...self, kind: entity.kind, columns: entity.columns.length, relations: entity.relations.length, reused: true, softDelete: entity.softDelete });
        continue;
      }
      emittedClasses.add(self.className);

      const rel = `src/${dir}/entities/${entityFileName(self.className)}`;
      writeFile(rel, renderEntity(entity, self, resolve, importDirOf, dir, dbType));
      barrelEntries.push({
        className: self.className,
        importPath: `${dir}/entities/${entityFileName(self.className).replace(/\.ts$/, '')}`,
      });
      rows.push({
        ...self, kind: entity.kind,
        columns: entity.columns.length, relations: entity.relations.length,
        softDelete: entity.softDelete, reused: false,
      });
    }

    // entity classes this module must register with TypeOrmModule.forFeature,
    // including any shared entity that physically lives in another module dir
    const entityClasses = [];
    const seenForFeature = new Set();
    for (const entity of plan.entities) {
      const self = resolve(entity.key);
      if (seenForFeature.has(self.className)) continue;
      seenForFeature.add(self.className);
      const homeDir = dirByClass.get(self.className);
      entityClasses.push({
        className: self.className,
        importFrom: homeDir === dir
          ? `./entities/${kebab(self.className)}.entity`
          : `../${homeDir}/entities/${kebab(self.className)}.entity`,
      });
    }

    const importByClass = new Map(entityClasses.map(c => [c.className, c.importFrom]));

    // Sibling-resource targets are not in this resource's entity list, but the
    // service now upserts them, so their import path has to be resolvable. Without
    // this the emitter fell back to './entities/<class>.entity', which does not exist
    // in this module's directory.
    for (const entity of plan.entities) {
      for (const rel of entity.relations) {
        if (rel.kind !== 'many-to-one-resource') continue;
        const target = resolve(rel.targetKey);
        if (!target || importByClass.has(target.className)) continue;
        const homeDir = dirByClass.get(target.className);
        if (!homeDir) continue;
        importByClass.set(target.className, homeDir === dir
          ? `./entities/${kebab(target.className)}.entity`
          : `../${homeDir}/entities/${kebab(target.className)}.entity`);
      }
    }
    const siblings = new Map(ir.resources.map(r => [
      r.name,
      { constant: ir.meta.basePathConstant, segment: r.pathSegment },
    ]));
    const svc = renderService(resource, plan, {
      resolve,
      basePathConstant: ir.meta.basePathConstant,
      eventTypeEnum: ir.meta.eventTypeEnum,
      notificationEvents: resource.notificationEvents ?? [],
      importPathFor: cn => importByClass.get(cn) ?? `./entities/${kebab(cn)}.entity`,
      siblings,
      host,
      nested,
    });
    warnings.push(...(svc.warnings ?? []));
    const ctrl = renderController(resource, { basePathConstant: ir.meta.basePathConstant, host, nested });
    // a hand-written <dir>.controller.extra.ts is picked up automatically
    const extraController = extraControllerFor(backendDir, dir);
    if (extraController) {
      warnings.push(`${resource.name}: registering hand-written ${dir}.controller.extra.ts (${extraController.className})`);
    }
    const mod = renderModule(resource, entityClasses, naming, extraController);
    writeFile(`src/${dir}/${svc.fileName}`, svc.text);
    writeFile(`src/${dir}/${ctrl.fileName}`, ctrl.text);
    writeFile(`src/${dir}/${mod.fileName}`, mod.text);

    // hooks: written ONCE if absent, never overwritten (see plan section 7)
    const hooks = renderHooks(resource);
    const hooksAbs = path.join(backendDir, `src/${dir}/${hooks.fileName}`);
    if (dryRun || !fs.existsSync(hooksAbs)) {
      writeFile(`src/${dir}/${hooks.fileName}`, hooks.text);
    } else {
      preserved.push(`src/${dir}/${hooks.fileName}`);
    }

    resourceModules.push({
      resource: resource.name,
      dir,
      pathSegment: resource.pathSegment,
      moduleClass: mod.className,
      moduleImportPath: `${dir}/${mod.fileName.replace(/\.ts$/, '')}`,
      className: mod.className,
      importPath: `${dir}/${mod.fileName.replace(/\.ts$/, '')}`,
    });

    // seed data from the spec's POST examples, when the spec has any
    // Spec-derived rows, when the spec has examples at all.
    const seed = renderSeedData(resource);
    if (seed) writeFile(`src/${dir}/${seed.fileName}`, seed.text);

    // Hand-authored rows: written ONCE, never overwritten (same contract as hooks).
    // Emitted for EVERY resource, so a read-only exampleless resource can still be
    // given data without that data being lost on the next emit.
    const localSeed = renderLocalSeedStub(resource);
    const localAbs = path.join(backendDir, `src/${dir}/${localSeed.fileName}`);
    if (dryRun || !fs.existsSync(localAbs)) {
      writeFile(`src/${dir}/${localSeed.fileName}`, localSeed.text);
    } else {
      preserved.push(`src/${dir}/${localSeed.fileName}`);
    }

    seeds.push({
      resource: resource.name,
      dir,
      serviceClass: svc.className,
      seedConst: seed ? seed.constName : null,
      localSeedConst: localSeed.constName,
      count: seed ? seed.count : 0,
    });

    const create = renderPayloadDto(resource, 'create');
    const update = renderPayloadDto(resource, 'update');
    const query = renderQueryDto(resource, nested);
    const barrel = renderDtoBarrel(resource);
    writeFile(`src/${dir}/dto/${create.fileName}`, create.text);
    writeFile(`src/${dir}/dto/${update.fileName}`, update.text);
    writeFile(`src/${dir}/dto/${query.fileName}`, query.text);
    writeFile(`src/${dir}/dto/${barrel.fileName}`, barrel.text);

    perResource.push({
      resource: resource.name,
      dir,
      entities: rows,
      dtos: [create.className, update.className, query.className],
      service: svc.className,
      controller: ctrl.className,
      module: mod.className,
      routes: Object.entries(resource.operations).filter(([, v]) => v).map(([k]) => k),
      options: plan.options,
    });
  }

  // Seeding order follows references, not declaration order - see
  // orderSeedsByReference in seed.mjs.
  const orderedSeeds = orderSeedsByReference(seeds, ir.resources);
  seeds.length = 0;
  seeds.push(...orderedSeeds);

  // In inject mode the host owns app.module.ts / entities.ts / tmf.constants.ts, so
  // they are NEVER regenerated - the caller inserts into them surgically instead.
  if (mode === 'inject') {
    return {
      written: written.sort(),
      warnings,
      perResource,
      entityCount: barrelEntries.length,
      merged,
      preserved,
      injectEntities: barrelEntries,
      injectModules: resourceModules,
      seeds,
      eventMembers: ir.resources.flatMap(r => r.notificationEvents ?? []).length,
      listenerRoutes: ir.listeners.length,
    };
  }

  // ── manifest merge, then regenerate every shared file from the UNION ──
  // A service can host several TMF components. Regenerating wiring from a single
  // IR silently dropped the others: emitting TMF674 wiped TMF673 out of
  // app.module.ts and left its controllers referencing a base-path constant that
  // was never written. The manifest is what makes the wiring additive.
  const ctx = scaffoldContext(ir, { serviceName: null, port: null });
  const manifest = readManifest(backendDir);
  const entry = componentEntry(ir, manifest.components[ir.meta.tmfNumber]);
  entry.resources = resourceModules;
  entry.entities = barrelEntries;
  entry.events = ir.resources.flatMap(r => r.notificationEvents ?? []);
  entry.listeners = ir.listeners.map(l => ({ eventName: l.eventName }));
  entry.seeds = seeds;
  manifest.components[ir.meta.tmfNumber] = entry;
  writeManifest(backendDir, manifest);

  const wiringFiles = writeWiring(backendDir, manifest, { databaseName: ctx.databaseName });
  written.push(...wiringFiles);

  // own mode only: the generated service's own test suite (jest.config.js,
  // three component-agnostic specs) already lives here from a prior scaffold,
  // so this is the only mode with somewhere for a suite to land. inject mode
  // surgically inserts into a hand-written host with no such convention.
  //
  // It runs AFTER the manifest merge, against the same union writeWiring just
  // built src/seed.ts, src/entities.ts and src/app.module.ts from. Run against
  // this single IR instead, the WHOLE-SERVICE specs described only the
  // component being emitted: in the three-component geographic service,
  // src/seed.ts seeds every hosted resource while test/seed.spec.ts mocked only
  // the ones from the IR at hand, the unmocked services loaded for real, and
  // seed.spec.ts failed outright.
  //
  // The PER-RESOURCE specs are the exception and take the single IR: one file
  // describes one resource, so emitting this component rewrites its own files
  // and leaves every other component's - written when that component was
  // emitted - untouched and still correct. They need columns, relations and
  // refs, none of which a manifest resource entry carries.
  const components = orderedComponents(manifest);
  emitSpecs({
    components,
    resources: components.flatMap(c => c.resources ?? []),
    // same expression writeWiring feeds renderSeedRunner, so the spec's
    // resource order is the seed runner's resource order
    seeds: components.flatMap(c => c.seeds ?? []),
    plans,
    resolve,
    entityDirOf: className => dirByClass.get(className) ?? null,
    meta: ir.meta,
    // the emitter contract renderService was given: a hand-written host takes a
    // different event dialect, so the spec must assert the call IT emits
    host,
  }, writeFile);

  return {
    written: written.sort(),
    warnings,
    perResource,
    entityCount: barrelEntries.length,
    merged,
    preserved,
    eventMembers: entry.events.length,
    listenerRoutes: entry.listeners.length,
    componentCount: Object.keys(manifest.components).length,
    wiringFiles: wiringFiles.length,
    seeds,
  };
}
