import { kebab, camel } from '../ir/naming.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';

/**
 * Seed data emitter.
 *
 * Payloads come from the spec's own `examples` on the POST requestBody, so seeded
 * rows are the vendor's illustrative data rather than something invented here. Only
 * v5/OAS3 specs carry examples (53 of 131; the 78 Swagger 2.0 specs carry none), so
 * a resource without examples simply gets no seed file.
 *
 * The runner goes through the resource SERVICE, not the repository, so seeding
 * exercises the same validation, id generation, response mapping and event emission
 * a real POST would - which also makes it a usable end-to-end check.
 */

/**
 * Hand-authored seed rows, written ONCE if absent and never overwritten - the same
 * contract as `*.hooks.ts`.
 *
 * Some specs carry no example anywhere: TMF654's /bucket is read-only AND exampleless,
 * so nothing can be derived for it, yet its conformance kit tests /{id} against
 * pre-existing rows and fails 184 assertions without them. Writing those rows into the
 * GENERATED seed file would lose them on the next `emit`, so they belong here.
 */
export function renderLocalSeedStub(resource) {
  const constName = `${camel(resource.name)}LocalSeed`;
  return {
    fileName: `${kebab(resource.name)}.seed.local.ts`,
    constName,
    text: [
      '// HAND-EDITABLE. Written once by tmfgen if absent, never overwritten.',
      '//',
      `// Rows added here are seeded alongside anything derived from the spec's`,
      '// examples. Use it when the spec carries no usable example - a read-only',
      '// resource whose conformance kit still expects data to already be there.',
      '//',
      '// Shape: the API payload, exactly as a POST body would look.',
      '',
      `export const ${constName}: Record<string, any>[] = [];`,
      '',
    ].join('\n'),
  };
}

export function renderSeedData(resource) {
  if (!resource.seedExamples?.length) return null;
  const constName = `${camel(resource.name)}Seed`;
  return {
    fileName: `${kebab(resource.name)}.seed.ts`,
    constName,
    count: resource.seedExamples.length,
    text: [
      BANNER,
      `// from the spec's examples: ${resource.seedExamples.map(e => e.label).join(', ')}`,
      '',
      `export const ${constName}: Record<string, any>[] = ${JSON.stringify(
        resource.seedExamples.map(e => e.value), null, 2)};`,
      '',
    ].join('\n'),
  };
}

/**
 * One runner for the whole service, built from the manifest so a multi-component
 * service seeds every component it hosts.
 *
 * @param entries [{ resource, dir, serviceClass, moduleImportPath, seedConst, seedImportPath }]
 */
/**
 * Order seeding so a resource is seeded AFTER every sibling resource it references.
 *
 * A sibling reference is a real foreign key, and `create()` drops a reference whose
 * target row does not exist (see the resolver in service.mjs) rather than inventing
 * one. Declaration order is the spec's, not a dependency order: TMF936 declares
 * ProductOffering before ProductSpecification but every offering references a
 * specification, so seeding in declaration order silently lost every reference.
 *
 * Stable: ties keep declaration order, and a reference cycle degrades to declaration
 * order for the resources involved rather than dropping any of them.
 */
export function orderSeedsByReference(entries, resources) {
  const deps = new Map(
    (resources ?? []).map(r => [r.name, (r.resourceRefs ?? []).map(rr => rr.targetResource)]),
  );
  const byName = new Map(entries.map(e => [e.resource, e]));
  const out = [];
  const state = new Map(); // undefined = unvisited, 1 = on stack, 2 = done
  const visit = (name) => {
    if (state.get(name) === 2 || state.get(name) === 1) return;
    state.set(name, 1);
    for (const target of deps.get(name) ?? []) {
      if (target !== name && byName.has(target)) visit(target);
    }
    state.set(name, 2);
    out.push(byName.get(name));
  };
  for (const e of entries) visit(e.resource);
  return out;
}

export function renderSeedRunner(entries) {
  if (!entries.length) {
    return {
      fileName: 'seed.ts',
      text: [
        BANNER,
        '// No resource in this service has seed rows (spec examples or hand-authored).',
        '// (Swagger 2.0 specs carry no examples; only v5/OAS3 specs do.)',
        'export {};',
        '',
      ].join('\n'),
    };
  }

  const imports = entries.flatMap(e => [
    `import { ${e.serviceClass} } from './${e.dir}/${kebab(e.resource)}.service';`,
    ...(e.seedConst ? [`import { ${e.seedConst} } from './${e.dir}/${kebab(e.resource)}.seed';`] : []),
    `import { ${e.localSeedConst} } from './${e.dir}/${kebab(e.resource)}.seed.local';`,
  ]);

  const blocks = entries.map(e => `
  await seedResource(
    '${e.resource}',
    [...${e.seedConst ?? '[]'}, ...${e.localSeedConst}],
    (payload) => app.get(${e.serviceClass}).create(payload as never),
    () => app.get(${e.serviceClass}).findAll({} as never),
  );`).join('');

  return {
    fileName: 'seed.ts',
    text: `${BANNER}
import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
${imports.join('\n')}

const logger = new Logger('seed');

/**
 * Idempotent by design: a resource that already holds rows is left alone, so this is
 * safe to run repeatedly against a dev database. Pass --force to seed anyway.
 */
const force = process.argv.includes('--force');

async function seedResource(
  name: string,
  payloads: Record<string, any>[],
  create: (payload: Record<string, any>) => Promise<unknown>,
  count: () => Promise<{ total: number }>,
): Promise<void> {
  if (!force) {
    const existing = await count();
    if (existing.total > 0) {
      logger.log(\`\${name}: \${existing.total} row(s) already present, skipping\`);
      return;
    }
  }
  let created = 0;
  for (const payload of payloads) {
    try {
      await create(payload);
      created++;
    } catch (err) {
      logger.error(\`\${name}: seed failed - \${(err as Error).message}\`);
    }
  }
  logger.log(\`\${name}: seeded \${created}/\${payloads.length}\`);
}

async function main(): Promise<void> {
  // application context only - no HTTP listener needed for seeding
  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['error', 'warn', 'log'],
  });
  try {${blocks}
    // Event emission is fire-and-forget (the service does not await it, matching the
    // reference), so closing immediately left event_log writes hitting a closed
    // connection. Give that work a moment to settle.
    await new Promise((resolve) => setTimeout(resolve, 1000));
  } finally {
    await app.close();
  }
}

main().catch((err) => {
  logger.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
`,
  };
}
