import { camel, pascal, kebab } from '../ir/naming.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';

/**
 * Service emitter.
 *
 * The centrepiece is `toResponse()`. In the golden reference it is hand-written
 * re-shaping, and the reason is that the reference flattens nested objects three
 * different ways chosen per field, leaving no round-trip rule. Because entityPlan
 * commits to ONE rule, the inverse is mechanical and every mapper below is derived:
 * each ref column carries the `sourceProp` it came from, so rebuilding the nested
 * API object is a straight projection back.
 *
 * Two deliberate departures from the reference, both recorded in the plan:
 *   - `update` runs in a transaction (the reference deletes children then saves, so
 *     a mid-flight failure loses data)
 *   - replaced single refs have their orphaned rows deleted (@ManyToOne has no
 *     orphanedRowAction, which M3 flagged as this milestone's debt)
 */

const AUDIT_AND_SOFT_DELETE = new Set([
  'createdDate', 'lastUpdate', 'deletedAt', 'deletedBy', 'deletedReason',
]);

/**
 * Does this entity, or any of its one-to-many descendants, carry a
 * server-managed `version` column? Decides whether a `prev` (previous-state)
 * parameter needs threading through the builder chain at all - a component
 * with no `version` field anywhere should get zero extra generated code.
 *
 * `many-to-one-ref` is deliberately NOT traversed: it always targets a
 * `kind: 'ref'` entity, which gets a fresh row (and fresh `uuidv4()` id) on
 * every rebuild with no client-suppliable identity to correlate against a
 * previous instance - so a `version` column there can only ever be "1.0",
 * never carried forward, and needs no `prev` plumbing from an ancestor.
 */
function subtreeHasVersion(entity, entityOf, visited = new Set()) {
  if (!entity || visited.has(entity.key)) return false;
  visited.add(entity.key);
  if (entity.kind !== 'ref' && entity.columns.some(c => c.isVersion)) return true;
  for (const rel of entity.relations) {
    if (rel.kind !== 'one-to-many') continue;
    if (subtreeHasVersion(entityOf(rel.targetKey), entityOf, visited)) return true;
  }
  return false;
}

/** entity key -> property path from the root, e.g. ['conditionVariable','policyCondition'] */
const pathOf = key => key.split('.').slice(1);

const aliasOf = (segments, rootAlias) =>
  segments.length ? camel(segments.join(' ')) : rootAlias;

/** Which response key a column maps back to. */
function responseKey(col) {
  if (col.sourceProp) return col.sourceProp;          // ref table: exact inverse
  if (col.expose) return col.expose;                   // atType -> '@type'
  return col.name;
}

function repoName(className) {
  return `${camel(className)}Repository`;
}

/* ── mappers ─────────────────────────────────────────────────────────── */

function renderMapper(entity, self, children, resolve, hrefFor, siblings, ownHrefBase, entityOf) {
  const lines = [];
  // A reference wrapper's own PK is internal: the wire `id` is the REFERRED id,
  // carried by the column whose sourceProp is 'id'. Emitting both produced a dead
  // `out.id = e.id` immediately overwritten by `out.id = e.refId`.
  const referredIdPresent = entity.columns.some(c => c.sourceProp === 'id');
  const dataKeys = entity.columns.filter(c =>
    !AUDIT_AND_SOFT_DELETE.has(c.name) && !(referredIdPresent && c.primary));

  // An OWNED (non-ref) sub-resource has its own `id` but no route of its own; some
  // TM Forum conformance profiles still mark `href` mandatory on it "in response
  // messages". `rootId` is threaded down from the aggregate root (not each
  // intermediate parent) so it can be synthesised, identifier-shaped rather than a
  // real dereferenceable route.
  const isOwnedChild = entity.kind === 'child' && !entity.refLike;

  // No null guard: every call site already guards (single refs via a ternary,
  // collections via `?? []`), so the return type stays non-optional and callers
  // do not have to widen.
  lines.push(`  private map${self.className}(e: ${self.className}${isOwnedChild ? ', rootId?: string' : ''}): Record<string, any> {`);
  lines.push('    const out: Record<string, any> = {};');

  for (const c of dataKeys) {
    const key = responseKey(c);
    const prop = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? `out.${key}` : `out['${key}']`;
    lines.push(`    ${prop} = e.${c.name};`);
  }
  if (hrefFor) {
    lines.push(`    out.href = \`/\${${hrefFor.constant}}/${hrefFor.segment}/\${e.id}\`;`);
  } else if (isOwnedChild && ownHrefBase) {
    lines.push(`    if (rootId) {`);
    lines.push(`      out.href = \`/\${${ownHrefBase.constant}}/${ownHrefBase.segment}/\${rootId}/${entity.ownerField}/\${e.id}\`;`);
    lines.push(`    }`);
  }

  for (const rel of entity.relations) {
    if (rel.kind === 'many-to-one-owner') continue; // back-reference, never serialised
    const target = resolve(rel.targetKey);
    if (!target) continue;
    if (rel.kind === 'one-to-many') {
      const targetEntity = entityOf?.(rel.targetKey);
      const targetNeedsRootId = targetEntity?.kind === 'child' && !targetEntity.refLike;
      const rootIdArg = targetNeedsRootId ? `, ${entity.kind === 'root' ? 'e.id' : 'rootId'}` : '';
      lines.push(`    out.${rel.property} = (e.${rel.property} ?? []).map((c) => this.map${target.className}(c${rootIdArg}));`);
    } else if (rel.kind === 'many-to-one-resource') {
      // The target is another resource with its own service, so there is no mapper
      // here. Project the TMF reference shape inline instead.
      const sib = siblings?.get(target.className);
      const hrefExpr = sib
        ? `\`/\${${sib.constant}}/${sib.segment}/\${e.${rel.property}.id}\``
        : 'undefined';
      lines.push(`    out.${rel.property} = e.${rel.property}`);
      lines.push(`      ? stripEmpty({`);
      lines.push(`          id: e.${rel.property}.id,`);
      lines.push(`          href: ${hrefExpr},`);
      lines.push(`          name: (e.${rel.property} as Record<string, any>).name,`);
      lines.push(`          '@referredType': '${target.className}',`);
      lines.push(`        })`);
      lines.push(`      : undefined;`);
    } else {
      lines.push(`    out.${rel.property} = e.${rel.property} ? this.map${target.className}(e.${rel.property}) : undefined;`);
    }
  }

  lines.push('    return stripEmpty(out);');
  lines.push('  }');
  return lines.join('\n');
}

/* ── builders (payload -> entity) ────────────────────────────────────── */

function renderBuilder(entity, self, resolve, entityOf) {
  const lines = [];
  const versionCol = entity.columns.find(c => c.isVersion);
  const settable = entity.columns.filter(
    c => !c.primary && !AUDIT_AND_SOFT_DELETE.has(c.name) && !c.isVersion,
  );
  const ownerRel = entity.relations.find(r => r.kind === 'many-to-one-owner');
  const ownerTarget = ownerRel ? resolve(ownerRel.targetKey) : null;
  // whether THIS entity (or something one-to-many beneath it) ever needs the
  // previous instance threaded in, so `version` can be carried forward
  const needsPrev = entityOf ? subtreeHasVersion(entity, entityOf) : false;

  // The owner back-reference must be assigned explicitly. Cascade alone does not
  // populate a `nullable: false` FK, which fails the insert with a FOREIGN KEY
  // constraint error - the reference sets `parent: entity` for the same reason.
  const ownerParam = ownerRel ? `, owner: ${ownerTarget.className}` : '';
  const prevParam = needsPrev ? `, prev?: ${self.className}` : '';
  lines.push(`  private build${self.className}(input: Record<string, any>, pending: PendingRef[]${ownerParam}${prevParam}): ${self.className} {`);
  lines.push(`    const e = this.${repoName(self.className)}.create();`);
  if (entity.kind === 'ref' || entity.refLike) {
    // A reference row's own PK is always fresh. `input.id` is the id of the entity
    // being REFERENCED and belongs in refId - using it as the PK made TypeORM assume
    // the row already existed, so it set the FK without inserting.
    lines.push('    e.id = uuidv4();');
  } else {
    lines.push('    e.id = input?.id ?? uuidv4();');
  }
  if (ownerRel) lines.push(`    e.${ownerRel.property} = owner;`);
  for (const c of settable) {
    const key = responseKey(c);
    lines.push(`    e.${c.name} = input?.['${key}'];`);
  }
  if (versionCol && entity.kind === 'ref') {
    // A `kind: 'ref'` row has no client-suppliable identity to correlate
    // against a previous instance (fresh uuidv4() every rebuild), so it can
    // never carry a version forward - always treated as brand new.
    lines.push(`    e.version = '1.0';`);
  } else if (versionCol) {
    // `version` is server-managed: client input is always ignored. A fresh
    // row (no `prev`) starts at "1.0"; a row that carries forward from a
    // matched previous instance gets bumped based on what actually changed.
    // keyed by WIRE name (not the internal column name) so it lines up with
    // `requiredFields`, which is the OAS spec's own required-attribute names
    const oldEntries = settable.map(c => `'${responseKey(c)}': prev?.${c.name}`).join(', ');
    const newEntries = settable.map(c => `'${responseKey(c)}': input?.['${responseKey(c)}']`).join(', ');
    const required = JSON.stringify(entity.requiredFields ?? []);
    lines.push(`    e.version = prev ? applyVersionBump(prev.version, { ${oldEntries} }, { ${newEntries} }, ${required}) : '1.0';`);
  }
  for (const rel of entity.relations) {
    if (rel.kind === 'many-to-one-owner') continue;
    const target = resolve(rel.targetKey);
    if (!target) continue;
    if (rel.kind === 'one-to-many') {
      const targetEntity = entityOf?.(rel.targetKey);
      if (targetEntity && subtreeHasVersion(targetEntity, entityOf)) {
        const mapVar = `prev${pascal(rel.property)}ByKey`;
        lines.push(`    const ${mapVar} = new Map((prev?.${rel.property} ?? []).map((c: any) => [c.${targetEntity.correlationColumn}, c]));`);
        lines.push(`    e.${rel.property} = (input?.${rel.property} ?? []).map((i: Record<string, any>) => this.build${target.className}(i, pending, e, ${mapVar}.get(i?.['${targetEntity.correlationWireKey}'])));`);
      } else {
        lines.push(`    e.${rel.property} = (input?.${rel.property} ?? []).map((i: Record<string, any>) => this.build${target.className}(i, pending, e));`);
      }
    } else if (rel.kind === 'many-to-one-ref') {
      // never threads `prev` - see subtreeHasVersion's note on `kind: 'ref'` targets
      lines.push(`    e.${rel.property} = input?.${rel.property} ? this.build${target.className}(input.${rel.property}, pending) : undefined;`);
    }
    // many-to-one-resource is resolved by id in the hooks/relation step, not built
  }
  if (entity.kind === 'ref') {
    // Registered so the caller can persist it BEFORE the aggregate. TypeORM's
    // cascade does not reach a ref owned by a child that is itself being
    // cascade-inserted, so the FK would point at a row that was never written.
    lines.push(`    pending.push({ target: ${self.className}, entity: e });`);
  }
  lines.push('    return e;');
  lines.push('  }');
  return lines.join('\n');
}

/* ── main ────────────────────────────────────────────────────────────── */

export function renderService(resource, plan, ctx) {
  const { resolve, basePathConstant, eventTypeEnum, notificationEvents, moduleName = resource.name } = ctx;
  const rootSelf = resolve(resource.name);
  const className = `${moduleName}Service`;

  const entities = plan.entities;
  const selfOf = new Map(entities.map(e => [e.key, resolve(e.key)]));
  const uniqueClasses = [...new Map(entities.map(e => [selfOf.get(e.key).className, e])).entries()];
  // `resolve()` only carries {className, tableName} - renderMapper also needs
  // entity-shape info (kind/refLike) for a relation's target, which this looks up.
  const entityOf = key => entities.find(e => e.key === key) ?? null;

  // relation paths for findOne / joins for findAll, derived from entity keys
  const relationPaths = entities
    .filter(e => e.kind !== 'root')
    .map(e => pathOf(e.key).join('.'))
    .filter(Boolean)
    .sort();

  const joins = entities
    .filter(e => e.kind !== 'root')
    .map(e => {
      const segs = pathOf(e.key);
      const parentAlias = aliasOf(segs.slice(0, -1), 'e');
      return { path: `${parentAlias}.${segs[segs.length - 1]}`, alias: aliasOf(segs, 'e') };
    })
    .sort((a, b) => a.alias.localeCompare(b.alias));

  // sibling-resource refs are joined too, but never built from the payload
  for (const rr of resource.resourceRefs) {
    joins.push({ path: `e.${rr.name}`, alias: camel(rr.name) });
    relationPaths.push(rr.name);
  }

  /**
   * Host contract. Defaults describe a generator-owned service; a hand-written host
   * is probed (src/inject/probeHost.mjs) because its dialect differs - the
   * geographic service takes an OBJECT with a timestamp field and types eventType
   * as a plain string, so no enum import is needed or wanted there.
   */
  const host = {
    emitterClass: 'EventEmitterService',
    emitterImport: '../event/event-emitter.service',
    method: 'emitEvent',
    callStyle: 'positional',
    eventTypeStyle: 'enum',
    objectFields: null,
    ...(ctx.host ?? {}),
  };
  const eventRef = ev => (host.eventTypeStyle === 'literal'
    ? `'${ev.eventName}'`
    : `${eventTypeEnum}.${ev.enumMember}`);
  const emitCall = (ev, idExpr, payloadExpr) => {
    if (host.callStyle === 'object') {
      const fields = [
        `      eventType: ${eventRef(ev)},`,
        `      resourceId: ${idExpr},`,
        `      resourceType: '${resource.name}',`,
        ...(host.objectFields?.includes('timestamp') ? ['      timestamp: new Date(),'] : []),
        `      payload: ${payloadExpr},`,
      ];
      return `    this.eventEmitter.${host.method}({\n${fields.join('\n')}\n    });`;
    }
    return `    this.eventEmitter.${host.method}(\n      ${eventRef(ev)},\n      ${idExpr},\n      '${resource.name}',\n      ${payloadExpr},\n    );`;
  };

  const eventOf = kind => notificationEvents.find(e => e.eventKind === kind) ?? null;
  const createEvent = eventOf('Create');
  const changeEvent = eventOf('AttributeValueChange') ?? eventOf('Change');
  const deleteEvent = eventOf('Delete');
  const stateEvent = eventOf('StateChange');
  const stateField = resource.fields.find(f => /^(lifecycleStatus|state|status)$/.test(f.name));

  const softDeleteCols = ['deletedAt', 'deletedBy', 'deletedReason'];
  const scalarAssignable = plan.entities
    .find(e => e.kind === 'root')
    .columns.filter(c => !c.primary && !AUDIT_AND_SOFT_DELETE.has(c.name) && !c.immutable && !c.isVersion);

  const refRelations = plan.entities.find(e => e.kind === 'root').relations
    .filter(r => r.kind === 'many-to-one-ref');
  const collectionRelations = plan.entities.find(e => e.kind === 'root').relations
    .filter(r => r.kind === 'one-to-many');

  // only resources that actually have a `version` column anywhere pull in the
  // bump helper, so components without one get no unused import
  const hasVersionField = plan.entities.some(e => e.columns.some(c => c.isVersion));

  const imports = [
    "import { Injectable, Logger, NotFoundException } from '@nestjs/common';",
    "import { InjectRepository } from '@nestjs/typeorm';",
    "import { DataSource, IsNull, Repository } from 'typeorm';",
    "import { v4 as uuidv4 } from 'uuid';",
    `import { ${basePathConstant} } from '../common/constants/tmf.constants';`,
    `import { projectFields${hasVersionField ? ', applyVersionBump' : ''} } from '../common/utils/tmf-resource.util';`,
    "import { applyBaseFilters } from '../common/utils/query-helper.util';",
    `import { ${host.emitterClass} } from '${host.emitterImport}';`,
    ...(host.eventTypeStyle === 'enum' ? [`import { ${eventTypeEnum} } from '../event/event-types';`] : []),
    ...uniqueClasses.map(([cn]) => `import { ${cn} } from '${ctx.importPathFor ? ctx.importPathFor(cn) : `./entities/${kebab(cn)}.entity`}';`),
    `import { Create${resource.name}Dto, Update${resource.name}Dto, Query${resource.name}Dto } from './dto';`,
    `import * as hooks from './${kebab(moduleName)}.hooks';`,
  ];

  const ctorParams = [
    ...uniqueClasses.map(([cn], i) =>
      `    @InjectRepository(${cn})\n    private readonly ${i === 0 ? 'repository' : repoName(cn)}: Repository<${cn}>,`),
    '    private readonly dataSource: DataSource,',
    `    private readonly eventEmitter: ${host.emitterClass},`,
  ];
  // the root repo is exposed as `repository`; mappers/builders still use repoName()
  const rootRepoAlias = `  private get ${repoName(rootSelf.className)}(): Repository<${rootSelf.className}> {\n    return this.repository;\n  }`;

  const mappers = uniqueClasses.map(([cn, entity]) => {
    const self = { className: cn };
    const isRoot = entity.kind === 'root';
    return renderMapper(entity, self, null, resolve,
      isRoot ? { constant: basePathConstant, segment: resource.pathSegment } : null,
      ctx.siblings,
      { constant: basePathConstant, segment: resource.pathSegment },
      entityOf);
  });
  const builders = uniqueClasses.map(([cn, entity]) => renderBuilder(entity, { className: cn }, resolve, entityOf));

  const houseFilterNote = Object.entries(resource.houseFilters)
    .filter(([, v]) => v).map(([k]) => k).join(', ') || 'none';

  const ops = resource.operations;

  const body = [];

  /* create */
  if (ops.create) {
    body.push(`  async create(dto: Create${resource.name}Dto): Promise<Record<string, any>> {
    const input = (await hooks.beforeCreate(dto as Record<string, any>)) ?? (dto as Record<string, any>);
    const pending: PendingRef[] = [];
    const entity = this.build${rootSelf.className}(input, pending);
    if (!entity.atType) {
      entity.atType = '${resource.name}';
    }
    // normalised ref rows first, then the aggregate that points at them
    for (const ref of pending) {
      await this.dataSource.getRepository(ref.target).save(ref.entity);
    }
    await this.repository.save(entity);
    const saved = await this.findEntity(entity.id);
    const response = this.map${rootSelf.className}(saved);${createEvent ? `
${emitCall(createEvent, 'saved.id', 'response')}` : ''}
    this.logger.log(\`created ${resource.camelName} \${saved.id}\`);
    return response;
  }`);
  }

  /* findAll */
  if (ops.list) {
    body.push(`  async findAll(query: Query${resource.name}Dto): Promise<{ data: Record<string, any>[]; total: number }> {
    // house filters available for this resource: ${houseFilterNote}
    const qb = this.repository.createQueryBuilder('e')
${joins.map(j => `      .leftJoinAndSelect('${j.path}', '${j.alias}')`).join('\n')}
      .where('e.deletedAt IS NULL');

    applyBaseFilters(qb, query, 'e');
    if (query.id) {
      qb.andWhere('e.id = :id', { id: query.id });
    }

    const total = await qb.getCount();
    qb.skip(query.offset ?? 0).take(query.limit ?? 20);
    const rows = await qb.getMany();
    const data = rows.map((r) => this.map${rootSelf.className}(r));
    return { data: query.fields ? projectFields(data, query.fields) : data, total };
  }`);
  }

  /* findEntity + findOne */
  body.push(`  async findEntity(id: string): Promise<${rootSelf.className}> {
    const entity = await this.repository.findOne({
      where: { id, deletedAt: IsNull() },
      relations: [${[...new Set(relationPaths)].map(p => `'${p}'`).join(', ')}],
    });
    if (!entity) {
      throw new NotFoundException(\`${resource.name} \${id} not found\`);
    }
    return entity;
  }`);

  if (ops.retrieve) {
    body.push(`  async findOne(id: string, fields?: string): Promise<Record<string, any>> {
    const entity = await this.findEntity(id);
    const response = (await hooks.afterFindOne(this.map${rootSelf.className}(entity), entity)) ?? this.map${rootSelf.className}(entity);
    return fields ? projectFields([response], fields)[0] : response;
  }`);
  }

  /* update */
  if (ops.update) {
    const rootEntity = plan.entities.find(e => e.kind === 'root');
    const rootVersionCol = rootEntity.columns.find(c => c.isVersion);
    const refCleanup = refRelations.map(r => `      const orphaned${pascal(r.property)} = existing.${r.property}?.id;`).join('\n');
    const refCleanupAfter = refRelations.map(r => {
      const target = resolve(r.targetKey);
      return `        if (orphaned${pascal(r.property)} && orphaned${pascal(r.property)} !== saved.${r.property}?.id) {
          await manager.delete(${target.className}, { id: orphaned${pascal(r.property)} });
        }`;
    }).join('\n');

    body.push(`  async update(id: string, dto: Update${resource.name}Dto): Promise<Record<string, any>> {
    const input = (await hooks.beforeUpdate(id, dto as Record<string, any>)) ?? (dto as Record<string, any>);

    // Wrapped in a transaction: collections are replaced wholesale, so a failure
    // between delete and insert would otherwise lose data.
    const pending: PendingRef[] = [];
    const saved = await this.dataSource.transaction(async (manager) => {
      const existing = await manager.findOne(${rootSelf.className}, {
        where: { id, deletedAt: IsNull() },
        relations: [${[...new Set(relationPaths)].map(p => `'${p}'`).join(', ')}],
      });
      if (!existing) {
        throw new NotFoundException(\`${resource.name} \${id} not found\`);
      }
${refCleanup ? `      // remember replaced single refs so their rows can be removed\n${refCleanup}\n` : ''}${rootVersionCol ? `      const __oldVersionSnapshot = { ${scalarAssignable.map(c => `'${responseKey(c)}': existing.${c.name}`).join(', ')} };\n` : ''}${scalarAssignable.map(c => {
      const key = responseKey(c);
      return `      if (input['${key}'] !== undefined) {
        existing.${c.name} = input['${key}'];
      }`;
    }).join('\n')}
${rootVersionCol ? `      const __newVersionSnapshot = { ${scalarAssignable.map(c => `'${responseKey(c)}': existing.${c.name}`).join(', ')} };
      existing.version = applyVersionBump(existing.version, __oldVersionSnapshot, __newVersionSnapshot, ${JSON.stringify(rootEntity.requiredFields ?? [])});
` : ''}${collectionRelations.map(r => {
      const target = resolve(r.targetKey);
      // A replaced collection also orphans any normalised ref rows its children
      // pointed at. Collect them before the delete, remove them after - @ManyToOne
      // has no orphanedRowAction to do it for us.
      const childEntity = plan.entities.find(e => e.key === r.targetKey);
      const childRefs = (childEntity?.relations ?? []).filter(x => x.kind === 'many-to-one-ref');
      // the back-reference to this entity is usually called `owner`, but it is
      // renamed when the child's own spec declares a field literally named
      // `owner` (see entityPlan.mjs ownerPropertyFor) - look up its real name
      // rather than assuming the default.
      const childOwnerRel = (childEntity?.relations ?? []).find(x => x.kind === 'many-to-one-owner');
      const childOwnerProp = childOwnerRel ? childOwnerRel.property : 'owner';
      const collect = childRefs.map(x => {
        const refTarget = resolve(x.targetKey);
        return `        const orphaned${pascal(r.property)}${pascal(x.property)}: string[] = (existing.${r.property} ?? [])
          .map((c) => c.${x.property}?.id)
          .filter((v): v is string => !!v);`;
      }).join('\n');
      const purge = childRefs.map(x => {
        const refTarget = resolve(x.targetKey);
        return `        if (orphaned${pascal(r.property)}${pascal(x.property)}.length) {
          await manager.delete(${refTarget.className}, orphaned${pascal(r.property)}${pascal(x.property)});
        }`;
      }).join('\n');
      // if this collection's items (or something nested one-to-many beneath
      // them) carry a `version`, correlate old vs new items BEFORE the delete
      // so it can be carried forward instead of resetting to "1.0" every time
      const needsPrev = subtreeHasVersion(childEntity, entityOf);
      const prevMapVar = `previous${pascal(r.property)}ByKey`;
      const prevMap = needsPrev
        ? `        const ${prevMapVar} = new Map((existing.${r.property} ?? []).map((c) => [c.${childEntity.correlationColumn}, c]));\n`
        : '';
      const buildCall = needsPrev
        ? `this.build${target.className}(i, pending, existing, ${prevMapVar}.get(i?.['${childEntity.correlationWireKey}']))`
        : `this.build${target.className}(i, pending, existing)`;
      return `      if (input.${r.property} !== undefined) {
${prevMap}${collect}${collect ? '\n' : ''}        await manager.delete(${target.className}, { ${childOwnerProp}: { id } });
${purge}${purge ? '\n' : ''}        existing.${r.property} = (input.${r.property} ?? []).map((i: Record<string, any>) => ${buildCall});
      }`;
    }).join('\n')}
${refRelations.map(r => {
      const target = resolve(r.targetKey);
      return `      if (input.${r.property} !== undefined) {
        existing.${r.property} = input.${r.property} ? this.build${target.className}(input.${r.property}, pending) : undefined;
      }`;
    }).join('\n')}
      for (const ref of pending) {
        await manager.save(ref.target, ref.entity);
      }
      const saved = await manager.save(existing);
${refCleanupAfter}
      return saved;
    });

    const fresh = await this.findEntity(saved.id);
    const response = this.map${rootSelf.className}(fresh);${changeEvent ? `
${emitCall(changeEvent, 'fresh.id', 'response')}` : ''}${stateEvent && stateField ? `
    // ${stateField.name} present in the payload -> the spec declares a state-change event
    if (input['${stateField.name}'] !== undefined) {
    ${emitCall(stateEvent, 'fresh.id', 'response')}
    }` : ''}
    return response;
  }`);
  }

  /* remove */
  if (ops.delete) {
    body.push(`  async remove(id: string, deletedBy?: string, deletedReason?: string): Promise<void> {
    const entity = await this.findEntity(id);
    // soft delete: the row stays, ${softDeleteCols.join('/')} record who and why
    entity.deletedAt = new Date();
    entity.deletedBy = deletedBy ?? 'system';
    entity.deletedReason = deletedReason ?? 'Deleted via API';
    await this.repository.save(entity);${deleteEvent ? `
${emitCall(deleteEvent, 'entity.id', `{ id: entity.id, href: \`/\${${basePathConstant}}/${resource.pathSegment}/\${entity.id}\` }`)}` : ''}
    this.logger.log(\`soft-deleted ${resource.camelName} \${id}\`);
  }`);
  }

  return {
    fileName: `${kebab(moduleName)}.service.ts`,
    className,
    text: [
      BANNER,
      imports.join('\n'),
      '',
      '/** A normalised ref row that must be persisted before the aggregate referencing it. */',
      'type PendingRef = { target: new () => any; entity: Record<string, any> };',
      '',
      '/** Drops undefined/null so the response carries only what the resource actually has. */',
      'function stripEmpty(obj: Record<string, any>): Record<string, any> {',
      '  for (const key of Object.keys(obj)) {',
      '    if (obj[key] === undefined || obj[key] === null) {',
      '      delete obj[key];',
      '    }',
      '  }',
      '  return obj;',
      '}',
      '',
      '@Injectable()',
      `export class ${className} {`,
      `  private readonly logger = new Logger(${className}.name);`,
      '',
      '  constructor(',
      ctorParams.join('\n'),
      '  ) {}',
      '',
      rootRepoAlias,
      '',
      body.join('\n\n'),
      '',
      '  /* ── payload -> entity ── */',
      builders.join('\n\n'),
      '',
      '  /* ── entity -> API response (inverse of the nesting rule) ── */',
      mappers.join('\n\n'),
      '}',
      '',
    ].join('\n'),
  };
}
