// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// payload shape from Topic_Create
import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString } from 'class-validator';

export class CreateTopicDto {
  /** is the filter that will be applied on the content of the Event. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  contentQuery?: string;

  /** is the filter that will be applied on the Event header properties. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  headerQuery?: string;

  /** use to identify grouping of events, per domain, per event types, per access control-right and so on. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@type'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@baseType'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@schemaLocation'?: string;
}
