// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
export { CreateGeographicAddressDto } from './create-geographic-address.dto';
export { UpdateGeographicAddressDto } from './update-geographic-address.dto';
export { QueryGeographicAddressDto } from './query-geographic-address.dto';
