// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// payload shape from GeographicAddress (no variant schema in spec)
import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString, IsArray, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

class GeographicLocationDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@baseType'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@schemaLocation'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@type'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@referredType'?: string;
}

class GeographicSubAddressDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  /** allows for buildings that have well-known names */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  buildingName?: string;

  /** used where a level type may be repeated e.g. BASEMENT 1, BASEMENT 2 */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  levelNumber?: string;

  /** describes level types within a building */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  levelType?: string;

  /** Name of the subAddress to identify it with a meaningful identification */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name?: string;

  /** private streets internal to a property (e.g. a university) may have internal names that are not recorded by the land title office. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  privateStreetName?: string;

  /** private streets numbers internal to a private street */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  privateStreetNumber?: string;

  /** Type of subAddress : it can be a subunit or a private street */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  subAddressType?: string;

  /** the discriminator used for the subunit often just a simple number e.g. FLAT 5, may also be a range */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  subUnitNumber?: string;

  /** the type of subunit e.g.BERTH, FLAT, PIER, SUITE, SHOP, TOWER, UNIT, WHARF */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  subUnitType?: string;
}

export class UpdateGeographicAddressDto {
  /** City that the address is in */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  city?: string;

  /** Country that the address is in */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  country?: string;

  /** An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi rural in nature. [ANZLIC-STREET], or a suburb, a bounded locality within a city, town or shire principally of urban character [ANZLICSTREET] */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  locality?: string;

  /** A user-friendly name for the place, such as [Paris Store], [London Store], [Main Home] */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name?: string;

  /** descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode) */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  postcode?: string;

  /** the State or Province that the address is in */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  stateOrProvince?: string;

  /** Name of the street or other street type */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  streetName?: string;

  /** Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  streetNr?: string;

  /** Last number in a range of street numbers allocated to a property */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  streetNrLast?: string;

  /** Last street number suffix for a ranged address */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  streetNrLastSuffix?: string;

  /** the first street number suffix */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  streetNrSuffix?: string;

  /** A modifier denoting a relative direction */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  streetSuffix?: string;

  /** alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  streetType?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @ValidateNested()
  @Type(() => GeographicLocationDto)
  geographicLocation?: GeographicLocationDto;

  @ApiPropertyOptional({ type: [GeographicSubAddressDto] })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => GeographicSubAddressDto)
  geographicSubAddress?: GeographicSubAddressDto[];

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@type'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@baseType'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@schemaLocation'?: string;
}
