// emit/mcs-common/app.mjs — src/App.tsx + App.css: standalone landing page shown only
// when this MFE runs un-federated. A real host never renders it - it mounts the exposes
// directly. Includes a dev-only preview switcher (reuses the same createProtectedPage-
// wrapped exposes) so generated CRUD pages can be reviewed without a host shell.
import fs from 'node:fs';
import path from 'node:path';
import { buildResourceModel, listPages } from './resourceModel.mjs';

const BANNER = '// GENERATED by fe-gen emit mcs-common - DO NOT EDIT. Re-run `fe-gen emit` instead.';

function appCss() {
  return `.landing {
  min-height: 100vh;
  padding: 30px;
  box-sizing: border-box;
  background: linear-gradient(180deg, #f5f3ff 0%, #eef2ff 100%);
  color: #13243b;
  font-family: 'Plus Jakarta Sans', 'Segoe UI', Tahoma, sans-serif;
}
.landing__hero {
  padding: 30px;
  border-radius: 24px;
  background: linear-gradient(135deg, #ddd6fe 0%, #ede9fe 54%, #f8f7ff 100%);
  border: 1px solid rgba(124, 58, 237, 0.2);
}
.landing__hero h1 { margin: 8px 0 12px; font-size: clamp(1.6rem, 3vw, 2.4rem); }
.landing__eyebrow { margin: 0; font-size: 0.74rem; text-transform: uppercase; letter-spacing: 0.14em; color: #6d28d9; font-weight: 700; }
.landing__actions { margin-top: 16px; display: flex; flex-wrap: wrap; gap: 10px; }
.landing__actions button.preview-trigger {
  padding: 9px 14px; border-radius: 10px; font-weight: 700; font-size: 0.86rem; color: #f5f3ff;
  border: 1px solid rgba(124, 58, 237, 0.28); background: #7c3aed; cursor: pointer; font-family: inherit;
}
.landing__actions button.preview-trigger:hover { background: #6d28d9; }
.preview-back {
  margin: 16px; padding: 8px 14px; border-radius: 8px; border: 1px solid #e2e8f0; background: #fff;
  color: #5b21b6; font-weight: 700; font-size: 0.85rem; cursor: pointer;
  font-family: 'Plus Jakarta Sans', 'Segoe UI', Tahoma, sans-serif;
}
.preview-back:hover { background: #f5f3ff; }
.landing__section { margin-top: 18px; padding: 20px; border-radius: 18px; background: rgba(255,255,255,0.9); border: 1px solid rgba(18,40,66,0.08); }
.landing__section h2 { margin: 0 0 12px; font-size: 1.1rem; }
.pill-list { display: flex; flex-wrap: wrap; gap: 10px; }
.pill { display: inline-flex; align-items: center; padding: 7px 12px; border-radius: 999px; background: #ede9fe; color: #5b21b6; font-weight: 700; font-size: 0.85rem; }
`;
}

function appTsx(feir) {
  const models = listPages(feir).map((p) => buildResourceModel(p));
  const hub = feir.output?.mfe?.hub === true;
  const mfe = feir.output?.mfe ?? {};
  const moduleName = mfe.moduleName || 'mfe';
  const snake = String(moduleName).replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[-\s]+/g, '_').toLowerCase();
  const remoteName = `${snake}_remote`;

  const importLines = models.map((m) => `import ${m.ResourceName}Preview from './exposes/${m.ResourceName}';`);
  if (hub) importLines.push("import HubPreview from './exposes/Hub';");

  const buttons = models.map((m) => `            <button className="preview-trigger" onClick={() => setView(${JSON.stringify(m.resourceKebab)})}>
              Preview: ${m.title ?? m.ResourceName}
            </button>`);
  if (hub) buttons.push(`            <button className="preview-trigger" onClick={() => setView('hub')}>
              Preview: Event Hub
            </button>`);

  const viewBranches = models.map((m) => `  if (view === ${JSON.stringify(m.resourceKebab)}) {
    return (
      <div>
        <button className="preview-back" onClick={() => setView('landing')}>← Back to landing</button>
        <${m.ResourceName}Preview />
      </div>
    );
  }`);
  if (hub) viewBranches.push(`  if (view === 'hub') {
    return (
      <div>
        <button className="preview-back" onClick={() => setView('landing')}>← Back to landing</button>
        <HubPreview />
      </div>
    );
  }`);

  const resourcePills = models.map((m) => `<span className="pill">${m.ResourceName}</span>`).join('\n            ');

  return `${BANNER}
// design-lab-only preview harness (see comment in the generated file below) - remove once
// a real host mounts these exposes instead.
import { useState } from 'react';
import './App.css';
${importLines.join('\n')}

type View = 'landing' | ${[...models.map((m) => JSON.stringify(m.resourceKebab)), ...(hub ? ["'hub'"] : [])].join(' | ')};

function App() {
  const [view, setView] = useState<View>('landing');

${viewBranches.join('\n\n')}

  return (
    <div className="landing">
      <header className="landing__hero">
        <p className="landing__eyebrow">TM Forum ODA Remote</p>
        <h1>${feir.meta?.label ?? feir.meta?.name ?? 'MFE'}</h1>
        <p>${feir.meta?.description ?? ''}</p>
        <div className="landing__actions">
${buttons.join('\n')}
        </div>
      </header>
      <section className="landing__section">
        <h2>Federation Contract</h2>
        <p>Remote: <code>${remoteName}</code></p>
      </section>
      <section className="landing__section">
        <h2>Exposed Resources</h2>
        <div className="pill-list">
            ${resourcePills}
        </div>
      </section>
    </div>
  );
}

export default App;
`;
}

export function emitApp(feir, appDir) {
  const written = [];
  const write = (rel, content) => {
    const abs = path.join(appDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf8');
    written.push(rel);
  };
  write('src/App.tsx', appTsx(feir));
  write('src/App.css', appCss());
  return { written, summary: 'App.tsx landing + preview switcher' };
}
