// emit/mcs-common/service.mjs — service/api.ts (once per app) + service/<resource>Service.ts
// (5 CRUD fns bound to one ENDPOINT const) per list page. Mirrors product-qualification's
// service/api.ts fetch wrapper (TMF630 pagination via X-Total-Count) verbatim.
import fs from 'node:fs';
import path from 'node:path';
import { buildResourceModel, listPages } from './resourceModel.mjs';

const BANNER = '// GENERATED by fe-gen emit mcs-common - DO NOT EDIT. Re-run `fe-gen emit` instead.';

function apiFile(feir) {
  const basePath = feir.api?.basePath ?? '';
  const envVar = 'REACT_APP_API_BASE_URL';
  return `${BANNER}
/**
 * Generic API service layer (product-qualification pattern).
 * Uses TMF630 pagination (offset/limit, X-Total-Count header).
 */

const API_BASE_URL = process.env.${envVar} || 'http://localhost:3000';
const API_KEY = process.env.REACT_APP_API_KEY || '';
const TMF_BASE = ${JSON.stringify(basePath)};

export class ApiError extends Error {
  status: number;
  body: any;

  constructor(status: number, message: string, body?: any) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.body = body;
  }
}

function buildHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  if (API_KEY) {
    headers['X-API-Key'] = API_KEY;
  }
  return headers;
}

function buildQueryString(params?: Record<string, string | number | undefined>): string {
  if (!params) return '';
  const searchParams = new URLSearchParams();
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== '') {
      searchParams.append(key, String(value));
    }
  });
  const qs = searchParams.toString();
  return qs ? \`?\${qs}\` : '';
}

async function request<T>(
  endpoint: string,
  options: { method?: string; body?: any; params?: Record<string, string | number | undefined> } = {},
): Promise<{ data: T; headers: Headers }> {
  const { method = 'GET', body, params } = options;
  const url = \`\${API_BASE_URL}\${TMF_BASE}\${endpoint}\${buildQueryString(params)}\`;

  const response = await fetch(url, {
    method,
    headers: buildHeaders(),
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!response.ok) {
    const errorBody = await response.json().catch(() => ({}));
    throw new ApiError(
      response.status,
      errorBody.message || errorBody.error || \`HTTP \${response.status}\`,
      errorBody,
    );
  }

  if (method === 'DELETE') {
    return { data: { accepted: response.status === 202 } as unknown as T, headers: response.headers };
  }

  const data = await response.json();
  return { data, headers: response.headers };
}

export async function apiGet<T>(endpoint: string, params?: Record<string, string | undefined>): Promise<T> {
  const { data } = await request<T>(endpoint, { params });
  return data;
}

export async function apiGetList<T>(
  endpoint: string,
  params?: Record<string, string | number | undefined>,
): Promise<{ data: T[]; total: number; resultCount: number }> {
  const { data, headers } = await request<T[]>(endpoint, { params });
  const total = Number(headers.get('X-Total-Count') ?? headers.get('x-total-count') ?? data.length);
  const resultCount = Number(headers.get('X-Result-Count') ?? headers.get('x-result-count') ?? data.length);
  return { data, total, resultCount };
}

export async function apiPost<T>(endpoint: string, body: any): Promise<T> {
  const { data } = await request<T>(endpoint, { method: 'POST', body });
  return data;
}

export async function apiPatch<T>(endpoint: string, body: any): Promise<T> {
  const { data } = await request<T>(endpoint, { method: 'PATCH', body });
  return data;
}

export async function apiDelete(endpoint: string): Promise<{ accepted: boolean }> {
  const { data } = await request<{ accepted: boolean }>(endpoint, { method: 'DELETE' });
  return data;
}

export function getErrorMessage(error: unknown): string {
  if (error instanceof ApiError) {
    return error.message;
  }
  if (error instanceof Error) {
    return error.message;
  }
  return 'An unexpected error occurred';
}
`;
}

function resourceServiceFile(model) {
  return `${BANNER}
import { apiGet, apiGetList, apiPost, apiPatch, apiDelete } from './api';
import type { ${model.ResourceName}, ${model.ResourceName}_FVO, ${model.ResourceName}_MVO } from '../types';
import type { ListParams } from '../types';

const ENDPOINT = ${JSON.stringify(model.endpoint)};

export async function list${model.ResourceName}s(params?: ListParams) {
  return apiGetList<${model.ResourceName}>(ENDPOINT, params);
}

export async function get${model.ResourceName}(id: string, fields?: string) {
  return apiGet<${model.ResourceName}>(\`\${ENDPOINT}/\${id}\`, fields ? { fields } : undefined);
}

export async function create${model.ResourceName}(body: ${model.ResourceName}_FVO) {
  return apiPost<${model.ResourceName}>(ENDPOINT, body);
}

export async function patch${model.ResourceName}(id: string, body: ${model.ResourceName}_MVO) {
  return apiPatch<${model.ResourceName}>(\`\${ENDPOINT}/\${id}\`, body);
}

export async function delete${model.ResourceName}(id: string) {
  return apiDelete(\`\${ENDPOINT}/\${id}\`);
}
`;
}

function hubServiceFile() {
  return `${BANNER}
import { apiGet, apiGetList, apiPost, apiDelete } from './api';
import type { Hub, Hub_FVO } from '../types/hub';
import type { ListParams } from '../types';

const ENDPOINT = '/hub';

export async function listHubs(params?: ListParams) {
  return apiGetList<Hub>(ENDPOINT, params);
}

export async function getHub(id: string, fields?: string) {
  return apiGet<Hub>(\`\${ENDPOINT}/\${id}\`, fields ? { fields } : undefined);
}

export async function createHub(body: Hub_FVO) {
  return apiPost<Hub>(ENDPOINT, body);
}

export async function deleteHub(id: string) {
  return apiDelete(\`\${ENDPOINT}/\${id}\`);
}
`;
}

function hubTypesFile() {
  return `${BANNER}
export interface Hub {
  id: string;
  href?: string;
  callback: string;
  query?: string;
  '@type'?: string;
}

export interface Hub_FVO {
  callback: string;
  query?: string;
  '@type'?: string;
}
`;
}

export function emitServices(feir, appDir) {
  const pages = listPages(feir);
  const written = [];
  const write = (rel, content) => {
    const abs = path.join(appDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf8');
    written.push(rel);
  };

  write('src/service/api.ts', apiFile(feir));

  const models = [];
  const serviceExports = [];
  for (const page of pages) {
    const model = buildResourceModel(page);
    models.push(model);
    write(`src/service/${model.resourceCamel}Service.ts`, resourceServiceFile(model));
    serviceExports.push(
      `export { list${model.ResourceName}s, get${model.ResourceName}, create${model.ResourceName}, patch${model.ResourceName}, delete${model.ResourceName} } from './${model.resourceCamel}Service';`,
    );
  }

  const hub = feir.output?.mfe?.hub === true;
  if (hub) {
    write('src/types/hub.ts', hubTypesFile());
    write('src/service/hubService.ts', hubServiceFile());
    serviceExports.push("export { listHubs, getHub, createHub, deleteHub } from './hubService';");
  }

  write('src/service/index.ts', [
    BANNER,
    "export { apiGet, apiGetList, apiPost, apiPatch, apiDelete, getErrorMessage, ApiError } from './api';",
    ...serviceExports,
    '',
  ].join('\n'));

  return { written, summary: `service: ${models.length} resource(s)${hub ? ' + hub' : ''}`, models, hub };
}
