// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { GeographicSite } from './geographic-site.entity';
import { TimePeriod } from './time-period.entity';

@Entity('geographic_site_relationship')
export class GeographicSiteRelationship {
  @PrimaryColumn({ type: 'varchar', length: 100 })
  id: string;

  /** The id the client gave this item. Unique within its parent only, so it is not the primary key; served back as `id`. */
  @Column({ type: 'varchar', length: 100, nullable: true })
  refId?: string;

  @Column({ type: 'int', nullable: true })
  sortOrder?: number;

  /** Type of relationship */
  @Column({ type: 'varchar', length: 100 })
  relationshipType: string;

  /** Role of the related site in the relationship */
  @Column({ type: 'varchar', length: 50, nullable: true })
  role?: string;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  @ManyToOne(() => GeographicSite, (parent) => parent.siteRelationship, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'geographic_site_id' })
  owner: GeographicSite;

  // normalised single ref: own table, FK held here
  @ManyToOne(() => TimePeriod, {
    cascade: true,
    eager: true,
    nullable: true,
  })
  @JoinColumn({ name: 'valid_for_id' })
  validFor?: TimePeriod;
}
