// GENERATED by fe-gen emit mfe - DO NOT EDIT. Re-run `fe-gen emit` instead.
// Module Federation (M5) - KONVENSI remote tim (capacity-management craco.config.js):
//   name      = snake_case dari moduleName + '_remote'  (revenue_sharing_algorithms_remote_remote)
//   filename  = camelCase + 'RemoteEntry.js'            (revenueSharingAlgorithmsRemoteRemoteEntry.js)
//   shared    = react trio { singleton:true, requiredVersion:false } (konvensi REMOTE.
//               host business-service pakai eager+strictVersion - aman utk remote ini.)
//   remotes   = {} KOSONG (self-contained - MUI di-bundle, TIDAK remote bersama).
//   exposes   = {key -> target} DIBANGKITKAN satu per halaman routable + ./routes.
// .mjs rule + optimization.sideEffects=false (template M3, wajib - lihat template craco).
const { ModuleFederationPlugin } = require("webpack").container;

module.exports = {
  webpack: {
    configure: (webpackConfig) => {
      webpackConfig.output.publicPath = "auto";
      webpackConfig.output.crossOriginLoading = "anonymous";
      webpackConfig.plugins.push(
        new ModuleFederationPlugin({
          name: 'revenue_sharing_algorithms_remote_remote',
          filename: 'revenueSharingAlgorithmsRemoteRemoteEntry.js',
          remotes: {}, // self-contained MFE - MUI di-bundle; TIDAK remote bersama (guardrail)
          exposes: {
            './PartyRevSharingAlgorithmsPage': './src/exposes/PartyRevSharingAlgorithmsPage.tsx',
            './routes': './src/exposes/routes.tsx',
          },
          shared: {
            react: { singleton: true, requiredVersion: false },
            "react-dom": { singleton: true, requiredVersion: false },
            "react-router-dom": { singleton: true, requiredVersion: false },
          },
        })
      );

      // Fix: Webpack 4 + .mjs strict ESM compatibility (wajib).
      webpackConfig.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto",
        resolve: { fullySpecified: false },
      });

      // Fix: MUI barrel ESM + sideEffects optimization (M3 - jangan hapus).
      if (webpackConfig.optimization) webpackConfig.optimization.sideEffects = false;
      else webpackConfig.optimization = { sideEffects: false };
      return webpackConfig;
    },
  },
};
