// GENERATED by fe-gen — CRA5 + Craco full-repo app (fe-default: Tailwind, no MUI/neudela).
// Re-run `fe-gen scaffold` instead of editing when the app is regenerated.
//
// Module Federation: DISABLED for full-repo apps. The MFE-mode configuration
// below is emitted by `fe-gen emit --mode mfe` (M5) — it is kept here as
// reference only (convention: name `<app>_remote`, filename `<camel>RemoteEntry.js`,
// shared react trio singleton:true requiredVersion:false).
//
// The .mjs webpack rule at the bottom MUST stay: it is the Webpack 4 + strict
// ESM compatibility fix (reference: capacity-management craco.config.js:41-47).
//
// style.postcss.plugins: fe-default styles via Tailwind (utility classes) + src/gen/tokens.css
// (CSS custom properties, ported 1:1 from example-component-in-dashboard.html) — tailwind.config.js
// maps color/radius/shadow tokens to those CSS variables.
const { ModuleFederationPlugin } = require("webpack").container;
const tailwindcss = require("tailwindcss");
const autoprefixer = require("autoprefixer");

module.exports = {
  style: {
    postcss: {
      // JANGAN pakai `style.postcss.plugins` (array) di sini — craco@7.1.0's
      // extendsPostcss() menaruh hasil gabungan plugin ke `postcssOptions.plugins`
      // sbg SEBUAH FUNCTION, tapi postcss-loader@6.x (dibawa react-scripts 5.0.1)
      // hanya menerima `postcssOptions.plugins` berbentuk ARRAY (function di level
      // itu diperlakukan sbg SATU plugin, bukan dipanggil) — silent no-op, build
      // TIDAK error, tapi @tailwind base/components/utilities lolos mentah tanpa
      // diproses (empirically verified). Pakai `loaderOptions` (bentuk yg didukung
      // penuh: full replace object, tanpa lewat extendsPostcss) sbg gantinya.
      loaderOptions: (postcssLoaderOptions) => {
        const existing = postcssLoaderOptions.postcssOptions?.plugins;
        const basePlugins = Array.isArray(existing) ? existing : [];
        postcssLoaderOptions.postcssOptions = {
          ...postcssLoaderOptions.postcssOptions,
          plugins: [...basePlugins, tailwindcss(), autoprefixer()],
        };
        return postcssLoaderOptions;
      },
    },
  },
  webpack: {
    configure: (webpackConfig) => {
      webpackConfig.output.publicPath = "auto";
      webpackConfig.output.crossOriginLoading = "anonymous";

      // ── MFE mode (M5) — emitted by fe-gen emit mfe, not written by hand ──
      // webpackConfig.plugins.push(
      //   new ModuleFederationPlugin({
      //     name: "<appName>_remote",
      //     filename: "<camelAppName>RemoteEntry.js",
      //     exposes: {},
      //     shared: {
      //       react: { singleton: true, requiredVersion: false },
      //       "react-dom": { singleton: true, requiredVersion: false },
      //       "react-router-dom": { singleton: true, requiredVersion: false },
      //     },
      //   })
      // );

      // Fix: Webpack 4 + .mjs strict ESM compatibility (ALWAYS present).
      webpackConfig.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto",
        resolve: { fullySpecified: false },
      });

      // sideEffects=false: sama fix empirik dgn fe-mui (barrel ESM re-export node_modules).
      // fe-default tak punya dependency UI barrel besar (tanpa @mui/*), tapi flag ini aman/no-op
      // untuk paket lain yang mendeklarasikan sideEffects:false + barrel ESM.
      if (webpackConfig.optimization) webpackConfig.optimization.sideEffects = false;
      else webpackConfig.optimization = { sideEffects: false };

      return webpackConfig;
    },
  },
};
