// GENERATED by fe-gen — PostCSS config (fe-default: Tailwind v4).
// v4 ships its PostCSS plugin as a separate package and handles @import +
// vendor prefixing itself, so postcss-import and autoprefixer are not listed.
module.exports = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
