// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, OneToMany, JoinColumn, CreateDateColumn, UpdateDateColumn, DeleteDateColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { GeographicLocationRefOrValue } from '../../geographic-address-validation/entities/geographic-location-ref-or-value.entity';
import { GeographicSubAddress2 } from './geographic-sub-address2.entity';

/**
 * Structured textual way of describing how to find a Property in an urban area (country properties are often defined differently). Note : Address corresponds to SID UrbanPropertyAddress
 */
@Entity('geographic_address')
export class GeographicAddress {
  @PrimaryColumn({ type: 'varchar', length: 36 })
  id: string;

  /** City that the address is in */
  @Column({ type: 'varchar', length: 255, nullable: true })
  city?: string;

  /** Country that the address is in */
  @Column({ type: 'varchar', length: 255, nullable: true })
  country?: string;

  /** An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi rural in nature. [ANZLIC-STREET], or a suburb, a bounded locality within a city, town or shire principally of urban character [ANZLICSTREET] */
  @Column({ type: 'varchar', length: 255, nullable: true })
  locality?: string;

  /** A user-friendly name for the place, such as [Paris Store], [London Store], [Main Home] */
  @Column({ type: 'varchar', length: 255, nullable: true })
  name?: string;

  /** descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode) */
  @Column({ type: 'varchar', length: 255, nullable: true })
  postcode?: string;

  /** the State or Province that the address is in */
  @Column({ type: 'varchar', length: 255, nullable: true })
  stateOrProvince?: string;

  /** Name of the street or other street type */
  @Column({ type: 'varchar', length: 255, nullable: true })
  streetName?: string;

  /** Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses */
  @Column({ type: 'varchar', length: 255, nullable: true })
  streetNr?: string;

  /** Last number in a range of street numbers allocated to a property */
  @Column({ type: 'varchar', length: 255, nullable: true })
  streetNrLast?: string;

  /** Last street number suffix for a ranged address */
  @Column({ type: 'varchar', length: 255, nullable: true })
  streetNrLastSuffix?: string;

  /** the first street number suffix */
  @Column({ type: 'varchar', length: 255, nullable: true })
  streetNrSuffix?: string;

  /** A modifier denoting a relative direction */
  @Column({ type: 'varchar', length: 255, nullable: true })
  streetSuffix?: string;

  /** alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf */
  @Column({ type: 'varchar', length: 100, nullable: true })
  streetType?: string;

  @DeleteDateColumn({ nullable: true })
  deletedAt?: Date;

  @Column({ type: 'varchar', length: 100, nullable: true })
  deletedBy?: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  deletedReason?: string;

  @CreateDateColumn()
  createdDate: Date;

  @UpdateDateColumn()
  lastUpdate: Date;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, default: 'GeographicAddress' })
  atType: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  // normalised single ref: own table, FK held here
  @ManyToOne(() => GeographicLocationRefOrValue, {
    cascade: true,
    eager: true,
    nullable: true,
  })
  @JoinColumn({ name: 'geographic_location_id' })
  geographicLocation?: GeographicLocationRefOrValue;

  @OneToMany(() => GeographicSubAddress2, (child) => child.owner, {
    cascade: true,
    eager: true,
    orphanedRowAction: 'delete',
  })
  geographicSubAddress: GeographicSubAddress2[];
}
