// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import {
  Controller,
  Post,
  Body,
  Logger,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { Repository } from 'typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { TMF673_BASE_PATH } from '../common/constants/tmf.constants';
import { EventSubscription } from '../subscription/entities/event-subscription.entity';

// Publish-only architecture: these endpoints are stubs that log and echo, matching
// the reference. Nothing is consumed here.
@ApiTags('listener')
@Controller(`${TMF673_BASE_PATH}/listener`)
export class GeographicAddressListenerController {
  private readonly logger = new Logger(GeographicAddressListenerController.name);

  constructor(
    @InjectRepository(EventSubscription)
    private readonly subscriptionRepository: Repository<EventSubscription>,
  ) {}

  private async findSubscription(body: any): Promise<EventSubscription> {
    if (body?.subscriptionId) {
      const sub = await this.subscriptionRepository.findOne({
        where: { id: body.subscriptionId },
      });
      if (sub) return sub;
    }
    const [latest] = await this.subscriptionRepository.find({
      order: { createdDate: 'DESC' },
      take: 1,
    });
    return (
      latest ||
      ({
        id: 'unknown',
        callback: '',
        createdDate: new Date(),
      } as unknown as EventSubscription)
    );
  }

  @Post('geographicAddressValidationStateChangeEvent')
  @HttpCode(HttpStatus.CREATED)
  async handleGeographicAddressValidationStateChangeEvent(@Body() body: any) {
    this.logger.log('Received geographicAddressValidationStateChangeEvent');
    return this.findSubscription(body);
  }
}
