import type { ResourceConfig } from '../../resource/types';
import { LOOKUP_FNS } from '../../app/lookups';
import { partyRevSharingAlgorithmService } from '../../app/services';

export const config: ResourceConfig = {
  service: partyRevSharingAlgorithmService,
  lookups: LOOKUP_FNS,
  list: {
    breadcrumb: ['Revenue Sharing Algorithm'],
    title: 'Party Revenue Sharing Algorithms',
    subtitle: 'TMF736 Revenue Sharing Algorithm Management',
    card: {
      title: 'Algorithms',
      description: 'Named policy sets plus condition/action variables that decide how revenue is split between parties.',
      noun: ['algorithm', 'algorithms'],
      minTableWidth: 1000,
      buttonActionVariant: 'menu',
      rowLabel: 'name',
      searchPlaceholder: 'Search algorithms by name',
      searchParam: 'name',
      emptyTitle: 'No revenue sharing algorithms yet',
      emptyBody: 'Create the first one with “New Algorithm”.',
      primaryAction: { label: 'New Algorithm', icon: { icon: 'Plus', size: 16 } },
      refresh: true,
      rowClick: 'open-detail',
    },
    rowFrom: {
      id: { path: 'id' },
      name: { path: 'name' },
      description: { path: 'description' },
      policyCount: { count: 'policy' },
      lastUpdate: { path: 'lastUpdate' },
    },
    columns: [
      { key: 'id', label: 'ID', width: 170, sortable: true, render: 'id-link' },
      { key: 'name', label: 'Name', width: 200, sortable: true, render: 'primary' },
      { key: 'description', label: 'Description', sortable: true, render: 'ellipsis' },
      {
        key: 'policyCount',
        label: 'Policies',
        width: 120,
        render: 'count-badge',
        badge: { icon: 'ScrollText', one: 'policy', many: 'policies' },
      },
      { key: 'lastUpdate', label: 'Last Update', width: 190, sortable: true, render: 'datetime-stack' },
    ],
    sortOptions: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'lastUpdate', label: 'Last Update' },
      { key: 'id', label: 'ID' },
    ],
    filterFields: [
      { key: 'id', label: 'ID', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'policy', label: 'Policies', type: 'text', list: 'policy', param: 'name', placeholder: 'Policy name' },
      { key: 'lastUpdate', label: 'Last Update', type: 'date' },
    ],
    rowActions: [
      {
        key: 'view',
        label: 'View details',
        ariaLabel: 'View {name}',
        icon: { icon: 'Eye', size: 16 },
        tone: 'brand',
        action: 'open-detail',
      },
      {
        key: 'edit',
        label: 'Edit',
        ariaLabel: 'Edit {name}',
        icon: { icon: 'Pencil', size: 16 },
        tone: 'neutral',
        action: 'open-edit',
      },
      {
        key: 'delete',
        label: 'Delete',
        ariaLabel: 'Delete {name}',
        icon: { icon: 'Trash2', size: 16 },
        tone: 'danger',
        action: 'confirm-delete',
      },
    ],
    mobileCard: {
      id: 'id',
      title: 'name',
      badge: 'policyCount',
      subtitle: { path: 'description' },
      meta: { format: 'Updated {0}', args: [{ dateTime: 'lastUpdate', empty: '—' }] },
    },
    delete: {
      title: 'Delete revenue sharing algorithm?',
      strong: 'name',
      text: 'will be permanently removed. This action cannot be undone.',
      confirmLabel: 'Delete',
      toast: 'Deleted successfully',
    },
  },
  form: {
    formId: 'create-party-rev-sharing-algorithm-form',
    width: 'wide',
    title: 'Create revenue sharing algorithm',
    description: 'A named policy set, plus the condition and action variables that decide how revenue is split. References are picked from their catalogues; ids and links are set by the server.',
    submitLabel: 'Create algorithm',
    validateOn: 'submit',
    fields: [
      {
        kind: 'text',
        name: 'name',
        label: 'Name',
        ariaLabel: 'Name',
        placeholder: 'e.g. Standard 70/30 Split',
        required: { message: 'Enter a name.' },
      },
      {
        kind: 'textarea',
        name: 'description',
        label: 'Description',
        placeholder: 'What this algorithm is for and when it applies',
        autoResize: true,
        minRows: 2,
        maxRows: 6,
      },
      {
        kind: 'repeatable',
        name: 'policies',
        section: { title: 'Policies', required: true, hint: 'At least one, from the policy catalogue' },
        initialItems: 1,
        minItems: { path: 'policy.id', message: 'Select at least one policy.' },
        item: {
          title: 'Policy {n}',
          removeLabel: 'Remove policy {n}',
          canRemove: 'more-than-one',
          fields: [
            {
              kind: 'ref',
              name: 'policy',
              lookup: 'policy',
              label: 'Policy',
              placeholder: 'Select a policy',
              required: { message: 'Select a policy.' },
              groupRuleOnFirst: true,
            },
          ],
        },
        addLabel: 'Add policy',
      },
      {
        kind: 'repeatable',
        name: 'conditionVariables',
        section: { title: 'Condition variables', hint: 'When — optional' },
        initialItems: 0,
        emptyText: 'No condition variables — the rule applies unconditionally.',
        item: {
          title: 'Condition variable {n}',
          removeLabel: 'Remove condition variable {n}',
          canRemove: 'always',
          grid: 3,
          fields: [
            {
              kind: 'ref',
              name: 'policyCondition',
              lookup: 'policyCondition',
              label: 'Policy condition',
              placeholder: 'Select a condition',
              required: { message: 'Select a policy condition.' },
            },
            {
              kind: 'ref',
              name: 'policyConditionVariable',
              lookup: 'policyVariable',
              label: 'Variable',
              placeholder: 'Select a variable',
              required: { message: 'Select a variable.' },
            },
            {
              kind: 'value',
              name: 'value',
              ariaLabel: 'Condition variable {n} value',
              placeholder: 'e.g. 300',
              required: { message: 'Enter a value.' },
            },
          ],
        },
        addLabel: 'Add condition variable',
      },
      {
        kind: 'repeatable',
        name: 'actionVariables',
        section: { title: 'Action variables', hint: 'Then — optional' },
        initialItems: 0,
        emptyText: 'No action variables.',
        item: {
          title: 'Action variable {n}',
          removeLabel: 'Remove action variable {n}',
          canRemove: 'always',
          grid: 3,
          fields: [
            {
              kind: 'ref',
              name: 'policyAction',
              lookup: 'policyAction',
              label: 'Policy action',
              placeholder: 'Select an action',
              required: { message: 'Select a policy action.' },
            },
            {
              kind: 'ref',
              name: 'policyActionVariable',
              lookup: 'policyVariable',
              label: 'Variable',
              placeholder: 'Select a variable',
              required: { message: 'Select a variable.' },
            },
            {
              kind: 'value',
              name: 'value',
              ariaLabel: 'Action variable {n} value',
              placeholder: 'e.g. 30',
              required: { message: 'Enter a value.' },
            },
          ],
        },
        addLabel: 'Add action variable',
      },
    ],
    guard: [
      { required: 'name', message: 'Name is required' },
      { anyItem: 'policies', path: 'policy.id', message: 'At least one policy with an ID is required' },
    ],
    payload: {
      '@type': { const: 'PartyRevSharingAlgorithm' },
      name: { from: 'name' },
      description: { from: 'description', omitEmpty: true },
      policy: {
        array: 'policies',
        keepWhen: ['policy.id'],
        each: { lovRef: 'policy', type: 'PolicyRef', referredType: 'Policy' },
      },
      conditionVariable: {
        array: 'conditionVariables',
        keepWhen: ['value', 'policyCondition.id', 'policyConditionVariable.id'],
        omitEmpty: true,
        item: {
          '@type': { const: 'PartyRevSharingPolicyConditionVariable' },
          value: { from: 'value', omitEmpty: true },
          policyCondition: { lovRef: 'policyCondition', type: 'PolicyConditionRef', referredType: 'PolicyCondition' },
          policyConditionVariable: {
            lovRef: 'policyConditionVariable',
            type: 'PolicyVariableRef',
            referredType: 'PolicyVariable',
          },
        },
      },
      actionVariable: {
        array: 'actionVariables',
        keepWhen: ['value', 'policyAction.id', 'policyActionVariable.id'],
        omitEmpty: true,
        item: {
          '@type': { const: 'PartyRevSharingPolicyActionVariable' },
          value: { from: 'value', omitEmpty: true },
          policyAction: { lovRef: 'policyAction', type: 'PolicyActionRef', referredType: 'PolicyAction' },
          policyActionVariable: {
            lovRef: 'policyActionVariable',
            type: 'PolicyVariableRef',
            referredType: 'PolicyVariable',
          },
        },
      },
    },
    toast: 'Revenue sharing algorithm created successfully',
    edit: {
      formId: 'edit-party-rev-sharing-algorithm-form',
      title: 'Edit {name}',
      description: 'Fields follow PartyRevSharingAlgorithm_MVO. Only the attributes you change are sent; ids and links stay as they are.',
      submitLabel: 'Save changes',
      fields: ['name', 'description', 'policies', 'conditionVariables', 'actionVariables'],
      payload: ['name', 'description', 'policy', 'conditionVariable', 'actionVariable'],
      toast: 'Revenue sharing algorithm updated successfully',
      noChanges: 'No changes to save.',
    },
  },
  detail: {
    idPrefix: 'algorithm',
    tabsAriaLabel: 'Record sections',
    breadcrumbRoot: 'Revenue Sharing Algorithm',
    header: { title: 'name', recordId: 'id', description: 'description' },
    loadingText: 'Loading revenue sharing algorithm…',
    notFound: {
      title: 'Algorithm not found',
      alertTitle: 'Revenue sharing algorithm not found',
      alertDescription: 'No algorithm with id {id} could be loaded.',
    },
    tabs: [
      { key: 'overview', label: 'Overview', icon: { icon: 'FileText', size: 15 } },
      { key: 'policies', label: 'Policies', icon: { icon: 'ScrollText', size: 15 }, count: 'policy' },
      {
        key: 'conditions',
        label: 'Condition Variables',
        icon: { icon: 'GitBranch', size: 15 },
        count: 'conditionVariable',
      },
      {
        key: 'actions',
        label: 'Action Variables',
        icon: { icon: 'SlidersHorizontal', size: 15 },
        count: 'actionVariable',
      },
    ],
    overview: {
      stats: {
        label: 'Algorithm summary',
        items: [
          {
            key: 'policies',
            label: 'Policies',
            icon: { icon: 'ScrollText', size: 14 },
            value: { count: 'policy' },
            hint: { join: 'policy', pick: ['name', 'id'], sep: ', ', empty: 'None referenced' },
            goTo: 'policies',
            ariaLabel: {
              format: '{0} — open the Policies tab',
              args: [{ plural: { count: 'policy' }, one: 'policy', many: 'policies' }],
            },
          },
          {
            key: 'conditions',
            label: 'Condition variables',
            icon: { icon: 'GitBranch', size: 14 },
            value: { count: 'conditionVariable' },
            hint: { ifAny: 'conditionVariable', then: 'When these hold', else: 'No conditions' },
            goTo: 'conditions',
            ariaLabel: {
              format: '{0} — open the tab',
              args: [{ plural: { count: 'conditionVariable' }, one: 'condition variable', many: 'condition variables' }],
            },
          },
          {
            key: 'actions',
            label: 'Action variables',
            icon: { icon: 'SlidersHorizontal', size: 14 },
            value: { count: 'actionVariable' },
            hint: { ifAny: 'actionVariable', then: 'Then these apply', else: 'No actions' },
            goTo: 'actions',
            ariaLabel: {
              format: '{0} — open the tab',
              args: [{ plural: { count: 'actionVariable' }, one: 'action variable', many: 'action variables' }],
            },
          },
          {
            key: 'updated',
            label: 'Last update',
            icon: { icon: 'Clock3', size: 14 },
            value: { relativeTime: 'lastUpdate', empty: '—' },
            hint: { dateTime: 'lastUpdate', empty: 'Not provided' },
          },
        ],
      },
      main: [
        {
          block: 'rule-flow',
          title: 'Sharing rule',
          count: { plural: { sumCount: ['conditionVariable', 'actionVariable'] }, one: 'variable', many: 'variables' },
          viewAll: { label: 'View all variables', goTo: 'conditions' },
          when: {
            label: 'When',
            icon: { icon: 'GitBranch', size: 15 },
            source: 'conditionVariable',
            emptyText: 'No condition variables — the rule applies unconditionally.',
            title: { pick: ['policyCondition.name', 'policyCondition.id'], empty: 'Condition {n}' },
            variable: { pick: ['policyConditionVariable.name', 'policyConditionVariable.id'] },
            value: 'value',
            ids: [
              { label: 'condition', path: 'policyCondition.id' },
              { label: 'variable', path: 'policyConditionVariable.id' },
            ],
          },
          then: {
            label: 'Then',
            icon: { icon: 'SlidersHorizontal', size: 15 },
            source: 'actionVariable',
            emptyText: 'No action variables.',
            title: { pick: ['policyAction.name', 'policyAction.id'], empty: 'Action {n}' },
            variable: { pick: ['policyActionVariable.name', 'policyActionVariable.id'] },
            value: 'value',
            ids: [{ label: 'action', path: 'policyAction.id' }, { label: 'variable', path: 'policyActionVariable.id' }],
          },
        },
        {
          block: 'entity-rows',
          title: 'Policies',
          source: 'policy',
          viewAll: { label: 'View all policies', goTo: 'policies' },
          emptyText: 'No policies.',
          icon: { icon: 'ScrollText', size: 16 },
          itemTitle: { pick: ['name', 'id'] },
          subtitle: {
            parts: [
              { expr: { path: 'version' }, format: 'Version {0}' },
              { expr: { pick: ['@referredType', '@type'] } },
            ],
            sep: ' · ',
          },
          meta: 'id',
        },
      ],
      aside: [
        {
          block: 'timeline',
          title: 'Timeline',
          items: [
            { key: 'updated', path: 'lastUpdate', icon: { icon: 'History', size: 14 }, title: 'Last updated' },
            { key: 'created', path: 'createdDate', icon: { icon: 'CalendarPlus', size: 14 }, title: 'Created' },
          ],
        },
        {
          block: 'key-value',
          title: 'Record',
          items: [
            { label: 'ID', path: 'id', mono: true },
            { label: 'Type', path: '@type', mono: true },
            { label: 'Base type', path: '@baseType', mono: true },
            { label: 'Schema', path: '@schemaLocation', mono: true },
            { label: 'API href', path: 'href', mono: true, link: true },
          ],
        },
      ],
    },
    collections: [
      {
        tab: 'policies',
        source: 'policy',
        title: 'Policies',
        count: { one: 'policy', many: 'policies' },
        search: { label: 'Search policies', placeholder: 'Search policies' },
        defaultView: 'card',
        card: {
          icon: { icon: 'ScrollText', size: 18 },
          title: { pick: ['name', 'id'] },
          subtitle: { pick: ['@referredType'], empty: 'Policy' },
          fields: [
            { label: 'ID', value: { path: 'id' }, mono: true },
            { label: 'Version', value: { path: 'version' }, mono: true },
            { label: 'Type', value: { path: '@type' }, mono: true },
            { label: 'Base type', value: { path: '@baseType' }, mono: true },
            { label: 'Schema', value: { path: '@schemaLocation' }, mono: true },
            { label: 'Href', value: { path: 'href' }, mono: true },
          ],
        },
        columns: [
          { key: 'name', label: 'Name', render: 'primary', value: { pick: ['name', 'id'] } },
          { key: 'id', label: 'ID', width: 200, render: 'mono-muted' },
          { key: 'version', label: 'Version', width: 110, render: 'mono-plain', empty: 'em-dash' },
        ],
      },
      {
        tab: 'conditions',
        source: 'conditionVariable',
        title: 'Condition variables',
        count: { one: 'variable', many: 'variables' },
        search: { label: 'Search condition variables', placeholder: 'Search variables' },
        defaultView: 'table',
        card: {
          icon: { icon: 'GitBranch', size: 18 },
          title: { pick: ['policyCondition.name', 'policyCondition.id'], empty: 'Condition variable {n}' },
          subtitle: { text: 'Policy condition' },
          fields: [
            { label: 'Value', value: { path: 'value' } },
            { label: 'Entry ID', value: { path: 'id' }, mono: true },
            { label: 'Entry type', value: { path: '@type' }, mono: true },
            { refOf: 'policyCondition', role: 'Condition' },
            { label: 'Variable', value: { path: 'policyConditionVariable.name' } },
            { refOf: 'policyConditionVariable', role: 'Variable' },
            { label: 'Entry href', value: { path: 'href' }, mono: true },
            { label: 'Base type', value: { path: '@baseType' }, mono: true },
            { label: 'Schema', value: { path: '@schemaLocation' }, mono: true },
          ],
        },
        columns: [
          { key: 'value', label: 'Value', width: 140, render: 'primary-plain', empty: 'em-dash' },
          { key: 'policyCondition', label: 'Policy Condition', render: 'ref-stack' },
          { key: 'policyConditionVariable', label: 'Condition Variable', render: 'ref-stack' },
        ],
      },
      {
        tab: 'actions',
        source: 'actionVariable',
        title: 'Action variables',
        count: { one: 'variable', many: 'variables' },
        search: { label: 'Search action variables', placeholder: 'Search variables' },
        defaultView: 'table',
        card: {
          icon: { icon: 'SlidersHorizontal', size: 18 },
          title: { pick: ['policyAction.name', 'policyAction.id'], empty: 'Action variable {n}' },
          subtitle: { text: 'Policy action' },
          fields: [
            { label: 'Value', value: { path: 'value' } },
            { label: 'Entry ID', value: { path: 'id' }, mono: true },
            { label: 'Entry type', value: { path: '@type' }, mono: true },
            { refOf: 'policyAction', role: 'Action' },
            { label: 'Variable', value: { path: 'policyActionVariable.name' } },
            { refOf: 'policyActionVariable', role: 'Variable' },
            { label: 'Entry href', value: { path: 'href' }, mono: true },
            { label: 'Base type', value: { path: '@baseType' }, mono: true },
            { label: 'Schema', value: { path: '@schemaLocation' }, mono: true },
          ],
        },
        columns: [
          { key: 'value', label: 'Value', width: 140, render: 'primary-plain', empty: 'em-dash' },
          { key: 'policyAction', label: 'Policy Action', render: 'ref-stack' },
          { key: 'policyActionVariable', label: 'Action Variable', render: 'ref-stack' },
        ],
      },
    ],
  },
};
