// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * GeographicAddress
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { GeographicAddressService } from '../../src/geographic-address/geographic-address.service';
import { GeographicAddressController } from '../../src/geographic-address/geographic-address.controller';
import { GeographicAddressEventType } from '../../src/event/event-types';
import { GeographicAddress } from '../../src/geographic-address/entities/geographic-address.entity';
import { GeographicLocationRefOrValue } from '../../src/geographic-address-validation/entities/geographic-location-ref-or-value.entity';
import { GeographicSubAddress2 } from '../../src/geographic-address/entities/geographic-sub-address2.entity';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn(() => qb),
    take: jest.fn(() => qb),
    getCount: jest.fn(async () => rows.length),
    getMany: jest.fn(async () => rows),
  };
  return qb;
}

const HREF = '/tmf-api/geographicAddressManagement/v4/geographicAddress/res-1';

/** The owner-bound collections this resource maps. */
const COLLECTIONS = ['geographicSubAddress'] as const;

/** The path segment each collection's row mapper writes into its href. */
const HREF_SEGMENT: Record<string, string> = {
  geographicSubAddress: 'geographicSubAddress',
};

/** The `@type` each collection's rows carry: their own entity class name. */
const ROW_AT_TYPE: Record<string, string> = {
  geographicSubAddress: 'GeographicSubAddress2',
};

function row(collection: string, index: number): AnyRec {
  return {
    id: `${collection}-row-${index}`,
    refId: `${collection}-ref-${index}`,
    atType: ROW_AT_TYPE[collection],
    sortOrder: index,
  };
}

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    city: 'res-city',
    country: 'res-country',
    locality: 'res-locality',
    name: 'res-name',
    postcode: 'res-postcode',
    stateOrProvince: 'res-stateOrProvince',
    streetName: 'res-streetName',
    streetNr: 'res-streetNr',
    streetNrLast: 'res-streetNrLast',
    streetNrLastSuffix: 'res-streetNrLastSuffix',
    streetNrSuffix: 'res-streetNrSuffix',
    streetSuffix: 'res-streetSuffix',
    streetType: 'res-streetType',
    atType: 'GeographicAddress',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    geographicSubAddress: [row('geographicSubAddress', 0)],
    ...over,
  };
}

describe('GeographicAddress entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [
      GeographicAddress,
      GeographicLocationRefOrValue,
      GeographicSubAddress2,
    ]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});
