// emit/apitype.mjs — F5 typed API registry emitter.
//
// Menulis src/gen/api/types.generated.ts HANYA bila FEIR punya `apis`/`models` (schema
// v2, opsional) — spec lama (hanya `api.endpoints`) tidak memicu file ini sama sekali,
// emitAll() melewatinya via convention "tidak menulis apa pun -> written kosong".
//
// shapeNode berdiskriminator `kind` (BUKAN `type` — lihat T1 di buildFEIR.scan()):
//   scalar  -> tipe primitif TS (scalarKind -> TS_SCALAR)
//   object  -> interface literal { ...properties }
//   array   -> Array<...items>
//   ref     -> nama model lain (PascalCase)
import fs from 'node:fs';
import path from 'node:path';

const BANNER = '// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.';

const pascal = (s) => String(s).charAt(0).toUpperCase() + String(s).slice(1);

const TS_SCALAR = {
  string: 'string',
  number: 'number',
  integer: 'number',
  boolean: 'boolean',
  date: 'string', // ISO date - dibawa sebagai string, bukan Date runtime (kontrak JSON)
  'date-time': 'string',
  unknown: 'unknown',
};

function tsType(node) {
  if (!node) return 'unknown';
  switch (node.kind) {
    case 'scalar':
      return TS_SCALAR[node.scalar] ?? 'unknown';
    case 'ref':
      return pascal(node.ref);
    case 'array':
      return `Array<${tsType(node.items)}>`;
    case 'object': {
      const props = Object.entries(node.properties ?? {}).map(
        ([k, v]) => `${JSON.stringify(k)}${v.optional ? '?' : ''}: ${tsType(v)}`,
      );
      return `{ ${props.join('; ')} }`;
    }
    default:
      throw new Error(`emit/apitype: shapeNode kind tak dikenal "${node.kind}"`);
  }
}

function modelInterface(name, node) {
  if (node.kind !== 'object') {
    // model bukan object (mis. langsung scalar/array) -> type alias, bukan interface
    return `export type ${pascal(name)} = ${tsType(node)};`;
  }
  const props = Object.entries(node.properties ?? {}).map(
    ([k, v]) => `  ${JSON.stringify(k)}${v.optional ? '?' : ''}: ${tsType(v)};`,
  );
  return `export interface ${pascal(name)} {\n${props.join('\n')}\n}`;
}

export function emitApitypes(feir, appDir) {
  if (!feir.apis?.length && !feir.models) {
    return { written: [], summary: '0 api registry (apis[]/models{} tidak dideklarasikan)' };
  }

  const L = [];
  L.push(BANNER);
  L.push('// Registry API bertipe (F5): satu interface per models{} + Request/Response per apis[].');
  L.push('');

  for (const [name, node] of Object.entries(feir.models ?? {})) {
    L.push(modelInterface(name, node));
    L.push('');
  }

  for (const api of feir.apis ?? []) {
    const reqBody = api.request?.body;
    if (reqBody) {
      const props = Object.entries(reqBody).map(([k]) => `  ${JSON.stringify(k)}?: unknown;`);
      L.push(`export interface ${pascal(api.name)}Request {\n${props.join('\n')}\n}`);
      L.push('');
    }
    if (api.response?.shape) {
      L.push(`export type ${pascal(api.name)}Response = ${tsType(api.response.shape)};`);
      L.push('');
    }
  }

  const abs = path.join(appDir, 'src/gen/api/types.generated.ts');
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, L.join('\n'), 'utf8');

  return {
    written: ['src/gen/api/types.generated.ts'],
    summary: `${Object.keys(feir.models ?? {}).length} model(s) + ${(feir.apis ?? []).length} api(s) -> src/gen/api/types.generated.ts`,
  };
}
