// emit/dashboard.mjs — F7 dashboard emitter.
//
// view: dashboard -> src/pages/<id>/Dashboard.tsx. stats[]/tables[] fetch data lewat
// apis[] (registry F5, WAJIB - dashboardSource selalu <apiName>.<path>, divalidasi gate
// checkDashboardSources sebelum sampai sini). charts[] TIDAK fetch apa pun (keputusan
// user: v1 tanpa dependency chart baru) - placeholder + satu warning per chart. Tidak
// boleh meninggalkan import/variabel mati (doc §21): data yang tidak dirender tidak
// pernah diminta.
import fs from 'node:fs';
import path from 'node:path';
import { loadAdapter } from '../../../libs/adapter.mjs';

const BANNER = '// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.';
const q1 = (s) => `'${String(s).replace(/'/g, "\\'")}'`;
const camel = (s) => String(s).charAt(0).toLowerCase() + String(s).slice(1);

function resolveApiPath(template, ir) {
  const base = ir.api?.basePath ?? '';
  const out = String(template).replace(/\{\{\s*api\.basePath\s*\}\}/g, base);
  if (/\{\{/.test(out)) throw new Error(`emit/dashboard: binding tak dikenal di api path "${out}"`);
  return out;
}

/** dashboardSource '<apiName>.<seg1>.<seg2>...' -> { apiName, path: [seg1, seg2, ...] }. */
function splitSource(source) {
  const [apiName, ...segs] = String(source).split('.');
  return { apiName, path: segs };
}

function accessorExpr(varName, segments) {
  return segments.reduce((acc, seg) => `(${acc} as Record<string, unknown> | undefined)?.[${q1(seg)}]`, varName);
}

function renderTableCell(field, render) {
  const value = `(row as Record<string, unknown>)?.[${q1(field)}]`;
  if (render === 'tag') {
    return `<UiChip size="small" label={String(${value} ?? '')} />`;
  }
  if (render === 'tag-count') {
    return `<UiChip size="small" label={String(Array.isArray(${value}) ? (${value} as unknown[]).length : 0)} />`;
  }
  if (render === 'date') {
    return `<>{${value} == null ? '' : new Date(String(${value})).toLocaleString()}</>`;
  }
  if (render === 'link') {
    return `<a href={String(${value} ?? '')} target="_blank" rel="noreferrer" style={{ color: 'inherit' }}>{String(${value} ?? '')}</a>`;
  }
  if (render === undefined) {
    return `<>{String(${value} ?? '')}</>`;
  }
  throw new Error(`emit/dashboard: render kind "${render}" tak dikenal di dashboard table (resmi: tag|tag-count|date|link)`);
}

function formatStatValue(varExpr, format) {
  if (format === 'currency') {
    return `new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(${varExpr}) || 0)`;
  }
  if (format === 'percent') {
    return `(${varExpr} ?? '-') + '%'`;
  }
  if (format === 'number') {
    return `new Intl.NumberFormat('id-ID').format(Number(${varExpr}) || 0)`;
  }
  return `String(${varExpr} ?? '-')`;
}

function dashboardFile(ir, page, adapter) {
  const dash = page.dashboard;
  const stats = dash.stats ?? [];
  const charts = dash.charts ?? [];
  const tables = dash.tables ?? [];
  const warnings = [];

  // Kumpulkan api unik yang BENAR-BENAR dipakai (stats+tables) - charts TIDAK fetch,
  // supaya tak ada request/data yang tak pernah dirender (doc §21 no dead code).
  const apiByName = new Map((ir.apis ?? []).map((a) => [a.name, a]));
  const usedApiNames = new Set([...stats.map((s) => s.value.source), ...tables.map((t) => t.source)].map((s) => splitSource(s).apiName));
  const fetchers = [...usedApiNames].map((name) => {
    const api = apiByName.get(name);
    if (!api) throw new Error(`emit/dashboard: apis[] tidak punya entry "${name}" (dirujuk dashboard ${page.id})`);
    return { name, camel: camel(name), path: resolveApiPath(api.path, ir), method: api.method };
  });

  const statCardCovered = adapter.coverage().find((c) => c.semantic === 'stat-card')?.status === 'covered';

  const L = [];
  L.push(BANNER);
  L.push(`// Dashboard ${page.id}: ${stats.length} stat, ${charts.length} chart (placeholder), ${tables.length} tabel.`);
  L.push('// Data stats/tables dari apis[] registry (F5) - fetch sekali saat mount, tanpa polling.');
  L.push('');
  L.push("import { ReactElement, useEffect, useState } from 'react';");
  L.push("import { apiRequest } from '../../gen/apiClient';");
  const uiMembers = ['UiBox', 'UiTypography', 'UiCard'];
  if (tables.length) uiMembers.push('UiTable', 'UiTableHead', 'UiTableBody', 'UiTableRow', 'UiTableCell');
  if (tables.some((tb) => (tb.columns ?? []).some((c) => c.render === 'tag' || c.render === 'tag-count'))) uiMembers.push('UiChip');
  if (statCardCovered && stats.length) uiMembers.push('UiStatCard');
  L.push(`import { ${[...new Set(uiMembers)].join(', ')} } from '../../gen/ui';`);
  L.push('');

  L.push('export default function Dashboard(): ReactElement {');
  L.push('  const [data, setData] = useState<Record<string, unknown>>({});');
  L.push('  const [loading, setLoading] = useState(true);');
  L.push('');
  L.push('  useEffect(() => {');
  L.push('    let alive = true;');
  L.push('    Promise.all([');
  for (const f of fetchers) {
    L.push(`      apiRequest(${q1(f.path)}, { method: ${q1(f.method)} }).then((e) => [${q1(f.name)}, e.data] as const),`);
  }
  L.push('    ]).then((entries) => {');
  L.push('      if (!alive) return;');
  L.push('      setData(Object.fromEntries(entries));');
  L.push('    }).catch(() => {');
  L.push('      // Backend belum tersedia / salah satu request gagal - dashboard tetap');
  L.push('      // tampil dengan data kosong (stat 0, tabel kosong), BUKAN crash. Sama pola');
  L.push('      // dengan empty-state list/detail lain - tanpa ini Promise.all yang reject');
  L.push('      // tak pernah tertangkap sama sekali (unhandled rejection -> React crash).');
  L.push('    }).finally(() => {');
  L.push('      if (alive) setLoading(false);');
  L.push('    });');
  L.push('    return () => { alive = false; };');
  L.push('  }, []);');
  L.push('');
  L.push('  if (loading) {');
  L.push("    return (<UiBox sx={{ p: 4 }}><UiTypography>Memuat...</UiTypography></UiBox>);");
  L.push('  }');
  L.push('');
  L.push('  return (');
  L.push("    <UiBox sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>");

  if (stats.length) {
    L.push("      <UiBox sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 2 }}>");
    for (const stat of stats) {
      const { apiName, path: segs } = splitSource(stat.value.source);
      const varExpr = accessorExpr(`data[${q1(apiName)}]`, segs);
      const formatted = formatStatValue(varExpr, stat.format);
      if (statCardCovered) {
        L.push(`        <UiStatCard label={${q1(stat.title)}} value={${formatted}} />`);
      } else {
        // Fallback (mui/neudela: status 'fallback') - rakit dari UiCard+UiTypography yang
        // SUDAH ada di barrel, bukan simbol UiStatCard (lihat catatan barrelMembersFor).
        L.push('        <UiCard sx={{ p: 2 }}>');
        L.push(`          <UiTypography variant="body2" sx={{ color: 'text.secondary' }}>{${q1(stat.title)}}</UiTypography>`);
        L.push(`          <UiTypography variant="h5">{${formatted}}</UiTypography>`);
        L.push('        </UiCard>');
      }
    }
    L.push('      </UiBox>');
  }

  for (const chart of charts) {
    warnings.push(
      `dashboard/${page.id}: chart "${chart.title}" (type=${chart.type}, source=${chart.source}) TIDAK dirender - v1 tanpa chart dependency (guardrail @mui/x-charts). Placeholder UiCard.`,
    );
    L.push('      <UiCard sx={{ p: 2 }}>');
    L.push(`        <UiTypography variant="body2" sx={{ color: 'text.secondary' }}>{${q1(chart.title)}}</UiTypography>`);
    L.push(`        <UiTypography variant="caption" sx={{ color: 'text.secondary' }}>{${q1('Chart ' + chart.type + ' belum tersedia (v1)')}}</UiTypography>`);
    L.push('      </UiCard>');
  }

  for (const table of tables) {
    const { apiName, path: segs } = splitSource(table.source);
    const rowsExpr = accessorExpr(`data[${q1(apiName)}]`, segs);
    const cols = table.columns ?? [];
    L.push('      <UiCard sx={{ p: 2 }}>');
    L.push(`        <UiTypography variant="h6">{${q1(table.title)}}</UiTypography>`);
    L.push('        <UiTable size="small">');
    L.push('          <UiTableHead>');
    L.push('            <UiTableRow>');
    for (const c of cols) L.push(`              <UiTableCell>{${q1(c.label)}}</UiTableCell>`);
    L.push('            </UiTableRow>');
    L.push('          </UiTableHead>');
    L.push('          <UiTableBody>');
    const limitExpr = table.limit ? `.slice(0, ${table.limit})` : '';
    L.push(`          {((${rowsExpr} as unknown[] | undefined) ?? [])${limitExpr}.map((row, i) => (`);
    L.push('            <UiTableRow key={i}>');
    for (const c of cols) L.push(`              <UiTableCell>${renderTableCell(c.field, c.render)}</UiTableCell>`);
    L.push('            </UiTableRow>');
    L.push('          ))}');
    L.push('          </UiTableBody>');
    L.push('        </UiTable>');
    L.push('      </UiCard>');
  }

  L.push('    </UiBox>');
  L.push('  );');
  L.push('}');
  L.push('');

  return { code: L.join('\n'), warnings };
}

export function emitDashboards(feir, appDir) {
  if (feir.output?.mfe?.federationTemplate === 'common-remote') {
    // Dashboards are out of scope for mcs-common in this round (no dashboard concept in
    // the hand-built reference, product-qualification has none either) - explicit no-op
    // rather than silently emitting a self-contained-style Dashboard.tsx nothing wires up.
    return { written: [], summary: 'dashboard: federationTemplate=common-remote - belum didukung mcs-common, dilewati' };
  }
  const dashboardPages = (feir.pages ?? []).filter((p) => p.view === 'dashboard');
  if (!dashboardPages.length) {
    return { written: [], summary: '0 dashboard page(s)' };
  }

  const adapter = loadAdapter(feir.ui?.library ?? 'mui');
  const written = [];
  const warnings = [];
  const write = (rel, content) => {
    const abs = path.join(appDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf8');
    written.push(rel);
  };

  for (const page of dashboardPages) {
    const { code, warnings: w } = dashboardFile(feir, page, adapter);
    write(`src/pages/${page.id}/Dashboard.tsx`, code);
    warnings.push(...w);
  }

  return {
    written: written.sort(),
    summary: `${dashboardPages.length} dashboard page(s) -> src/pages/<id>/Dashboard.tsx`,
    warnings,
  };
}
