// emit/form.mjs - M4 form emitter (todo 8).
//
// Dari FEIR forms add/edit -> 3 file per page (deterministik, tanpa import @mui/):
//   src/pages/<id>/zodSchemas.ts  - FieldSpec[] (kontrak StandardFormModal), payloadSpec
//                                   (api.payload), defaults, zod schema mirror, mapDetailToDefaults
//   src/pages/<id>/AddForm.tsx    - StandardFormModal assembly, submit -> POST create
//   src/pages/<id>/EditForm.tsx   - StandardFormModal assembly, prefill GET retrieve -> defaults,
//                                   submit -> PATCH update (payload TANPA @type dari editPayloadSpec)
//
// Kontrak runtime WAJIB (template src/gen/StandardFormModal.tsx - baca sebelum pakai):
//   StandardFormModal membangun schema zod-nya SENDIRI dari fields[].zodRules di runtime;
//   emitter TIDAK passing schema - zodSchemas.ts adalah artifact mirror (di-assert payload-check)
//   + sumber FieldSpec yang sama yang diserahkan ke modal (konsistensi by construction).
//   itemPayload repeatable direkonstruksi runtime (toPayload di StandardFormModal.submit);
//   payloadSpec root memetakan flat -> wire (token "fields.X" / "item.Y").
// Guardrail: 0 import "@mui/" di file emitted; 0 U+FFFD; deterministik (tanpa clock/random/path);
//            SEMUA komentar ASCII (hygiene encoding - klasik mojibake replacement char).
import fs from 'node:fs';
import path from 'node:path';
import { loadAdapter } from '../../../libs/adapter.mjs';
import { endpointsFor } from './endpoints.mjs';

const BANNER = '// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.';

const TOKEN_RE = /^item\.([A-Za-z0-9_]+)$/;

/* ---------- naming helpers (sama pola emit/page.mjs) ------------------ */

const kebab = (s) => String(s).replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const pascal = (s) => String(s).charAt(0).toUpperCase() + String(s).slice(1);
const pascalKebab = (s) => String(s).split('-').map(pascal).join('');
const q1 = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

function resolveApiPath(template, ir) {
  const base = ir.api?.basePath ?? '';
  const out = String(template).replace(/\{\{\s*api\.basePath\s*\}\}/g, base);
  if (/\{\{/.test(out)) throw new Error(`emit/form: binding tak dikenal di api path "${out}"`);
  return out;
}

function resourceInfo(page, ir) {
  const pathStr = resolveApiPath(page.list?.api, ir);
  const seg = pathStr.split('/').filter(Boolean).pop();
  if (!seg) throw new Error(`emit/form: tidak dapat menentukan resource dari list.api "${page.list?.api}"`);
  // pascalKebab (bukan pascal polos): resource multi-kata dari path REST kebab-case
  // (mis. /api/retail/activity-log) HARUS jadi identifier valid (ActivityLog), bukan
  // 'Activity-log' (hyphen di nama interface/type -> SyntaxError TS). Bug nyata,
  // ditemukan lewat spec dengan resource path multi-kata pertama kali.
  return { camel: seg, kebab: kebab(seg), pascal: pascalKebab(seg) };
}

/* ---------- semantic -> runtime FieldSpec.type (kontrak StandardFormModal) ---------- */

export const TYPE_RUNTIME = {
  'text-input': 'text',
  textarea: 'textarea',
  'number-input': 'number',
  'email-input': 'email',
  'password-input': 'password',
  select: 'select',
  toggle: 'toggle',
  'repeatable-group': 'repeatable',
  // F3
  'date-input': 'date',
  'datetime-input': 'datetime',
  checkbox: 'checkbox',
  'radio-group': 'radio',
  typeahead: 'autocomplete',
};

/* ---------- zod expression builder (mirror persis keputusan runtime zodField:
             required -> .min(1,msg), lalu minLength/maxLength/email/pattern;
             number -> min/max; repeatable -> z.array(itemSchema)[.min(n,msg)];
             toggle -> boolean optional) ---------- */

export function zodFieldExpr(f, rtLookup = TYPE_RUNTIME) {
  const rules = f.zodRules ?? [];
  const req = !!f.required;
  const rt = rtLookup[f.type] ?? f.type;
  const msgOf = (r) => q1(r?.message ?? 'Wajib diisi');

  if (rt === 'repeatable') {
    const itemExprs = (f.itemFields ?? []).map((sub) => `${q1(sub.name)}: ${zodFieldExpr(sub, rtLookup)}`);
    let s = `z.array(z.object({ ${itemExprs.join(', ')} }))`;
    const mi = rules.find((r) => r.rule === 'minItems');
    if (mi) s += `.min(${JSON.stringify(mi.value ?? 1)}, ${msgOf(mi)})`;
    else if (req) s += `.min(1, ${msgOf(rules.find((r) => r.rule === 'required'))})`;
    return s;
  }
  if (rt === 'toggle' || rt === 'checkbox') return 'z.boolean().optional()';
  if (rt === 'number') {
    let s = 'z.coerce.number()';
    for (const r of rules) {
      if (r.rule === 'min') s += `.min(${JSON.stringify(r.value)}, ${msgOf(r)})`;
      if (r.rule === 'max') s += `.max(${JSON.stringify(r.value)}, ${msgOf(r)})`;
    }
    if (!req) s += '.optional()';
    return s;
  }
  let s = 'z.string()';
  if (req) s += `.min(1, ${msgOf(rules.find((r) => r.rule === 'required'))})`;
  for (const r of rules) {
    if (r.rule === 'minLength') s += `.min(${JSON.stringify(r.value)}, ${msgOf(r)})`;
    else if (r.rule === 'maxLength') s += `.max(${JSON.stringify(r.value)}, ${msgOf(r)})`;
    else if (r.rule === 'email') s += '.email()';
    else if (r.rule === 'pattern') s += `.regex(new RegExp(${JSON.stringify(String(r.value))}))`;
  }
  if (!req) s += '.optional()';
  return s;
}

/* ---------- FieldSpec literal emission ------------------------------- */

function tsValue(v) {
  return JSON.stringify(v); // numbers/booleans/null/strings/objects - JSON literal valid TS
}

function zodRulesLiteral(rules) {
  const L = rules.map((r) => {
    const parts = [`rule: ${JSON.stringify(r.rule)}`];
    if (r.value !== undefined) parts.push(`value: ${tsValue(r.value)}`);
    if (r.message !== undefined) parts.push(`message: ${JSON.stringify(r.message)}`);
    return `{ ${parts.join(', ')} }`;
  });
  return `[${L.join(', ')}]`;
}

function fieldSpecLiteral(f, rtLookup = TYPE_RUNTIME) {
  const rt = rtLookup[f.type] ?? f.type;
  const parts = [];
  parts.push(`name: ${JSON.stringify(f.name)}`);
  parts.push(`type: ${JSON.stringify(rt)}`);
  if (f.label !== undefined) parts.push(`label: ${JSON.stringify(f.label)}`);
  if (f.required) parts.push('required: true');
  if (f.readOnly) parts.push('readOnly: true');
  if (f.defaultValue !== undefined) parts.push(`defaultValue: ${tsValue(f.defaultValue)}`);
  if (f.placeholder !== undefined) parts.push(`placeholder: ${JSON.stringify(f.placeholder)}`);
  if (f.computedFrom !== undefined) parts.push(`computedFrom: ${JSON.stringify(f.computedFrom)}`);
  if (f.rows !== undefined) parts.push(`rows: ${JSON.stringify(f.rows)}`);
  if (f.options && Object.keys(f.options).length) parts.push(`options: ${tsValue(f.options)}`);
  if (f.minItems !== undefined) parts.push(`minItems: ${JSON.stringify(f.minItems)}`);
  if (f.min !== undefined) parts.push(`min: ${tsValue(f.min)}`);
  if (f.max !== undefined) parts.push(`max: ${tsValue(f.max)}`);
  if (f.layout !== undefined) parts.push(`layout: ${JSON.stringify(f.layout)}`);
  if (f.itemLabel !== undefined) parts.push(`itemLabel: ${JSON.stringify(f.itemLabel)}`);
  if (f.addButton !== undefined) parts.push(`addButton: ${JSON.stringify(f.addButton)}`);
  const rules = f.zodRules ?? [];
  if (rules.length) parts.push(`zodRules: ${zodRulesLiteral(rules)}`);
  if (f.itemFields?.length) {
    parts.push(`itemFields: [${f.itemFields.map((sub) => fieldSpecLiteral(sub, rtLookup)).join(', ')}]`);
  }
  if (f.itemPayload && Object.keys(f.itemPayload).length) parts.push(`itemPayload: ${tsValue(f.itemPayload)}`);
  return `{\n      ${parts.join(',\n      ')}\n    }`;
}

/* ---------- defaults ------------------------------------------------ */

function defaultsForFields(fields) {
  const out = {};
  for (const f of fields) {
    if (f.type === 'repeatable-group' || f.type === 'repeatable') out[f.name] = [];
    else if (f.defaultValue !== undefined) out[f.name] = f.defaultValue;
    else if (f.type === 'toggle' || f.type === 'checkbox') out[f.name] = false;
    else out[f.name] = ''; // termasuk date-input/datetime-input/radio-group/typeahead (F3)
  }
  return out;
}

/* ---------- mapDetailToDefaults: inverse itemPayload (wire nested -> flat field) ---------- */

function collectItemTokens(payload, prefix = [], out = []) {
  for (const [k, v] of Object.entries(payload ?? {})) {
    if (typeof v === 'string') {
      const m = TOKEN_RE.exec(v);
      if (m) out.push({ flat: m[1], wire: [...prefix, k] });
    } else if (v && typeof v === 'object' && !Array.isArray(v)) {
      collectItemTokens(v, [...prefix, k], out);
    }
  }
  return out;
}

function wireAccessor(wire) {
  if (!wire.length) return '(item as Record<string, unknown>)';
  // item["a"] adalah unknown - cast explicit utk TS strict. Key tunggal -> akses langsung.
  let acc = '(item as Record<string, unknown>)';
  for (const k of wire) {
    acc = `((${acc}) as Record<string, unknown> | undefined)?.[${JSON.stringify(k)}]`;
  }
  return acc;
}

function itemPrefillLiteral(itemFields, itemPayload) {
  const leafDefault = new Map();
  for (const sf of itemFields ?? []) leafDefault.set(sf.name, sf.defaultValue);
  const tokens = collectItemTokens(itemPayload);
  const parts = tokens.map(({ flat, wire }) => {
    const dflt = leafDefault.has(flat) ? leafDefault.get(flat) : '';
    const dfltTs = typeof dflt === 'string' ? JSON.stringify(dflt) : tsValue(dflt);
    return `    ${JSON.stringify(flat)}: ${wireAccessor(wire)} ?? ${dfltTs}`;
  });
  return parts.join(',\n');
}

/** Root prefill dari add api.payload (token fields.X) - wire key -> flat name. */
function rootPrefillLiteral(fields, addPayload) {
  const byName = new Map(fields.map((f) => [f.name, f]));
  const parts = [];
  for (const [wireKey, token] of Object.entries(addPayload)) {
    if (typeof token !== 'string') continue; // nested object bukan root scalar
    const m = /^fields\.([A-Za-z0-9_]+)$/.exec(token);
    if (!m) continue;
    const flat = m[1];
    const f = byName.get(flat);
    if (f && (f.type === 'repeatable-group' || f.type === 'repeatable')) continue; // di-rekonstruksi blok repeatable
    const dflt = typeof f?.defaultValue === 'string' ? JSON.stringify(f.defaultValue) : "''";
    parts.push(`    ${JSON.stringify(flat)}: detail[${JSON.stringify(wireKey)}] ?? ${dflt}`);
  }
  return parts.join(',\n');
}

function mapDetailFn(pageFields, addPayload) {
  const repeatables = (pageFields ?? []).filter((f) => f.type === 'repeatable-group' || f.type === 'repeatable');
  const blocks = repeatables.map((f) => {
    const arrVar = f.name;
    return [
      `  const ${arrVar}Arr = (detail[${JSON.stringify(f.name)}] as Array<Record<string, unknown>> | undefined) ?? [];`,
      `  out[${JSON.stringify(f.name)}] = ${arrVar}Arr.map((item: Record<string, unknown>) => ({`,
      itemPrefillLiteral(f.itemFields, f.itemPayload),
      '  }));',
    ].join('\n');
  });
  return [
    `export function mapDetailToDefaults(detail: Record<string, unknown>): Record<string, unknown> {`,
    `  const out: Record<string, unknown> = {`,
    rootPrefillLiteral(pageFields, addPayload),
    '  };',
    blocks.join('\n'),
    '  return out;',
    '}',
  ].join('\n');
}

/* ---------- zodSchemas.ts ------------------------------------------- */

export function zodSchemasFile(page, fields, editFields, defaults, editDefaults, addPayload, editPayload) {
  const shapeAdd = fields.map((f) => `${q1(f.name)}: ${zodFieldExpr(f)}`).join(', ');
  const shapeEdit = editFields.map((f) => `${q1(f.name)}: ${zodFieldExpr(f)}`).join(', ');
  const L = [];
  L.push(BANNER);
  L.push('// Zod schemas + FieldSpec (kontrak StandardFormModal) + payload spec (api.payload)');
  L.push('// untuk form add/edit halaman ini. FieldSpec adalah SATU-SATUNYA sumber yang diserahkan');
  L.push('// ke StandardFormModal runtime (modal membangun schema zod internal dari zodRules).');
  L.push('// zodSchema di bawah = mirror eksplisit (di-assert fe-payload-check; dibutuhkan tsc).');
  L.push("import { z } from 'zod';");
  L.push("import type { FieldSpec } from '../../gen/StandardFormModal';");
  L.push('');
  L.push(`export const addFields: FieldSpec[] = [\n    ${fields.map((f) => fieldSpecLiteral(f)).join(',\n    ')}\n  ];`);
  L.push('');
  L.push(`export const editFields: FieldSpec[] = [\n    ${editFields.map((f) => fieldSpecLiteral(f)).join(',\n    ')}\n  ];`);
  L.push('');
  L.push(`export const addDefaults: Record<string, unknown> = ${tsValue(defaults)};`);
  L.push(`export const editDefaultsBase: Record<string, unknown> = ${tsValue(editDefaults)};`);
  L.push('');
  L.push(`export const addPayloadSpec: Record<string, unknown> = ${tsValue(addPayload)};`);
  L.push(`export const editPayloadSpec: Record<string, unknown> = ${tsValue(editPayload)};`);
  L.push('');
  L.push(`export const addZodSchema = z.object({ ${shapeAdd} });`);
  L.push(`export const editZodSchema = z.object({ ${shapeEdit} });`);
  L.push('');
  L.push(mapDetailFn(fields, addPayload));
  L.push('');
  return L.join('\n');
}

/* ---------- AddForm.tsx --------------------------------------------- */

export function addFormFile(ir, page, form, res) {
  const mode = ir.formEngine?.defaultMode ?? 'onChange';
  const reMode = ir.formEngine?.defaultReValidateMode ?? 'onChange';
  const L = [];
  L.push(BANNER);
  L.push(`// Form add ${page.id} - assembly StandardFormModal (RHF+zod runtime di src/gen/).`);
  L.push('// Payload POST = addPayloadSpec (api.payload; itemPayload direkonstruksi runtime).');
  L.push('// FieldSpec/zodRules/defaults di zodSchemas.ts (sumber tunggal).');
  L.push('');
  L.push("import { ReactElement, useCallback } from 'react';");
  L.push("import { StandardFormModal } from '../../gen/StandardFormModal';");
  L.push(`import { create${res.pascal} } from '../../gen/api/${res.kebab}';`);
  L.push("import { addDefaults, addFields, addPayloadSpec } from './zodSchemas';");
  L.push('');
  L.push('export interface AddFormProps {');
  L.push('  open: boolean;');
  L.push('  onClose: () => void;');
  L.push('  onSaved: () => void;');
  L.push('}');
  L.push('');
  L.push('export default function AddForm({ open, onClose, onSaved }: AddFormProps): ReactElement {');
  L.push('  const handleSubmit = useCallback(');
  L.push('    async (values: Record<string, unknown>) => {');
  L.push(`      await create${res.pascal}(values);`);
  L.push('      onSaved();');
  L.push('      onClose(); // tutup modal setelah simpan sukses (guard: jangan hang terbuka)');
  L.push('    },');
  L.push('    [onSaved, onClose],');
  L.push('  );');
  L.push('');
  L.push('  return (');
  L.push('    <StandardFormModal');
  L.push('      open={open}');
  L.push(`      title={${JSON.stringify(form.title ?? 'Form')}}`);
  L.push(`      width={${JSON.stringify(form.width ?? 'md')}}`);
  L.push('      fields={addFields}');
  L.push('      defaultValues={addDefaults}');
  L.push('      payloadSpec={addPayloadSpec}');
  L.push(`      mode={${q1(mode)}}`);
  L.push(`      reValidateMode={${q1(reMode)}}`);
  L.push(`      submitLabel={${JSON.stringify(form.buttons?.submit?.label ?? 'Simpan')}}`);
  L.push(`      cancelLabel={${JSON.stringify(form.buttons?.cancel?.label ?? 'Batal')}}`);
  L.push('      onSubmit={handleSubmit}');
  L.push('      onClose={onClose}');
  L.push('    />');
  L.push('  );');
  L.push('}');
  L.push('');
  return L.join('\n');
}

/* ---------- EditForm.tsx --------------------------------------------- */

export function editFormFile(ir, page, form, res) {
  const mode = ir.formEngine?.defaultMode ?? 'onChange';
  const reMode = ir.formEngine?.defaultReValidateMode ?? 'onChange';
  const L = [];
  L.push(BANNER);
  L.push(`// Form edit ${page.id} - StandardFormModal + prefill GET retrieve -> defaults flat.`);
  L.push('// PATCH payload = editPayloadSpec (api.payload edit - TANPA @type; partial _MVO).');
  L.push('// Gate `ready`: modal baru dibuka setelah prefill selesai (kontrak reset-on-open);');
  L.push('// kalau retrieve gagal, form tetap terbuka dengan defaults kosong + console.error.');
  L.push('');
  L.push("import { ReactElement, useCallback, useEffect, useState } from 'react';");
  L.push("import { StandardFormModal } from '../../gen/StandardFormModal';");
  L.push("import { ApiError } from '../../gen/apiClient';");
  L.push(`import { get${res.pascal}, update${res.pascal} } from '../../gen/api/${res.kebab}';`);
  L.push("import { editDefaultsBase, editFields, editPayloadSpec, mapDetailToDefaults } from './zodSchemas';");
  L.push('');
  L.push('export interface EditFormProps {');
  L.push('  open: boolean;');
  L.push('  id: string | number;');
  L.push('  onClose: () => void;');
  L.push('  onSaved: () => void;');
  L.push('}');
  L.push('');
  L.push('export default function EditForm({ open, id, onClose, onSaved }: EditFormProps): ReactElement {');
  L.push('  const [defaults, setDefaults] = useState<Record<string, unknown>>(editDefaultsBase);');
  L.push('  const [ready, setReady] = useState(false);');
  L.push('');
  L.push('  useEffect(() => {');
  L.push('    if (!open) return;');
  L.push('    let cancelled = false;');
  L.push('    setReady(false);');
  L.push(`    get${res.pascal}(id)`);
  L.push('      .then((detail) => {');
  L.push('        if (cancelled) return;');
  L.push('        setDefaults(detail ? mapDetailToDefaults(detail as Record<string, unknown>) : editDefaultsBase);');
  L.push('        setReady(true);');
  L.push('      })');
  L.push('      .catch((err) => {');
  L.push('        if (cancelled) return;');
  L.push("        console.error('[fe-gen] EditForm prefill gagal:', err instanceof ApiError ? err.message : err);");
  L.push('        setReady(true);');
  L.push('      });');
  L.push('    return () => {');
  L.push('      cancelled = true;');
  L.push('    };');
  L.push('  }, [open, id]);');
  L.push('');
  L.push('  const handleSubmit = useCallback(');
  L.push('    async (values: Record<string, unknown>) => {');
  L.push(`      await update${res.pascal}(id, values);`);
  L.push('      onSaved();');
  L.push('      onClose(); // tutup modal setelah simpan sukses');
  L.push('    },');
  L.push('    [id, onSaved, onClose],');
  L.push('  );');
  L.push('');
  L.push('  return (');
  L.push('    <StandardFormModal');
  L.push('      open={open && ready}');
  L.push(`      title={${JSON.stringify(form.title ?? 'Form')}}`);
  L.push(`      width={${JSON.stringify(form.width ?? 'md')}}`);
  L.push('      fields={editFields}');
  L.push('      defaultValues={defaults}');
  L.push('      payloadSpec={editPayloadSpec}');
  L.push(`      mode={${q1(mode)}}`);
  L.push(`      reValidateMode={${q1(reMode)}}`);
  L.push(`      submitLabel={${JSON.stringify(form.buttons?.submit?.label ?? 'Simpan')}}`);
  L.push(`      cancelLabel={${JSON.stringify(form.buttons?.cancel?.label ?? 'Batal')}}`);
  L.push('      onSubmit={handleSubmit}');
  L.push('      onClose={onClose}');
  L.push('    />');
  L.push('  );');
  L.push('}');
  L.push('');
  return L.join('\n');
}

/* ---------- emitForms ------------------------------------------------ */

/**
 * Emit form files untuk setiap page FEIR yang punya forms.add/edit.
 * @returns {{ written: string[], summary: string }}
 */
/** Warning eksplisit (F3): field yang payload-nya pakai transform TIDAK BISA di-inverse
 * saat edit (rootPrefillLiteral/collectItemTokens hanya mengenali token string) - field
 * itu dikosongkan di EditForm, bukan diam-diam. Satu warning per field yang terpengaruh. */
function collectTransformWarnings(pageId, payload) {
  const warnings = [];
  for (const [k, v] of Object.entries(payload ?? {})) {
    if (v && typeof v === 'object' && !Array.isArray(v) && '$src' in v) {
      if (v.$tx) warnings.push(`form ${pageId}: field "${k}" pakai transform "${v.$tx}" - prefill edit tidak dapat di-inverse, field dikosongkan`);
    } else if (v && typeof v === 'object' && !Array.isArray(v)) {
      warnings.push(...collectTransformWarnings(pageId, v));
    }
  }
  return warnings;
}

export function emitForms(feir, appDir) {
  if (feir.output?.mfe?.federationTemplate === 'common-remote') {
    // mcs-common owns form emission entirely (emit/mcs-common/pages.mjs's Create*Dialog) -
    // it renders relation/repeatable fields its own way (RefAutocompleteField, local
    // useFieldArray), not StandardFormModal's FieldSpec dispatch. See emit/mfe.mjs's guard.
    return { written: [], summary: 'form: federationTemplate=common-remote - delegasi ke emit/mcs-common (form.mjs dilewati)' };
  }
  // F3: form.mjs sebelumnya TIDAK PERNAH konsultasi adapter - field type apa pun lolos
  // ke StandardFormModal.tsx (dispatch statis), termasuk semantic yang UNSUPPORTED untuk
  // library aktif (mis. typeahead di fe-default/neudela). Beda dengan emit/page.mjs yang
  // sudah resolve() setiap kolom/tombol. Preflight ini menyamakan perlakuannya: field yang
  // adapter-nya throw UNSUPPORTED gagal SEKARANG (pesan jelas), bukan diam-diam jadi text
  // input generik saat runtime.
  const adapter = loadAdapter(feir.ui?.library ?? 'mui');
  const checkFieldSupport = (f, pointer) => {
    if (!f || f.reuse) return;
    adapter.resolve(f.type); // melempar bila UNSUPPORTED - pesan sudah baku dari adapter
    for (const [i, sub] of (f.itemFields ?? []).entries()) checkFieldSupport(sub, `${pointer}/itemFields/${i}`);
  };
  for (const page of feir.pages ?? []) {
    for (const kind of ['add', 'edit']) {
      for (const [i, f] of (page.forms?.[kind]?.fields ?? []).entries()) {
        checkFieldSupport(f, `/pages/${page.id}/forms/${kind}/fields/${i}`);
      }
    }
  }

  const written = [];
  const write = (rel, content) => {
    if (content.includes('\uFFFD')) {
      throw new Error(`emit/form: U+FFFD ditemukan di "${rel}" (mojibake guard) - berhenti`);
    }
    const abs = path.join(appDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf8');
    written.push(rel);
  };

  let formPages = 0;
  const warnings = [];
  for (const page of feir.pages ?? []) {
    const forms = page.forms;
    if (!forms?.add && !forms?.edit) continue;
    const res = resourceInfo(page, feir);
    const eps = endpointsFor(feir, page);
    if (forms.add && !eps.create) {
      throw new Error(`emit/form: page ${page.id} bentuk add tapi FEIR tidak punya endpoint create (no invented endpoints)`);
    }
    if (forms.edit && (!eps.update || !eps.retrieve)) {
      throw new Error(`emit/form: page ${page.id} bentuk edit tapi FEIR tidak punya endpoint update/retrieve (no invented endpoints)`);
    }

    const addFieldDefs = forms.add?.fields ?? [];
    const addPayload = forms.add?.api?.payload ?? {};
    const editHasFields = (forms.edit?.fields ?? []).some((f) => f && !(f.reuse === 'add'));
    const editFieldDefs = editHasFields ? forms.edit.fields : addFieldDefs; // reuse: add
    const editPayload = forms.edit?.api?.payload ?? {};

    warnings.push(...collectTransformWarnings(page.id, addPayload));
    warnings.push(...collectTransformWarnings(page.id, editPayload));

    const addDefaults = defaultsForFields(addFieldDefs);
    const editDefaults = defaultsForFields(editFieldDefs);

    write(`src/pages/${page.id}/zodSchemas.ts`, zodSchemasFile(page, addFieldDefs, editFieldDefs, addDefaults, editDefaults, addPayload, editPayload));
    if (forms.add) write(`src/pages/${page.id}/AddForm.tsx`, addFormFile(feir, page, forms.add, res));
    if (forms.edit) write(`src/pages/${page.id}/EditForm.tsx`, editFormFile(feir, page, forms.edit, res));
    formPages += 1;
  }

  return {
    written: written.sort(),
    summary: `${formPages} form pair(s) -> src/pages/<id>/zodSchemas.ts + AddForm.tsx + EditForm.tsx`,
    warnings,
  };
}