// emit/mfe.mjs - M5 MFE emitter (todo 10).
//
// Aktif HANYA saat feir.output.type === 'mfe'. Menulis app-level (sekali per emitAll):
//   craco.config.js          - Module Federation (KONVENSI remote tim, capacity craco):
//                              name `snake_remote`, filename `<camel>RemoteEntry.js`,
//                              exposes {key -> target} DIBANGKITKAN dari feir.pages
//                              (src/exposes/*), remotes {} KOSONG (self-contained —
//                              MUI di-bundle; TIDAK pernah common_remote), shared react
//                              trio { singleton:true, requiredVersion:false }, .mjs rule,
//                              optimization.sideEffects=false.
//   src/exposes/*.tsx        - wrapper federation boundary, SATU per halaman routable
//                              (view list/dashboard) + `./routes`. Tiap wrapper merender
//                              halamannya sendiri; `./routes` re-export appRoutes/appMenu
//                              utk host. Daftar expose DIBANGKITKAN dari feir.pages -
//                              bukan dibaca dari spec (lihat deriveExposes).
//   src/gen/auth.tsx         - token receipt STUB (host menyuntik window.__HOST_AUTH__).
//                              Login TIDAK diimplementasi - host yang pegang sesi.
//   .tmfgen-fe-manifest.json - manifest idempoten: daftar file managed/generated + hash
//                              (deteksi file managed yg diedit -> warning), port, exposes.
//
// Guardrail: 0 referensi common_remote / REACT_APP_COMMON_REMOTE_URL (throw bila ada) —
// berlaku PENUH untuk output.mfe.federationTemplate default ('none', 3 adapter self-
// contained). Bila federationTemplate === 'common-remote', emitter ini SKIP total (lihat
// emitMfes()) - craco/exposes/dst untuk template itu ditulis emit/mcs-common/* sebagai
// gantinya, jadi guard di sini tidak pernah dilonggarkan/dilewati untuk kasus lama.
// Deterministik: murni FEIR + isi file saat ini; tanpa clock/random/path absolut.
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';

const BANNER = '// GENERATED by fe-gen emit mfe - DO NOT EDIT. Re-run `fe-gen emit` instead.';

/* ---------- naming helpers (sama pola page/form) ---------------- */

// revenueSharingAlgorithms -> revenue_sharing_algorithms
const snake = (s) => String(s).replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[-\s]+/g, '_').toLowerCase();
// revenueSharingAlgorithms -> revenueSharingAlgorithms
const camel = (s) => String(s).replace(/[-_]+([a-zA-Z])/g, (_, c) => c.toUpperCase());
const q1 = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

// party-rev-sharing-algorithms -> PartyRevSharingAlgorithms (aturan identik dengan
// emit/page.mjs, yang menamai komponen route dari page.id).
const pascal = (w) => (w ? w[0].toUpperCase() + w.slice(1) : w);
const pascalKebab = (s) => String(s).split('-').map(pascal).join('');

/* ---------- derivasi exposes dari halaman ------------------------- */

// Halaman yang punya route sendiri. HARUS himpunan yang sama dengan routablePages di
// emit/page.mjs (routesFile): kalau berbeda, ada halaman yang bisa di-route tapi tidak
// bisa di-mount host, atau sebuah expose menunjuk file halaman yang tidak pernah ditulis.
const ROUTABLE_VIEWS = new Set(['list', 'dashboard']);

/**
 * Daftar expose MFE, dibangkitkan dari FEIR - satu per halaman routable, plus `./routes`.
 *
 * Sebelumnya daftar ini ditulis tangan di spec (`output.mfe.exposes`) dan SETIAP wrapper
 * non-`./routes` merender halaman list pertama, apa pun namanya. Untuk spec 1-halaman itu
 * tidak kelihatan; untuk app 24 halaman, 24 expose menampilkan halaman yang sama. Halaman
 * adalah satu-satunya sumber yang tahu apa yang benar-benar ada, jadi daftar diturunkan
 * dari sana dan `output.mfe.exposes` TIDAK lagi dibaca (federationTemplate 'none').
 *
 * @param {object} feir FEIR hasil buildFEIR.
 * @returns {{key:string,target:string,page:object|null}[]} urut halaman, `./routes` terakhir.
 */
export function deriveExposes(feir) {
  const pages = (feir.pages ?? []).filter((p) => ROUTABLE_VIEWS.has(p.view));
  if (!pages.length) {
    throw new Error('emit/mfe: FEIR tidak punya halaman routable (view list/dashboard) - MFE tanpa expose halaman tidak bermakna');
  }
  const out = [];
  const seen = new Set();
  for (const p of pages) {
    const key = `./${pascalKebab(p.id)}Page`;
    if (seen.has(key)) {
      throw new Error(`emit/mfe: dua halaman menghasilkan expose yang sama (${key}) - page.id harus unik`);
    }
    seen.add(key);
    out.push({ key, target: `src/exposes/${pascalKebab(p.id)}Page.tsx`, page: p });
  }
  out.push({ key: './routes', target: 'src/exposes/routes.tsx', page: null });
  return out;
}

function readPortFromPkg(appDir) {
  const pkg = JSON.parse(fs.readFileSync(path.join(appDir, 'package.json'), 'utf8'));
  const start = pkg.scripts?.start ?? '';
  // Dua bentuk yang pernah dipakai template: `set PORT=5013 && craco start` (lama,
  // Windows-only) dan `cross-env PORT=5013 craco start` (sekarang). Regex lama hanya
  // mengenali bentuk pertama, jadi manifest MFE diam-diam mencatat port: null setelah
  // template pindah ke cross-env. Terima keduanya.
  const m = /(?:set\s+|cross-env\s+)?PORT=(\d{2,5})/i.exec(start);
  return m ? Number(m[1]) : null;
}

function guardCommonRemote(feiR) {
  const blob = JSON.stringify(feiR);
  if (/common_remote|REACT_APP_COMMON_REMOTE_URL/i.test(blob)) {
    throw new Error('emit/mfe: FEIR mengandung referensi common_remote - guardrail (harus 0)');
  }
}

/* ---------- craco.config.js -------------------------------------- */

function cracoFile(feir) {
  const mfe = feir.output?.mfe ?? {};
  const moduleName = mfe.moduleName || 'mfe';
  if (!/^[A-Za-z][A-Za-z0-9]*$/.test(String(moduleName))) {
    throw new Error(`emit/mfe: output.mfe.moduleName "${moduleName}" bukan camelCase valid`);
  }
  const remoteName = `${snake(moduleName)}_remote`;        // revenue_sharing_algorithms_remote
  const entryFile = `${camel(moduleName)}RemoteEntry.js`;  // revenueSharingAlgorithmsRemoteEntry.js
  const exposes = deriveExposes(feir);
  const exposesLiteral = exposes
    .map((e) => `            ${q1(e.key)}: ${q1(`./${String(e.target).replace(/^\.\//, '')}`)},`)
    .join('\n');

  const L = [];
  L.push(BANNER);
  L.push('// Module Federation (M5) - KONVENSI remote tim (capacity-management craco.config.js):');
  L.push(`//   name      = snake_case dari moduleName + '_remote'  (${remoteName})`);
  L.push(`//   filename  = camelCase + 'RemoteEntry.js'            (${entryFile})`);
  L.push('//   shared    = react trio { singleton:true, requiredVersion:false } (konvensi REMOTE.');
  L.push('//               host business-service pakai eager+strictVersion - aman utk remote ini.)');
  L.push('//   remotes   = {} KOSONG (self-contained - MUI di-bundle, TIDAK remote bersama).');
  L.push('//   exposes   = {key -> target} DIBANGKITKAN satu per halaman routable + ./routes.');
  L.push('// .mjs rule + optimization.sideEffects=false (template M3, wajib - lihat template craco).');
  L.push('const { ModuleFederationPlugin } = require("webpack").container;');
  L.push('');
  L.push('module.exports = {');
  L.push('  webpack: {');
  L.push('    configure: (webpackConfig) => {');
  L.push('      webpackConfig.output.publicPath = "auto";');
  L.push('      webpackConfig.output.crossOriginLoading = "anonymous";');
  L.push('      webpackConfig.plugins.push(');
  L.push('        new ModuleFederationPlugin({');
  L.push(`          name: ${q1(remoteName)},`);
  L.push(`          filename: ${q1(entryFile)},`);
  L.push('          remotes: {}, // self-contained MFE - MUI di-bundle; TIDAK remote bersama (guardrail)');
  L.push('          exposes: {');
  L.push(exposesLiteral);
  L.push('          },');
  L.push('          shared: {');
  L.push('            react: { singleton: true, requiredVersion: false },');
  L.push('            "react-dom": { singleton: true, requiredVersion: false },');
  L.push('            "react-router-dom": { singleton: true, requiredVersion: false },');
  L.push('          },');
  L.push('        })');
  L.push('      );');
  L.push('');
  L.push('      // Fix: Webpack 4 + .mjs strict ESM compatibility (wajib).');
  L.push('      webpackConfig.module.rules.push({');
  L.push('        test: /\\.mjs$/,');
  L.push('        include: /node_modules/,');
  L.push('        type: "javascript/auto",');
  L.push('        resolve: { fullySpecified: false },');
  L.push('      });');
  L.push('');
  L.push('      // Fix: MUI barrel ESM + sideEffects optimization (M3 - jangan hapus).');
  L.push('      if (webpackConfig.optimization) webpackConfig.optimization.sideEffects = false;');
  L.push('      else webpackConfig.optimization = { sideEffects: false };');
  L.push('      return webpackConfig;');
  L.push('    },');
  L.push('  },');
  L.push('};');
  return L.join('\n') + '\n';
}

/* ---------- src/exposes/*.tsx wrapper ---------------------------- */

function exposeWrapperFile(expose) {
  if (!expose.page) {
    return [
      BANNER,
      '// Federation boundary `./routes` - re-export appRoutes + appMenu (dari src/gen/routes).',
      '// Host memasang routes ini di router-nya (registrasi host = manual, luar scope generator).',
      "export { appRoutes, appMenu } from '../gen/routes';",
      '',
    ].join('\n');
  }
  const p = expose.page;
  // Nama file komponen per view dipilih dengan aturan yang sama seperti routesFile() di
  // emit/page.mjs - dashboard menulis Dashboard.tsx, list menulis List.tsx.
  const kind = p.view === 'dashboard' ? 'Dashboard' : 'List';
  const name = `${pascalKebab(p.id)}Page`;
  return [
    BANNER,
    `// Federation boundary ${expose.key} -> ${expose.target}.`,
    `// Merender halamannya sendiri (view ${p.view}, page ${p.id}) - bukan halaman list pertama.`,
    '// Rute detail tidak di-expose: komponennya membaca :id dari router, jadi hanya',
    '// bermakna lewat ./routes yang dipasang host.',
    `import Page from '../pages/${p.id}/${kind}';`,
    '',
    `export default function ${name}() {`,
    '  return <Page />;',
    '}',
    '',
  ].join('\n');
}

/* ---------- src/gen/auth.tsx token receipt stub ------------------- */

function authFile() {
  return [
    BANNER,
    '// Token receipt STUB (M5). Login TIDAK diimplementasi di MFE - host yang pegang sesi.',
    '// Kontrak host: host menulis window.__HOST_AUTH__ = { token?, apiKey?, ... } (JSON)',
    '// SEBELUM memuat MFE. gen.config.apiKey (x-api-key utk BE ApiKeyGuard) & token',
    '// (bearer) dibaca apiClient runtime dari getConfig()/config.ts - nilai TIDAK dari build-env.',
    'export interface HostAuth {',
    '  token?: string;',
    '  apiKey?: string;',
    '  [key: string]: unknown;',
    '}',
    '',
    '/* eslint-disable @typescript-eslint/no-explicit-any */',
    'export function getHostAuth(): HostAuth | null {',
    "  if (typeof window === 'undefined') return null;",
    '  const raw = (window as any).__HOST_AUTH__;',
    "  if (!raw || typeof raw !== 'object') return null;",
    '  return raw as HostAuth;',
    '}',
    '',
  ].join('\n');
}

/* ---------- manifest ---------------------------------------------- */

function sha1(text) {
  return createHash('sha1').update(String(text), 'utf8').digest('hex');
}

function manifestFile(feir, appDir, written, managed) {
  const port = readPortFromPkg(appDir);
  const mfe = feir.output?.mfe ?? {};
  const moduleName = mfe.moduleName || 'mfe';
  const remoteName = `${snake(moduleName)}_remote`;
  const entryFile = `${camel(moduleName)}RemoteEntry.js`;
  // union(written, managed): file managed yang tak di-tulis pass ini (mis. auth.tsx yang
  // sudah ada) tetap tercatat -> manifest stabil/idempoten. Manifest sendiri dikecualikan.
  const allPaths = [...new Set([...written, ...managed])].sort().filter((p) => p !== '.tmfgen-fe-manifest.json');
  const files = allPaths.map((rel) => {
    const abs = path.join(appDir, rel);
    const content = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : '';
    return { path: rel, status: managed.has(rel) ? 'managed' : 'generated', hash: sha1(content) };
  });
  return JSON.stringify(
    {
      manifestVersion: 1,
      name: feir.meta?.name ?? 'mfe',
      moduleName,
      remoteName,
      entryFile,
      port,
      files,
      exposes: deriveExposes(feir).map((e) => ({ key: e.key, target: e.target })),
    },
    null,
    2,
  ) + '\n';
}

/* ---------- emitMfes ---------------------------------------------- */

/**
 * Emit MFE artifacts. Idempoten: re-emit menimpa file managed (craco, exposes, auth)
 * dan memperbarui manifest; bila file managed TERNYATA DITEDIT (hash berubah vs
 * manifest) -> warning + ditimpa (overwrite policy: manusia tidak pernah di managed file).
 * @returns {{ written: string[], summary: string }}
 */
export function emitMfes(feir, appDir) {
  if (feir.output?.type !== 'mfe') {
    return { written: [], summary: 'MFE mode nonaktif (output.type != mfe) - dilewati' };
  }
  if (feir.output?.mfe?.federationTemplate === 'common-remote') {
    // Delegasi penuh ke emit/mcs-common/* (lihat emit/index.mjs) - emitter ini TIDAK
    // menulis apa pun untuk template federated. Guard di bawah TIDAK dipanggil di sini
    // karena tidak relevan (mcs-common MEMANG mengonsumsi common_remote secara sengaja);
    // guard tetap berlaku 100% untuk federationTemplate default ('none').
    return { written: [], summary: 'MFE mode: federationTemplate=common-remote - delegasi ke emit/mcs-common (mfe.mjs dilewati)' };
  }
  guardCommonRemote(feir);

  const mfe = feir.output?.mfe ?? {};
  const written = [];
  const warnings = [];
  const write = (rel, content) => {
    const abs = path.join(appDir, rel);
    // deteksi file managed yg diedit/diubah vs output kanonik: bila isi saat ini beda
    // dari yang akan ditulis -> warning + ditimpakan (overwrite policy managed).
    if (fs.existsSync(abs)) {
      const cur = fs.readFileSync(abs, 'utf8');
      if (cur !== content) {
        warnings.push(`${rel} berubah dari output kanonik fe-gen - DITIMPALAN (file managed)`);
      }
    }
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf8');
    written.push(rel);
  };

  const managedSet = new Set();

  // 1. craco.config.js — Module Federation
  write('craco.config.js', cracoFile(feir));
  managedSet.add('craco.config.js');

  // 2. exposes wrapper — satu per halaman routable + ./routes (dibangkitkan; lihat deriveExposes)
  const exposes = deriveExposes(feir);
  for (const e of exposes) {
    write(e.target, exposeWrapperFile(e));
    managedSet.add(e.target);
  }

  // 3. auth stub (file BARU - tidak menyentuh runtime sedia ada)
  const authPath = 'src/gen/auth.tsx';
  if (!fs.existsSync(path.join(appDir, authPath))) {
    write(authPath, authFile());
  } else {
    warnings.push(`${authPath} sudah ada - dibiarkan (auth receipt stub tidak ditimpakan)`);
  }
  managedSet.add(authPath); // tercatat di manifest walau tidak di-tulis pass ini (stabil)

  // 4. manifest
  write('.tmfgen-fe-manifest.json', manifestFile(feir, appDir, written, managedSet));

  const summary =
    `MFE: remote=${snake(mfe.moduleName)}_remote entry=${camel(mfe.moduleName)}RemoteEntry.js ` +
    `exposes=${exposes.length} port=${readPortFromPkg(appDir)} (manifest + auth stub)`;
  return { written: [...new Set(written)].sort(), summary, warnings };
}
