// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EventModule } from '../event/event.module';
import { TopicController } from './topic.controller';
import { TopicService } from './topic.service';
import { Topic } from './entities/topic.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Topic,
    ]),
    EventModule,
  ],
  controllers: [TopicController],
  providers: [TopicService],
  exports: [TopicService],
})
export class TopicModule {}
