// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EventModule } from '../event/event.module';
import { PartyRevSharingAlgorithmController } from './party-rev-sharing-algorithm.controller';
import { PartyRevSharingAlgorithmService } from './party-rev-sharing-algorithm.service';
import { PartyRevSharingAlgorithm } from './entities/party-rev-sharing-algorithm.entity';
import { PolicyRef } from './entities/policy-ref.entity';
import { PolicyConditionRef } from './entities/policy-condition-ref.entity';
import { PolicyVariableRef } from './entities/policy-variable-ref.entity';
import { PartyRevSharingPolicyConditionVariable } from './entities/party-rev-sharing-policy-condition-variable.entity';
import { PolicyActionRef } from './entities/policy-action-ref.entity';
import { PartyRevSharingPolicyActionVariable } from './entities/party-rev-sharing-policy-action-variable.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      PartyRevSharingAlgorithm,
      PolicyRef,
      PolicyConditionRef,
      PolicyVariableRef,
      PartyRevSharingPolicyConditionVariable,
      PolicyActionRef,
      PartyRevSharingPolicyActionVariable,
    ]),
    EventModule,
  ],
  controllers: [PartyRevSharingAlgorithmController],
  providers: [PartyRevSharingAlgorithmService],
  exports: [PartyRevSharingAlgorithmService],
})
export class PartyRevSharingAlgorithmModule {}
