// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/** TMF688 - event names come from the spec's /listener/* paths. */
export enum EventEventType {
  TOPIC_CHANGE = 'topicChangeEvent',
  TOPIC_CREATE = 'topicCreateEvent',
  TOPIC_DELETE = 'topicDeleteEvent',
}
