// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, OneToMany, JoinColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { GeographicPointReferred } from './geographic-point-referred.entity';
import { RetrieveLocationRelation } from './retrieve-location-relation.entity';

@Entity('retrieve_location_relation_intersection')
export class RetrieveLocationRelationIntersection {
  @PrimaryColumn({ type: 'varchar', length: 36 })
  id: string;

  /** Name of the geo location */
  @Column({ type: 'varchar', length: 255 })
  name: string;

  /** Type of the geographic location - one of: point, line, graph, ring polygon */
  @Column({ type: 'varchar', length: 100 })
  geometryType: string;

  /** Geocoding referential */
  @Column({ type: 'varchar', length: 255 })
  spatialRef: string;

  /** Accuracy of the coordinate specified */
  @Column({ type: 'varchar', length: 255 })
  accuracy: string;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  @ManyToOne(() => RetrieveLocationRelation, (parent) => parent.intersection, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'retrieve_location_relation_id' })
  owner: RetrieveLocationRelation;

  @OneToMany(() => GeographicPointReferred, (child) => child.owner, {
    cascade: true,
    eager: true,
    orphanedRowAction: 'delete',
  })
  geometry: GeographicPointReferred[];
}
