// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, IsNull, Repository } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { TMF673_BASE_PATH } from '../common/constants/tmf.constants';
import { projectFields } from '../common/utils/tmf-resource.util';
import { applyBaseFilters } from '../common/utils/query-helper.util';
import { EventEmitterService } from '../event/event-emitter.service';
import { GeographicAddressEventType } from '../event/event-types';
import { GeographicAddress } from './entities/geographic-address.entity';
import { GeographicLocationRefOrValue } from '../geographic-address-validation/entities/geographic-location-ref-or-value.entity';
import { GeographicSubAddress2 } from './entities/geographic-sub-address2.entity';
import { CreateGeographicAddressDto, UpdateGeographicAddressDto, QueryGeographicAddressDto } from './dto';
import * as hooks from './geographic-address.hooks';

/** A normalised ref row that must be persisted before the aggregate referencing it. */
type PendingRef = { target: new () => any; entity: Record<string, any> };

/** Drops undefined/null so the response carries only what the resource actually has. */
function stripEmpty(obj: Record<string, any>): Record<string, any> {
  for (const key of Object.keys(obj)) {
    if (obj[key] === undefined || obj[key] === null) {
      delete obj[key];
    }
  }
  return obj;
}

@Injectable()
export class GeographicAddressService {
  private readonly logger = new Logger(GeographicAddressService.name);

  constructor(
    @InjectRepository(GeographicAddress)
    private readonly repository: Repository<GeographicAddress>,
    @InjectRepository(GeographicLocationRefOrValue)
    private readonly geographicLocationRefOrValueRepository: Repository<GeographicLocationRefOrValue>,
    @InjectRepository(GeographicSubAddress2)
    private readonly geographicSubAddress2Repository: Repository<GeographicSubAddress2>,
    private readonly dataSource: DataSource,
    private readonly eventEmitter: EventEmitterService,
  ) {}

  private get geographicAddressRepository(): Repository<GeographicAddress> {
    return this.repository;
  }

  async create(dto: CreateGeographicAddressDto): Promise<Record<string, any>> {
    const input = (await hooks.beforeCreate(dto as Record<string, any>)) ?? (dto as Record<string, any>);
    const pending: PendingRef[] = [];
    const entity = this.buildGeographicAddress(input, pending);
    if (!entity.atType) {
      entity.atType = 'GeographicAddress';
    }
    // A create must produce something the client can then READ.
    //
    // Where the spec lets a client choose the id, it may pick one belonging to a
    // soft-deleted row. save() then UPDATES that invisible row, and findEntity below -
    // which filters deletedAt IS NULL - cannot see it, so a POST answered
    //   404 "<Resource> <id> not found"
    // while quietly overwriting a row nobody can reach. From the API's point of view
    // that id was free: GET on it already returned 404. So the row is resurrected
    // rather than left buried.
    entity.deletedAt = null as unknown as Date;
    entity.deletedBy = undefined;
    entity.deletedReason = undefined;
    // normalised ref rows first, then the aggregate that points at them
    for (const ref of pending) {
      await this.dataSource.getRepository(ref.target).save(ref.entity);
    }
    await this.repository.save(entity);
    const saved = await this.findEntity(entity.id);
    const response = this.mapGeographicAddress(saved);
    this.logger.log(`created geographicAddress ${saved.id}`);
    return response;
  }

  async findAll(query: QueryGeographicAddressDto): Promise<{ data: Record<string, any>[]; total: number }> {
    // house filters available for this resource: name, q, sort
    const qb = this.repository.createQueryBuilder('e')
      .leftJoinAndSelect('e.geographicLocation', 'geographicLocation')
      .leftJoinAndSelect('e.geographicSubAddress', 'geographicSubAddress')
      .where('e.deletedAt IS NULL');

    applyBaseFilters(qb, query, 'e');
    if (query.id) {
      qb.andWhere('e.id = :id', { id: query.id });
    }

    const total = await qb.getCount();
    qb.skip(query.offset ?? 0).take(query.limit ?? 20);
    const rows = await qb.getMany();
    const data = rows.map((r) => this.mapGeographicAddress(r));
    return { data: query.fields ? projectFields(data, query.fields) : data, total };
  }

  async findEntity(id: string): Promise<GeographicAddress> {
    const entity = await this.repository.findOne({
      where: { id, deletedAt: IsNull() },
      relations: ['geographicLocation', 'geographicSubAddress'],
    });
    if (!entity) {
      throw new NotFoundException(`GeographicAddress ${id} not found`);
    }
    return entity;
  }

  async findOne(id: string, fields?: string): Promise<Record<string, any>> {
    const entity = await this.findEntity(id);
    const response = (await hooks.afterFindOne(this.mapGeographicAddress(entity), entity)) ?? this.mapGeographicAddress(entity);
    return fields ? projectFields([response], fields)[0] : response;
  }

  /* ── payload -> entity ── */
  private buildGeographicAddress(input: Record<string, any>, pending: PendingRef[]): GeographicAddress {
    const e = this.geographicAddressRepository.create();
    e.id = input?.id ?? uuidv4();
    e.city = input?.['city'];
    e.country = input?.['country'];
    e.locality = input?.['locality'];
    e.name = input?.['name'];
    e.postcode = input?.['postcode'];
    e.stateOrProvince = input?.['stateOrProvince'];
    e.streetName = input?.['streetName'];
    e.streetNr = input?.['streetNr'];
    e.streetNrLast = input?.['streetNrLast'];
    e.streetNrLastSuffix = input?.['streetNrLastSuffix'];
    e.streetNrSuffix = input?.['streetNrSuffix'];
    e.streetSuffix = input?.['streetSuffix'];
    e.streetType = input?.['streetType'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    e.geographicLocation = input?.geographicLocation ? this.buildGeographicLocationRefOrValue(input.geographicLocation, pending) : undefined;
    e.geographicSubAddress = (input?.geographicSubAddress ?? []).map((i: Record<string, any>, __i: number) => Object.assign(this.buildGeographicSubAddress2(i, pending, e), { sortOrder: __i }));
    return e;
  }

  private buildGeographicLocationRefOrValue(input: Record<string, any>, pending: PendingRef[]): GeographicLocationRefOrValue {
    const e = this.geographicLocationRefOrValueRepository.create();
    e.id = uuidv4();
    e.refId = input?.['id'];
    e.href = input?.['href'];
    e.name = input?.['name'];
    e.referredType = input?.['@referredType'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    pending.push({ target: GeographicLocationRefOrValue, entity: e });
    return e;
  }

  private buildGeographicSubAddress2(input: Record<string, any>, pending: PendingRef[], owner: GeographicAddress): GeographicSubAddress2 {
    const e = this.geographicSubAddress2Repository.create();
    e.id = uuidv4();
    e.owner = owner;
    e.refId = input?.['id'];
    e.buildingName = input?.['buildingName'];
    e.levelNumber = input?.['levelNumber'];
    e.levelType = input?.['levelType'];
    e.name = input?.['name'];
    e.privateStreetName = input?.['privateStreetName'];
    e.privateStreetNumber = input?.['privateStreetNumber'];
    e.subAddressType = input?.['subAddressType'];
    e.subUnitNumber = input?.['subUnitNumber'];
    e.subUnitType = input?.['subUnitType'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    return e;
  }

  /* ── entity -> API response (inverse of the nesting rule) ── */
  private mapGeographicAddress(e: GeographicAddress): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.id;
    out.city = e.city;
    out.country = e.country;
    out.locality = e.locality;
    out.name = e.name;
    out.postcode = e.postcode;
    out.stateOrProvince = e.stateOrProvince;
    out.streetName = e.streetName;
    out.streetNr = e.streetNr;
    out.streetNrLast = e.streetNrLast;
    out.streetNrLastSuffix = e.streetNrLastSuffix;
    out.streetNrSuffix = e.streetNrSuffix;
    out.streetSuffix = e.streetSuffix;
    out.streetType = e.streetType;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation ?? '';
    out['@baseType'] = e.atBaseType ?? '';
    out.href = `/${TMF673_BASE_PATH}/geographicAddress/${e.id}`;
    out.geographicLocation = e.geographicLocation ? this.mapGeographicLocationRefOrValue(e.geographicLocation) : undefined;
    out.geographicSubAddress = [...(e.geographicSubAddress ?? [])].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)).map((c) => this.mapGeographicSubAddress2(c, e.id));
    return stripEmpty(out);
  }

  private mapGeographicLocationRefOrValue(e: GeographicLocationRefOrValue): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.refId;
    out.href = e.href;
    out.name = e.name;
    out['@referredType'] = e.referredType;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    return stripEmpty(out);
  }

  private mapGeographicSubAddress2(e: GeographicSubAddress2, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.refId ?? e.id;
    out.buildingName = e.buildingName;
    out.levelNumber = e.levelNumber;
    out.levelType = e.levelType;
    out.name = e.name;
    out.privateStreetName = e.privateStreetName;
    out.privateStreetNumber = e.privateStreetNumber;
    out.subAddressType = e.subAddressType;
    out.subUnitNumber = e.subUnitNumber;
    out.subUnitType = e.subUnitType;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF673_BASE_PATH}/geographicAddress/${rootId}/geographicSubAddress/${e.refId ?? e.id}`;
    }
    return stripEmpty(out);
  }
}
