// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EventSubscription } from './entities/event-subscription.entity';
import { GeographicAddressSubscriptionController } from './geographic-address-subscription.controller';
import { SubscriptionService } from './subscription.service';

@Module({
  imports: [TypeOrmModule.forFeature([EventSubscription])],
  controllers: [GeographicAddressSubscriptionController],
  providers: [SubscriptionService],
})
export class SubscriptionModule {}
