// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * The seed lists are plain API payloads. They are allowed to be empty, but they
 * must stay arrays of objects - `seed.ts` spreads them straight into `create()`.
 */
import { eventLocalSeed } from '../src/tmf-event/event.seed.local';
import { topicLocalSeed } from '../src/topic/topic.seed.local';
import { hubLocalSeed } from '../src/hub/hub.seed.local';

const SEEDS: [string, Record<string, any>[]][] = [
  ['eventLocalSeed', eventLocalSeed],
  ['topicLocalSeed', topicLocalSeed],
  ['hubLocalSeed', hubLocalSeed],
];

describe.each(SEEDS)('%s seed rows', (_name, rows) => {
  it('are an array of payload objects', () => {
    expect(Array.isArray(rows)).toBe(true);
    for (const row of rows) {
      expect(typeof row).toBe('object');
      expect(row).not.toBeNull();
    }
  });
});
