// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// TMF673 API Place - GeographicAddress
export const TMF673_BASE_PATH = 'tmf-api/geographicAddressManagement/v4';
export const TMF673_EVENT_EXCHANGE = 'geographicAddress.events';
// TMF674 Geographic Site
export const TMF674_BASE_PATH = 'tmf-api/geographicSiteManagement/v4';
export const TMF674_EVENT_EXCHANGE = 'geographicSite.events';
// TMF675 API GeographicLocation
export const TMF675_BASE_PATH = 'tmf-api/geographicLocation/v1';
export const TMF675_EVENT_EXCHANGE = 'geographicLocation.events';
