// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, OneToMany, JoinColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { CharacteristicRelationship } from './characteristic-relationship.entity';
import { Event } from './event.entity';

/**
 * Describes a given characteristic of an object or entity through a name/value pair.
 */
@Entity('characteristic')
export class Characteristic {
  @PrimaryColumn({ type: 'varchar', length: 100 })
  id: string;

  /** The id the client gave this item. Unique within its parent only, so it is not the primary key; served back as `id`. */
  @Column({ type: 'varchar', length: 100, nullable: true })
  refId?: string;

  @Column({ type: 'int', nullable: true })
  sortOrder?: number;

  /** Name of the characteristic */
  @Column({ type: 'varchar', length: 255 })
  name: string;

  /** Data type of the value of the characteristic */
  @Column({ type: 'varchar', length: 100, nullable: true })
  valueType?: string;

  @Column({ type: 'jsonb', nullable: true })
  value?: Record<string, any>;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  @ManyToOne(() => Event, (parent) => parent.analyticCharacteristic, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'event_id' })
  owner: Event;

  @OneToMany(() => CharacteristicRelationship, (child) => child.owner, {
    cascade: true,
    eager: true,
    orphanedRowAction: 'delete',
  })
  characteristicRelationship: CharacteristicRelationship[];
}
