// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { Event } from './event.entity';

/**
 * Related Entity reference. A related party defines party or party role linked to a specific entity.
 */
@Entity('related_party')
export class RelatedParty {
  @PrimaryColumn({ type: 'varchar', length: 36 })
  id: string;

  /** Name of the related entity. */
  @Column({ type: 'varchar', length: 255, nullable: true })
  name?: string;

  /** Role played by the related party */
  @Column({ type: 'varchar', length: 50, nullable: true })
  role?: string;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  @ManyToOne(() => Event, (parent) => parent.relatedParty, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'event_id' })
  owner: Event;
}
