// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * GeographicLocation
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { GeographicLocationService } from '../../src/geographic-location/geographic-location.service';
import { GeographicLocationController } from '../../src/geographic-location/geographic-location.controller';
import { GeographicLocationEventType } from '../../src/event/event-types';
import { GeographicLocation } from '../../src/geographic-location/entities/geographic-location.entity';
import { GeographicPoint } from '../../src/geographic-location/entities/geographic-point.entity';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn(() => qb),
    take: jest.fn(() => qb),
    getCount: jest.fn(async () => rows.length),
    getMany: jest.fn(async () => rows),
  };
  return qb;
}

const HREF = '/tmf-api/geographicLocation/v1/geographicLocation/res-1';

/** The owner-bound collections this resource maps. */
const COLLECTIONS = ['geometry'] as const;

/** The path segment each collection's row mapper writes into its href. */
const HREF_SEGMENT: Record<string, string> = { geometry: 'geometry' };

/** The `@type` each collection's rows carry: their own entity class name. */
const ROW_AT_TYPE: Record<string, string> = { geometry: 'GeographicPoint' };

function row(collection: string, index: number): AnyRec {
  return {
    id: `${collection}-row-${index}`,
    refId: `${collection}-ref-${index}`,
    atType: ROW_AT_TYPE[collection],
    sortOrder: index,
  };
}

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    name: 'res-name',
    geometryType: 'res-geometryType',
    spatialRef: 'res-spatialRef',
    accuracy: 'res-accuracy',
    atType: 'GeographicLocation',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    geometry: [row('geometry', 0)],
    ...over,
  };
}

describe('GeographicLocation entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [GeographicLocation, GeographicPoint]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});
