// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * GeographicLocation
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { NotFoundException } from '@nestjs/common';
import { PATH_METADATA } from '@nestjs/common/constants';
import { Test } from '@nestjs/testing';
import { GeographicLocationService } from '../../src/geographic-location/geographic-location.service';
import { GeographicLocationController } from '../../src/geographic-location/geographic-location.controller';
import { GeographicLocation } from '../../src/geographic-location/entities/geographic-location.entity';
import { GeographicPoint } from '../../src/geographic-location/entities/geographic-point.entity';
import * as hooks from '../../src/geographic-location/geographic-location.hooks';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

/**
 * The double REMEMBERS its window and applies it, which a double returning
 * every row whatever was asked for cannot: findAll reads the total BEFORE it
 * narrows the query, so `total` is the unpaged count while `data` is one page.
 * With an unwindowed double the two are always equal and neither half of that
 * sentence is under test - counting after the window, or reporting
 * `data.length` as the total, both stay green.
 */
function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  let offset = 0;
  let limit: number | undefined;
  const windowed = () =>
    limit === undefined ? rows : rows.slice(offset, offset + limit);
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn((n: number) => {
      offset = n;
      return qb;
    }),
    take: jest.fn((n: number) => {
      limit = n;
      return qb;
    }),
    getCount: jest.fn(async () => windowed().length),
    getMany: jest.fn(async () => windowed()),
  };
  return qb;
}

const HREF = '/tmf-api/geographicLocation/v1/geographicLocation/res-1';

/** The route Nest registers from @Controller(`${BASE_PATH}/...`). */
const ROUTE_PATH = 'tmf-api/geographicLocation/v1/geographicLocation';

/** The id every delegation asserts on, and the scalar the write paths move. */
const ID = 'res-1';
const FIELD = 'name';
const LIST_QUERY = { limit: 5 };

/** The owner-bound collections this resource maps. */
const COLLECTIONS = ['geometry'] as const;

/** The path segment each collection's row mapper writes into its href. */
const HREF_SEGMENT: Record<string, string> = { geometry: 'geometry' };

/**
 * What an owned row's href is built on. NOT `HREF`: renderService hands a
 * child mapper the FLAT `resource.pathSegment`, while the root mapper gets
 * `nested.hrefSegment` under --nested-routes - so the two bases diverge for
 * a nested resource, and only here is that visible.
 */
const ROW_HREF_BASE = '/tmf-api/geographicLocation/v1/geographicLocation/res-1';

/** The `@type` each collection's rows carry: their own entity class name. */
const ROW_AT_TYPE: Record<string, string> = { geometry: 'GeographicPoint' };

function row(collection: string, index: number): AnyRec {
  return {
    id: `${collection}-row-${index}`,
    refId: `${collection}-ref-${index}`,
    atType: ROW_AT_TYPE[collection],
    sortOrder: index,
  };
}

/** The `@type` a create stamps on a payload that carries none. */
const AT_TYPE = 'GeographicLocation';
/** One the payload supplies instead, which must survive that default. */
const SUPPLIED_AT_TYPE = 'CustomGeographicLocation';

/** Each settable root scalar: the payload key it is read from -> its column. */
const SCALARS: Record<string, string> = {
  name: 'name',
  geometryType: 'geometryType',
  spatialRef: 'spatialRef',
  accuracy: 'accuracy',
  '@schemaLocation': 'atSchemaLocation',
  '@baseType': 'atBaseType',
};

function scalarPayload(): AnyRec {
  const out: AnyRec = {};
  for (const w of Object.keys(SCALARS)) out[w] = `res-${SCALARS[w]}`;
  return out;
}

/** What each collection's rows report as their id on the way out. */
const ROW_ID: Record<string, string> = { geometry: 'geometry-ref-0' };

/** Owned collections, whose rows fall back to their own key with no refId. */
const REF_ID_FALLBACK = ['geometry'] as const;

/**
 * A sort key and a selected attribute. They are named differently on
 * purpose: applyBaseFilters turns `sort` straight into `e.<key>` SQL, so
 * that one is the COLUMN name, while projectFields matches `fields`
 * against the keys of the MAPPED row, which are the response keys.
 */
const SORT_KEY = 'name';
const SELECTED = 'name';
/** One the client did not ask for, which selection must then drop. */
const NOT_SELECTED = 'geometryType';

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    name: 'res-name',
    geometryType: 'res-geometryType',
    spatialRef: 'res-spatialRef',
    accuracy: 'res-accuracy',
    atType: 'GeographicLocation',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    geometry: [row('geometry', 0)],
    ...over,
  };
}

describe('GeographicLocation entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [GeographicLocation, GeographicPoint]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});

describe('GeographicLocationService', () => {
  let repo: AnyRec;
  let refSave: jest.Mock;
  let dataSource: AnyRec;
  let eventEmitter: AnyRec;
  let service: GeographicLocationService;

  beforeEach(() => {
    repo = makeRepo();
    refSave = jest.fn(async (e: AnyRec) => e);
    dataSource = {
      getRepository: jest.fn(() => ({
        create: jest.fn((v: AnyRec) => v),
        findOne: jest.fn(async () => null),
        save: refSave,
      })),
    };
    eventEmitter = { emitEvent: jest.fn() };
    service = new GeographicLocationService(
      repo as never,
      makeRepo() as never,
      dataSource as never,
      eventEmitter as never,
    );
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('create', () => {
    beforeEach(() => {
      // beforeCreate is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(undefined);
    });

    it('persists every scalar and answers with the stored resource plus its href', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.create(scalarPayload() as never);

      const persisted = repo.save.mock.calls[0][0];
      for (const w of Object.keys(SCALARS)) {
        expect(persisted[SCALARS[w]]).toBe(`res-${SCALARS[w]}`);
      }
      expect(res.id).toBe(ID);
      expect(res.href).toBe(HREF);
    });

    it('keeps a client-supplied id and defaults @type to GeographicLocation', async () => {
      repo.findOne.mockResolvedValue(entity({ id: 'chosen' }));
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('chosen');
      expect(persisted.atType).toBe(AT_TYPE);
    });

    it('generates a uuid when no id is supplied and keeps a supplied @type', async () => {
      repo.findOne.mockResolvedValue(entity());
      await service.create({ '@type': SUPPLIED_AT_TYPE } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toMatch(/^[0-9a-f-]{36}$/);
      expect(persisted.atType).toBe(SUPPLIED_AT_TYPE);
    });

    it('clears the soft-delete stamps so a reused id is resurrected', async () => {
      // A client may reuse the id of a row that was soft-deleted. Left stamped,
      // save() updates a row findEntity cannot see, and the POST answers 404
      // on the very id it just wrote.
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.deletedAt).toBeNull();
      expect(persisted.deletedBy).toBeUndefined();
      expect(persisted.deletedReason).toBeUndefined();
    });

    it('numbers each collection row by its position in the payload', async () => {
      // a row carrying no sortOrder sorts at 0 on the way out, so the
      // first row written has to carry 0 for both paths to agree
      repo.findOne.mockResolvedValue(entity());
      const payload: AnyRec = {};
      for (const c of COLLECTIONS) {
        payload[c] = [{ id: `${c}-a` }, { id: `${c}-b` }];
      }
      await service.create(payload as never);

      const persisted = repo.save.mock.calls[0][0];
      for (const c of COLLECTIONS) {
        const rows = persisted[c] as AnyRec[];
        expect(rows.map((r) => r.sortOrder)).toEqual([0, 1]);
        expect(rows.map((r) => r.refId)).toEqual([`${c}-a`, `${c}-b`]);
      }
    });

    it('leaves every collection empty when the payload omits them', async () => {
      repo.findOne.mockResolvedValue(entity());
      await service.create({} as never);
      const persisted = repo.save.mock.calls[0][0];
      for (const c of COLLECTIONS) expect(persisted[c]).toEqual([]);
      expect(refSave).not.toHaveBeenCalled();
    });

    it('builds from the payload the beforeCreate hook returns, not the dto', async () => {
      // beforeCreate lives in a file tmfgen does not manage. What it returns is
      // its owner's business, so it is SPIED here rather than asserted on: what
      // is under test is that create builds from the value it got back.
      const HOOK_PAYLOAD: AnyRec = { id: 'from-hook', name: 'res-from-hook' };
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(HOOK_PAYLOAD);
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'ignored' } as never);

      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('from-hook');
      expect(persisted.name).toBe('res-from-hook');
    });
  });

  describe('findAll', () => {
    it('maps the page it asked for and reports the unpaged total', async () => {
      const rows = [entity(), entity({ id: 'res-2' }), entity({ id: 'res-3' })];
      repo.createQueryBuilder.mockReturnValue(makeQueryBuilder(rows));
      const { data, total } = await service.findAll({ limit: 2 } as never);
      // the count is taken BEFORE the window narrows the query
      expect(total).toBe(3);
      expect(data.map((d) => d.id)).toEqual([ID, 'res-2']);
      for (const w of Object.keys(SCALARS)) {
        expect(data[0][w]).toBe(`res-${SCALARS[w]}`);
      }
    });

    it('excludes soft-deleted rows and narrows by id', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({ id: ID } as never);
      expect(qb.where).toHaveBeenCalledWith('e.deletedAt IS NULL');
      expect(qb.andWhere).toHaveBeenCalledWith('e.id = :id', { id: ID });
    });

    it('pages with the supplied window', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      // deliberately not the defaults asserted below
      await service.findAll({ offset: 40, limit: 25 } as never);
      expect(qb.skip).toHaveBeenCalledWith(40);
      expect(qb.take).toHaveBeenCalledWith(25);
    });

    it('defaults to 20 rows from offset 0', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({} as never);
      expect(qb.skip).toHaveBeenCalledWith(0);
      expect(qb.take).toHaveBeenCalledWith(20);
    });

    it('orders by the requested sort key', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({ sort: `-${SORT_KEY}` } as never);
      expect(qb.addOrderBy).toHaveBeenCalledWith(`e.${SORT_KEY}`, 'DESC');
    });

    it('projects only the requested fields, keeping id and href', async () => {
      repo.createQueryBuilder.mockReturnValue(makeQueryBuilder([entity()]));
      const { data } = await service.findAll({ fields: SELECTED } as never);
      expect(data[0][SELECTED]).toBe(`res-${SCALARS[SELECTED]}`);
      expect(data[0].id).toBe(ID);
      expect(data[0].href).toBe(HREF);
      expect(Object.keys(data[0])).not.toContain('@type');
      expect(Object.keys(data[0])).not.toContain(NOT_SELECTED);
    });
  });

  describe('findEntity / findOne', () => {
    beforeEach(() => {
      // afterFindOne is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'afterFindOne').mockResolvedValue(undefined);
    });

    it('throws NotFoundException when the row is missing or soft-deleted', async () => {
      repo.findOne.mockResolvedValue(null);
      await expect(service.findEntity('nope')).rejects.toBeInstanceOf(
        NotFoundException,
      );
      await expect(service.findOne('nope')).rejects.toBeInstanceOf(
        NotFoundException,
      );
    });

    it('maps every scalar and the resource href', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID);
      for (const w of Object.keys(SCALARS)) {
        expect(res[w]).toBe(`res-${SCALARS[w]}`);
      }
      expect(res.href).toBe(HREF);
    });

    it('maps every collection row, with the href its own mapper writes', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) {
        expect(res[c]).toHaveLength(1);
        expect(res[c][0].id).toBe(ROW_ID[c]);
        if (HREF_SEGMENT[c]) {
          expect(res[c][0].href).toBe(
            `${ROW_HREF_BASE}/${HREF_SEGMENT[c]}/${ROW_ID[c]}`,
          );
        }
      }
    });

    it('falls back to the row key when an owned row carries no refId', async () => {
      const over: AnyRec = {};
      for (const c of REF_ID_FALLBACK) over[c] = [{ id: `${c}-only` }];
      repo.findOne.mockResolvedValue(entity(over));
      const res = await service.findOne(ID);
      for (const c of REF_ID_FALLBACK) expect(res[c][0].id).toBe(`${c}-only`);
    });

    it('returns empty collections when the row carries none', async () => {
      repo.findOne.mockResolvedValue({ id: ID, atType: AT_TYPE });
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) expect(res[c]).toEqual([]);
    });

    it('orders each collection by sortOrder rather than by insertion', async () => {
      const over: AnyRec = {};
      for (const c of Object.keys(ROW_ID)) {
        over[c] = [
          { id: `${c}-b`, refId: `${c}-b`, sortOrder: 2 },
          { id: `${c}-a`, refId: `${c}-a`, sortOrder: 1 },
        ];
      }
      repo.findOne.mockResolvedValue(entity(over));
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) {
        expect(res[c].map((r: AnyRec) => r.id)).toEqual([`${c}-a`, `${c}-b`]);
      }
    });

    it('treats a row with no sortOrder as 0, so it sorts first', async () => {
      const over: AnyRec = {};
      for (const c of Object.keys(ROW_ID)) {
        over[c] = [
          { id: `${c}-b`, refId: `${c}-b`, sortOrder: 1 },
          { id: `${c}-a`, refId: `${c}-a` },
        ];
      }
      repo.findOne.mockResolvedValue(entity(over));
      const res = await service.findOne(ID);
      for (const c of Object.keys(ROW_ID)) {
        expect(res[c].map((r: AnyRec) => r.id)).toEqual([`${c}-a`, `${c}-b`]);
      }
    });

    it('defaults @schemaLocation and @baseType to ""', async () => {
      repo.findOne.mockResolvedValue({ id: ID, atType: AT_TYPE });
      const res = await service.findOne(ID);
      expect(res['@schemaLocation']).toBe('');
      expect(res['@baseType']).toBe('');
    });

    it('projects the requested fields on a single read', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID, SELECTED);
      expect(res[SELECTED]).toBe(`res-${SCALARS[SELECTED]}`);
      expect(Object.keys(res)).not.toContain(NOT_SELECTED);
    });

    it('answers with whatever the afterFindOne hook gives back', async () => {
      // afterFindOne lives in a file tmfgen does not manage. What it returns is
      // its owner's business, so it is SPIED here rather than asserted on: what
      // is under test is that findOne hands it the mapped response and answers
      // with the value it got back.
      const DECORATED: AnyRec = { id: 'from-hook' };
      jest.spyOn(hooks, 'afterFindOne').mockResolvedValue(DECORATED);
      const stored = entity();
      repo.findOne.mockResolvedValue(stored);
      const res = await service.findOne(ID);
      expect(hooks.afterFindOne).toHaveBeenCalledWith(
        expect.objectContaining({ href: HREF }),
        stored,
      );
      expect(res).toBe(DECORATED);
    });
  });
});

describe('GeographicLocationController', () => {
  let svc: AnyRec;
  let ctrl: GeographicLocationController;

  beforeEach(() => {
    svc = {
      findAll: jest.fn(async () => ({ data: [], total: 0 })),
      findOne: jest.fn(async () => ({ id: ID })),
    };
    ctrl = new GeographicLocationController(svc as never);
  });

  it('passes the query through to findAll', async () => {
    await ctrl.findAll(LIST_QUERY as never);
    expect(svc.findAll).toHaveBeenCalledWith(LIST_QUERY);
  });

  it('forwards the id and the field selection to findOne', async () => {
    await ctrl.findOne(ID, FIELD);
    expect(svc.findOne).toHaveBeenCalledWith(ID, FIELD);
  });

  it('is constructible by Nest with its route metadata intact', async () => {
    // A concrete controller carrying no decorator of its own emits no
    // constructor `design:paramtypes`, so Nest builds it with zero arguments
    // and every route 500s; losing only @Controller() keeps injection working
    // but silently unmounts the routes. Both are checked separately.
    const moduleRef = await Test.createTestingModule({
      controllers: [GeographicLocationController],
      providers: [{ provide: GeographicLocationService, useValue: svc }],
    }).compile();

    const resolved = moduleRef.get(
      GeographicLocationController,
    ) as unknown as AnyRec;
    expect(resolved.service).toBe(svc);
    const paramtypes = Reflect.getMetadata(
      'design:paramtypes',
      GeographicLocationController,
    );
    expect(paramtypes).toEqual([GeographicLocationService]);
    const routePath = Reflect.getMetadata(
      PATH_METADATA,
      GeographicLocationController,
    );
    expect(routePath).toBe(ROUTE_PATH);
  });
});
