// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.
// Halaman list employees (view: list). Assembly runtime: useCrudPage + StandardList + api defs.
// Komponen UI = barrel src/gen/ui.tsx (adapter.resolve) - tanpa import MUI langsung.
// Titik sambung form/detail: emit/form.mjs dan emit/detail.mjs (todo berikutnya).
// modal add/edit di-buka dari sini via emit/form.mjs (state addOpen/editId).

import { ComponentProps, ReactElement, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Eye, Pencil, Trash2, Plus } from 'lucide-react';
import type { ListParams, Severity } from '../../gen/useCrudPage';
import { useCrudPage } from '../../gen/useCrudPage';
import { resolveTemplate } from '../../gen/QueryContext';
import { StandardList } from '../../gen/StandardList';
import { createEmployees, deleteEmployees, listEmployees, updateEmployees } from '../../gen/api/employees';
import type { Employees } from '../../gen/api/employees';
import { UiAlert, UiBox, UiButton, UiChip, UiIconButton, UiSnackbar, UiTextField } from '../../gen/ui';
import { UiSelect } from '../../gen/uiwrappers';
import AddForm from './AddForm';
import EditForm from './EditForm';

export default function List(): ReactElement {
  const navigate = useNavigate();
  const [snack, setSnack] = useState<{ message: string; severity: Severity } | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  const [editId, setEditId] = useState<string | number | null>(null);

  const notify = (message: string, severity: Severity): void => {
    setSnack({ message, severity });
  };

  // modal add di-assembly emit/form.mjs - dikontrol state addOpen.
  const openAdd = (): void => {
    setAddOpen(true);
  };

  // modal edit di-assembly emit/form.mjs - dikontrol state editId.
  const openEdit = (id: string | number): void => {
    setEditId(id);
  };

  // detail page di-assembly emit/detail.mjs (todo berikutnya) - route sudah nyata.
  const openDetail = (id: string | number): void => {
    navigate('/employees/:id'.replace(':id', String(id)));
  };

  const crud = useCrudPage<Employees>(
    {
      list: async (params: ListParams) => {
  let q: string | undefined = params.q;
  if (q !== undefined && q !== '') {
    q = resolveTemplate('{{search.q}}', { search: { q } });
  }
        const result = await listEmployees({
          offset: Number(resolveTemplate('{{pagination.offset}}', { pagination: { offset: params.offset ?? 0 } })),
          limit: Number(resolveTemplate('{{pagination.limit}}', { pagination: { limit: params.limit ?? 10 } })),
          q,
        });
        return { rows: result.rows, total: result.total };
      },
      create: (payload) => createEmployees(payload),
      update: (id, payload) => updateEmployees(id, payload),
      remove: (id) => deleteEmployees(id),
      getRowId: (row) => row.id ?? row.href ?? '',
    },
    {
      scheme: 'offset-limit',
      searchDebounceMs: 300,
      defaultPageSize: 10,
      notify,
    },
  );

  const confirmDelete = (id: string | number): void => {
    if (window.confirm('Hapus data ini? Klik OK untuk melanjutkan.')) {
      void crud.remove(id);
    }
  };

  const columns: ComponentProps<typeof StandardList>['columns'] = [
  {
    field: 'name',
    headerName: 'Nama',
    sortable: true,
    filterable: false,
  },
  {
    field: 'email',
    headerName: 'Email',
    sortable: false,
    filterable: false,
  },
  {
    field: 'department',
    headerName: 'Departemen',
    sortable: false,
    filterable: false,
  renderCell: (params) => <UiChip size="small" label={String(params.value ?? '')} />,
  },
  {
    field: 'role',
    headerName: 'Jabatan',
    sortable: false,
    filterable: false,
  },
  {
    field: 'hireDate',
    headerName: 'Tanggal Masuk',
    sortable: false,
    filterable: false,
  valueFormatter: (value) => (value == null ? '' : new Date(String(value)).toLocaleString()),
  },
  ];

  return (
    <UiBox sx={{ display: 'flex', flexDirection: 'column', gap: 1, height: '100%', minHeight: '60vh' }}>
      <StandardList
        columns={columns}
        rows={crud.rows}
        rowCount={crud.rowCount}
        pageModel={crud.pagination}
        sortModel={crud.sort}
        filterModel={crud.filter}
        onPaginationModelChange={crud.setPagination}
        onSortModelChange={crud.setSort}
        onFilterModelChange={crud.setFilter}
        loading={crud.loading}
        getRowId={(row) => row.id ?? row.href ?? ''}
        pageSizeOptions={[10, 25, 50]}
        emptyText={'Belum ada karyawan'}
        emptyAction={{ label: 'Tambah Karyawan', onClick: () => setAddOpen(true) }}
        searchField={
          <>
            <UiTextField size="small" placeholder={'Cari nama atau email...'} value={crud.searchQ} onChange={(e) => crud.setSearchQ(e.target.value)} sx={{ width: 260 }} />
            <UiSelect label={'Departemen'} placeholder={'Semua Departemen'} value={crud.extra['department'] ?? ''} options={[{ value: 'sales', label: 'Penjualan' }, { value: 'engineering', label: 'Teknik' }, { value: 'finance', label: 'Keuangan' }, { value: 'operations', label: 'Operasional' }, { value: 'hr', label: 'SDM' }]} onChange={(v) => { crud.setExtra((x) => ({ ...x, 'department': v || undefined })); crud.setPagination((p) => ({ ...p, page: 0 })); }} />
          </>
        }
        toolbarActions={
          <UiButton tone='primary' startIcon={<Plus size={16} />} onClick={openAdd}>{'Tambah Karyawan'}</UiButton>
        }
        rowActions={(row) => (
          <UiBox sx={{ display: 'flex', gap: 0.5 }}>
            <UiIconButton size="small" title={'Detail'} aria-label={'Detail'} onClick={() => openDetail(row.id as string)}><Eye size={16} /></UiIconButton>
            <UiIconButton size="small" title={'Edit'} aria-label={'Edit'} onClick={() => openEdit(row.id as string)}><Pencil size={16} /></UiIconButton>
            <UiIconButton size="small" title={'Hapus'} aria-label={'Hapus'} onClick={() => confirmDelete(row.id as string)}><Trash2 size={16} /></UiIconButton>
          </UiBox>
        )
        }
      />
      <UiSnackbar
        open={snack !== null}
        autoHideDuration={4000}
        onClose={() => setSnack(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
      >
        <UiAlert severity={snack?.severity ?? 'info'} onClose={() => setSnack(null)} variant="filled">
          {snack?.message}
        </UiAlert>
      </UiSnackbar>
      <AddForm open={addOpen} onClose={() => setAddOpen(false)} onSaved={() => { void crud.reload(); notify('Data berhasil dibuat', 'success'); }} />
      <EditForm open={editId !== null} id={editId ?? 0} onClose={() => setEditId(null)} onSaved={() => { void crud.reload(); notify('Data berhasil diperbarui', 'success'); }} />
    </UiBox>
  );
}
