// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// payload shape from GeographicLocation (no variant schema in spec)
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsDefined, IsOptional, IsString, IsArray, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

class GeometryDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  /** x coordinate (usually latitude) */
  @ApiProperty()
  @IsDefined()
  @IsString()
  x: string;

  /** y coordinate (usually longitude) */
  @ApiProperty()
  @IsDefined()
  @IsString()
  y: string;

  /** z coordinate (usually elevation) */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  z?: string;
}

export class CreateGeographicLocationDto {
  /** Name of the geo location */
  @ApiProperty()
  @IsDefined()
  @IsString()
  name: string;

  /** Type of the geographic location - one of: point, line, graph, ring polygon */
  @ApiProperty()
  @IsDefined()
  @IsString()
  geometryType: string;

  /** Geocoding referential */
  @ApiProperty()
  @IsDefined()
  @IsString()
  spatialRef: string;

  /** Accuracy of the coordinate specified */
  @ApiProperty()
  @IsDefined()
  @IsString()
  accuracy: string;

  @ApiPropertyOptional({ type: [GeometryDto] })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => GeometryDto)
  geometry?: GeometryDto[];

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@type'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@baseType'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@schemaLocation'?: string;
}
