// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, IsNull, Repository } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { TMF675_BASE_PATH } from '../common/constants/tmf.constants';
import { projectFields } from '../common/utils/tmf-resource.util';
import { applyBaseFilters } from '../common/utils/query-helper.util';
import { EventEmitterService } from '../event/event-emitter.service';
import { GeographicLocationEventType } from '../event/event-types';
import { RetrieveLocationRelation } from './entities/retrieve-location-relation.entity';
import { GeographicLocationRef } from './entities/geographic-location-ref.entity';
import { GeographicPointReferred } from './entities/geographic-point-referred.entity';
import { RetrieveLocationRelationIntersection } from './entities/retrieve-location-relation-intersection.entity';
import { CreateRetrieveLocationRelationDto, UpdateRetrieveLocationRelationDto, QueryRetrieveLocationRelationDto } from './dto';
import * as hooks from './retrieve-location-relation.hooks';

/** A normalised ref row that must be persisted before the aggregate referencing it. */
type PendingRef = { target: new () => any; entity: Record<string, any> };

/** Drops undefined/null so the response carries only what the resource actually has. */
function stripEmpty(obj: Record<string, any>): Record<string, any> {
  for (const key of Object.keys(obj)) {
    if (obj[key] === undefined || obj[key] === null) {
      delete obj[key];
    }
  }
  return obj;
}

@Injectable()
export class RetrieveLocationRelationService {
  private readonly logger = new Logger(RetrieveLocationRelationService.name);

  constructor(
    @InjectRepository(RetrieveLocationRelation)
    private readonly repository: Repository<RetrieveLocationRelation>,
    @InjectRepository(GeographicLocationRef)
    private readonly geographicLocationRefRepository: Repository<GeographicLocationRef>,
    @InjectRepository(GeographicPointReferred)
    private readonly geographicPointReferredRepository: Repository<GeographicPointReferred>,
    @InjectRepository(RetrieveLocationRelationIntersection)
    private readonly retrieveLocationRelationIntersectionRepository: Repository<RetrieveLocationRelationIntersection>,
    private readonly dataSource: DataSource,
    private readonly eventEmitter: EventEmitterService,
  ) {}

  private get retrieveLocationRelationRepository(): Repository<RetrieveLocationRelation> {
    return this.repository;
  }

  async create(dto: CreateRetrieveLocationRelationDto): Promise<Record<string, any>> {
    const input = (await hooks.beforeCreate(dto as Record<string, any>)) ?? (dto as Record<string, any>);
    const pending: PendingRef[] = [];
    const entity = this.buildRetrieveLocationRelation(input, pending);
    if (!entity.atType) {
      entity.atType = 'RetrieveLocationRelation';
    }
    // normalised ref rows first, then the aggregate that points at them
    for (const ref of pending) {
      await this.dataSource.getRepository(ref.target).save(ref.entity);
    }
    await this.repository.save(entity);
    const saved = await this.findEntity(entity.id);
    const response = this.mapRetrieveLocationRelation(saved);
    this.logger.log(`created retrieveLocationRelation ${saved.id}`);
    return response;
  }

  async findAll(query: QueryRetrieveLocationRelationDto): Promise<{ data: Record<string, any>[]; total: number }> {
    // house filters available for this resource: sort
    const qb = this.repository.createQueryBuilder('e')
      .leftJoinAndSelect('e.geographicLocation', 'geographicLocation')
      .leftJoinAndSelect('e.intersection', 'intersection')
      .leftJoinAndSelect('intersection.geometry', 'intersectionGeometry')
      .where('e.deletedAt IS NULL');

    applyBaseFilters(qb, query, 'e');
    if (query.id) {
      qb.andWhere('e.id = :id', { id: query.id });
    }

    const total = await qb.getCount();
    qb.skip(query.offset ?? 0).take(query.limit ?? 20);
    const rows = await qb.getMany();
    const data = rows.map((r) => this.mapRetrieveLocationRelation(r));
    return { data: query.fields ? projectFields(data, query.fields) : data, total };
  }

  async findEntity(id: string): Promise<RetrieveLocationRelation> {
    const entity = await this.repository.findOne({
      where: { id, deletedAt: IsNull() },
      relations: ['geographicLocation', 'intersection', 'intersection.geometry'],
    });
    if (!entity) {
      throw new NotFoundException(`RetrieveLocationRelation ${id} not found`);
    }
    return entity;
  }

  async findOne(id: string, fields?: string): Promise<Record<string, any>> {
    const entity = await this.findEntity(id);
    const response = (await hooks.afterFindOne(this.mapRetrieveLocationRelation(entity), entity)) ?? this.mapRetrieveLocationRelation(entity);
    return fields ? projectFields([response], fields)[0] : response;
  }

  /* ── payload -> entity ── */
  private buildRetrieveLocationRelation(input: Record<string, any>, pending: PendingRef[]): RetrieveLocationRelation {
    const e = this.retrieveLocationRelationRepository.create();
    e.id = input?.id ?? uuidv4();
    e.status = input?.['status'];
    e.distance = input?.['distance'];
    e.time = input?.['time'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    e.geographicLocation = (input?.geographicLocation ?? []).map((i: Record<string, any>) => this.buildGeographicLocationRef(i, pending, e));
    e.intersection = (input?.intersection ?? []).map((i: Record<string, any>) => this.buildRetrieveLocationRelationIntersection(i, pending, e));
    return e;
  }

  private buildGeographicLocationRef(input: Record<string, any>, pending: PendingRef[], owner: RetrieveLocationRelation): GeographicLocationRef {
    const e = this.geographicLocationRefRepository.create();
    e.id = input?.id ?? uuidv4();
    e.owner = owner;
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    return e;
  }

  private buildGeographicPointReferred(input: Record<string, any>, pending: PendingRef[], owner: RetrieveLocationRelationIntersection): GeographicPointReferred {
    const e = this.geographicPointReferredRepository.create();
    e.id = input?.id ?? uuidv4();
    e.owner = owner;
    e.x = input?.['x'];
    e.y = input?.['y'];
    e.z = input?.['z'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    return e;
  }

  private buildRetrieveLocationRelationIntersection(input: Record<string, any>, pending: PendingRef[], owner: RetrieveLocationRelation): RetrieveLocationRelationIntersection {
    const e = this.retrieveLocationRelationIntersectionRepository.create();
    e.id = input?.id ?? uuidv4();
    e.owner = owner;
    e.name = input?.['name'];
    e.geometryType = input?.['geometryType'];
    e.spatialRef = input?.['spatialRef'];
    e.accuracy = input?.['accuracy'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    e.geometry = (input?.geometry ?? []).map((i: Record<string, any>) => this.buildGeographicPointReferred(i, pending, e));
    return e;
  }

  /* ── entity -> API response (inverse of the nesting rule) ── */
  private mapRetrieveLocationRelation(e: RetrieveLocationRelation): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.id;
    out.status = e.status;
    out.distance = e.distance;
    out.time = e.time;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    out.href = `/${TMF675_BASE_PATH}/retrieveLocationRelation/${e.id}`;
    out.geographicLocation = (e.geographicLocation ?? []).map((c) => this.mapGeographicLocationRef(c, e.id));
    out.intersection = (e.intersection ?? []).map((c) => this.mapRetrieveLocationRelationIntersection(c, e.id));
    return stripEmpty(out);
  }

  private mapGeographicLocationRef(e: GeographicLocationRef, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.id;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF675_BASE_PATH}/retrieveLocationRelation/${rootId}/geographicLocation/${e.id}`;
    }
    return stripEmpty(out);
  }

  private mapGeographicPointReferred(e: GeographicPointReferred, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.id;
    out.x = e.x;
    out.y = e.y;
    out.z = e.z;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF675_BASE_PATH}/retrieveLocationRelation/${rootId}/geometry/${e.id}`;
    }
    return stripEmpty(out);
  }

  private mapRetrieveLocationRelationIntersection(e: RetrieveLocationRelationIntersection, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.id;
    out.name = e.name;
    out.geometryType = e.geometryType;
    out.spatialRef = e.spatialRef;
    out.accuracy = e.accuracy;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF675_BASE_PATH}/retrieveLocationRelation/${rootId}/intersection/${e.id}`;
    }
    out.geometry = (e.geometry ?? []).map((c) => this.mapGeographicPointReferred(c, rootId));
    return stripEmpty(out);
  }
}
