// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EventModule } from '../event/event.module';
import { RetrieveLocationRelationController } from './retrieve-location-relation.controller';
import { RetrieveLocationRelationService } from './retrieve-location-relation.service';
import { RetrieveLocationRelation } from './entities/retrieve-location-relation.entity';
import { GeographicLocationRef } from './entities/geographic-location-ref.entity';
import { GeographicPointReferred } from './entities/geographic-point-referred.entity';
import { RetrieveLocationRelationIntersection } from './entities/retrieve-location-relation-intersection.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      RetrieveLocationRelation,
      GeographicLocationRef,
      GeographicPointReferred,
      RetrieveLocationRelationIntersection,
    ]),
    EventModule,
  ],
  controllers: [RetrieveLocationRelationController],
  providers: [RetrieveLocationRelationService],
  exports: [RetrieveLocationRelationService],
})
export class RetrieveLocationRelationModule {}
