// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/** TMF736 - event names come from the spec's /listener/* paths. */
export enum RevenueSharingAlgorithmEventType {
  PARTY_REV_SHARING_ALGORITHM_ATTRIBUTE_VALUE_CHANGE = 'partyRevSharingAlgorithmAttributeValueChangeEvent',
  PARTY_REV_SHARING_ALGORITHM_CREATE = 'partyRevSharingAlgorithmCreateEvent',
  PARTY_REV_SHARING_ALGORITHM_DELETE = 'partyRevSharingAlgorithmDeleteEvent',
  PARTY_REV_SHARING_ALGORITHM_STATE_CHANGE = 'partyRevSharingAlgorithmStateChangeEvent',
}
