// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * The seed lists are plain API payloads. They are allowed to be empty, but they
 * must stay arrays of objects - `seed.ts` spreads them straight into `create()`.
 */
import { geographicLocationLocalSeed } from '../src/geographic-location/geographic-location.seed.local';
import { retrieveGeographicLocationLocalSeed } from '../src/retrieve-geographic-location/retrieve-geographic-location.seed.local';
import { retrieveLocationRelationLocalSeed } from '../src/retrieve-location-relation/retrieve-location-relation.seed.local';

const SEEDS: [string, Record<string, any>[]][] = [
  ['geographicLocationLocalSeed', geographicLocationLocalSeed],
  ['retrieveGeographicLocationLocalSeed', retrieveGeographicLocationLocalSeed],
  ['retrieveLocationRelationLocalSeed', retrieveLocationRelationLocalSeed],
];

describe.each(SEEDS)('%s seed rows', (_name, rows) => {
  it('are an array of payload objects', () => {
    expect(Array.isArray(rows)).toBe(true);
    for (const row of rows) {
      expect(typeof row).toBe('object');
      expect(row).not.toBeNull();
    }
  });
});
