// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * `seed.ts` runs `main()` at import time, so each case re-imports the module with
 * the process argv and seed rows it needs. NestFactory and the app module are
 * mocked: seeding is exercised end to end without a database.
 *
 * This service seeds 7 resource(s), each resolved by class token.
 */
type AnyRec = Record<string, any>;

// Each case re-imports the module graph and waits for main()'s fire-and-forget
// tail. The budget is generous because several suites share one machine:
// at 30s this timed out under load while passing in isolation.
jest.setTimeout(120000);

const createApplicationContext = jest.fn();

jest.mock('@nestjs/core', () => ({
  NestFactory: {
    createApplicationContext: (...a: unknown[]) =>
      createApplicationContext(...a),
  },
}));
jest.mock('../src/app.module', () => ({ AppModule: class AppModule {} }));

let rows0_1: AnyRec[] = [];
let rows1_1: AnyRec[] = [];
let rows2_1: AnyRec[] = [];
let rows3_1: AnyRec[] = [];
let rows4_1: AnyRec[] = [];
let rows5_1: AnyRec[] = [];
let rows6_1: AnyRec[] = [];

jest.mock('../src/geographic-address/geographic-address.seed.local', () => ({
  get geographicAddressLocalSeed() {
    return rows0_1;
  },
}));

jest.mock(
  '../src/geographic-address-validation/geographic-address-validation.seed.local',
  () => ({
    get geographicAddressValidationLocalSeed() {
      return rows1_1;
    },
  }),
);

jest.mock(
  '../src/geographic-sub-address/geographic-sub-address.seed.local',
  () => ({
    get geographicSubAddressLocalSeed() {
      return rows2_1;
    },
  }),
);

jest.mock('../src/geographic-site/geographic-site.seed.local', () => ({
  get geographicSiteLocalSeed() {
    return rows3_1;
  },
}));

jest.mock('../src/geographic-location/geographic-location.seed.local', () => ({
  get geographicLocationLocalSeed() {
    return rows4_1;
  },
}));

jest.mock(
  '../src/retrieve-geographic-location/retrieve-geographic-location.seed.local',
  () => ({
    get retrieveGeographicLocationLocalSeed() {
      return rows5_1;
    },
  }),
);

jest.mock(
  '../src/retrieve-location-relation/retrieve-location-relation.seed.local',
  () => ({
    get retrieveLocationRelationLocalSeed() {
      return rows6_1;
    },
  }),
);

async function runSeed(argv: string[], services: AnyRec[]) {
  // The seed resolves each service by its class token, and seedResource calls
  // app.get() lazily per closure - so route by token identity, not call order.
  // The tokens must come from the same module registry seed.ts will use, hence
  // the imports live inside the isolated scope below.
  const byToken = new Map<unknown, AnyRec>();
  const app = {
    get: jest.fn((token: unknown) => byToken.get(token)),
    close: jest.fn(async () => undefined),
  };
  createApplicationContext.mockResolvedValue(app);
  const argvBefore = process.argv;
  process.argv = ['node', 'seed', ...argv];
  jest.resetModules();
  await jest.isolateModulesAsync(async () => {
    const { GeographicAddressService } =
      await import('../src/geographic-address/geographic-address.service');
    const { GeographicAddressValidationService } =
      await import('../src/geographic-address-validation/geographic-address-validation.service');
    const { GeographicSubAddressService } =
      await import('../src/geographic-sub-address/geographic-sub-address.service');
    const { GeographicSiteService } =
      await import('../src/geographic-site/geographic-site.service');
    const { GeographicLocationService } =
      await import('../src/geographic-location/geographic-location.service');
    const { RetrieveGeographicLocationService } =
      await import('../src/retrieve-geographic-location/retrieve-geographic-location.service');
    const { RetrieveLocationRelationService } =
      await import('../src/retrieve-location-relation/retrieve-location-relation.service');
    byToken.set(GeographicAddressService, services[0]);
    byToken.set(GeographicAddressValidationService, services[1]);
    byToken.set(GeographicSubAddressService, services[2]);
    byToken.set(GeographicSiteService, services[3]);
    byToken.set(GeographicLocationService, services[4]);
    byToken.set(RetrieveGeographicLocationService, services[5]);
    byToken.set(RetrieveLocationRelationService, services[6]);
    await import('../src/seed');
  });
  await new Promise((r) => setTimeout(r, 1100));
  process.argv = argvBefore;
  return app;
}

function svc(total: number, createImpl?: jest.Mock) {
  return {
    create: createImpl ?? jest.fn(async () => ({})),
    findAll: jest.fn(async () => ({ total })),
  };
}

/** The resource under test first, then a quiet stand-in for each of the others. */
function services(total: number, first: AnyRec) {
  return [first, ...Array.from({ length: 6 }, () => svc(total))];
}

describe('seed', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    rows0_1 = [];
    rows1_1 = [];
    rows2_1 = [];
    rows3_1 = [];
    rows4_1 = [];
    rows5_1 = [];
    rows6_1 = [];
  });

  it('skips a resource that already holds rows', async () => {
    const a = svc(3);
    rows0_1 = [{ id: 'a' }];
    const app = await runSeed([], services(3, a));

    expect(a.findAll).toHaveBeenCalled();
    expect(a.create).not.toHaveBeenCalled();
    expect(app.close).toHaveBeenCalled();
  });

  it('seeds every payload when the resource is empty', async () => {
    const a = svc(0);
    rows0_1 = [{ id: 'a' }, { id: 'b' }];
    await runSeed([], services(0, a));

    expect(a.create).toHaveBeenCalledTimes(2);
  });

  it('--force seeds without checking the existing count', async () => {
    const a = svc(99);
    rows0_1 = [{ id: 'a' }];
    await runSeed(['--force'], services(99, a));

    expect(a.findAll).not.toHaveBeenCalled();
    expect(a.create).toHaveBeenCalledTimes(1);
  });

  it('logs and continues when one payload fails to seed', async () => {
    const failing = jest
      .fn()
      .mockRejectedValueOnce(new Error('duplicate key'))
      .mockResolvedValueOnce({});
    const a = svc(0, failing);
    rows0_1 = [{ id: 'bad' }, { id: 'good' }];
    const app = await runSeed([], services(0, a));

    expect(failing).toHaveBeenCalledTimes(2);
    expect(app.close).toHaveBeenCalled();
  });

  it('closes the context and exits non-zero when seeding throws', async () => {
    const a = {
      create: jest.fn(async () => ({})),
      findAll: jest.fn(async () => {
        throw new Error('db down');
      }),
    };
    rows0_1 = [{ id: 'a' }];
    const exit = jest
      .spyOn(process, 'exit')
      .mockImplementation((() => undefined) as never);
    const app = await runSeed([], services(0, a));

    expect(app.close).toHaveBeenCalled();
    expect(exit).toHaveBeenCalledWith(1);
    exit.mockRestore();
  });
});
