// GENERATED by fe-gen emit mfe - DO NOT EDIT. Re-run `fe-gen emit` instead.
// Federation boundary ./ItemsPage -> src/exposes/ItemsPage.tsx.
// Merender halamannya sendiri (view list, page items) - bukan halaman list pertama.
// Rute detail tidak di-expose: komponennya membaca :id dari router, jadi hanya
// bermakna lewat ./routes yang dipasang host.
import Page from '../pages/items/List';

export default function ItemsPage() {
  return <Page />;
}
