// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.
// Form add products - assembly StandardFormModal (RHF+zod runtime di src/gen/).
// Payload POST = addPayloadSpec (api.payload; itemPayload direkonstruksi runtime).
// FieldSpec/zodRules/defaults di zodSchemas.ts (sumber tunggal).

import { ReactElement, useCallback } from 'react';
import { StandardFormModal } from '../../gen/StandardFormModal';
import { createProducts } from '../../gen/api/products';
import { addDefaults, addFields, addPayloadSpec } from './zodSchemas';

export interface AddFormProps {
  open: boolean;
  onClose: () => void;
  onSaved: () => void;
}

export default function AddForm({ open, onClose, onSaved }: AddFormProps): ReactElement {
  const handleSubmit = useCallback(
    async (values: Record<string, unknown>) => {
      await createProducts(values);
      onSaved();
      onClose(); // tutup modal setelah simpan sukses (guard: jangan hang terbuka)
    },
    [onSaved, onClose],
  );

  return (
    <StandardFormModal
      open={open}
      title={"Tambah Produk"}
      width={"lg"}
      fields={addFields}
      defaultValues={addDefaults}
      payloadSpec={addPayloadSpec}
      mode={'onChange'}
      reValidateMode={'onChange'}
      submitLabel={"Simpan"}
      cancelLabel={"Batal"}
      onSubmit={handleSubmit}
      onClose={onClose}
    />
  );
}
