// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.
// Halaman detail products (detail mode page). Data dari GET retrieve (api defs).
// pageContext binding {{prefix.field}} di-resolve emit-time -> accessor data detail
// (route param :id) - runtime QueryContext dan src/gen/ tidak disentuh.
// Tab/blocks dari FEIR detail.sections: description-list + table (renderColumns nested).

import { ReactElement, useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Pencil, Trash2 } from 'lucide-react';
import { ApiError } from '../../gen/apiClient';
import { deleteProducts, getProducts } from '../../gen/api/products';
import type { Products } from '../../gen/api/products';
import { UiAlert, UiBox, UiButton, UiCard, UiIconButton, UiTabs, UiTab, UiTypography } from '../../gen/ui';
import EditForm from './EditForm';

export default function Detail(): ReactElement {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState<Products | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState(0);
  const [editOpen, setEditOpen] = useState(false);

  const load = useCallback(async () => {
    if (id === undefined) return;
    setLoading(true);
    setError(null);
    try {
      const detail = await getProducts(id);
      setData(detail);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    void load();
  }, [load]);

  const backToList = (): void => {
    navigate('/products');
  };

  const handleDelete = (): void => {
    if (id === undefined) return;
    if (window.confirm('Hapus data ini? Klik OK untuk melanjutkan.')) {
      deleteProducts(id)
        .then(() => {
          backToList();
        })
        .catch((err) => {
          setError(err instanceof ApiError ? err.message : String(err));
        });
    }
  };

  if (loading) {
    return (<UiBox sx={{ p: 4 }}><UiTypography>Memuat...</UiTypography></UiBox>);
  }
  if (error !== null) {
    return (<UiBox sx={{ p: 4 }}><UiAlert severity="error">{error}</UiAlert></UiBox>);
  }
  if (data === null) {
    return (<UiBox sx={{ p: 4 }}><UiTypography>Data tidak ditemukan</UiTypography></UiBox>);
  }

  return (
    <UiBox sx={{ display: 'flex', flexDirection: 'column', gap: 2, minHeight: '60vh' }}>
      <UiBox sx={{ display: 'flex', alignItems: 'flex-start', gap: 1, flexWrap: 'wrap' }}>
        <UiIconButton size="small" title="Kembali" aria-label="Kembali" onClick={backToList}><ArrowLeft size={18} /></UiIconButton>
        <UiBox sx={{ flexGrow: 1, minWidth: 240 }}>
          <UiTypography variant="h5">{String((data as Record<string, unknown>)?.["name"] ?? '')}</UiTypography>
          <UiTypography variant="body2" sx={{ color: 'text.secondary' }}>{String((data as Record<string, unknown>)?.["sku"] ?? '')}</UiTypography>
        </UiBox>
        <UiBox sx={{ display: 'flex', gap: 1 }}>
          <UiButton tone='primary' startIcon={<Pencil size={16} />} onClick={() => setEditOpen(true)}>{'Edit'}</UiButton>
          <UiButton tone='danger' startIcon={<Trash2 size={16} />} onClick={handleDelete}>{'Hapus'}</UiButton>
        </UiBox>
      </UiBox>
      <UiBox sx={{ width: '100%' }}>
        <UiTabs value={tab} onChange={(_e: unknown, v: number) => setTab(v)}>
          <UiTab label={'Ringkasan'} />
        </UiTabs>
      </UiBox>
      <UiBox sx={{ width: '100%' }}>
        {(() => {
          switch (tab) {
            case 0: return <Tab0Body data={data} />;
            default: return <Tab0Body data={data} />;
          }
        })()}
      </UiBox>
      {editOpen && id !== undefined ? <EditForm open={editOpen} id={id} onClose={() => setEditOpen(false)} onSaved={() => void load()} /> : null}
    </UiBox>
  );
}

function Tab0Body(props: { data: Products }): ReactElement {
  const data = props.data;
  return (
    <UiBox sx={{ p: 1 }}>
        <UiCard sx={{ p: 2 }}>
          <UiBox sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
            <UiBox sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
              <UiTypography variant="body2" sx={{ width: 170, flexShrink: 0, color: 'text.secondary' }}>{'Nama Produk'}</UiTypography>
              <UiTypography variant="body2" sx={{ wordBreak: 'break-word' }}>{String((data as Record<string, unknown>)?.["name"] ?? '')}</UiTypography>
            </UiBox>
            <UiBox sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
              <UiTypography variant="body2" sx={{ width: 170, flexShrink: 0, color: 'text.secondary' }}>{'SKU'}</UiTypography>
              <UiTypography variant="body2" sx={{ wordBreak: 'break-word' }}>{String((data as Record<string, unknown>)?.["sku"] ?? '')}</UiTypography>
            </UiBox>
            <UiBox sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
              <UiTypography variant="body2" sx={{ width: 170, flexShrink: 0, color: 'text.secondary' }}>{'Kategori'}</UiTypography>
              <UiTypography variant="body2" sx={{ wordBreak: 'break-word' }}>{String((data as Record<string, unknown>)?.["category"] ?? '')}</UiTypography>
            </UiBox>
            <UiBox sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
              <UiTypography variant="body2" sx={{ width: 170, flexShrink: 0, color: 'text.secondary' }}>{'Harga'}</UiTypography>
              <UiTypography variant="body2" sx={{ wordBreak: 'break-word' }}>{String((data as Record<string, unknown>)?.["price"] ?? '')}</UiTypography>
            </UiBox>
            <UiBox sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
              <UiTypography variant="body2" sx={{ width: 170, flexShrink: 0, color: 'text.secondary' }}>{'Deskripsi'}</UiTypography>
              <UiTypography variant="body2" sx={{ wordBreak: 'break-word' }}>{String((data as Record<string, unknown>)?.["description"] ?? '')}</UiTypography>
            </UiBox>
            <UiBox sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
              <UiTypography variant="body2" sx={{ width: 170, flexShrink: 0, color: 'text.secondary' }}>{'Tanggal Restock'}</UiTypography>
              <UiTypography variant="body2" sx={{ wordBreak: 'break-word' }}>{String((data as Record<string, unknown>)?.["restockDate"] ?? '')}</UiTypography>
            </UiBox>
          </UiBox>
        </UiCard>
    </UiBox>
  );
}
