// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.
// Zod schemas + FieldSpec (kontrak StandardFormModal) + payload spec (api.payload)
// untuk form add/edit halaman ini. FieldSpec adalah SATU-SATUNYA sumber yang diserahkan
// ke StandardFormModal runtime (modal membangun schema zod internal dari zodRules).
// zodSchema di bawah = mirror eksplisit (di-assert fe-payload-check; dibutuhkan tsc).
import { z } from 'zod';
import type { FieldSpec } from '../../gen/StandardFormModal';

export const addFields: FieldSpec[] = [
    {
      name: "name",
      type: "text",
      label: "Nama Produk",
      required: true,
      zodRules: [{ rule: "required", message: "Wajib diisi" }, { rule: "minLength", value: 3, message: "Minimal 3 karakter" }]
    },
    {
      name: "sku",
      type: "text",
      label: "SKU",
      required: true,
      zodRules: [{ rule: "required", message: "Wajib diisi" }]
    },
    {
      name: "category",
      type: "select",
      label: "Kategori",
      required: true,
      options: {"electronics":"Elektronik","groceries":"Sembako","apparel":"Pakaian","furniture":"Furnitur"},
      zodRules: [{ rule: "required", message: "Wajib diisi" }]
    },
    {
      name: "price",
      type: "number",
      label: "Harga",
      required: true,
      min: 0,
      zodRules: [{ rule: "required", message: "Wajib diisi" }, { rule: "min", value: 0, message: "Minimal 0" }]
    },
    {
      name: "description",
      type: "textarea",
      label: "Deskripsi",
      rows: 3
    },
    {
      name: "restockDate",
      type: "date",
      label: "Tanggal Restock"
    },
    {
      name: "inStock",
      type: "checkbox",
      label: "Tersedia di Stok"
    },
    {
      name: "variants",
      type: "repeatable",
      label: "Varian Produk",
      itemLabel: "Varian {{index}}",
      addButton: "+ Tambah Varian",
      minItems: 0,
      itemFields: [
        {
          name: "label",
          type: "text",
          label: "Nama Varian",
          required: true,
          zodRules: [{ rule: "required", message: "Wajib diisi" }]
        },
        {
          name: "extraPrice",
          type: "number",
          label: "Tambahan Harga",
          min: 0,
          zodRules: [{ rule: "min", value: 0, message: "Minimal 0" }]
        }
      ]
    }
  ];

export const editFields: FieldSpec[] = [
    {
      name: "name",
      type: "text",
      label: "Nama Produk",
      required: true,
      zodRules: [{ rule: "required", message: "Wajib diisi" }, { rule: "minLength", value: 3, message: "Minimal 3 karakter" }]
    },
    {
      name: "sku",
      type: "text",
      label: "SKU",
      required: true,
      zodRules: [{ rule: "required", message: "Wajib diisi" }]
    },
    {
      name: "category",
      type: "select",
      label: "Kategori",
      required: true,
      options: {"electronics":"Elektronik","groceries":"Sembako","apparel":"Pakaian","furniture":"Furnitur"},
      zodRules: [{ rule: "required", message: "Wajib diisi" }]
    },
    {
      name: "price",
      type: "number",
      label: "Harga",
      required: true,
      min: 0,
      zodRules: [{ rule: "required", message: "Wajib diisi" }, { rule: "min", value: 0, message: "Minimal 0" }]
    },
    {
      name: "description",
      type: "textarea",
      label: "Deskripsi",
      rows: 3
    },
    {
      name: "restockDate",
      type: "date",
      label: "Tanggal Restock"
    },
    {
      name: "inStock",
      type: "checkbox",
      label: "Tersedia di Stok"
    },
    {
      name: "variants",
      type: "repeatable",
      label: "Varian Produk",
      itemLabel: "Varian {{index}}",
      addButton: "+ Tambah Varian",
      minItems: 0,
      itemFields: [
        {
          name: "label",
          type: "text",
          label: "Nama Varian",
          required: true,
          zodRules: [{ rule: "required", message: "Wajib diisi" }]
        },
        {
          name: "extraPrice",
          type: "number",
          label: "Tambahan Harga",
          min: 0,
          zodRules: [{ rule: "min", value: 0, message: "Minimal 0" }]
        }
      ]
    }
  ];

export const addDefaults: Record<string, unknown> = {"name":"","sku":"","category":"","price":"","description":"","restockDate":"","inStock":false,"variants":[]};
export const editDefaultsBase: Record<string, unknown> = {"name":"","sku":"","category":"","price":"","description":"","restockDate":"","inStock":false,"variants":[]};

export const addPayloadSpec: Record<string, unknown> = {"name":{"$src":"fields.name","$tx":"trim"},"sku":{"$src":"fields.sku","$tx":"trim"},"category":"fields.category","price":{"$src":"fields.price","$tx":"number"},"description":"fields.description","restockDate":"fields.restockDate","inStock":"fields.inStock","variants":"fields.variants"};
export const editPayloadSpec: Record<string, unknown> = {"name":"fields.name","category":"fields.category","price":{"$src":"fields.price","$tx":"number"},"description":"fields.description","inStock":"fields.inStock","variants":"fields.variants"};

export const variantZodSchema = z.object({ 'label': z.string().min(1, 'Wajib diisi'), 'extraPrice': z.coerce.number().min(0, 'Minimal 0').optional() });
export const addZodSchema = z.object({ 'name': z.string().min(1, 'Wajib diisi').min(3, 'Minimal 3 karakter'), 'sku': z.string().min(1, 'Wajib diisi'), 'category': z.string().min(1, 'Wajib diisi'), 'price': z.coerce.number().min(0, 'Minimal 0'), 'description': z.string().optional(), 'restockDate': z.string().optional(), 'inStock': z.boolean().optional(), 'variants': z.array(variantZodSchema).optional() });
export const editZodSchema = z.object({ 'name': z.string().min(1, 'Wajib diisi').min(3, 'Minimal 3 karakter'), 'sku': z.string().min(1, 'Wajib diisi'), 'category': z.string().min(1, 'Wajib diisi'), 'price': z.coerce.number().min(0, 'Minimal 0'), 'description': z.string().optional(), 'restockDate': z.string().optional(), 'inStock': z.boolean().optional(), 'variants': z.array(variantZodSchema).optional() });

export function mapDetailToDefaults(detail: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {
    "category": detail["category"] ?? '',
    "description": detail["description"] ?? '',
    "restockDate": detail["restockDate"] ?? '',
    "inStock": detail["inStock"] ?? '',
    "variants": detail["variants"] ?? []
  };

  return out;
}
