// GENERATED by fe-gen emit - DO NOT EDIT. Re-run `fe-gen emit` instead.
// Halaman list activity-log (view: list). Assembly runtime: useCrudPage + StandardList + api defs.
// Komponen UI = barrel src/gen/ui.tsx (adapter.resolve) - tanpa import MUI langsung.
// Titik sambung form/detail: emit/form.mjs dan emit/detail.mjs (todo berikutnya).
// modal add/edit di-buka dari sini via emit/form.mjs (state addOpen/editId).

import { ComponentProps, ReactElement, useState } from 'react';
import {  } from 'lucide-react';
import type { ListParams, Severity } from '../../gen/useCrudPage';
import { useCrudPage } from '../../gen/useCrudPage';
import { resolveTemplate } from '../../gen/QueryContext';
import { StandardList } from '../../gen/StandardList';
import { createActivityLog, deleteActivityLog, listActivityLog, updateActivityLog } from '../../gen/api/activity-log';
import type { ActivityLog } from '../../gen/api/activity-log';
import { UiAlert, UiBox, UiSnackbar } from '../../gen/ui';

export default function List(): ReactElement {
  const [snack, setSnack] = useState<{ message: string; severity: Severity } | null>(null);

  const notify = (message: string, severity: Severity): void => {
    setSnack({ message, severity });
  };

  const crud = useCrudPage<ActivityLog>(
    {
      list: async (params: ListParams) => {
        const result = await listActivityLog({
          offset: Number(resolveTemplate('{{pagination.offset}}', { pagination: { offset: params.offset ?? 0 } })),
          limit: Number(resolveTemplate('{{pagination.limit}}', { pagination: { limit: params.limit ?? 10 } })),
        });
        return { rows: result.rows, total: result.total };
      },
      create: (payload) => createActivityLog(payload),
      update: (id, payload) => updateActivityLog(id, payload),
      remove: (id) => deleteActivityLog(id),
      getRowId: (row) => row.id ?? row.href ?? '',
    },
    {
      scheme: 'offset-limit',
      searchDebounceMs: 300,
      defaultPageSize: 10,
      notify,
    },
  );

  const columns: ComponentProps<typeof StandardList>['columns'] = [
  {
    field: 'action',
    headerName: 'Aksi',
    sortable: true,
    filterable: false,
  },
  {
    field: 'user',
    headerName: 'Pengguna',
    sortable: false,
    filterable: false,
  },
  {
    field: 'target',
    headerName: 'Target',
    sortable: false,
    filterable: false,
  },
  {
    field: 'timestamp',
    headerName: 'Waktu',
    sortable: false,
    filterable: false,
  valueFormatter: (value) => (value == null ? '' : new Date(String(value)).toLocaleString()),
  },
  ];

  return (
    <UiBox sx={{ display: 'flex', flexDirection: 'column', gap: 1, height: '100%', minHeight: '60vh' }}>
      <StandardList
        columns={columns}
        rows={crud.rows}
        rowCount={crud.rowCount}
        pageModel={crud.pagination}
        sortModel={crud.sort}
        filterModel={crud.filter}
        onPaginationModelChange={crud.setPagination}
        onSortModelChange={crud.setSort}
        onFilterModelChange={crud.setFilter}
        loading={crud.loading}
        getRowId={(row) => row.id ?? row.href ?? ''}
        pageSizeOptions={[10, 25, 50]}
        emptyText={'Belum ada aktivitas'}
      />
      <UiSnackbar
        open={snack !== null}
        autoHideDuration={4000}
        onClose={() => setSnack(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
      >
        <UiAlert severity={snack?.severity ?? 'info'} onClose={() => setSnack(null)} variant="filled">
          {snack?.message}
        </UiAlert>
      </UiSnackbar>
    </UiBox>
  );
}
