// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, IsNull, Repository } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { TMF674_BASE_PATH } from '../common/constants/tmf.constants';
import { projectFields } from '../common/utils/tmf-resource.util';
import { applyBaseFilters } from '../common/utils/query-helper.util';
import { EventEmitterService } from '../event/event-emitter.service';
import { GeographicSiteEventType } from '../event/event-types';
import { GeographicSite } from './entities/geographic-site.entity';
import { HourPeriod } from './entities/hour-period.entity';
import { CalendarPeriod } from './entities/calendar-period.entity';
import { PlaceRefOrValue } from './entities/place-ref-or-value.entity';
import { RelatedParty } from './entities/related-party.entity';
import { TimePeriod } from './entities/time-period.entity';
import { GeographicSiteRelationship } from './entities/geographic-site-relationship.entity';
import { CreateGeographicSiteDto, UpdateGeographicSiteDto, QueryGeographicSiteDto } from './dto';
import * as hooks from './geographic-site.hooks';

/** A normalised ref row that must be persisted before the aggregate referencing it. */
type PendingRef = { target: new () => any; entity: Record<string, any> };

/** Drops undefined/null so the response carries only what the resource actually has. */
function stripEmpty(obj: Record<string, any>): Record<string, any> {
  for (const key of Object.keys(obj)) {
    if (obj[key] === undefined || obj[key] === null) {
      delete obj[key];
    }
  }
  return obj;
}

@Injectable()
export class GeographicSiteService {
  private readonly logger = new Logger(GeographicSiteService.name);

  constructor(
    @InjectRepository(GeographicSite)
    private readonly repository: Repository<GeographicSite>,
    @InjectRepository(HourPeriod)
    private readonly hourPeriodRepository: Repository<HourPeriod>,
    @InjectRepository(CalendarPeriod)
    private readonly calendarPeriodRepository: Repository<CalendarPeriod>,
    @InjectRepository(PlaceRefOrValue)
    private readonly placeRefOrValueRepository: Repository<PlaceRefOrValue>,
    @InjectRepository(RelatedParty)
    private readonly relatedPartyRepository: Repository<RelatedParty>,
    @InjectRepository(TimePeriod)
    private readonly timePeriodRepository: Repository<TimePeriod>,
    @InjectRepository(GeographicSiteRelationship)
    private readonly geographicSiteRelationshipRepository: Repository<GeographicSiteRelationship>,
    private readonly dataSource: DataSource,
    private readonly eventEmitter: EventEmitterService,
  ) {}

  private get geographicSiteRepository(): Repository<GeographicSite> {
    return this.repository;
  }

  async create(dto: CreateGeographicSiteDto): Promise<Record<string, any>> {
    const input = (await hooks.beforeCreate(dto as Record<string, any>)) ?? (dto as Record<string, any>);
    const pending: PendingRef[] = [];
    const entity = this.buildGeographicSite(input, pending);
    if (!entity.atType) {
      entity.atType = 'GeographicSite';
    }
    // A create must produce something the client can then READ.
    //
    // Where the spec lets a client choose the id, it may pick one belonging to a
    // soft-deleted row. save() then UPDATES that invisible row, and findEntity below -
    // which filters deletedAt IS NULL - cannot see it, so a POST answered
    //   404 "<Resource> <id> not found"
    // while quietly overwriting a row nobody can reach. From the API's point of view
    // that id was free: GET on it already returned 404. So the row is resurrected
    // rather than left buried.
    entity.deletedAt = null as unknown as Date;
    entity.deletedBy = undefined;
    entity.deletedReason = undefined;
    // normalised ref rows first, then the aggregate that points at them
    for (const ref of pending) {
      await this.dataSource.getRepository(ref.target).save(ref.entity);
    }
    await this.repository.save(entity);
    const saved = await this.findEntity(entity.id);
    const response = this.mapGeographicSite(saved);
    this.eventEmitter.emitEvent(
      GeographicSiteEventType.GEOGRAPHIC_SITE_CREATE,
      saved.id,
      'GeographicSite',
      response,
    );
    this.logger.log(`created geographicSite ${saved.id}`);
    return response;
  }

  async findAll(query: QueryGeographicSiteDto): Promise<{ data: Record<string, any>[]; total: number }> {
    // house filters available for this resource: name, q, sort
    const qb = this.repository.createQueryBuilder('e')
      .leftJoinAndSelect('e.calendar', 'calendar')
      .leftJoinAndSelect('e.place', 'place')
      .leftJoinAndSelect('e.relatedParty', 'relatedParty')
      .leftJoinAndSelect('e.siteRelationship', 'siteRelationship')
      .leftJoinAndSelect('calendar.hourPeriod', 'calendarHourPeriod')
      .leftJoinAndSelect('siteRelationship.validFor', 'siteRelationshipValidFor')
      .where('e.deletedAt IS NULL');

    applyBaseFilters(qb, query, 'e');
    if (query.id) {
      qb.andWhere('e.id = :id', { id: query.id });
    }

    const total = await qb.getCount();
    qb.skip(query.offset ?? 0).take(query.limit ?? 20);
    const rows = await qb.getMany();
    const data = rows.map((r) => this.mapGeographicSite(r));
    return { data: query.fields ? projectFields(data, query.fields) : data, total };
  }

  async findEntity(id: string): Promise<GeographicSite> {
    const entity = await this.repository.findOne({
      where: { id, deletedAt: IsNull() },
      relations: ['calendar', 'calendar.hourPeriod', 'place', 'relatedParty', 'siteRelationship', 'siteRelationship.validFor'],
    });
    if (!entity) {
      throw new NotFoundException(`GeographicSite ${id} not found`);
    }
    return entity;
  }

  async findOne(id: string, fields?: string): Promise<Record<string, any>> {
    const entity = await this.findEntity(id);
    const response = (await hooks.afterFindOne(this.mapGeographicSite(entity), entity)) ?? this.mapGeographicSite(entity);
    return fields ? projectFields([response], fields)[0] : response;
  }

  async update(id: string, dto: UpdateGeographicSiteDto): Promise<Record<string, any>> {
    const input = (await hooks.beforeUpdate(id, dto as Record<string, any>)) ?? (dto as Record<string, any>);

    // Wrapped in a transaction: collections are replaced wholesale, so a failure
    // between delete and insert would otherwise lose data.
    const pending: PendingRef[] = [];
    const saved = await this.dataSource.transaction(async (manager) => {
      const existing = await manager.findOne(GeographicSite, {
        where: { id, deletedAt: IsNull() },
        relations: ['calendar', 'calendar.hourPeriod', 'place', 'relatedParty', 'siteRelationship', 'siteRelationship.validFor'],
      });
      if (!existing) {
        throw new NotFoundException(`GeographicSite ${id} not found`);
      }
      if (input['code'] !== undefined) {
        existing.code = input['code'];
      }
      if (input['description'] !== undefined) {
        existing.description = input['description'];
      }
      if (input['name'] !== undefined) {
        existing.name = input['name'];
      }
      if (input['status'] !== undefined) {
        existing.status = input['status'];
      }
      if (input.calendar !== undefined) {
        await manager.delete(CalendarPeriod, { owner: { id } });
        existing.calendar = (input.calendar ?? []).map((i: Record<string, any>) => this.buildCalendarPeriod(i, pending, existing));
      }
      if (input.place !== undefined) {
        await manager.delete(PlaceRefOrValue, { owner: { id } });
        existing.place = (input.place ?? []).map((i: Record<string, any>) => this.buildPlaceRefOrValue(i, pending, existing));
      }
      if (input.relatedParty !== undefined) {
        await manager.delete(RelatedParty, { owner: { id } });
        existing.relatedParty = (input.relatedParty ?? []).map((i: Record<string, any>) => this.buildRelatedParty(i, pending, existing));
      }
      if (input.siteRelationship !== undefined) {
        const orphanedSiteRelationshipValidFor: string[] = (existing.siteRelationship ?? [])
          .map((c) => c.validFor?.id)
          .filter((v): v is string => !!v);
        await manager.delete(GeographicSiteRelationship, { owner: { id } });
        if (orphanedSiteRelationshipValidFor.length) {
          await manager.delete(TimePeriod, orphanedSiteRelationshipValidFor);
        }
        existing.siteRelationship = (input.siteRelationship ?? []).map((i: Record<string, any>) => this.buildGeographicSiteRelationship(i, pending, existing));
      }

      for (const ref of pending) {
        await manager.save(ref.target, ref.entity);
      }
      const saved = await manager.save(existing);

      return saved;
    });

    const fresh = await this.findEntity(saved.id);
    const response = this.mapGeographicSite(fresh);
    this.eventEmitter.emitEvent(
      GeographicSiteEventType.GEOGRAPHIC_SITE_ATTRIBUTE_VALUE_CHANGE,
      fresh.id,
      'GeographicSite',
      response,
    );
    return response;
  }

  async remove(id: string, deletedBy?: string, deletedReason?: string): Promise<void> {
    const entity = await this.findEntity(id);
    // soft delete: the row stays, deletedAt/deletedBy/deletedReason record who and why
    entity.deletedAt = new Date();
    entity.deletedBy = deletedBy ?? 'system';
    entity.deletedReason = deletedReason ?? 'Deleted via API';
    await this.repository.save(entity);
    this.eventEmitter.emitEvent(
      GeographicSiteEventType.GEOGRAPHIC_SITE_DELETE,
      entity.id,
      'GeographicSite',
      { id: entity.id, href: `/${TMF674_BASE_PATH}/geographicSite/${entity.id}` },
    );
    this.logger.log(`soft-deleted geographicSite ${id}`);
  }

  /* ── payload -> entity ── */
  private buildGeographicSite(input: Record<string, any>, pending: PendingRef[]): GeographicSite {
    const e = this.geographicSiteRepository.create();
    e.id = input?.id ?? uuidv4();
    e.code = input?.['code'];
    e.description = input?.['description'];
    e.name = input?.['name'];
    e.status = input?.['status'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    e.calendar = (input?.calendar ?? []).map((i: Record<string, any>, __i: number) => Object.assign(this.buildCalendarPeriod(i, pending, e), { sortOrder: __i }));
    e.place = (input?.place ?? []).map((i: Record<string, any>, __i: number) => Object.assign(this.buildPlaceRefOrValue(i, pending, e), { sortOrder: __i }));
    e.relatedParty = (input?.relatedParty ?? []).map((i: Record<string, any>, __i: number) => Object.assign(this.buildRelatedParty(i, pending, e), { sortOrder: __i }));
    e.siteRelationship = (input?.siteRelationship ?? []).map((i: Record<string, any>, __i: number) => Object.assign(this.buildGeographicSiteRelationship(i, pending, e), { sortOrder: __i }));
    return e;
  }

  private buildHourPeriod(input: Record<string, any>, pending: PendingRef[], owner: CalendarPeriod): HourPeriod {
    const e = this.hourPeriodRepository.create();
    e.id = uuidv4();
    e.owner = owner;
    e.refId = input?.['id'];
    e.endHour = input?.['endHour'];
    e.startHour = input?.['startHour'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    return e;
  }

  private buildCalendarPeriod(input: Record<string, any>, pending: PendingRef[], owner: GeographicSite): CalendarPeriod {
    const e = this.calendarPeriodRepository.create();
    e.id = uuidv4();
    e.owner = owner;
    e.refId = input?.['id'];
    e.day = input?.['day'];
    e.status = input?.['status'];
    e.timeZone = input?.['timeZone'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    e.hourPeriod = (input?.hourPeriod ?? []).map((i: Record<string, any>, __i: number) => Object.assign(this.buildHourPeriod(i, pending, e), { sortOrder: __i }));
    return e;
  }

  private buildPlaceRefOrValue(input: Record<string, any>, pending: PendingRef[], owner: GeographicSite): PlaceRefOrValue {
    const e = this.placeRefOrValueRepository.create();
    e.id = uuidv4();
    e.owner = owner;
    e.refId = input?.['id'];
    e.name = input?.['name'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    return e;
  }

  private buildRelatedParty(input: Record<string, any>, pending: PendingRef[], owner: GeographicSite): RelatedParty {
    const e = this.relatedPartyRepository.create();
    e.id = uuidv4();
    e.owner = owner;
    e.refId = input?.['id'];
    e.name = input?.['name'];
    e.role = input?.['role'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    return e;
  }

  private buildTimePeriod(input: Record<string, any>, pending: PendingRef[]): TimePeriod {
    const e = this.timePeriodRepository.create();
    e.id = uuidv4();
    e.endDateTime = input?.['endDateTime'];
    e.startDateTime = input?.['startDateTime'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    pending.push({ target: TimePeriod, entity: e });
    return e;
  }

  private buildGeographicSiteRelationship(input: Record<string, any>, pending: PendingRef[], owner: GeographicSite): GeographicSiteRelationship {
    const e = this.geographicSiteRelationshipRepository.create();
    e.id = uuidv4();
    e.owner = owner;
    e.refId = input?.['id'];
    e.relationshipType = input?.['relationshipType'];
    e.role = input?.['role'];
    e.atType = input?.['@type'];
    e.atSchemaLocation = input?.['@schemaLocation'];
    e.atBaseType = input?.['@baseType'];
    e.validFor = input?.validFor ? this.buildTimePeriod(input.validFor, pending) : undefined;
    return e;
  }

  /* ── entity -> API response (inverse of the nesting rule) ── */
  private mapGeographicSite(e: GeographicSite): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.id;
    out.code = e.code;
    out.description = e.description;
    out.name = e.name;
    out.status = e.status;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation ?? '';
    out['@baseType'] = e.atBaseType ?? '';
    out.href = `/${TMF674_BASE_PATH}/geographicSite/${e.id}`;
    out.calendar = [...(e.calendar ?? [])].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)).map((c) => this.mapCalendarPeriod(c, e.id));
    out.place = [...(e.place ?? [])].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)).map((c) => this.mapPlaceRefOrValue(c, e.id));
    out.relatedParty = [...(e.relatedParty ?? [])].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)).map((c) => this.mapRelatedParty(c, e.id));
    out.siteRelationship = [...(e.siteRelationship ?? [])].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)).map((c) => this.mapGeographicSiteRelationship(c, e.id));
    return stripEmpty(out);
  }

  private mapHourPeriod(e: HourPeriod, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.refId ?? e.id;
    out.endHour = e.endHour;
    out.startHour = e.startHour;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF674_BASE_PATH}/geographicSite/${rootId}/hourPeriod/${e.refId ?? e.id}`;
    }
    return stripEmpty(out);
  }

  private mapCalendarPeriod(e: CalendarPeriod, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.refId ?? e.id;
    out.day = e.day;
    out.status = e.status;
    out.timeZone = e.timeZone;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF674_BASE_PATH}/geographicSite/${rootId}/calendar/${e.refId ?? e.id}`;
    }
    out.hourPeriod = [...(e.hourPeriod ?? [])].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)).map((c) => this.mapHourPeriod(c, rootId));
    return stripEmpty(out);
  }

  private mapPlaceRefOrValue(e: PlaceRefOrValue, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.refId ?? e.id;
    out.name = e.name;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF674_BASE_PATH}/geographicSite/${rootId}/place/${e.refId ?? e.id}`;
    }
    return stripEmpty(out);
  }

  private mapRelatedParty(e: RelatedParty, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.refId ?? e.id;
    out.name = e.name;
    out.role = e.role;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF674_BASE_PATH}/geographicSite/${rootId}/relatedParty/${e.refId ?? e.id}`;
    }
    return stripEmpty(out);
  }

  private mapTimePeriod(e: TimePeriod): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.id;
    out.endDateTime = e.endDateTime;
    out.startDateTime = e.startDateTime;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    return stripEmpty(out);
  }

  private mapGeographicSiteRelationship(e: GeographicSiteRelationship, rootId?: string): Record<string, any> {
    const out: Record<string, any> = {};
    out.id = e.refId ?? e.id;
    out.relationshipType = e.relationshipType;
    out.role = e.role;
    out['@type'] = e.atType;
    out['@schemaLocation'] = e.atSchemaLocation;
    out['@baseType'] = e.atBaseType;
    if (rootId) {
      out.href = `/${TMF674_BASE_PATH}/geographicSite/${rootId}/siteRelationship/${e.refId ?? e.id}`;
    }
    out.validFor = e.validFor ? this.mapTimePeriod(e.validFor) : undefined;
    return stripEmpty(out);
  }
}
