// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * The per-resource hook modules are the domain seam the generated services call
 * at fixed points. Each is a pass-through unless the component assigns something
 * server-side, so the contract under test is "returns undefined, or a payload
 * that still carries what the caller sent".
 */
import * as partyRevSharingAlgorithmHooks from '../src/party-rev-sharing-algorithm/party-rev-sharing-algorithm.hooks';

type Hooks = typeof partyRevSharingAlgorithmHooks;

const MODULES: [string, Hooks][] = [
  ['partyRevSharingAlgorithm', partyRevSharingAlgorithmHooks],
];

describe.each(MODULES)('%s hooks', (_name, hooks) => {
  it('leaves the update payload and the mapped response untouched', async () => {
    await expect(
      hooks.beforeUpdate('id-1', { name: 'A' }),
    ).resolves.toBeUndefined();
    await expect(
      hooks.afterFindOne({ id: 'id-1' }, {}),
    ).resolves.toBeUndefined();
  });

  it('either passes the create payload through or returns it enriched', async () => {
    const result = await hooks.beforeCreate({ name: 'A' });
    if (result !== undefined) {
      expect(result.name).toBe('A');
    }
  });
});
