// emitFESpec.mjs — M1 frontend-spec baseline emitter (IR -> frontend-spec-*.yaml)
// API: emitFESpec(ir) -> Promise<string> (validated YAML text; throws when output
// fails the todo-1 validator so an invalid file is never written).
// Cross-checked by todo 3 (determinism golden) — keep the emitter a pure function
// of the IR: no clock, no random, no cwd-dependent content.
import { kebab, words } from '../ir/naming.mjs';
import { validateString } from './validateFESpec.mjs';

const IND = '  ';
const pad = (n, s) => IND.repeat(n) + s;

/** Quote a scalar only when YAML would misread it; keep the output human-clean. */
const q = v => {
  const s = String(v ?? '');
  return /^[A-Za-z0-9][A-Za-z0-9 _\-./()@%'+]*$/.test(s) ? s : JSON.stringify(s);
};

const humanize = s =>
  words(s).map(w => (w ? w[0].toUpperCase() + w.slice(1) : w)).join(' ');

const plural = s => (/(s|x|ch|sh|z)$/i.test(s) ? `${s}es` : `${s}s`);

const OP_METHOD = { list: 'GET', create: 'POST', retrieve: 'GET', update: 'PATCH', delete: 'DELETE' };
const INFRA_PROP = new Set(['@baseType', '@schemaLocation', 'id', 'href']);

const fieldLabel = name =>
  name === 'name' ? 'Nama' : name === 'description' ? 'Deskripsi' : name === 'id' ? 'ID' : humanize(name);

function inputType(f) {
  if (f.name === 'description') return 'textarea';
  if (f.tsType === 'boolean' || f.column?.type === 'boolean') return 'toggle';
  if (f.enumValues?.length) return 'select';
  return 'text';
}

function scalarWire(f) {
  return f.sourceProp || f.name;
}

function pageIcon(name) {
  if (/Validation/i.test(name)) return 'FileCheck';
  if (/Address/i.test(name)) return 'MapPin';
  if (/Algorithm|Policy|Charge/i.test(name)) return 'Percent';
  return 'LayoutDashboard';
}

const subOf = (r, prop) => r.subResources.find(s => s.propertyName === prop) ?? null;
const refOf = (r, prop) => r.resourceRefs.find(f => f.name === prop) ?? null;
const scalarOf = (r, prop) => r.fields.find(f => f.name === prop) ?? null;

/** Resource-level flattenedRef (cross-component ref) usable as payload object: needs id/href/name column. */
function flatOf(r, prop) {
  const fr = r.flattenedRefs?.find(f => f.name === prop) ?? null;
  return fr && fr.columns.some(c => ['id', 'href', 'name'].includes(c.sourceProp)) ? fr : null;
}

/** Bagaimana sebuah prop shape di-render di payload form: null = tak bisa dirender (bukan field user). */
function payloadEntryKind(r, p) {
  if (p === '@type') return 'atType';
  if (subOf(r, p)) return 'sub';
  if (refOf(r, p)) return 'ref';
  if (flatOf(r, p)) return 'flat';
  if (scalarOf(r, p)) return 'scalar';
  return null;
}

function renderValueBase(basePath, path) {
  return `"{{api.basePath}}${path}"`;
}

/* ── block writers ─────────────────────────────────────────────────── */

function header(lines, ir) {
  const m = ir.meta;
  lines.push('# ============================================================');
  lines.push(`# TMF${m.tmfNumber} frontend-spec baseline — generated by tmfgen fe-spec`);
  lines.push('# ------------------------------------------------------------');
  lines.push('# Sumber IR : generator/ir-cache (hasil `tmfgen ir`)');
  lines.push(`# Base path : /${m.basePath}`);
  lines.push('# GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.');
  lines.push('# ============================================================');
  lines.push('');
}

function metaBlock(lines, ir) {
  const m = ir.meta;
  const portal = m.serviceNameSuggestion.replace(/-service$/, '') + '-portal';
  const name = /^[a-z0-9-]+$/.test(portal) ? portal : kebab(ir.resources[0]?.name ?? 'app') + '-portal';
  lines.push('meta:');
  lines.push(pad(1, `name: ${q(name)}`));
  lines.push(pad(1, `label: ${q(m.specTitle)}`));
  lines.push(pad(1, 'version: 0.1.0'));
  lines.push(pad(1, 'lang: id'));
  lines.push(pad(1, `description: ${q(`Portal manajemen ${m.specTitle} (TMF${m.tmfNumber})`)}`));
  lines.push('');
}

function apiBlock(lines, ir) {
  const m = ir.meta;
  lines.push('api:');
  lines.push(pad(1, `basePath: ${q(`/${m.basePath}`)}`));
  lines.push(pad(1, 'headers:                              # BE generated pakai ApiKeyGuard'));
  lines.push(pad(2, '# KONTRAK RUNTIME: nilai secret HANYA lewat {{config.*}} (runtime gen.config),'));
  lines.push(pad(2, '# TIDAK pernah lewat build-env / {{env.*}}.'));
  lines.push(pad(2, `x-api-key: ${q('{{config.TMF_API_KEY}}')}`));
  lines.push(pad(1, 'endpoints:'));
  for (const r of ir.resources) {
    for (const op of ['list', 'create', 'retrieve', 'update', 'delete']) {
      if (!r.operations[op]) continue;
      const path = op === 'list' || op === 'create' ? r.paths.collection : r.paths.item;
      lines.push(pad(2, `${q(`${r.camelName}.${op}`)}: ${OP_METHOD[op].padEnd(5)} ${path}`));
    }
  }
  if (ir.hub.present || ir.listeners.length) {
    lines.push(pad(2, '# hub/listener (event subscription) — bukan resource CRUD;'));
    lines.push(pad(2, '#   POST /hub, DELETE /hub/{id}; listener POST ' + ir.listeners.map(l => l.path).join(', ')));
  }
  lines.push('');
}

function outputBlock(lines) {
  lines.push('output:');
  lines.push(pad(1, '# SEMENTARA full-repo: satu app utuh. Ganti ke mfe (hostApp/exposes) bila'));
  lines.push(pad(1, '# target deploy adalah MFE - keputusan akhir di F2 (draf fe-generators).'));
  lines.push(pad(1, 'type: full-repo'));
  lines.push(pad(1, 'fullRepo:'));
  lines.push(pad(2, 'router: react-router'));
  lines.push(pad(2, 'state: context'));
  lines.push(pad(2, 'packageManager: npm'));
  lines.push('');
}

function uiBlock(lines) {
  lines.push('ui:');
  lines.push(pad(1, 'library: mui'));
  lines.push(pad(1, 'version: "^9.0.0"              # mui WAJIB ^9.x (normalisasi validator v1)'));
  lines.push(pad(1, 'theme:'));
  lines.push(pad(2, 'name: indigo'));
  lines.push(pad(2, 'darkMode: true'));
  lines.push(pad(2, 'tokens:'));
  lines.push(pad(3, 'primary: "#2563eb"'));
  lines.push(pad(3, 'surface: "#ffffff"'));
  lines.push(pad(3, 'background: "#f8fafc"'));
  lines.push(pad(3, 'text: "#0f172a"'));
  lines.push(pad(3, 'textMuted: "#64748b"'));
  lines.push(pad(3, 'radius: 8'));
  lines.push(pad(3, 'font: Inter'));
  lines.push('');
}

function formEngineBlock(lines) {
  lines.push('formEngine:');
  lines.push(pad(1, 'library: react-hook-form'));
  lines.push(pad(1, 'version: "^7.0.0"'));
  lines.push(pad(1, 'validator: zod'));
  lines.push(pad(1, 'validatorVersion: "^3.0.0"'));
  lines.push(pad(1, 'defaultMode: onChange'));
  lines.push(pad(1, 'defaultReValidateMode: onChange'));
  lines.push(pad(1, 'behaviour:'));
  lines.push(pad(2, 'shouldUnregister: true'));
  lines.push(pad(2, 'resetOnSubmit: false'));
  lines.push('');
}

function layoutBlock(lines) {
  lines.push('layout:');
  lines.push(pad(1, 'shell: sidebar-topbar'));
  lines.push(pad(1, 'sidebar:'));
  lines.push(pad(2, 'collapsible: true'));
  lines.push(pad(2, 'itemsSource: from-pages'));
  lines.push(pad(1, 'topbar:'));
  lines.push(pad(2, 'search: false'));
  lines.push(pad(2, 'themeToggle: true'));
  lines.push(pad(1, 'footer: false'));
  lines.push('');
}

function authBlock(lines) {
  lines.push('auth:');
  lines.push(pad(1, '# KONTRAK: BE generated memakai ApiKeyGuard (x-api-key via api.headers),'));
  lines.push(pad(1, '# BUKAN login session/JWT. enabled tetap false sampai ada auth server.'));
  lines.push(pad(1, 'enabled: false'));
  lines.push('');
}

/* ── page: list view ───────────────────────────────────────────────── */

function listView(lines, depth, r) {
  const hasQ = r.houseFilters.q;
  lines.push(pad(depth, 'view: list'));
  lines.push(pad(depth, 'list:'));
  lines.push(pad(depth + 1, `api: ${renderValueBase(r.paths.collection, r.paths.collection)}`));
  lines.push(pad(depth + 1, 'method: GET'));
  lines.push(pad(depth + 1, 'queryParams:'));
  lines.push(pad(depth + 2, 'fields: ""'));
  lines.push(pad(depth + 2, 'offset: "{{pagination.offset}}"'));
  lines.push(pad(depth + 2, 'limit: "{{pagination.limit}}"'));
  if (hasQ) lines.push(pad(depth + 2, 'q: "{{search.q}}"'));
  lines.push(pad(depth + 1, 'search:'));
  if (hasQ) {
    lines.push(pad(depth + 2, 'enabled: true'));
    lines.push(pad(depth + 2, 'mode: server-side'));
    lines.push(pad(depth + 2, 'debounceMs: 300'));
    const sf = r.fields.filter(f => f.name === 'name' || f.name === 'description').map(f => f.name);
    lines.push(pad(depth + 2, `placeholder: ${q(sf.length === 2 ? 'Cari nama / deskripsi...' : `Cari ${fieldLabel(sf[0] ?? 'item').toLowerCase()}...`)}`));
    lines.push(pad(depth + 2, `fields: [${sf.join(', ')}]`));
  } else {
    lines.push(pad(depth + 2, 'enabled: false'));
    lines.push(pad(depth + 2, 'mode: none'));
  }

  // 2-3 data columns from the meaningful scalars + (first refLike) tag-count + actions
  const scalars = r.fields.filter(f => f.kind === 'scalar' && f.tsType !== 'Date');
  const wanted = [];
  for (const cand of ['name', 'description', ...scalars.map(s => s.name)]) {
    if (scalars.some(s => s.name === cand) && !wanted.includes(cand)) wanted.push(cand);
    if (wanted.length === 3) break;
  }
  const tagRes = r.subResources.find(s => s.refLike) ?? null;
  lines.push(pad(depth + 1, 'columns:'));
  for (const c of wanted.slice(0, 3)) {
    const f = scalarOf(r, c);
    lines.push(pad(depth + 2, `- field: ${q(c)}`));
    lines.push(pad(depth + 3, `label: ${q(fieldLabel(c))}`));
    if (c === 'name') lines.push(pad(depth + 3, 'sortable: true'));
    if (c === 'description') lines.push(pad(depth + 3, 'render: truncated'));
  }
  if (tagRes) {
    lines.push(pad(depth + 2, `- field: ${q(tagRes.propertyName)}`));
    lines.push(pad(depth + 3, `label: ${q(humanize(tagRes.propertyName))}`));
    lines.push(pad(depth + 3, 'render: tag-count'));
  }
  lines.push(pad(depth + 2, '- field: actions'));
  lines.push(pad(depth + 3, 'label: ""'));
  lines.push(pad(depth + 3, 'type: row-actions'));
  lines.push(pad(depth + 3, 'items:'));
  lines.push(pad(depth + 4, '- { label: Detail, icon: Eye, action: open-detail }'));
  if (r.operations.update) lines.push(pad(depth + 4, '- { label: Edit, icon: Pencil, action: open-form, form: edit }'));
  if (r.operations.delete) lines.push(pad(depth + 4, '- { label: Hapus, icon: Trash2, action: delete, confirm: true }'));

  lines.push(pad(depth + 1, 'pagination:'));
  lines.push(pad(depth + 2, 'mode: server-side'));
  lines.push(pad(depth + 2, 'scheme: offset-limit'));
  lines.push(pad(depth + 2, 'perPageOptions: [10, 25, 50]'));
  lines.push(pad(depth + 1, 'emptyState:'));
  const title = humanize(r.name);
  if (r.operations.create) {
    lines.push(pad(depth + 2, `title: ${q(`Belum ada ${title}`)}`));
    lines.push(pad(depth + 2, `action: { label: ${q(`Tambah ${title}`)}, open: add }`));
  } else {
    lines.push(pad(depth + 2, `title: ${q(`Belum ada ${title}`)}`));
  }
}

/* ── page: toolbar + forms ─────────────────────────────────────────── */

/** @type seed value for a repeatable item, when the spec ships one (OAS3 only). */
function seedItem(r, prop) {
  const seed = (r.seedExamples ?? [])[0];
  return seed?.value?.[prop]?.[0] ?? null;
}

function itemPayloadBlocks(lines, depth, r, sub) {
  const seed = seedItem(r, sub.propertyName);
  const itemType = seed?.['@type'] ?? sub.itemRef ?? sub.className;
  lines.push(pad(depth, 'itemPayload:'));
  lines.push(pad(depth + 1, '"@type": item.atType'));
  for (const f of sub.fields.filter(f => f.kind === 'scalar')) {
    lines.push(pad(depth + 1, `${q(scalarWire(f))}: item.${f.name === 'refId' ? 'id' : f.name}`));
  }
  for (const fr of sub.flattenedRefs) {
    const col = prop => fr.columns.find(c => c.sourceProp === prop) ?? null;
    const href = col('href');
    const id = col('id');
    const name = col('name');
    const rtype = col('@referredType');
    lines.push(pad(depth + 1, `${q(fr.name)}:`));
    lines.push(pad(depth + 2, `"@type": ${q(fr.targetRef)}`));
    if (href) lines.push(pad(depth + 2, `href: item.${href.name}`));
    if (id) lines.push(pad(depth + 2, `id: item.${id.name}`));
    if (name) lines.push(pad(depth + 2, `name: item.${name.name}`));
    if (rtype) lines.push(pad(depth + 2, `"@referredType": item.${rtype.name}`));
  }
}

function itemFieldsBlocks(lines, depth, r, sub) {
  const seed = seedItem(r, sub.propertyName);
  const itemType = seed?.['@type'] ?? sub.itemRef ?? sub.className;
  const nestTypeOf = fr => seed?.[fr.name]?.['@referredType'];
  lines.push(pad(depth, 'itemFields:'));
  lines.push(pad(depth + 1, `- name: atType`));
  lines.push(pad(depth + 2, 'type: text'));
  lines.push(pad(depth + 2, 'readOnly: true'));
  lines.push(pad(depth + 2, `defaultValue: ${q(itemType)}`));
  for (const f of sub.fields.filter(f => f.kind === 'scalar')) {
    const wire = scalarWire(f);
    lines.push(pad(depth + 1, `- name: ${q(f.name === 'refId' ? 'id' : f.name)}`));
    lines.push(pad(depth + 2, `label: ${q(wire === 'id' ? `${humanize(sub.propertyName)} ID` : wire === '@referredType' || f.name === 'referredType' ? '@referredType' : fieldLabel(f.name))}`));
    if (wire === '@referredType' && seed?.['@referredType']) {
      const rt = seed['@referredType'];
      lines.push(pad(depth + 2, 'type: select'));
      lines.push(pad(depth + 2, `options: { ${rt}: ${rt} }`));
      lines.push(pad(depth + 2, `defaultValue: ${q(rt)}`));
    } else if (wire === 'href') {
      lines.push(pad(depth + 2, 'type: text'));
      lines.push(pad(depth + 2, 'readOnly: true'));
      lines.push(pad(depth + 2, 'computedFrom: id'));
    } else {
      lines.push(pad(depth + 2, `type: ${f.tsType === 'boolean' || f.column?.type === 'boolean' ? 'toggle' : 'text'}`));
    }
    if ((sub.requiredFields ?? []).includes(wire)) lines.push(pad(depth + 2, 'required: true'));
  }
  for (const fr of sub.flattenedRefs) {
    const pref = fr.name;
    const rt = nestTypeOf(fr);
    const rtype = fr.columns.find(c => c.sourceProp === '@referredType') ?? null;
    const idc = fr.columns.find(c => c.sourceProp === 'id') ?? null;
    const nc = fr.columns.find(c => c.sourceProp === 'name') ?? null;
    for (const col of [idc, nc, rtype]) {
      if (!col) continue;
      lines.push(pad(depth + 1, `- name: ${q(col.name)}`));
      lines.push(pad(depth + 2, `label: ${q(col.sourceProp === 'id' ? `${humanize(pref)} ID` : col.sourceProp === 'name' ? humanize(pref) : '@referredType')}`));
      if (col.sourceProp === '@referredType') {
        lines.push(pad(depth + 2, 'type: select'));
        lines.push(pad(depth + 2, `options: { ${rt}: ${rt} }`));
        lines.push(pad(depth + 2, `defaultValue: ${q(rt)}`));
      } else {
        lines.push(pad(depth + 2, 'type: text'));
      }
    }
  }
}

function refObjectFields(lines, depth, r, refName, shapeRequired) {
  const pref = camel(refName);
  lines.push(pad(depth, `- name: ${q(`${pref}Id`)}`));
  lines.push(pad(depth + 1, `label: ${q(`${humanize(refName)} ID`)}`));
  lines.push(pad(depth + 1, 'type: text'));
  if (shapeRequired) lines.push(pad(depth + 1, 'required: true'));
  lines.push(pad(depth, `- name: ${q(`${pref}Href`)}`));
  lines.push(pad(depth + 1, `label: ${q(`${humanize(refName)} Href`)}`));
  lines.push(pad(depth + 1, 'type: text'));
  lines.push(pad(depth + 1, 'readOnly: true'));
  lines.push(pad(depth + 1, 'computedFrom: ' + `${pref}Id`));
}

/** Props pada shape yang boleh dikirim user: non-infra DAN bisa dirender (bukan @type/skip). */
function formUserProps(shape, isCreate, r) {
  return (shape?.properties ?? []).filter(p => {
    if (p === '@type') return isCreate;
    if (INFRA_PROP.has(p)) return false;
    return payloadEntryKind(r, p) !== null;
  });
}

function createShapeOf(r) {
  return r.createShape ?? {
    required: r.required,
    properties: ['@type', ...r.fields.filter(f => f.kind === 'scalar').map(f => f.name), ...r.subResources.map(s => s.propertyName)],
  };
}

function updateShapeOf(r) {
  return r.updateShape ?? {
    required: [],
    properties: ['@type', ...r.fields.filter(f => f.kind === 'scalar').map(f => f.name), ...r.subResources.map(s => s.propertyName), ...r.resourceRefs.map(x => x.name)],
  };
}

function formPayloadBlocks(lines, depth, r, shape, mode) {
  const props = formUserProps(shape, mode === 'create', r);
  // Guard: shape infra-only (contoh tmf703 Entity: @baseType/@schemaLocation/@type) —
  // jangan pernah menulis `payload:` kosong (YAML null -> schema tolak). Caller
  // (formsBlock) sudah skip form utuh; ini belt-and-braces.
  if (!props.length) return;
  lines.push(pad(depth, 'payload:'));
  for (const p of props) {
    const kind = payloadEntryKind(r, p);
    if (kind === 'atType') {
      lines.push(pad(depth + 1, '"@type": fields.atType'));
      continue;
    }
    if (kind === 'sub') {
      lines.push(pad(depth + 1, `${q(p)}: fields.${q(p)}`));
    } else if (kind === 'ref') {
      const pref = camel(p);
      lines.push(pad(depth + 1, `${q(p)}:`));
      lines.push(pad(depth + 2, `id: fields.${pref}Id`));
      lines.push(pad(depth + 2, `href: fields.${pref}Href`));
    } else if (kind === 'flat') {
      const fr = flatOf(r, p);
      const col = prop => fr.columns.find(c => c.sourceProp === prop) ?? null;
      const idc = col('id');
      const hrefc = col('href');
      const nc = col('name');
      lines.push(pad(depth + 1, `${q(p)}:`));
      if (idc) lines.push(pad(depth + 2, `id: fields.${idc.name}`));
      if (hrefc) lines.push(pad(depth + 2, `href: fields.${hrefc.name}`));
      if (!idc && !hrefc && nc) lines.push(pad(depth + 2, `name: fields.${nc.name}`));
    } else if (kind === 'scalar') {
      lines.push(pad(depth + 1, `${q(p)}: fields.${q(p)}`));
    }
  }
}

function formFieldsBlocks(lines, depth, r, shape, isCreate) {
  const props = formUserProps(shape, isCreate, r);
  lines.push(pad(depth, 'fields:'));
  for (const p of props) {
    const kind = payloadEntryKind(r, p);
    if (kind === 'atType') {
      lines.push(pad(depth + 1, `- name: atType`));
      lines.push(pad(depth + 2, 'label: "@type"'));
      lines.push(pad(depth + 2, 'type: text'));
      lines.push(pad(depth + 2, 'readOnly: true'));
      lines.push(pad(depth + 2, `defaultValue: ${q(r.name)}`));
      if (shape.required.includes('@type')) lines.push(pad(depth + 2, 'required: true'));
      continue;
    }
    if (kind === 'sub') {
      const s = subOf(r, p);
      lines.push(pad(depth + 1, `- name: ${q(p)}`));
      lines.push(pad(depth + 2, `label: ${q(humanize(p))}`));
      lines.push(pad(depth + 2, 'type: repeatable'));
      if (shape.required.includes(p)) lines.push(pad(depth + 2, 'required: true'));
      if (s.minItems != null) lines.push(pad(depth + 2, `minItems: ${s.minItems}`));
      else if (s.refLike) lines.push(pad(depth + 2, 'minItems: 1'));
      lines.push(pad(depth + 2, `itemLabel: ${q(`${humanize(p)} #{{index}}`)}`));
      lines.push(pad(depth + 2, `addButton: ${q(`+ Tambah ${humanize(p)}`)}`));
      itemPayloadBlocks(lines, depth + 2, r, s);
      itemFieldsBlocks(lines, depth + 2, r, s);
    } else if (kind === 'ref') {
      const f = refOf(r, p);
      lines.push(pad(depth + 1, `- name: ${q(`${camel(f.name)}Ref`)}`));
      lines.push(pad(depth + 2, `label: ${q(humanize(f.name))}`));
      lines.push(pad(depth + 2, 'type: text'));
      lines.push(pad(depth + 2, 'readOnly: true'));
      lines.push(pad(depth + 2, 'computedFrom: ' + `${camel(f.name)}Id`));
      refObjectFields(lines, depth + 1, r, f.name, shape.required.includes(f.name));
    } else if (kind === 'flat') {
      // resource-level flattenedRef (cross-component ref): flat Id/Href fields, nested payload
      const fr = flatOf(r, p);
      const col = prop => fr.columns.find(c => c.sourceProp === prop) ?? null;
      const idc = col('id');
      const hrefc = col('href');
      if (idc) {
        lines.push(pad(depth + 1, `- name: ${q(idc.name)}`));
        lines.push(pad(depth + 2, `label: ${q(`${humanize(fr.name)} ID`)}`));
        lines.push(pad(depth + 2, 'type: text'));
        if (shape.required.includes(p)) lines.push(pad(depth + 2, 'required: true'));
      }
      if (hrefc) {
        lines.push(pad(depth + 1, `- name: ${q(hrefc.name)}`));
        lines.push(pad(depth + 2, `label: ${q(`${humanize(fr.name)} Href`)}`));
        lines.push(pad(depth + 2, 'type: text'));
        lines.push(pad(depth + 2, 'readOnly: true'));
        lines.push(pad(depth + 2, `computedFrom: ${q(idc ? idc.name : '')}`));
      }
    } else if (kind === 'scalar') {
      const f = scalarOf(r, p);
      lines.push(pad(depth + 1, `- name: ${q(f.name)}`));
      lines.push(pad(depth + 2, `label: ${q(fieldLabel(f.name))}`));
      lines.push(pad(depth + 2, `type: ${inputType(f)}`));
      if (inputType(f) === 'select') {
        const opts = f.enumValues.map(v => `${v}: ${q(v)}`).join(', ');
        lines.push(pad(depth + 2, `options: { ${opts} }`));
      }
      if (inputType(f) === 'textarea') lines.push(pad(depth + 2, 'rows: 3'));
      if (shape.required.includes(f.name)) lines.push(pad(depth + 2, 'required: true'));
    }
  }
}

function buttonsBlock(lines, depth) {
  lines.push(pad(depth, 'buttons:'));
  lines.push(pad(depth + 1, 'submit: { label: Simpan, position: footer-right, variant: primary }'));
  lines.push(pad(depth + 1, 'cancel: { label: Batal, variant: ghost }'));
}

function formsBlock(lines, depth, r) {
  const create = r.operations.create;
  const update = r.operations.update;
  const addProps = create ? formUserProps(createShapeOf(r), true, r) : [];
  const editProps = update ? formUserProps(updateShapeOf(r), false, r) : [];
  // FIX (todo 3 sweep): shape yang SEMUA infra (tmf703 Entity: @baseType/@schemaLocation/@type)
  // tidak punya field user -> payload kosong -> `payload: null` ditolak schema. Form tanpa
  // satupun field user tidak berguna -> skip form utuh + komentar (formDef.api Wajib payload).
  if (create && !addProps.length) {
    lines.push(pad(depth, `# add: create-shape infra-only (${(createShapeOf(r).properties ?? []).join(', ')}) — tidak ada field user; form add di-skip`));
  }
  if (update && !editProps.length) {
    lines.push(pad(depth, `# edit: update-shape infra-only (${(updateShapeOf(r).properties ?? []).join(', ')}) — tidak ada field user; form edit di-skip`));
  }
  if (create && addProps.length) {
    const createShape = createShapeOf(r);
    lines.push(pad(depth, 'add:'));
    lines.push(pad(depth + 1, 'mode: modal'));
    lines.push(pad(depth + 1, `title: ${q(`Tambah ${humanize(r.name)}`)}`));
    lines.push(pad(depth + 1, 'api:'));
    lines.push(pad(depth + 2, 'method: POST'));
    lines.push(pad(depth + 2, `path: ${renderValueBase(r.paths.collection, r.paths.collection)}`));
    formPayloadBlocks(lines, depth + 2, r, createShape, 'create');
    formFieldsBlocks(lines, depth + 1, r, createShape, true);
    buttonsBlock(lines, depth + 1);
  }
  if (update && editProps.length) {
    const updateShape = updateShapeOf(r);
    lines.push(pad(depth, 'edit:'));
    lines.push(pad(depth + 1, 'mode: modal'));
    lines.push(pad(depth + 1, `title: ${q(`Edit ${humanize(r.name)}`)}`));
    if (create && addProps.length) lines.push(pad(depth + 1, 'prefillFrom: detail'));
    lines.push(pad(depth + 1, 'api:'));
    lines.push(pad(depth + 2, 'method: PATCH'));
    lines.push(pad(depth + 2, `path: ${renderValueBase(r.paths.item, r.paths.item)}`));
    formPayloadBlocks(lines, depth + 2, r, updateShape, 'update');
    if (create && addProps.length) {
      lines.push(pad(depth + 1, 'fields: [ reuse: add ]'));
    } else {
      formFieldsBlocks(lines, depth + 1, r, updateShape, false);
    }
    buttonsBlock(lines, depth + 1);
  }
}

/* ── page: detail view ─────────────────────────────────────────────── */

function detailSummaryFields(r) {
  const out = [];
  for (const f of r.fields.filter(f => f.kind === 'scalar')) {
    out.push({ field: f.name, label: f.name === 'name' ? 'Nama' : f.name === 'description' ? 'Deskripsi' : humanize(f.name) });
  }
  out.push({ field: '@type', label: '@type' });
  out.push({ field: 'id', label: 'ID', mono: true });
  out.push({ field: 'href', label: 'Href', render: 'link' });
  return out;
}

function detailView(lines, depth, r) {
  const singular = r.camelName;
  const hasName = r.fields.some(f => f.kind === 'scalar' && f.name === 'name');
  lines.push(pad(depth, 'detail:'));
  lines.push(pad(depth + 1, 'mode: page'));
  lines.push(pad(depth + 1, `path: ${q('/' + plural(r.pathKey ? r.pathKey : r.name) + '/:id')}`));
  lines.push(pad(depth + 1, `api: ${renderValueBase(r.paths.item, r.paths.item)}`));
  lines.push(pad(depth + 1, 'header:'));
  lines.push(pad(depth + 2, `title: ${q(`{{${singular}.${hasName ? 'name' : 'id'}}}`)}`));
  lines.push(pad(depth + 2, `subtitle: ${q(`{{${singular}.id}}`)}`));
  lines.push(pad(depth + 2, 'backButton: true'));
  if (r.operations.update || r.operations.delete) {
    lines.push(pad(depth + 2, 'actions:'));
    if (r.operations.update) lines.push(pad(depth + 3, '- { label: Edit, action: open-form, form: edit }'));
    if (r.operations.delete) lines.push(pad(depth + 3, '- { label: Hapus, variant: danger, action: delete, confirm: true }'));
  }
  lines.push(pad(depth + 1, 'sections:'));
  lines.push(pad(depth + 2, '- type: tabs'));
  lines.push(pad(depth + 3, 'tabs:'));
  lines.push(pad(depth + 4, '- label: Ringkasan'));
  lines.push(pad(depth + 5, 'blocks:'));
  lines.push(pad(depth + 5, '- type: card'));
  lines.push(pad(depth + 6, 'layout: description-list'));
  lines.push(pad(depth + 6, 'fields:'));
  for (const f of detailSummaryFields(r)) {
    const parts = [`field: ${q(f.field)}`, `label: ${q(f.label)}`];
    if (f.mono) parts.push('mono: true');
    if (f.render) parts.push(`render: ${f.render}`);
    lines.push(pad(depth + 7, `- { ${parts.join(', ')} }`));
  }
  for (const sub of r.subResources) {
    lines.push(pad(depth + 4, `- label: ${q(humanize(sub.propertyName))}`));
    lines.push(pad(depth + 5, 'blocks:'));
    lines.push(pad(depth + 5, '- type: table'));
    lines.push(pad(depth + 6, `field: ${q(sub.propertyName)}`));
    const cols = sub.fields.filter(f => f.kind === 'scalar').slice(0, 5).map(f => scalarWire(f));
    lines.push(pad(depth + 6, `columns: [${cols.map(q).join(', ')}]`));
    if (sub.flattenedRefs.length) {
      lines.push(pad(depth + 6, 'renderColumns:'));
      for (const fr of sub.flattenedRefs) {
        lines.push(pad(depth + 7, `- { field: ${q(fr.name)}, sub: name, label: ${q(humanize(fr.name))} }`));
      }
    }
    lines.push(pad(depth + 6, `emptyState: { title: ${q(`Belum ada ${humanize(sub.propertyName)}`)} }`));
  }
}

/* ── page block ────────────────────────────────────────────────────── */

function camel(s) {
  const p = s.split(/[^A-Za-z0-9]+/).filter(Boolean).map(w => w[0].toUpperCase() + w.slice(1)).join('');
  return p ? p[0].toLowerCase() + p.slice(1) : s;
}

function pageBlock(lines, depth, r) {
  const d = depth + 1;
  const idx = r.pathKey ? r.pathKey : r.name;
  const title = humanize(r.name);
  const path = `/${plural(idx)}`;
  lines.push(`  # ========================================================`);
  lines.push(`  # ${title.toUpperCase()} — list + ${r.operations.create || r.operations.update ? 'add/edit modal + ' : ''}detail`);
  lines.push(`  # ========================================================`);
  lines.push(pad(depth, `- id: ${q(idx)}`));
  lines.push(pad(d, `path: ${q(path)}`));
  lines.push(pad(d, `title: ${q(title)}`));
  lines.push(pad(d, `icon: ${pageIcon(r.name)}`));
  lines.push(pad(d, 'nav:'));
  lines.push(pad(d + 1, 'parent: top'));
  lines.push('');
  if (r.operations.create) {
    lines.push(pad(d, 'actions:'));
    lines.push(pad(d + 1, `- label: ${q(`Tambah ${title}`)}`));
    lines.push(pad(d + 2, 'variant: primary'));
    lines.push(pad(d + 2, 'position: top-right'));
    lines.push(pad(d + 2, 'action: open-form'));
    lines.push(pad(d + 2, 'form: add'));
    lines.push(pad(d + 2, 'icon: Plus'));
    lines.push('');
  }
  const hasAdd = r.operations.create && formUserProps(createShapeOf(r), true, r).length > 0;
  const hasEdit = r.operations.update && formUserProps(updateShapeOf(r), false, r).length > 0;
  listView(lines, d, r);
  if (hasAdd || hasEdit) {
    lines.push('');
    lines.push(pad(d, 'forms:'));
    formsBlock(lines, d + 1, r);
  }
  if (r.operations.retrieve) {
    lines.push('');
    detailView(lines, d, r);
  }
  lines.push('');
}

function pagesBlock(lines, ir) {
  lines.push('# ============================================================');
  lines.push('# PAGES');
  lines.push('# ============================================================');
  lines.push('pages:');
  let emitted = 0;
  for (const r of ir.resources) {
    if (!r.operations.list) {
      lines.push(`  # ${r.name}: tidak ada list operation — page di-skip (baseline CRUD)`);
      continue;
    }
    pageBlock(lines, 1, r);
    emitted++;
  }
  if (!emitted) lines.push('  # (tidak ada resource dengan list operation)');
}

export async function emitFESpec(ir) {
  const lines = [];
  header(lines, ir);
  metaBlock(lines, ir);
  apiBlock(lines, ir);
  outputBlock(lines);
  uiBlock(lines);
  formEngineBlock(lines);
  layoutBlock(lines);
  authBlock(lines);
  pagesBlock(lines, ir);
  const text = lines.join('\n') + '\n';

  // VALIDASI INLINE sebelum tulis: jangan pernah menulis file yang invalid.
  const v = await validateString(text, { name: 'frontend-spec (inline)' });
  if (!v.ok) {
    const err = new Error(
      'generated frontend-spec is INVALID against fe-spec.schema.json:\n' +
        v.errors.slice(0, 10).map(e => `  ${e.pointer}: ${e.message}`).join('\n'),
    );
    err.validationErrors = v.errors;
    throw err;
  }
  return text;
}