// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { GeographicSiteListenerController } from '../../src/listener/geographic-site-listener.controller';

type AnyRec = Record<string, any>;

describe('GeographicSiteListenerController', () => {
  let repo: AnyRec;
  let ctrl: AnyRec;

  beforeEach(() => {
    repo = { findOne: jest.fn(), find: jest.fn(async () => []) };
    ctrl = new GeographicSiteListenerController(
      repo as never,
    ) as unknown as AnyRec;
  });

  it('returns the subscription named in the body when it exists', async () => {
    const sub = { id: 'sub-1', callback: 'https://a/hook' };
    repo.findOne.mockResolvedValue(sub);
    await expect(
      ctrl.handleGeographicSiteAttributeValueChangeEvent({
        subscriptionId: 'sub-1',
      }),
    ).resolves.toBe(sub);
    expect(repo.findOne).toHaveBeenCalledWith({ where: { id: 'sub-1' } });
  });

  it('falls back to the most recent subscription when the id is unknown', async () => {
    repo.findOne.mockResolvedValue(null);
    const latest = { id: 'sub-latest' };
    repo.find.mockResolvedValue([latest]);
    await expect(
      ctrl.handleGeographicSiteAttributeValueChangeEvent({
        subscriptionId: 'missing',
      }),
    ).resolves.toBe(latest);
    expect(repo.find).toHaveBeenCalledWith({
      order: { createdDate: 'DESC' },
      take: 1,
    });
  });

  it('falls back to the most recent subscription when the body carries no id', async () => {
    const latest = { id: 'sub-latest' };
    repo.find.mockResolvedValue([latest]);
    await expect(
      ctrl.handleGeographicSiteAttributeValueChangeEvent({}),
    ).resolves.toBe(latest);
    expect(repo.findOne).not.toHaveBeenCalled();
  });

  it('synthesises a placeholder when there are no subscriptions at all', async () => {
    repo.find.mockResolvedValue([]);
    const res =
      await ctrl.handleGeographicSiteAttributeValueChangeEvent(undefined);
    expect(res.id).toBe('unknown');
    expect(res.callback).toBe('');
  });

  it('answers every declared listener endpoint the same way', async () => {
    const latest = { id: 'sub-latest' };
    repo.find.mockResolvedValue([latest]);

    const handlers = [
      'handleGeographicSiteAttributeValueChangeEvent',
      'handleGeographicSiteCreateEvent',
      'handleGeographicSiteDeleteEvent',
      'handleGeographicSiteStatusChangeEvent',
    ];

    for (const name of handlers) {
      const handler = ctrl[name] as (b: unknown) => Promise<unknown>;
      expect(typeof handler).toBe('function');
      await expect(handler.call(ctrl, {})).resolves.toBe(latest);
    }
  });
});
