// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
// payload shape from Event_Create
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsDefined, IsOptional, IsString, IsArray, IsDateString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

class ReportingSystemDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@baseType'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@schemaLocation'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@type'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@referredType'?: string;
}

class SourceDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@baseType'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@schemaLocation'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@type'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@referredType'?: string;
}

class CharacteristicRelationshipDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  /** The type of relationship */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  relationshipType?: string;
}

class AnalyticCharacteristicDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  /** Name of the characteristic */
  @ApiProperty()
  @IsDefined()
  @IsString()
  name: string;

  /** Data type of the value of the characteristic */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  valueType?: string;

  @ApiProperty()
  @IsDefined()
  value: any;

  @ApiPropertyOptional({ type: [CharacteristicRelationshipDto] })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CharacteristicRelationshipDto)
  characteristicRelationship?: CharacteristicRelationshipDto[];
}

class RelatedPartyDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  href?: string;

  /** Name of the related entity. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  name?: string;

  /** Role played by the related party */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  role?: string;
}

export class CreateEventDto {
  /** The correlation id for this event. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  correlationId?: string;

  /** An explnatory of the event. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  description?: string;

  /** The domain of the event. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  domain?: string;

  /** The identifier of the notification. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  eventId?: string;

  /** Time of the event occurrence. */
  @ApiPropertyOptional({ format: 'date-time' })
  @IsOptional()
  @IsDateString()
  eventTime?: string;

  /** The type of the notification. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  eventType?: string;

  /** A priority. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  priority?: string;

  /** The time the event occured. */
  @ApiPropertyOptional({ format: 'date-time' })
  @IsOptional()
  @IsDateString()
  timeOcurred?: string;

  /** The title of the event. */
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  title?: string;

  @ApiPropertyOptional()
  @IsOptional()
  event?: any;

  @ApiPropertyOptional()
  @IsOptional()
  @ValidateNested()
  @Type(() => ReportingSystemDto)
  reportingSystem?: ReportingSystemDto;

  @ApiPropertyOptional()
  @IsOptional()
  @ValidateNested()
  @Type(() => SourceDto)
  source?: SourceDto;

  @ApiPropertyOptional({ type: [AnalyticCharacteristicDto] })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AnalyticCharacteristicDto)
  analyticCharacteristic?: AnalyticCharacteristicDto[];

  @ApiPropertyOptional({ type: [RelatedPartyDto] })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => RelatedPartyDto)
  relatedParty?: RelatedPartyDto[];

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@type'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@baseType'?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  '@schemaLocation'?: string;
}
