// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
export { CreateEventDto } from './create-event.dto';
export { UpdateEventDto } from './update-event.dto';
export { QueryEventDto } from './query-event.dto';
