// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * Hub
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { PATH_METADATA, ROUTE_ARGS_METADATA } from '@nestjs/common/constants';
import { RouteParamtypes } from '@nestjs/common/enums/route-paramtypes.enum';
import { Test } from '@nestjs/testing';
import { HubService } from '../../src/hub/hub.service';
import { HubController } from '../../src/hub/hub.controller';
import { CreateHubDto } from '../../src/hub/dto';
import { Hub } from '../../src/hub/entities/hub.entity';
import * as hooks from '../../src/hub/hub.hooks';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn(() => qb),
    take: jest.fn(() => qb),
    getCount: jest.fn(async () => rows.length),
    getMany: jest.fn(async () => rows),
  };
  return qb;
}

const HREF = '/tmf-api/event/v4/hub/res-1';

/** The route Nest registers from @Controller(`${BASE_PATH}/...`). */
const ROUTE_PATH = 'tmf-api/event/v4/hub';

/** The id every delegation asserts on, and the scalar the write paths move. */
const ID = 'res-1';
const FIELD = 'callback';
const LIST_QUERY = { limit: 5 };
const CREATE_BODY = { callback: 'res-callback' };

/** The `@type` a create stamps on a payload that carries none. */
const AT_TYPE = 'Hub';
/** One the payload supplies instead, which must survive that default. */
const SUPPLIED_AT_TYPE = 'CustomHub';

/** Each settable root scalar: the payload key it is read from -> its column. */
const SCALARS: Record<string, string> = {
  callback: 'callback',
  query: 'query',
  '@schemaLocation': 'atSchemaLocation',
  '@baseType': 'atBaseType',
};

function scalarPayload(): AnyRec {
  const out: AnyRec = {};
  for (const w of Object.keys(SCALARS)) out[w] = `res-${SCALARS[w]}`;
  return out;
}

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    callback: 'res-callback',
    query: 'res-query',
    atType: 'Hub',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    ...over,
  };
}

describe('Hub entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [Hub]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});

describe('HubService', () => {
  let repo: AnyRec;
  let refSave: jest.Mock;
  let dataSource: AnyRec;
  let eventEmitter: AnyRec;
  let service: HubService;

  beforeEach(() => {
    repo = makeRepo();
    refSave = jest.fn(async (e: AnyRec) => e);
    dataSource = {
      getRepository: jest.fn(() => ({
        create: jest.fn((v: AnyRec) => v),
        findOne: jest.fn(async () => null),
        save: refSave,
      })),
    };
    eventEmitter = { emitEvent: jest.fn() };
    service = new HubService(
      repo as never,
      dataSource as never,
      eventEmitter as never,
    );
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('create', () => {
    beforeEach(() => {
      // beforeCreate is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(undefined);
    });

    it('persists every scalar and answers with the stored resource plus its href', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.create(scalarPayload() as never);

      const persisted = repo.save.mock.calls[0][0];
      for (const w of Object.keys(SCALARS)) {
        expect(persisted[SCALARS[w]]).toBe(`res-${SCALARS[w]}`);
      }
      expect(res.id).toBe(ID);
      expect(res.href).toBe(HREF);
    });

    it('keeps a client-supplied id and defaults @type to Hub', async () => {
      repo.findOne.mockResolvedValue(entity({ id: 'chosen' }));
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('chosen');
      expect(persisted.atType).toBe(AT_TYPE);
    });

    it('generates a uuid when no id is supplied and keeps a supplied @type', async () => {
      repo.findOne.mockResolvedValue(entity());
      await service.create({ '@type': SUPPLIED_AT_TYPE } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toMatch(/^[0-9a-f-]{36}$/);
      expect(persisted.atType).toBe(SUPPLIED_AT_TYPE);
    });

    it('clears the soft-delete stamps so a reused id is resurrected', async () => {
      // A client may reuse the id of a row that was soft-deleted. Left stamped,
      // save() updates a row findEntity cannot see, and the POST answers 404
      // on the very id it just wrote.
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.deletedAt).toBeNull();
      expect(persisted.deletedBy).toBeUndefined();
      expect(persisted.deletedReason).toBeUndefined();
    });

    it('builds from the payload the beforeCreate hook returns, not the dto', async () => {
      // beforeCreate lives in a file tmfgen does not manage. What it returns is
      // its owner's business, so it is SPIED here rather than asserted on: what
      // is under test is that create builds from the value it got back.
      const HOOK_PAYLOAD: AnyRec = {
        id: 'from-hook',
        callback: 'res-from-hook',
      };
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(HOOK_PAYLOAD);
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'ignored' } as never);

      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('from-hook');
      expect(persisted.callback).toBe('res-from-hook');
    });
  });
});

/** The design:paramtype Nest hands ValidationPipe for a route's @Body(). */
function bodyParamType(route: string): unknown {
  const args = Reflect.getMetadata(
    ROUTE_ARGS_METADATA,
    HubController,
    route,
  ) as AnyRec;
  const prefix = `${RouteParamtypes.BODY}:`;
  const bodyKey = Object.keys(args).find((k) => k.startsWith(prefix));
  expect(bodyKey).toBeDefined();
  const index = Number((bodyKey as string).split(':')[1]);
  const types = Reflect.getMetadata(
    'design:paramtypes',
    HubController.prototype,
    route,
  );
  return types[index];
}

describe('HubController', () => {
  let svc: AnyRec;
  let ctrl: HubController;

  beforeEach(() => {
    svc = {
      create: jest.fn(async () => ({ id: ID, href: HREF })),
      findAll: jest.fn(async () => ({ data: [], total: 0 })),
      findOne: jest.fn(async () => ({ id: ID })),
      remove: jest.fn(async () => undefined),
    };
    ctrl = new HubController(svc as never);
  });

  it('sets the Location header from the created resource href', async () => {
    const res = { location: jest.fn() };
    const out = await ctrl.create(CREATE_BODY as never, res as never);
    expect(svc.create).toHaveBeenCalledWith(CREATE_BODY);
    expect(res.location).toHaveBeenCalledWith(HREF);
    expect(out.id).toBe(ID);
  });

  it('omits the Location header when the created resource has no href', async () => {
    svc.create.mockResolvedValue({ id: ID });
    const res = { location: jest.fn() };
    await ctrl.create({} as never, res as never);
    expect(res.location).not.toHaveBeenCalled();
  });

  it('passes the query through to findAll', async () => {
    await ctrl.findAll(LIST_QUERY as never);
    expect(svc.findAll).toHaveBeenCalledWith(LIST_QUERY);
  });

  it('forwards the id and the field selection to findOne', async () => {
    await ctrl.findOne(ID, FIELD);
    expect(svc.findOne).toHaveBeenCalledWith(ID, FIELD);
  });

  it('delegates the delete route', async () => {
    await ctrl.remove(ID);
    expect(svc.remove).toHaveBeenCalledWith(ID);
  });

  it('is constructible by Nest with its route metadata intact', async () => {
    // A concrete controller carrying no decorator of its own emits no
    // constructor `design:paramtypes`, so Nest builds it with zero arguments
    // and every route 500s; losing only @Controller() keeps injection working
    // but silently unmounts the routes. Both are checked separately.
    const moduleRef = await Test.createTestingModule({
      controllers: [HubController],
      providers: [{ provide: HubService, useValue: svc }],
    }).compile();

    const resolved = moduleRef.get(HubController) as unknown as AnyRec;
    expect(resolved.service).toBe(svc);
    const paramtypes = Reflect.getMetadata('design:paramtypes', HubController);
    expect(paramtypes).toEqual([HubService]);
    const routePath = Reflect.getMetadata(PATH_METADATA, HubController);
    expect(routePath).toBe(ROUTE_PATH);
  });

  it('types every write body as its DTO class, so ValidationPipe has a schema', () => {
    // ValidationPipe validates against the parameter's design:paramtype. A body
    // left as `any`/`unknown` erases to Object, which accepts every payload
    // unchecked and makes Swagger emit no request body schema.
    expect(bodyParamType('create')).toBe(CreateHubDto);
  });
});
