// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { Characteristic } from './characteristic.entity';

/**
 * Another Characteristic that is related to the current Characteristic;
 */
@Entity('characteristic_relationship')
export class CharacteristicRelationship {
  @PrimaryColumn({ type: 'varchar', length: 100 })
  id: string;

  /** The id the client gave this item. Unique within its parent only, so it is not the primary key; served back as `id`. */
  @Column({ type: 'varchar', length: 100, nullable: true })
  refId?: string;

  @Column({ type: 'int', nullable: true })
  sortOrder?: number;

  /** The type of relationship */
  @Column({ type: 'varchar', length: 100, nullable: true })
  relationshipType?: string;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  @ManyToOne(() => Characteristic, (parent) => parent.characteristicRelationship, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'characteristic_id' })
  owner: Characteristic;
}
