// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from 'typeorm';
import { Expose } from 'class-transformer';
import { GeographicAddressValidationAlternateGeographicAddress } from './geographic-address-validation-alternate-geographic-address.entity';

/**
 * Representation of a GeographicSubAddress It is used for addressing within a property in an urban area (country properties are often defined differently). It may refer to a building, a building cluster, or a floor of a multistory building.
 */
@Entity('geographic_address_geographic_sub_address')
export class GeographicAddressGeographicSubAddress {
  @PrimaryColumn({ type: 'varchar', length: 100 })
  id: string;

  /** The id the client gave this item. Unique within its parent only, so it is not the primary key; served back as `id`. */
  @Column({ type: 'varchar', length: 100, nullable: true })
  refId?: string;

  @Column({ type: 'int', nullable: true })
  sortOrder?: number;

  /** allows for buildings that have well-known names */
  @Column({ type: 'varchar', length: 255, nullable: true })
  buildingName?: string;

  /** used where a level type may be repeated e.g. BASEMENT 1, BASEMENT 2 */
  @Column({ type: 'varchar', length: 255, nullable: true })
  levelNumber?: string;

  /** describes level types within a building */
  @Column({ type: 'varchar', length: 100, nullable: true })
  levelType?: string;

  /** Name of the subAddress to identify it with a meaningful identification */
  @Column({ type: 'varchar', length: 255, nullable: true })
  name?: string;

  /** private streets internal to a property (e.g. a university) may have internal names that are not recorded by the land title office. */
  @Column({ type: 'varchar', length: 255, nullable: true })
  privateStreetName?: string;

  /** private streets numbers internal to a private street */
  @Column({ type: 'varchar', length: 255, nullable: true })
  privateStreetNumber?: string;

  /** Type of subAddress : it can be a subunit or a private street */
  @Column({ type: 'varchar', length: 100, nullable: true })
  subAddressType?: string;

  /** the discriminator used for the subunit often just a simple number e.g. FLAT 5, may also be a range */
  @Column({ type: 'varchar', length: 255, nullable: true })
  subUnitNumber?: string;

  /** the type of subunit e.g.BERTH, FLAT, PIER, SUITE, SHOP, TOWER, UNIT, WHARF */
  @Column({ type: 'varchar', length: 100, nullable: true })
  subUnitType?: string;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;

  @ManyToOne(() => GeographicAddressValidationAlternateGeographicAddress, (parent) => parent.geographicSubAddress, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'geographic_address_validation_alternate_geographic_address_id' })
  owner: GeographicAddressValidationAlternateGeographicAddress;
}
