// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EventSubscription } from '../subscription/entities/event-subscription.entity';
import { EventListenerController } from './event-listener.controller';

@Module({
  imports: [TypeOrmModule.forFeature([EventSubscription])],
  controllers: [EventListenerController],
})
export class ListenerModule {}
