// GENERATED by fe-gen emit mcs-common - DO NOT EDIT. Re-run `fe-gen emit` instead.
// design-lab-only preview harness (see comment in the generated file below) - remove once
// a real host mounts these exposes instead.
import { useState } from 'react';
import './App.css';
import PartyRevSharingAlgorithmPreview from './exposes/PartyRevSharingAlgorithm';
import HubPreview from './exposes/Hub';

type View = 'landing' | "party-rev-sharing-algorithm" | 'hub';

function App() {
  const [view, setView] = useState<View>('landing');

  if (view === "party-rev-sharing-algorithm") {
    return (
      <div>
        <button className="preview-back" onClick={() => setView('landing')}>← Back to landing</button>
        <PartyRevSharingAlgorithmPreview />
      </div>
    );
  }

  if (view === 'hub') {
    return (
      <div>
        <button className="preview-back" onClick={() => setView('landing')}>← Back to landing</button>
        <HubPreview />
      </div>
    );
  }

  return (
    <div className="landing">
      <header className="landing__hero">
        <p className="landing__eyebrow">TM Forum ODA Remote</p>
        <h1>Revenue Sharing Algorithm</h1>
        <p>Portal manajemen PartyRevSharingAlgorithm (TMF736), federasi common_remote</p>
        <div className="landing__actions">
            <button className="preview-trigger" onClick={() => setView("party-rev-sharing-algorithm")}>
              Preview: Party Rev Sharing Algorithms
            </button>
            <button className="preview-trigger" onClick={() => setView('hub')}>
              Preview: Event Hub
            </button>
        </div>
      </header>
      <section className="landing__section">
        <h2>Federation Contract</h2>
        <p>Remote: <code>revenue_sharing_algorithms_remote</code></p>
      </section>
      <section className="landing__section">
        <h2>Exposed Resources</h2>
        <div className="pill-list">
            <span className="pill">PartyRevSharingAlgorithm</span>
        </div>
      </section>
    </div>
  );
}

export default App;
