// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Entity, PrimaryColumn, Column } from 'typeorm';
import { Expose } from 'class-transformer';

@Entity('retrieve_geographic_location_thing')
export class RetrieveGeographicLocationThing {
  @PrimaryColumn({ type: 'varchar', length: 100 })
  id: string;

  @Column({ type: 'varchar', length: 100, nullable: true })
  type?: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  uri?: string;

  @Expose({ name: '@type' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atType?: string;

  @Expose({ name: '@schemaLocation' })
  @Column({ type: 'varchar', length: 1000, nullable: true })
  atSchemaLocation?: string;

  @Expose({ name: '@baseType' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  atBaseType?: string;
}
