// GENERATED by fe-gen emit mcs-common - DO NOT EDIT. Re-run `fe-gen emit` instead.
import { apiGet, apiGetList, apiPost, apiPatch, apiDelete } from './api';
import type { PartyRevSharingAlgorithm, PartyRevSharingAlgorithm_FVO, PartyRevSharingAlgorithm_MVO } from '../types';
import type { ListParams } from '../types';

const ENDPOINT = "/partyRevSharingAlgorithm";

export async function listPartyRevSharingAlgorithms(params?: ListParams) {
  return apiGetList<PartyRevSharingAlgorithm>(ENDPOINT, params);
}

export async function getPartyRevSharingAlgorithm(id: string, fields?: string) {
  return apiGet<PartyRevSharingAlgorithm>(`${ENDPOINT}/${id}`, fields ? { fields } : undefined);
}

export async function createPartyRevSharingAlgorithm(body: PartyRevSharingAlgorithm_FVO) {
  return apiPost<PartyRevSharingAlgorithm>(ENDPOINT, body);
}

export async function patchPartyRevSharingAlgorithm(id: string, body: PartyRevSharingAlgorithm_MVO) {
  return apiPatch<PartyRevSharingAlgorithm>(`${ENDPOINT}/${id}`, body);
}

export async function deletePartyRevSharingAlgorithm(id: string) {
  return apiDelete(`${ENDPOINT}/${id}`);
}
