// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
import { Controller, Get, Post, Patch, Body, Param, Query, HttpCode, HttpStatus, Res, UseGuards, UseInterceptors } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiParam, ApiResponse } from '@nestjs/swagger';
import { Response } from 'express';
import { TMF673_BASE_PATH } from '../common/constants/tmf.constants';
import { ApiKeyGuard } from '../common/guards/api-key.guard';
import { PaginationInterceptor } from '../common/interceptors/pagination.interceptor';
import { GeographicAddressValidationService } from './geographic-address-validation.service';
import { CreateGeographicAddressValidationDto, UpdateGeographicAddressValidationDto, QueryGeographicAddressValidationDto } from './dto';

@ApiTags('geographicAddressValidation')
@UseGuards(ApiKeyGuard)
@UseInterceptors(PaginationInterceptor)
@Controller(`${TMF673_BASE_PATH}/geographicAddressValidation`)
export class GeographicAddressValidationController {
  constructor(private readonly service: GeographicAddressValidationService) {}

  @Post()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Creates a GeographicAddressValidation', description: 'This operation creates a GeographicAddressValidation entity.', operationId: 'createGeographicAddressValidation' })
  @ApiResponse({ status: 201, description: 'Created' })
  @ApiResponse({ status: 400, description: 'Bad Request' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  @ApiResponse({ status: 405, description: 'Method Not Allowed' })
  @ApiResponse({ status: 409, description: 'Conflict' })
  async create(
    @Body() dto: CreateGeographicAddressValidationDto,
    @Res({ passthrough: true }) res: Response,
  ): Promise<Record<string, any>> {
    const result = await this.service.create(dto);
    if (result?.href) {
      res.location(result.href);
    }
    return result;
  }

  @Get()
  @ApiOperation({ summary: 'List or find GeographicAddressValidation objects', description: 'This operation list or find GeographicAddressValidation entities', operationId: 'listGeographicAddressValidation' })
  @ApiResponse({ status: 200, description: 'Success' })
  @ApiResponse({ status: 400, description: 'Bad Request' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  @ApiResponse({ status: 404, description: 'Not Found' })
  @ApiResponse({ status: 405, description: 'Method Not Allowed' })
  @ApiResponse({ status: 409, description: 'Conflict' })
  findAll(@Query() query: QueryGeographicAddressValidationDto) {
    return this.service.findAll(query);
  }

  @Get(':id')
  @ApiOperation({ summary: 'Retrieves a GeographicAddressValidation by ID', description: 'This operation retrieves a GeographicAddressValidation entity. Attribute selection is enabled for all first level attributes.', operationId: 'retrieveGeographicAddressValidation' })
  @ApiResponse({ status: 200, description: 'Success' })
  @ApiResponse({ status: 400, description: 'Bad Request' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  @ApiResponse({ status: 404, description: 'Not Found' })
  @ApiResponse({ status: 405, description: 'Method Not Allowed' })
  @ApiResponse({ status: 409, description: 'Conflict' })
  @ApiParam({ name: 'id', description: 'Identifier of the GeographicAddressValidation' })
  findOne(
    @Param('id') id: string,
    @Query('fields') fields?: string,
  ): Promise<Record<string, any>> {
    return this.service.findOne(id, fields);
  }

  @Patch(':id')
  @ApiOperation({ summary: 'Updates partially a GeographicAddressValidation', description: 'This operation updates partially a GeographicAddressValidation entity.', operationId: 'patchGeographicAddressValidation' })
  @ApiResponse({ status: 200, description: 'Success' })
  @ApiResponse({ status: 400, description: 'Bad Request' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  @ApiResponse({ status: 404, description: 'Not Found' })
  @ApiResponse({ status: 405, description: 'Method Not Allowed' })
  @ApiResponse({ status: 409, description: 'Conflict' })
  @ApiParam({ name: 'id', description: 'Identifier of the GeographicAddressValidation' })
  update(
    @Param('id') id: string,
    @Body() dto: UpdateGeographicAddressValidationDto,
  ): Promise<Record<string, any>> {
    return this.service.update(id, dto);
  }
}
