// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * GeographicSubAddress
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { NotFoundException } from '@nestjs/common';
import { PATH_METADATA } from '@nestjs/common/constants';
import { Test } from '@nestjs/testing';
import { GeographicSubAddressService } from '../../src/geographic-sub-address/geographic-sub-address.service';
import { GeographicSubAddressController } from '../../src/geographic-sub-address/geographic-sub-address.controller';
import { GeographicSubAddress } from '../../src/geographic-sub-address/entities/geographic-sub-address.entity';
import * as hooks from '../../src/geographic-sub-address/geographic-sub-address.hooks';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

/**
 * The double REMEMBERS its window and applies it, which a double returning
 * every row whatever was asked for cannot: findAll reads the total BEFORE it
 * narrows the query, so `total` is the unpaged count while `data` is one page.
 * With an unwindowed double the two are always equal and neither half of that
 * sentence is under test - counting after the window, or reporting
 * `data.length` as the total, both stay green.
 */
function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  let offset = 0;
  let limit: number | undefined;
  const windowed = () =>
    limit === undefined ? rows : rows.slice(offset, offset + limit);
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn((n: number) => {
      offset = n;
      return qb;
    }),
    take: jest.fn((n: number) => {
      limit = n;
      return qb;
    }),
    getCount: jest.fn(async () => windowed().length),
    getMany: jest.fn(async () => windowed()),
  };
  return qb;
}

const HREF =
  '/tmf-api/geographicAddressManagement/v4/geographicSubAddress/res-1';

/** The route Nest registers from @Controller(`${BASE_PATH}/...`). */
const ROUTE_PATH =
  'tmf-api/geographicAddressManagement/v4/geographicSubAddress';

/** The id every delegation asserts on, and the scalar the write paths move. */
const ID = 'res-1';
const FIELD = 'buildingName';
const LIST_QUERY = { limit: 5 };

/** The `@type` a create stamps on a payload that carries none. */
const AT_TYPE = 'GeographicSubAddress';
/** One the payload supplies instead, which must survive that default. */
const SUPPLIED_AT_TYPE = 'CustomGeographicSubAddress';

/** Each settable root scalar: the payload key it is read from -> its column. */
const SCALARS: Record<string, string> = {
  buildingName: 'buildingName',
  levelNumber: 'levelNumber',
  levelType: 'levelType',
  name: 'name',
  privateStreetName: 'privateStreetName',
  privateStreetNumber: 'privateStreetNumber',
  subAddressType: 'subAddressType',
  subUnitNumber: 'subUnitNumber',
  subUnitType: 'subUnitType',
  '@schemaLocation': 'atSchemaLocation',
  '@baseType': 'atBaseType',
};

function scalarPayload(): AnyRec {
  const out: AnyRec = {};
  for (const w of Object.keys(SCALARS)) out[w] = `res-${SCALARS[w]}`;
  return out;
}

/**
 * A sort key and a selected attribute. They are named differently on
 * purpose: applyBaseFilters turns `sort` straight into `e.<key>` SQL, so
 * that one is the COLUMN name, while projectFields matches `fields`
 * against the keys of the MAPPED row, which are the response keys.
 */
const SORT_KEY = 'buildingName';
const SELECTED = 'buildingName';
/** One the client did not ask for, which selection must then drop. */
const NOT_SELECTED = 'levelNumber';

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    buildingName: 'res-buildingName',
    levelNumber: 'res-levelNumber',
    levelType: 'res-levelType',
    name: 'res-name',
    privateStreetName: 'res-privateStreetName',
    privateStreetNumber: 'res-privateStreetNumber',
    subAddressType: 'res-subAddressType',
    subUnitNumber: 'res-subUnitNumber',
    subUnitType: 'res-subUnitType',
    atType: 'GeographicSubAddress',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    ...over,
  };
}

describe('GeographicSubAddress entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [GeographicSubAddress]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});

describe('GeographicSubAddressService', () => {
  let repo: AnyRec;
  let refSave: jest.Mock;
  let dataSource: AnyRec;
  let eventEmitter: AnyRec;
  let service: GeographicSubAddressService;

  beforeEach(() => {
    repo = makeRepo();
    refSave = jest.fn(async (e: AnyRec) => e);
    dataSource = {
      getRepository: jest.fn(() => ({
        create: jest.fn((v: AnyRec) => v),
        findOne: jest.fn(async () => null),
        save: refSave,
      })),
    };
    eventEmitter = { emitEvent: jest.fn() };
    service = new GeographicSubAddressService(
      repo as never,
      dataSource as never,
      eventEmitter as never,
    );
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('create', () => {
    beforeEach(() => {
      // beforeCreate is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(undefined);
    });

    it('persists every scalar and answers with the stored resource plus its href', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.create(scalarPayload() as never);

      const persisted = repo.save.mock.calls[0][0];
      for (const w of Object.keys(SCALARS)) {
        expect(persisted[SCALARS[w]]).toBe(`res-${SCALARS[w]}`);
      }
      expect(res.id).toBe(ID);
      expect(res.href).toBe(HREF);
    });

    it('keeps a client-supplied id and defaults @type to GeographicSubAddress', async () => {
      repo.findOne.mockResolvedValue(entity({ id: 'chosen' }));
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('chosen');
      expect(persisted.atType).toBe(AT_TYPE);
    });

    it('generates a uuid when no id is supplied and keeps a supplied @type', async () => {
      repo.findOne.mockResolvedValue(entity());
      await service.create({ '@type': SUPPLIED_AT_TYPE } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toMatch(/^[0-9a-f-]{36}$/);
      expect(persisted.atType).toBe(SUPPLIED_AT_TYPE);
    });

    it('clears the soft-delete stamps so a reused id is resurrected', async () => {
      // A client may reuse the id of a row that was soft-deleted. Left stamped,
      // save() updates a row findEntity cannot see, and the POST answers 404
      // on the very id it just wrote.
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'chosen' } as never);
      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.deletedAt).toBeNull();
      expect(persisted.deletedBy).toBeUndefined();
      expect(persisted.deletedReason).toBeUndefined();
    });

    it('builds from the payload the beforeCreate hook returns, not the dto', async () => {
      // beforeCreate lives in a file tmfgen does not manage. What it returns is
      // its owner's business, so it is SPIED here rather than asserted on: what
      // is under test is that create builds from the value it got back.
      const HOOK_PAYLOAD: AnyRec = {
        id: 'from-hook',
        buildingName: 'res-from-hook',
      };
      jest.spyOn(hooks, 'beforeCreate').mockResolvedValue(HOOK_PAYLOAD);
      repo.findOne.mockResolvedValue(entity());
      await service.create({ id: 'ignored' } as never);

      const persisted = repo.save.mock.calls[0][0];
      expect(persisted.id).toBe('from-hook');
      expect(persisted.buildingName).toBe('res-from-hook');
    });
  });

  describe('findAll', () => {
    it('maps the page it asked for and reports the unpaged total', async () => {
      const rows = [entity(), entity({ id: 'res-2' }), entity({ id: 'res-3' })];
      repo.createQueryBuilder.mockReturnValue(makeQueryBuilder(rows));
      const { data, total } = await service.findAll({ limit: 2 } as never);
      // the count is taken BEFORE the window narrows the query
      expect(total).toBe(3);
      expect(data.map((d) => d.id)).toEqual([ID, 'res-2']);
      for (const w of Object.keys(SCALARS)) {
        expect(data[0][w]).toBe(`res-${SCALARS[w]}`);
      }
    });

    it('excludes soft-deleted rows and narrows by id', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({ id: ID } as never);
      expect(qb.where).toHaveBeenCalledWith('e.deletedAt IS NULL');
      expect(qb.andWhere).toHaveBeenCalledWith('e.id = :id', { id: ID });
    });

    it('pages with the supplied window', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      // deliberately not the defaults asserted below
      await service.findAll({ offset: 40, limit: 25 } as never);
      expect(qb.skip).toHaveBeenCalledWith(40);
      expect(qb.take).toHaveBeenCalledWith(25);
    });

    it('defaults to 20 rows from offset 0', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({} as never);
      expect(qb.skip).toHaveBeenCalledWith(0);
      expect(qb.take).toHaveBeenCalledWith(20);
    });

    it('orders by the requested sort key', async () => {
      const qb = makeQueryBuilder([entity()]);
      repo.createQueryBuilder.mockReturnValue(qb);
      await service.findAll({ sort: `-${SORT_KEY}` } as never);
      expect(qb.addOrderBy).toHaveBeenCalledWith(`e.${SORT_KEY}`, 'DESC');
    });

    it('projects only the requested fields, keeping id and href', async () => {
      repo.createQueryBuilder.mockReturnValue(makeQueryBuilder([entity()]));
      const { data } = await service.findAll({ fields: SELECTED } as never);
      expect(data[0][SELECTED]).toBe(`res-${SCALARS[SELECTED]}`);
      expect(data[0].id).toBe(ID);
      expect(data[0].href).toBe(HREF);
      expect(Object.keys(data[0])).not.toContain('@type');
      expect(Object.keys(data[0])).not.toContain(NOT_SELECTED);
    });
  });

  describe('findEntity / findOne', () => {
    beforeEach(() => {
      // afterFindOne is user-owned; only the it() below is about it
      jest.spyOn(hooks, 'afterFindOne').mockResolvedValue(undefined);
    });

    it('throws NotFoundException when the row is missing or soft-deleted', async () => {
      repo.findOne.mockResolvedValue(null);
      await expect(service.findEntity('nope')).rejects.toBeInstanceOf(
        NotFoundException,
      );
      await expect(service.findOne('nope')).rejects.toBeInstanceOf(
        NotFoundException,
      );
    });

    it('maps every scalar and the resource href', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID);
      for (const w of Object.keys(SCALARS)) {
        expect(res[w]).toBe(`res-${SCALARS[w]}`);
      }
      expect(res.href).toBe(HREF);
    });

    it('defaults @schemaLocation and @baseType to ""', async () => {
      repo.findOne.mockResolvedValue({ id: ID, atType: AT_TYPE });
      const res = await service.findOne(ID);
      expect(res['@schemaLocation']).toBe('');
      expect(res['@baseType']).toBe('');
    });

    it('projects the requested fields on a single read', async () => {
      repo.findOne.mockResolvedValue(entity());
      const res = await service.findOne(ID, SELECTED);
      expect(res[SELECTED]).toBe(`res-${SCALARS[SELECTED]}`);
      expect(Object.keys(res)).not.toContain(NOT_SELECTED);
    });

    it('answers with whatever the afterFindOne hook gives back', async () => {
      // afterFindOne lives in a file tmfgen does not manage. What it returns is
      // its owner's business, so it is SPIED here rather than asserted on: what
      // is under test is that findOne hands it the mapped response and answers
      // with the value it got back.
      const DECORATED: AnyRec = { id: 'from-hook' };
      jest.spyOn(hooks, 'afterFindOne').mockResolvedValue(DECORATED);
      const stored = entity();
      repo.findOne.mockResolvedValue(stored);
      const res = await service.findOne(ID);
      expect(hooks.afterFindOne).toHaveBeenCalledWith(
        expect.objectContaining({ href: HREF }),
        stored,
      );
      expect(res).toBe(DECORATED);
    });
  });
});

describe('GeographicSubAddressController', () => {
  let svc: AnyRec;
  let ctrl: GeographicSubAddressController;

  beforeEach(() => {
    svc = {
      findAll: jest.fn(async () => ({ data: [], total: 0 })),
      findOne: jest.fn(async () => ({ id: ID })),
    };
    ctrl = new GeographicSubAddressController(svc as never);
  });

  it('passes the query through to findAll', async () => {
    await ctrl.findAll(LIST_QUERY as never);
    expect(svc.findAll).toHaveBeenCalledWith(LIST_QUERY);
  });

  it('forwards the id and the field selection to findOne', async () => {
    await ctrl.findOne(ID, FIELD);
    expect(svc.findOne).toHaveBeenCalledWith(ID, FIELD);
  });

  it('is constructible by Nest with its route metadata intact', async () => {
    // A concrete controller carrying no decorator of its own emits no
    // constructor `design:paramtypes`, so Nest builds it with zero arguments
    // and every route 500s; losing only @Controller() keeps injection working
    // but silently unmounts the routes. Both are checked separately.
    const moduleRef = await Test.createTestingModule({
      controllers: [GeographicSubAddressController],
      providers: [{ provide: GeographicSubAddressService, useValue: svc }],
    }).compile();

    const resolved = moduleRef.get(
      GeographicSubAddressController,
    ) as unknown as AnyRec;
    expect(resolved.service).toBe(svc);
    const paramtypes = Reflect.getMetadata(
      'design:paramtypes',
      GeographicSubAddressController,
    );
    expect(paramtypes).toEqual([GeographicSubAddressService]);
    const routePath = Reflect.getMetadata(
      PATH_METADATA,
      GeographicSubAddressController,
    );
    expect(routePath).toBe(ROUTE_PATH);
  });
});
