// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.
/**
 * GeographicSubAddress
 *
 * The generated service and controller, against mocked repositories.
 *
 * TypeORM is mocked rather than run: a service emitted with --db postgres
 * carries postgres column types and will not boot on sqlite, so an in-memory
 * database is not an option.
 *
 * Every literal below is derived from this resource, never hand-written: see
 * the mapping table in emit/spec/resource.mjs for where each one comes from.
 */
import { PATH_METADATA } from '@nestjs/common/constants';
import { Test } from '@nestjs/testing';
import { GeographicSubAddressService } from '../../src/geographic-sub-address/geographic-sub-address.service';
import { GeographicSubAddressController } from '../../src/geographic-sub-address/geographic-sub-address.controller';
import { GeographicAddressEventType } from '../../src/event/event-types';
import { GeographicSubAddress } from '../../src/geographic-sub-address/entities/geographic-sub-address.entity';

type AnyRec = Record<string, any>;

function makeRepo(): AnyRec {
  return {
    create: jest.fn(() => ({}) as AnyRec),
    save: jest.fn(async (e: AnyRec) => e),
    findOne: jest.fn(),
    createQueryBuilder: jest.fn(),
  };
}

function makeQueryBuilder(rows: AnyRec[]): AnyRec {
  const qb: AnyRec = {
    leftJoinAndSelect: jest.fn(() => qb),
    where: jest.fn(() => qb),
    andWhere: jest.fn(() => qb),
    addOrderBy: jest.fn(() => qb),
    skip: jest.fn(() => qb),
    take: jest.fn(() => qb),
    getCount: jest.fn(async () => rows.length),
    getMany: jest.fn(async () => rows),
  };
  return qb;
}

const HREF =
  '/tmf-api/geographicAddressManagement/v4/geographicSubAddress/res-1';

/** The route Nest registers from @Controller(`${BASE_PATH}/...`). */
const ROUTE_PATH =
  'tmf-api/geographicAddressManagement/v4/geographicSubAddress';

/** The id every delegation asserts on, and the scalar the write paths move. */
const ID = 'res-1';
const FIELD = 'buildingName';
const LIST_QUERY = { limit: 5 };

function entity(over: AnyRec = {}): AnyRec {
  return {
    id: 'res-1',
    buildingName: 'res-buildingName',
    levelNumber: 'res-levelNumber',
    levelType: 'res-levelType',
    name: 'res-name',
    privateStreetName: 'res-privateStreetName',
    privateStreetNumber: 'res-privateStreetNumber',
    subAddressType: 'res-subAddressType',
    subUnitNumber: 'res-subUnitNumber',
    subUnitType: 'res-subUnitType',
    atType: 'GeographicSubAddress',
    atSchemaLocation: 'res-atSchemaLocation',
    atBaseType: 'res-atBaseType',
    ...over,
  };
}

describe('GeographicSubAddress entities', () => {
  it('are constructible, so the mocked repositories stand in for real rows', () => {
    for (const E of [GeographicSubAddress]) {
      expect(new (E as new () => object)()).toBeInstanceOf(E as never);
    }
  });
});

describe('GeographicSubAddressController', () => {
  let svc: AnyRec;
  let ctrl: GeographicSubAddressController;

  beforeEach(() => {
    svc = {
      findAll: jest.fn(async () => ({ data: [], total: 0 })),
      findOne: jest.fn(async () => ({ id: ID })),
    };
    ctrl = new GeographicSubAddressController(svc as never);
  });

  it('passes the query through to findAll', async () => {
    await ctrl.findAll(LIST_QUERY as never);
    expect(svc.findAll).toHaveBeenCalledWith(LIST_QUERY);
  });

  it('forwards the id and the field selection to findOne', async () => {
    await ctrl.findOne(ID, FIELD);
    expect(svc.findOne).toHaveBeenCalledWith(ID, FIELD);
  });

  it('is constructible by Nest with its route metadata intact', async () => {
    // A concrete controller carrying no decorator of its own emits no
    // constructor `design:paramtypes`, so Nest builds it with zero arguments
    // and every route 500s; losing only @Controller() keeps injection working
    // but silently unmounts the routes. Both are checked separately.
    const moduleRef = await Test.createTestingModule({
      controllers: [GeographicSubAddressController],
      providers: [{ provide: GeographicSubAddressService, useValue: svc }],
    }).compile();

    const resolved = moduleRef.get(
      GeographicSubAddressController,
    ) as unknown as AnyRec;
    expect(resolved.service).toBe(svc);
    const paramtypes = Reflect.getMetadata(
      'design:paramtypes',
      GeographicSubAddressController,
    );
    expect(paramtypes).toEqual([GeographicSubAddressService]);
    const routePath = Reflect.getMetadata(
      PATH_METADATA,
      GeographicSubAddressController,
    );
    expect(routePath).toBe(ROUTE_PATH);
  });
});
