import { pascal } from '../../ir/naming.mjs';
import {
  LATEST_ORDER_COLUMN,
  LATEST_ORDER_DIRECTION,
  LATEST_TAKE,
  PLACEHOLDER_SUBSCRIPTION,
} from '../behaviour.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';
const PRINT_WIDTH = 80;
const I1 = '    '; // 4
const I2 = '      '; // 6
const I3 = '        '; // 8

/**
 * test/listener/listener.spec.ts - EVERY hosted component's listener controller.
 *
 * Every declared /listener/* path becomes a handle<EventName> stub that all
 * share the same subscription-lookup fallback chain (see emit/wiring.mjs's
 * listenerController): look up the subscription named in the body, fall back
 * to the most recent one, and finally synthesise a placeholder when there are
 * none at all. The per-component parts are only the class name, its file, and
 * the full list of handler names - taken from the manifest entry, the same
 * source wiring.mjs builds the controllers from: class =
 * `${pascal(slug)}ListenerController`, handlers = `handle${pascal(eventName)}`
 * for each entry in the component's `listeners`.
 *
 * wiring.mjs writes ONE listener controller per hosted component. Built from a
 * single IR this suite described whichever component happened to be emitted
 * last and left a stale file behind when that component declared no events -
 * in the three-component geographic service it imported
 * GeographicSiteListenerController while every other emitted spec targeted
 * GeographicLocation. It is built from the manifest union instead.
 *
 * A component that declares no events has no /listener/* paths at all, so it
 * contributes no suite; when NO component declares any, this returns null.
 *
 * Handler names are TMF-derived and vary widely in length (22 to 55+ chars in
 * the golden set), so several lines below only fit Prettier's 80-column print
 * width unwrapped for short names. Each helper picks the same line breaks
 * Prettier itself would choose, verified against every golden case rather
 * than hand-guessed.
 */

function ctorLines(cls) {
  const single = `${I1}ctrl = new ${cls}(repo as never) as unknown as AnyRec;`;
  if (single.length <= PRINT_WIDTH) return [single];
  return [`${I1}ctrl = new ${cls}(`, `${I2}repo as never,`, `${I1}) as unknown as AnyRec;`];
}

function awaitExpectWithBody(handler, bodyInline, bodyKey, bodyValue, resultExpr) {
  const single = `${I1}await expect(ctrl.${handler}(${bodyInline})).resolves.toBe(${resultExpr});`;
  if (single.length <= PRINT_WIDTH) return [single];

  const mid = `${I2}ctrl.${handler}(${bodyInline}),`;
  if (mid.length <= PRINT_WIDTH) {
    return [`${I1}await expect(`, mid, `${I1}).resolves.toBe(${resultExpr});`];
  }

  return [
    `${I1}await expect(`,
    `${I2}ctrl.${handler}({`,
    `${I3}${bodyKey}: '${bodyValue}',`,
    `${I2}}),`,
    `${I1}).resolves.toBe(${resultExpr});`,
  ];
}

function awaitExpectEmptyBody(handler) {
  const single = `${I1}await expect(ctrl.${handler}({})).resolves.toBe(latest);`;
  if (single.length <= PRINT_WIDTH) return [single];
  return [`${I1}await expect(`, `${I2}ctrl.${handler}({}),`, `${I1}).resolves.toBe(latest);`];
}

function constResUndefined(handler) {
  const single = `${I1}const res = await ctrl.${handler}(undefined);`;
  if (single.length <= PRINT_WIDTH) return [single];

  const mid = `${I2}await ctrl.${handler}(undefined);`;
  if (mid.length <= PRINT_WIDTH) return [`${I1}const res =`, mid];

  return [
    `${I1}const res =`,
    `${I2}await ctrl.${handler}(`,
    `${I3}undefined,`,
    `${I2});`,
  ];
}

function handlersArrayLines(handlers) {
  const single = `${I1}const handlers = [${handlers.map(h => `'${h}'`).join(', ')}];`;
  if (single.length <= PRINT_WIDTH) return [single];
  return [
    `${I1}const handlers = [`,
    ...handlers.map(h => `${I2}'${h}',`),
    `${I1}];`,
  ];
}

/** The listener-controller suite for one hosted component. */
function controllerSuite(cls, handlers) {
  const first = handlers[0];
  return [
    `describe('${cls}', () => {`,
    '  let repo: AnyRec;',
    '  let ctrl: AnyRec;',
    '',
    '  beforeEach(() => {',
    '    repo = { findOne: jest.fn(), find: jest.fn(async () => []) };',
    ...ctorLines(cls),
    '  });',
    '',
    "  it('returns the subscription named in the body when it exists', async () => {",
    "    const sub = { id: 'sub-1', callback: 'https://a/hook' };",
    '    repo.findOne.mockResolvedValue(sub);',
    ...awaitExpectWithBody(first, "{ subscriptionId: 'sub-1' }", 'subscriptionId', 'sub-1', 'sub'),
    "    expect(repo.findOne).toHaveBeenCalledWith({ where: { id: 'sub-1' } });",
    '  });',
    '',
    "  it('falls back to the most recent subscription when the id is unknown', async () => {",
    '    repo.findOne.mockResolvedValue(null);',
    "    const latest = { id: 'sub-latest' };",
    '    repo.find.mockResolvedValue([latest]);',
    ...awaitExpectWithBody(
      first,
      "{ subscriptionId: 'missing' }",
      'subscriptionId',
      'missing',
      'latest',
    ),
    '    expect(repo.find).toHaveBeenCalledWith({',
    `      order: { ${LATEST_ORDER_COLUMN}: '${LATEST_ORDER_DIRECTION}' },`,
    `      take: ${LATEST_TAKE},`,
    '    });',
    '  });',
    '',
    "  it('falls back to the most recent subscription when the body carries no id', async () => {",
    "    const latest = { id: 'sub-latest' };",
    '    repo.find.mockResolvedValue([latest]);',
    ...awaitExpectEmptyBody(first),
    '    expect(repo.findOne).not.toHaveBeenCalled();',
    '  });',
    '',
    "  it('synthesises a placeholder when there are no subscriptions at all', async () => {",
    '    repo.find.mockResolvedValue([]);',
    ...constResUndefined(first),
    `    expect(res.id).toBe('${PLACEHOLDER_SUBSCRIPTION.id}');`,
    `    expect(res.callback).toBe('${PLACEHOLDER_SUBSCRIPTION.callback}');`,
    '  });',
    '',
    "  it('answers every declared listener endpoint the same way', async () => {",
    "    const latest = { id: 'sub-latest' };",
    '    repo.find.mockResolvedValue([latest]);',
    '',
    ...handlersArrayLines(handlers),
    '',
    '    for (const name of handlers) {',
    '      const handler = ctrl[name] as (b: unknown) => Promise<unknown>;',
    "      expect(typeof handler).toBe('function');",
    '      await expect(handler.call(ctrl, {})).resolves.toBe(latest);',
    '    }',
    '  });',
    '});',
    '',
  ];
}

export function emitListenerSpec({ components }) {
  const ctrls = components
    .map(c => ({
      cls: `${pascal(c.slug)}ListenerController`,
      file: `${c.slug}-listener.controller`,
      handlers: (c.listeners ?? []).map(l => `handle${pascal(l.eventName)}`),
    }))
    .filter(c => c.handlers.length);
  if (!ctrls.length) return null;

  const lines = [
    BANNER,
    ...ctrls.map(c => `import { ${c.cls} } from '../../src/listener/${c.file}';`),
    '',
    'type AnyRec = Record<string, any>;',
    '',
    ...ctrls.flatMap(c => controllerSuite(c.cls, c.handlers)),
  ];
  return { rel: 'test/listener/listener.spec.ts', text: lines.join('\n') };
}
