import { kebab } from '../../ir/naming.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';
const PRINT_WIDTH = 80;

/**
 * `jest.mock(path, factory)` for a getter-backed seed module. Paths vary in
 * length with the resource name, so whether Prettier keeps the header
 * (`jest.mock('path', () => ({`) on one line or breaks the whole call onto
 * separate lines depends on that length - verified against golden cases
 * rather than hand-guessed. The two forms indent the body two spaces apart.
 */
function mockBlock(path, getterName, rowsVar) {
  const header = `jest.mock('${path}', () => ({`;
  if (header.length <= PRINT_WIDTH) {
    return [header, `  get ${getterName}() {`, `    return ${rowsVar};`, '  },', '}));'];
  }
  return [
    'jest.mock(',
    `  '${path}',`,
    '  () => ({',
    `    get ${getterName}() {`,
    `      return ${rowsVar};`,
    '    },',
    '  }),',
    ');',
  ];
}

/**
 * The dynamic `const { X } = await import('path');` inside isolateModulesAsync.
 * Prettier breaks the destructure from the await when the line overflows, but
 * leaves the (possibly still-overflowing) import path itself unbroken - it
 * cannot split a string literal argument.
 */
function importLine(cls, path) {
  const single = `    const { ${cls} } = await import('${path}');`;
  if (single.length <= PRINT_WIDTH) return [single];
  return [`    const { ${cls} } =`, `      await import('${path}');`];
}

/**
 * test/seed.spec.ts - exercises `seed.ts` end to end with NestFactory and the
 * app module mocked, so seeding is covered without a database.
 *
 * jest.mock paths are rebased to `../src/...` because the spec sits at
 * `test/seed.spec.ts` while `seed.ts` itself lives at `src/seed.ts` and mocks
 * its sibling modules with paths relative to itself (`./app.module`,
 * `./<dir>/<resource>.seed`, ...). A wrong depth here does not error - Jest
 * mocks a module that does not exist, the real one loads, and the assertions
 * fail confusingly rather than with a missing-module error.
 *
 * The five fixed cases test the FIRST resource in ctx.seeds. That resource's
 * combined seed list is `[...seedConst, ...localSeedConst]` (see
 * `renderSeedRunner` in emit/seed.mjs); a resource whose spec carried no
 * examples has no `seedConst` at all (every v4/Swagger2 spec: no `examples`
 * block exists to derive one from), so the test mutates whichever of the two
 * row arrays actually feeds that resource's seed list.
 */
export function emitSeedSpec({ seeds }) {
  if (!seeds.length) return null;

  const first = seeds[0];
  const testVar = first.seedConst ? 'rows0_0' : 'rows0_1';

  const rowDecls = [];
  const seedMocks = [];
  const resetLines = [];
  const isolatedImports = [];
  const tokenSets = [];

  seeds.forEach((s, i) => {
    const base = `../src/${s.dir}/${kebab(s.resource)}`;
    if (s.seedConst) {
      rowDecls.push(`let rows${i}_0: AnyRec[] = [];`);
      resetLines.push(`    rows${i}_0 = [];`);
      seedMocks.push(mockBlock(`${base}.seed`, s.seedConst, `rows${i}_0`).join('\n'));
    }
    rowDecls.push(`let rows${i}_1: AnyRec[] = [];`);
    resetLines.push(`    rows${i}_1 = [];`);
    seedMocks.push(mockBlock(`${base}.seed.local`, s.localSeedConst, `rows${i}_1`).join('\n'));

    isolatedImports.push(...importLine(s.serviceClass, `${base}.service`));
    tokenSets.push(`    byToken.set(${s.serviceClass}, services[${i}]);`);
  });

  const lines = [
    BANNER,
    '/**',
    " * `seed.ts` runs `main()` at import time, so each case re-imports the module with",
    ' * the process argv and seed rows it needs. NestFactory and the app module are',
    ' * mocked: seeding is exercised end to end without a database.',
    ' *',
    ` * This component seeds ${seeds.length} resource(s), each resolved by class token.`,
    ' */',
    'type AnyRec = Record<string, any>;',
    '',
    "// Each case re-imports the module graph and waits for main()'s fire-and-forget",
    '// tail. The budget is generous because several suites share one machine:',
    '// at 30s this timed out under load while passing in isolation.',
    'jest.setTimeout(120000);',
    '',
    'const createApplicationContext = jest.fn();',
    '',
    "jest.mock('@nestjs/core', () => ({",
    '  NestFactory: {',
    '    createApplicationContext: (...a: unknown[]) =>',
    '      createApplicationContext(...a),',
    '  },',
    '}));',
    "jest.mock('../src/app.module', () => ({ AppModule: class AppModule {} }));",
    '',
    ...rowDecls,
    '',
    seedMocks.join('\n\n'),
    '',
    'async function runSeed(argv: string[], services: AnyRec[]) {',
    "  // The seed resolves each service by its class token, and seedResource calls",
    '  // app.get() lazily per closure - so route by token identity, not call order.',
    '  // The tokens must come from the same module registry seed.ts will use, hence',
    '  // the imports live inside the isolated scope below.',
    '  const byToken = new Map<unknown, AnyRec>();',
    '  const app = {',
    '    get: jest.fn((token: unknown) => byToken.get(token)),',
    '    close: jest.fn(async () => undefined),',
    '  };',
    '  createApplicationContext.mockResolvedValue(app);',
    '  const argvBefore = process.argv;',
    "  process.argv = ['node', 'seed', ...argv];",
    '  jest.resetModules();',
    '  await jest.isolateModulesAsync(async () => {',
    ...isolatedImports,
    ...tokenSets,
    "    await import('../src/seed');",
    '  });',
    "  await new Promise((r) => setTimeout(r, 1100));",
    '  process.argv = argvBefore;',
    '  return app;',
    '}',
    '',
    'function svc(total: number, createImpl?: jest.Mock) {',
    '  return {',
    '    create: createImpl ?? jest.fn(async () => ({})),',
    '    findAll: jest.fn(async () => ({ total })),',
    '  };',
    '}',
    '',
    '/** The resource under test first, then a quiet stand-in for each of the others. */',
    'function services(total: number, first: AnyRec) {',
    `  return [first, ...Array.from({ length: ${seeds.length - 1} }, () => svc(total))];`,
    '}',
    '',
    "describe('seed', () => {",
    '  beforeEach(() => {',
    '    jest.clearAllMocks();',
    ...resetLines,
    '  });',
    '',
    "  it('skips a resource that already holds rows', async () => {",
    '    const a = svc(3);',
    `    ${testVar} = [{ id: 'a' }];`,
    '    const app = await runSeed([], services(3, a));',
    '',
    '    expect(a.findAll).toHaveBeenCalled();',
    '    expect(a.create).not.toHaveBeenCalled();',
    '    expect(app.close).toHaveBeenCalled();',
    '  });',
    '',
    "  it('seeds every payload when the resource is empty', async () => {",
    '    const a = svc(0);',
    `    ${testVar} = [{ id: 'a' }, { id: 'b' }];`,
    '    await runSeed([], services(0, a));',
    '',
    '    expect(a.create).toHaveBeenCalledTimes(2);',
    '  });',
    '',
    "  it('--force seeds without checking the existing count', async () => {",
    '    const a = svc(99);',
    `    ${testVar} = [{ id: 'a' }];`,
    "    await runSeed(['--force'], services(99, a));",
    '',
    '    expect(a.findAll).not.toHaveBeenCalled();',
    '    expect(a.create).toHaveBeenCalledTimes(1);',
    '  });',
    '',
    "  it('logs and continues when one payload fails to seed', async () => {",
    '    const failing = jest',
    '      .fn()',
    "      .mockRejectedValueOnce(new Error('duplicate key'))",
    '      .mockResolvedValueOnce({});',
    '    const a = svc(0, failing);',
    `    ${testVar} = [{ id: 'bad' }, { id: 'good' }];`,
    '    const app = await runSeed([], services(0, a));',
    '',
    '    expect(failing).toHaveBeenCalledTimes(2);',
    '    expect(app.close).toHaveBeenCalled();',
    '  });',
    '',
    "  it('closes the context and exits non-zero when seeding throws', async () => {",
    '    const a = {',
    '      create: jest.fn(async () => ({})),',
    '      findAll: jest.fn(async () => {',
    "        throw new Error('db down');",
    '      }),',
    '    };',
    `    ${testVar} = [{ id: 'a' }];`,
    '    const exit = jest',
    "      .spyOn(process, 'exit')",
    '      .mockImplementation((() => undefined) as never);',
    '    const app = await runSeed([], services(0, a));',
    '',
    '    expect(app.close).toHaveBeenCalled();',
    '    expect(exit).toHaveBeenCalledWith(1);',
    '    exit.mockRestore();',
    '  });',
    '});',
    '',
  ];
  return { rel: 'test/seed.spec.ts', text: lines.join('\n') };
}
