import { kebab } from '../../ir/naming.mjs';

const BANNER = '// GENERATED by tmfgen - DO NOT EDIT. Re-run the generator instead.';
const PRINT_WIDTH = 80;

/**
 * test/seed-local.spec.ts - the seed lists are plain API payloads.
 *
 * They are allowed to be empty, but they must stay arrays of objects: seed.ts
 * spreads them straight into create(). A resource whose spec carried no
 * examples has no `seedConst` at all and contributes only its local list.
 *
 * ctx.seeds is the manifest UNION, so this covers every resource the service
 * seeds, not just the component being emitted.
 */

/** `['name', name],`, broken the way Prettier breaks it when too wide. */
function seedEntryLines(name) {
  const single = `  ['${name}', ${name}],`;
  if (single.length <= PRINT_WIDTH) return [single];
  return ['  [', `    '${name}',`, `    ${name},`, '  ],'];
}
export function emitSeedLocalSpec({ seeds }) {
  if (!seeds.length) return null;

  const entries = [];
  for (const s of seeds) {
    const base = `../src/${s.dir}/${kebab(s.resource)}`;
    if (s.seedConst) entries.push({ name: s.seedConst, path: `${base}.seed` });
    entries.push({ name: s.localSeedConst, path: `${base}.seed.local` });
  }
  if (!entries.length) return null;

  const lines = [
    BANNER,
    '/**',
    ' * The seed lists are plain API payloads. They are allowed to be empty, but they',
    ' * must stay arrays of objects - `seed.ts` spreads them straight into `create()`.',
    ' */',
    ...entries.map(e => `import { ${e.name} } from '${e.path}';`),
    '',
    'const SEEDS: [string, Record<string, any>[]][] = [',
    ...entries.flatMap(e => seedEntryLines(e.name)),
    '];',
    '',
    "describe.each(SEEDS)('%s seed rows', (_name, rows) => {",
    "  it('are an array of payload objects', () => {",
    '    expect(Array.isArray(rows)).toBe(true);',
    '    for (const row of rows) {',
    "      expect(typeof row).toBe('object');",
    '      expect(row).not.toBeNull();',
    '    }',
    '  });',
    '});',
    '',
  ];
  return { rel: 'test/seed-local.spec.ts', text: lines.join('\n') };
}
